### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  commentId: T:Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  id: AssemblyManifest
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.#ctor
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.ExternalProxyStubs
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.XmlExternalProxyStubs
  langs:
  - csharp
  name: AssemblyManifest
  nameWithType: AssemblyManifest
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  type: Class
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: Describes a Win32 assembly manifest.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public class AssemblyManifest : Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
  inheritance:
  - System.Object
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
  derivedClasses:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationManifest
  implements: []
  inheritedMembers:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.AssemblyIdentity
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.AssemblyReferences
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.Description
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.EntryPoint
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.FileReferences
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.InputStream
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.OutputMessages
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.ReadOnly
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.ResolveFiles
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.ResolveFiles(System.String[])
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.SourcePath
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.ToString
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.UpdateFileInfo
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.UpdateFileInfo(System.String)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.Validate
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.ValidatePlatform
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.XmlAssemblyIdentity
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.XmlAssemblyReferences
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.XmlDescription
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.XmlFileReferences
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.XmlSchema
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  attributes:
  - type: System.Runtime.InteropServices.ComVisibleAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.Build.Tasks.Deployment.ManifestUtilities/AssemblyManifest.xml
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.#ctor
  commentId: M:Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  langs:
  - csharp
  name: AssemblyManifest()
  nameWithType: AssemblyManifest.AssemblyManifest()
  fullName: AssemblyManifest.AssemblyManifest()
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: Initializes a new instance of the <xref href="Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest"></xref> class.
  syntax:
    content: public AssemblyManifest ();
    parameters: []
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.Build.Tasks.Deployment.ManifestUtilities/AssemblyManifest.xml
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.ExternalProxyStubs
  commentId: P:Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.ExternalProxyStubs
  id: ExternalProxyStubs
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  langs:
  - csharp
  name: ExternalProxyStubs
  nameWithType: AssemblyManifest.ExternalProxyStubs
  fullName: AssemblyManifest.ExternalProxyStubs
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: Gets the set of external proxy stubs referenced by the manifest for isolated applications and Reg-Free COM.
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[] ExternalProxyStubs { get; }
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[]
      description: Returns the set of external proxy stubs referenced by the manifest for isolated applications and Reg-Free COM.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.ExternalProxyStubs*
  exceptions: []
  attributes: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.Build.Tasks.Deployment.ManifestUtilities/AssemblyManifest.xml
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.XmlExternalProxyStubs
  commentId: P:Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.XmlExternalProxyStubs
  id: XmlExternalProxyStubs
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  langs:
  - csharp
  name: XmlExternalProxyStubs
  nameWithType: AssemblyManifest.XmlExternalProxyStubs
  fullName: AssemblyManifest.XmlExternalProxyStubs
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: Gets or sets the set of external proxy stubs referenced by the manifest for isolated applications and Reg-Free COM in XML format.
  syntax:
    content: >-
      [System.ComponentModel.Browsable(false)]

      public Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[] XmlExternalProxyStubs { get; set; }
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[]
      description: Returns the set of external proxy stubs referenced by the manifest for isolated applications and Reg-Free COM in XML format.
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.XmlExternalProxyStubs*
  exceptions: []
  attributes:
  - type: System.ComponentModel.BrowsableAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.Build.Tasks.Deployment.ManifestUtilities/AssemblyManifest.xml
references:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: Manifest
  nameWithType: Manifest
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.#ctor
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  isExternal: false
  name: AssemblyManifest()
  nameWithType: AssemblyManifest.AssemblyManifest()
  fullName: AssemblyManifest.AssemblyManifest()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.ExternalProxyStubs
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  isExternal: false
  name: ExternalProxyStubs
  nameWithType: AssemblyManifest.ExternalProxyStubs
  fullName: AssemblyManifest.ExternalProxyStubs
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  name: ProxyStub
  nameWithType: ProxyStub
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[]
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: ProxyStub[]
  nameWithType: ProxyStub[]
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[]
  spec.csharp:
  - uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
    name: ProxyStub
    nameWithType: ProxyStub
    fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.XmlExternalProxyStubs
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  isExternal: false
  name: XmlExternalProxyStubs
  nameWithType: AssemblyManifest.XmlExternalProxyStubs
  fullName: AssemblyManifest.XmlExternalProxyStubs
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.#ctor*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  isExternal: false
  name: AssemblyManifest
  nameWithType: AssemblyManifest.AssemblyManifest
  fullName: AssemblyManifest.AssemblyManifest
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.Build.Tasks.Deployment.ManifestUtilities/AssemblyManifest.xml
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.ExternalProxyStubs*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  isExternal: false
  name: ExternalProxyStubs
  nameWithType: AssemblyManifest.ExternalProxyStubs
  fullName: AssemblyManifest.ExternalProxyStubs
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.Build.Tasks.Deployment.ManifestUtilities/AssemblyManifest.xml
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.XmlExternalProxyStubs*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  isExternal: false
  name: XmlExternalProxyStubs
  nameWithType: AssemblyManifest.XmlExternalProxyStubs
  fullName: AssemblyManifest.XmlExternalProxyStubs
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.Build.Tasks.Deployment.ManifestUtilities/AssemblyManifest.xml
