### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  commentId: T:Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  id: UpdateManifestForBrowserApplication
  children:
  - Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.#ctor
  - Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest
  - Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute
  - Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser
  langs:
  - csharp
  name: UpdateManifestForBrowserApplication
  nameWithType: UpdateManifestForBrowserApplication
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  type: Class
  assemblies:
  - PresentationBuildTasks
  namespace: Microsoft.Build.Tasks.Windows
  summary: Implements the <code>UpdateManifestForBrowserApplication</code> task. Use the <code>UpdateManifestForBrowserApplication</code> element in your project file to create and execute this task. For usage and parameter information, see [UpdateManifestForBrowserApplication](http://msdn.microsoft.com/library/653339f7-654b-4d64-a26a-5c9f27036895).
  syntax:
    content: 'public sealed class UpdateManifestForBrowserApplication : Microsoft.Build.Utilities.Task'
  inheritance:
  - System.Object
  - Microsoft.Build.Utilities.Task
  implements: []
  inheritedMembers:
  - Microsoft.Build.Utilities.Task.BuildEngine
  - Microsoft.Build.Utilities.Task.BuildEngine2
  - Microsoft.Build.Utilities.Task.BuildEngine3
  - Microsoft.Build.Utilities.Task.BuildEngine4
  - Microsoft.Build.Utilities.Task.HelpKeywordPrefix
  - Microsoft.Build.Utilities.Task.HostObject
  - Microsoft.Build.Utilities.Task.Log
  - Microsoft.Build.Utilities.Task.TaskResources
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.Build.Tasks.Windows/UpdateManifestForBrowserApplication.xml
  author: stevehoag
  ms.author: shoag
  manager: wpickett
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.#ctor
  commentId: M:Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  langs:
  - csharp
  name: UpdateManifestForBrowserApplication()
  nameWithType: UpdateManifestForBrowserApplication.UpdateManifestForBrowserApplication()
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.UpdateManifestForBrowserApplication()
  type: Constructor
  assemblies:
  - PresentationBuildTasks
  namespace: Microsoft.Build.Tasks.Windows
  summary: Initializes a new instance of the <xref href="Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication"></xref> class.
  syntax:
    content: public UpdateManifestForBrowserApplication ();
    parameters: []
  overload: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.Build.Tasks.Windows/UpdateManifestForBrowserApplication.xml
  author: stevehoag
  ms.author: shoag
  manager: wpickett
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest
  commentId: P:Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest
  id: ApplicationManifest
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  langs:
  - csharp
  name: ApplicationManifest
  nameWithType: UpdateManifestForBrowserApplication.ApplicationManifest
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest
  type: Property
  assemblies:
  - PresentationBuildTasks
  namespace: Microsoft.Build.Tasks.Windows
  summary: Gets or sets the path and name of the application manifest file that you want to add the <code><hostInBrowser /></code> element to.
  syntax:
    content: >-
      [Microsoft.Build.Framework.Required]

      public Microsoft.Build.Framework.ITaskItem[] ApplicationManifest { get; set; }
    return:
      type: Microsoft.Build.Framework.ITaskItem[]
      description: The path and name of the application manifest file that you want to add the <code><hostInBrowser /></code> element to.
  overload: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest*
  exceptions: []
  attributes:
  - type: Microsoft.Build.Framework.RequiredAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.Build.Tasks.Windows/UpdateManifestForBrowserApplication.xml
  author: stevehoag
  ms.author: shoag
  manager: wpickett
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute
  commentId: M:Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute
  id: Execute
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  langs:
  - csharp
  name: Execute()
  nameWithType: UpdateManifestForBrowserApplication.Execute()
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute()
  type: Method
  assemblies:
  - PresentationBuildTasks
  namespace: Microsoft.Build.Tasks.Windows
  summary: Executes a task.
  syntax:
    content: public override bool Execute ();
    parameters: []
    return:
      type: System.Boolean
      description: '`true` if the task executed successfully; otherwise, `false`.'
  overload: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.Build.Tasks.Windows/UpdateManifestForBrowserApplication.xml
  author: stevehoag
  ms.author: shoag
  manager: wpickett
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser
  commentId: P:Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser
  id: HostInBrowser
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  langs:
  - csharp
  name: HostInBrowser
  nameWithType: UpdateManifestForBrowserApplication.HostInBrowser
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser
  type: Property
  assemblies:
  - PresentationBuildTasks
  namespace: Microsoft.Build.Tasks.Windows
  summary: Gets a value that indicates whether to modify the application manifest to include the **<hostInBrowser />** element.
  syntax:
    content: >-
      [Microsoft.Build.Framework.Required]

      public bool HostInBrowser { get; set; }
    return:
      type: System.Boolean
      description: '`true` to modify the application manifest to include the **<hostInBrowser />** element; otherwise, `false`.'
  overload: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser*
  exceptions: []
  attributes:
  - type: Microsoft.Build.Framework.RequiredAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.Build.Tasks.Windows/UpdateManifestForBrowserApplication.xml
  author: stevehoag
  ms.author: shoag
  manager: wpickett
references:
- uid: Microsoft.Build.Utilities.Task
  parent: Microsoft.Build.Utilities
  isExternal: false
  name: Task
  nameWithType: Task
  fullName: Microsoft.Build.Utilities.Task
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.#ctor
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: UpdateManifestForBrowserApplication()
  nameWithType: UpdateManifestForBrowserApplication.UpdateManifestForBrowserApplication()
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.UpdateManifestForBrowserApplication()
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: ApplicationManifest
  nameWithType: UpdateManifestForBrowserApplication.ApplicationManifest
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest
- uid: Microsoft.Build.Framework.ITaskItem
  name: ITaskItem
  nameWithType: ITaskItem
  fullName: Microsoft.Build.Framework.ITaskItem
- uid: Microsoft.Build.Framework.ITaskItem[]
  parent: Microsoft.Build.Framework
  isExternal: false
  name: ITaskItem[]
  nameWithType: ITaskItem[]
  fullName: Microsoft.Build.Framework.ITaskItem[]
  spec.csharp:
  - uid: Microsoft.Build.Framework.ITaskItem
    name: ITaskItem
    nameWithType: ITaskItem
    fullName: Microsoft.Build.Framework.ITaskItem
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: Execute()
  nameWithType: UpdateManifestForBrowserApplication.Execute()
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute()
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: HostInBrowser
  nameWithType: UpdateManifestForBrowserApplication.HostInBrowser
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.#ctor*
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: UpdateManifestForBrowserApplication
  nameWithType: UpdateManifestForBrowserApplication.UpdateManifestForBrowserApplication
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.UpdateManifestForBrowserApplication
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.Build.Tasks.Windows/UpdateManifestForBrowserApplication.xml
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest*
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: ApplicationManifest
  nameWithType: UpdateManifestForBrowserApplication.ApplicationManifest
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.Build.Tasks.Windows/UpdateManifestForBrowserApplication.xml
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute*
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: Execute
  nameWithType: UpdateManifestForBrowserApplication.Execute
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.Build.Tasks.Windows/UpdateManifestForBrowserApplication.xml
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser*
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: HostInBrowser
  nameWithType: UpdateManifestForBrowserApplication.HostInBrowser
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.Build.Tasks.Windows/UpdateManifestForBrowserApplication.xml
