### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.SynchronousReceiveElement
  commentId: T:System.ServiceModel.Configuration.SynchronousReceiveElement
  id: SynchronousReceiveElement
  children:
  - System.ServiceModel.Configuration.SynchronousReceiveElement.#ctor
  - System.ServiceModel.Configuration.SynchronousReceiveElement.BehaviorType
  - System.ServiceModel.Configuration.SynchronousReceiveElement.CreateBehavior
  langs:
  - csharp
  name: SynchronousReceiveElement
  nameWithType: SynchronousReceiveElement
  fullName: System.ServiceModel.Configuration.SynchronousReceiveElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a configuration element that is used to specify run-time behavior for receiving messages in either a service or client application. This class cannot be inherited.
  syntax:
    content: 'public sealed class SynchronousReceiveElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/SynchronousReceiveElement.xml
- uid: System.ServiceModel.Configuration.SynchronousReceiveElement.#ctor
  commentId: M:System.ServiceModel.Configuration.SynchronousReceiveElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.SynchronousReceiveElement
  langs:
  - csharp
  name: SynchronousReceiveElement()
  nameWithType: SynchronousReceiveElement.SynchronousReceiveElement()
  fullName: SynchronousReceiveElement.SynchronousReceiveElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.SynchronousReceiveElement"></xref> class.
  syntax:
    content: public SynchronousReceiveElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.SynchronousReceiveElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/SynchronousReceiveElement.xml
- uid: System.ServiceModel.Configuration.SynchronousReceiveElement.BehaviorType
  commentId: P:System.ServiceModel.Configuration.SynchronousReceiveElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Configuration.SynchronousReceiveElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: SynchronousReceiveElement.BehaviorType
  fullName: SynchronousReceiveElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets the type of this behavior configuration element.
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: The type of the behavior.
  overload: System.ServiceModel.Configuration.SynchronousReceiveElement.BehaviorType*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/SynchronousReceiveElement.xml
- uid: System.ServiceModel.Configuration.SynchronousReceiveElement.CreateBehavior
  commentId: M:System.ServiceModel.Configuration.SynchronousReceiveElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Configuration.SynchronousReceiveElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: SynchronousReceiveElement.CreateBehavior()
  fullName: SynchronousReceiveElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: To be added.
  overload: System.ServiceModel.Configuration.SynchronousReceiveElement.CreateBehavior*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/SynchronousReceiveElement.xml
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: BehaviorExtensionElement
  nameWithType: BehaviorExtensionElement
  fullName: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Configuration.SynchronousReceiveElement.#ctor
  parent: System.ServiceModel.Configuration.SynchronousReceiveElement
  isExternal: false
  name: SynchronousReceiveElement()
  nameWithType: SynchronousReceiveElement.SynchronousReceiveElement()
  fullName: SynchronousReceiveElement.SynchronousReceiveElement()
- uid: System.ServiceModel.Configuration.SynchronousReceiveElement.BehaviorType
  parent: System.ServiceModel.Configuration.SynchronousReceiveElement
  isExternal: false
  name: BehaviorType
  nameWithType: SynchronousReceiveElement.BehaviorType
  fullName: SynchronousReceiveElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.SynchronousReceiveElement.CreateBehavior
  parent: System.ServiceModel.Configuration.SynchronousReceiveElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: SynchronousReceiveElement.CreateBehavior()
  fullName: SynchronousReceiveElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Configuration.SynchronousReceiveElement.#ctor*
  parent: System.ServiceModel.Configuration.SynchronousReceiveElement
  isExternal: false
  name: SynchronousReceiveElement
  nameWithType: SynchronousReceiveElement.SynchronousReceiveElement
  fullName: SynchronousReceiveElement.SynchronousReceiveElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/SynchronousReceiveElement.xml
- uid: System.ServiceModel.Configuration.SynchronousReceiveElement.BehaviorType*
  parent: System.ServiceModel.Configuration.SynchronousReceiveElement
  isExternal: false
  name: BehaviorType
  nameWithType: SynchronousReceiveElement.BehaviorType
  fullName: SynchronousReceiveElement.BehaviorType
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/SynchronousReceiveElement.xml
- uid: System.ServiceModel.Configuration.SynchronousReceiveElement.CreateBehavior*
  parent: System.ServiceModel.Configuration.SynchronousReceiveElement
  isExternal: false
  name: CreateBehavior
  nameWithType: SynchronousReceiveElement.CreateBehavior
  fullName: SynchronousReceiveElement.CreateBehavior
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/SynchronousReceiveElement.xml
