### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  commentId: T:System.ServiceModel.Activities.Tracking.Configuration.StateElement
  id: StateElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.StateElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name
  - System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties
  langs:
  - csharp
  name: StateElement
  nameWithType: StateElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  type: Class
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: A configuration element that specifies workflow instance state or activity instance state the user subscribes tracking information for.
  remarks: This element is placed within a <xref:System.ServiceModel.Activities.Tracking.Configuration.StateElementCollection> within a <xref:System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement> to specify the activity states the query should filter on.
  syntax:
    content: 'public class StateElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.#ctor
  commentId: M:System.ServiceModel.Activities.Tracking.Configuration.StateElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  langs:
  - csharp
  name: StateElement()
  nameWithType: StateElement.StateElement()
  fullName: StateElement.StateElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Activities.Tracking.Configuration.StateElement"></xref> class.
  syntax:
    content: public StateElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.StateElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey
  id: ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  langs:
  - csharp
  name: ElementKey
  nameWithType: StateElement.ElementKey
  fullName: StateElement.ElementKey
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets a key that uniquely identifies the element query.
  syntax:
    content: public override object ElementKey { get; }
    return:
      type: System.Object
      description: The element key.
  overload: System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name
  id: Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  langs:
  - csharp
  name: Name
  nameWithType: StateElement.Name
  fullName: StateElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets or sets the state name to filter on.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("name", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsKey=true)]

      [System.Configuration.StringValidator(MinLength=0)]

      public string Name { get; set; }
    return:
      type: System.String
      description: The state name to filter on. The default value is “*” (all).
  overload: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  langs:
  - csharp
  name: Properties
  nameWithType: StateElement.Properties
  fullName: StateElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets a collection of <xref href="System.Configuration.ConfigurationProperty"></xref> properties.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: A collection of configuration properties.
  overload: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateElement.xml
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  parent: System.ServiceModel.Activities.Tracking.Configuration
  isExternal: false
  name: TrackingConfigurationElement
  nameWithType: TrackingConfigurationElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: StateElement()
  nameWithType: StateElement.StateElement()
  fullName: StateElement.StateElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: ElementKey
  nameWithType: StateElement.ElementKey
  fullName: StateElement.ElementKey
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: Name
  nameWithType: StateElement.Name
  fullName: StateElement.Name
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: Properties
  nameWithType: StateElement.Properties
  fullName: StateElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: StateElement
  nameWithType: StateElement.StateElement
  fullName: StateElement.StateElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey*
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: ElementKey
  nameWithType: StateElement.ElementKey
  fullName: StateElement.ElementKey
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name*
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: Name
  nameWithType: StateElement.Name
  fullName: StateElement.Name
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: Properties
  nameWithType: StateElement.Properties
  fullName: StateElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateElement.xml
