### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  commentId: T:System.ServiceModel.Activities.Configuration.FactorySettingsElement
  id: FactorySettingsElement
  children:
  - System.ServiceModel.Activities.Configuration.FactorySettingsElement.#ctor
  - System.ServiceModel.Activities.Configuration.FactorySettingsElement.IdleTimeout
  - System.ServiceModel.Activities.Configuration.FactorySettingsElement.LeaseTimeout
  - System.ServiceModel.Activities.Configuration.FactorySettingsElement.MaxItemsInCache
  - System.ServiceModel.Activities.Configuration.FactorySettingsElement.Properties
  langs:
  - csharp
  name: FactorySettingsElement
  nameWithType: FactorySettingsElement
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  type: Class
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: Enables assigning values to the settings of a channel factory configuration element in a workflow service application. This is a sealed class.
  syntax:
    content: 'public sealed class FactorySettingsElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/FactorySettingsElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.#ctor
  commentId: M:System.ServiceModel.Activities.Configuration.FactorySettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  langs:
  - csharp
  name: FactorySettingsElement()
  nameWithType: FactorySettingsElement.FactorySettingsElement()
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.FactorySettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: Creates a new instance of the <xref href="System.ServiceModel.Activities.Configuration.FactorySettingsElement"></xref> class.
  syntax:
    content: public FactorySettingsElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Configuration.FactorySettingsElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/FactorySettingsElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.IdleTimeout
  commentId: P:System.ServiceModel.Activities.Configuration.FactorySettingsElement.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: FactorySettingsElement.IdleTimeout
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: Gets or sets the maximum interval of time for which the object can remain idle in a workflow cache before being disposed.
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(System.ServiceModel.Configuration.TimeSpanOrInfiniteConverter))]

      [System.Configuration.ConfigurationProperty("idleTimeout", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      [System.ServiceModel.Configuration.ServiceModelTimeSpanValidator(MinValueString="00:00:00")]

      public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: A timespan object.
  overload: System.ServiceModel.Activities.Configuration.FactorySettingsElement.IdleTimeout*
  exceptions: []
  attributes:
  - type: System.ComponentModel.TypeConverterAttribute
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.ServiceModel.Configuration.ServiceModelTimeSpanValidator
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/FactorySettingsElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.LeaseTimeout
  commentId: P:System.ServiceModel.Activities.Configuration.FactorySettingsElement.LeaseTimeout
  id: LeaseTimeout
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  langs:
  - csharp
  name: LeaseTimeout
  nameWithType: FactorySettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.LeaseTimeout
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: Gets or sets the interval of time after which an object will be removed from a workflow cache.
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(System.ServiceModel.Configuration.TimeSpanOrInfiniteConverter))]

      [System.Configuration.ConfigurationProperty("leaseTimeout", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      [System.ServiceModel.Configuration.ServiceModelTimeSpanValidator(MinValueString="00:00:00")]

      public TimeSpan LeaseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: A timespan object.
  overload: System.ServiceModel.Activities.Configuration.FactorySettingsElement.LeaseTimeout*
  exceptions: []
  attributes:
  - type: System.ComponentModel.TypeConverterAttribute
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.ServiceModel.Configuration.ServiceModelTimeSpanValidator
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/FactorySettingsElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.MaxItemsInCache
  commentId: P:System.ServiceModel.Activities.Configuration.FactorySettingsElement.MaxItemsInCache
  id: MaxItemsInCache
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  langs:
  - csharp
  name: MaxItemsInCache
  nameWithType: FactorySettingsElement.MaxItemsInCache
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.MaxItemsInCache
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: Gets or sets the maximum number of objects that can be in a workflow cache.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("maxItemsInCache", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      [System.Configuration.IntegerValidator(MinValue=0)]

      public int MaxItemsInCache { get; set; }
    return:
      type: System.Int32
      description: An integer representing a maximum number.
  overload: System.ServiceModel.Activities.Configuration.FactorySettingsElement.MaxItemsInCache*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.IntegerValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/FactorySettingsElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.Properties
  commentId: P:System.ServiceModel.Activities.Configuration.FactorySettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: FactorySettingsElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Activities.Configuration.FactorySettingsElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/FactorySettingsElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.#ctor
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: FactorySettingsElement()
  nameWithType: FactorySettingsElement.FactorySettingsElement()
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.FactorySettingsElement()
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.IdleTimeout
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: FactorySettingsElement.IdleTimeout
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: false
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.LeaseTimeout
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: FactorySettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.LeaseTimeout
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.MaxItemsInCache
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: MaxItemsInCache
  nameWithType: FactorySettingsElement.MaxItemsInCache
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.MaxItemsInCache
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.Properties
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: Properties
  nameWithType: FactorySettingsElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.#ctor*
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: FactorySettingsElement
  nameWithType: FactorySettingsElement.FactorySettingsElement
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.FactorySettingsElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/FactorySettingsElement.xml
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.IdleTimeout*
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: FactorySettingsElement.IdleTimeout
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.IdleTimeout
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/FactorySettingsElement.xml
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.LeaseTimeout*
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: FactorySettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.LeaseTimeout
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/FactorySettingsElement.xml
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.MaxItemsInCache*
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: MaxItemsInCache
  nameWithType: FactorySettingsElement.MaxItemsInCache
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.MaxItemsInCache
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/FactorySettingsElement.xml
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement.Properties*
  parent: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  isExternal: false
  name: Properties
  nameWithType: FactorySettingsElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/FactorySettingsElement.xml
