### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.AssemblyInfo
  commentId: T:System.Web.Configuration.AssemblyInfo
  id: AssemblyInfo
  children:
  - System.Web.Configuration.AssemblyInfo.#ctor(System.String)
  - System.Web.Configuration.AssemblyInfo.Assembly
  - System.Web.Configuration.AssemblyInfo.Properties
  langs:
  - csharp
  name: AssemblyInfo
  nameWithType: AssemblyInfo
  fullName: System.Web.Configuration.AssemblyInfo
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: References an assembly to be linked to during compilation of a dynamic resource. This class cannot be inherited.
  remarks: "ASP.NET automatically links assemblies to a resource when compiling each code module. An <xref:System.Web.Configuration.AssemblyInfo> object references an assembly. An assembly is a collection of types and resources that are built to work together and form a logical unit of functionality. An assembly provides the common language runtime with the information it needs to identify type implementations. To the runtime, a type does not exist outside the context of an assembly.  \n  \n Commonly linked assemblies are listed in the `assemblies` node of the `compilation` section of the configuration. Additionally, assemblies can be manually added to a code resource when additional functionality for an application is needed."
  syntax:
    content: 'public sealed class AssemblyInfo : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AssemblyInfo.xml
- uid: System.Web.Configuration.AssemblyInfo.#ctor(System.String)
  commentId: M:System.Web.Configuration.AssemblyInfo.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Configuration.AssemblyInfo
  langs:
  - csharp
  name: AssemblyInfo(String)
  nameWithType: AssemblyInfo.AssemblyInfo(String)
  fullName: AssemblyInfo.AssemblyInfo(String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Creates an instance of an <xref href="System.Web.Configuration.AssemblyInfo"></xref> class.
  remarks: If the <xref:System.Web.Configuration.AssemblyInfo> instance is not initialized with assembly information, an exception is thrown.
  example:
  - "The following code example demonstrates how to create an <xref:System.Web.Configuration.AssemblyInfo> object. This code example is part of a larger example provided for the <xref:System.Web.Configuration.AssemblyCollection> class.  \n  \n [!code-csharp[System.Web.Configuration.AssemblyCollection#2](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.AssemblyCollection/CS/AssemblyCollection.cs#2)]\n [!code-vb[System.Web.Configuration.AssemblyCollection#2](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.AssemblyCollection/VB/AssemblyCollection.vb#2)]"
  syntax:
    content: public AssemblyInfo (string assemblyName);
    parameters:
    - id: assemblyName
      type: System.String
      description: Specifies a comma-separated assembly name combination consisting of version, culture, and public-key tokens.
  overload: System.Web.Configuration.AssemblyInfo.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AssemblyInfo.xml
- uid: System.Web.Configuration.AssemblyInfo.Assembly
  commentId: P:System.Web.Configuration.AssemblyInfo.Assembly
  id: Assembly
  parent: System.Web.Configuration.AssemblyInfo
  langs:
  - csharp
  name: Assembly
  nameWithType: AssemblyInfo.Assembly
  fullName: AssemblyInfo.Assembly
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets or sets an assembly reference to use during compilation of a dynamic resource.
  remarks: ASP.NET first searches for the assembly DLL in the application's private Bin directory and then in the system assembly cache.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("assembly", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsKey=true, IsRequired=true)]

      [System.Configuration.StringValidator(MinLength=1)]

      public string Assembly { get; set; }
    return:
      type: System.String
      description: A comma-separated string value specifying the version, culture, and public-key tokens of an assembly.
  overload: System.Web.Configuration.AssemblyInfo.Assembly*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AssemblyInfo.xml
- uid: System.Web.Configuration.AssemblyInfo.Properties
  commentId: P:System.Web.Configuration.AssemblyInfo.Properties
  id: Properties
  parent: System.Web.Configuration.AssemblyInfo
  langs:
  - csharp
  name: Properties
  nameWithType: AssemblyInfo.Properties
  fullName: AssemblyInfo.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.AssemblyInfo.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AssemblyInfo.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.AssemblyInfo.#ctor(System.String)
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: AssemblyInfo(String)
  nameWithType: AssemblyInfo.AssemblyInfo(String)
  fullName: AssemblyInfo.AssemblyInfo(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.AssemblyInfo.Assembly
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: Assembly
  nameWithType: AssemblyInfo.Assembly
  fullName: AssemblyInfo.Assembly
- uid: System.Web.Configuration.AssemblyInfo.Properties
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: Properties
  nameWithType: AssemblyInfo.Properties
  fullName: AssemblyInfo.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.AssemblyInfo.#ctor*
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: AssemblyInfo
  nameWithType: AssemblyInfo.AssemblyInfo
  fullName: AssemblyInfo.AssemblyInfo
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AssemblyInfo.xml
- uid: System.Web.Configuration.AssemblyInfo.Assembly*
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: Assembly
  nameWithType: AssemblyInfo.Assembly
  fullName: AssemblyInfo.Assembly
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AssemblyInfo.xml
- uid: System.Web.Configuration.AssemblyInfo.Properties*
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: Properties
  nameWithType: AssemblyInfo.Properties
  fullName: AssemblyInfo.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AssemblyInfo.xml
