### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement
  commentId: T:System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement
  id: StateMachineStateQueryElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.ActivityName
  - System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.NewTrackingQuery
  - System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.Properties
  langs:
  - csharp
  name: StateMachineStateQueryElement
  nameWithType: StateMachineStateQueryElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement
  type: Class
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Represents a configuration StateMachineStateQuery element in DotNetConfig.xsd.
  syntax:
    content: 'public class StateMachineStateQueryElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Annotations
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.UpdateTrackingQuery(System.Activities.Tracking.TrackingQuery)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateMachineStateQueryElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.#ctor
  commentId: M:System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement
  langs:
  - csharp
  name: StateMachineStateQueryElement()
  nameWithType: StateMachineStateQueryElement.StateMachineStateQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.StateMachineStateQueryElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement"></xref> class.
  syntax:
    content: public StateMachineStateQueryElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateMachineStateQueryElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.ActivityName
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.ActivityName
  id: ActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement
  langs:
  - csharp
  name: ActivityName
  nameWithType: StateMachineStateQueryElement.ActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.ActivityName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets or sets the activity name filter attribute in StateMachineTrackingQuery element.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("activityName", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsKey=true)]

      [System.Configuration.StringValidator(MinLength=1)]

      public string ActivityName { get; set; }
    return:
      type: System.String
      description: The activity name filter attribute in StateMachineTrackingQuery element.
  overload: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.ActivityName*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateMachineStateQueryElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.NewTrackingQuery
  commentId: M:System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.NewTrackingQuery
  id: NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement
  langs:
  - csharp
  name: NewTrackingQuery()
  nameWithType: StateMachineStateQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.NewTrackingQuery()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Creates a StateMachine-specific CustomTrackingQuery, if the user specifies StateMachineTrackingQuery element in app.config.
  syntax:
    content: protected override System.Activities.Tracking.TrackingQuery NewTrackingQuery ();
    parameters: []
    return:
      type: System.Activities.Tracking.TrackingQuery
      description: A CustomTrackingQuery instance that tracks StateMachine specific TrackingRecord.
  overload: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.NewTrackingQuery*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateMachineStateQueryElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.Properties
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement
  langs:
  - csharp
  name: Properties
  nameWithType: StateMachineStateQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets the attributes in StateMachineTrackingQuery element.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: The attributes in StateMachineTrackingQuery element.
  overload: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateMachineStateQueryElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  parent: System.ServiceModel.Activities.Tracking.Configuration
  isExternal: false
  name: TrackingQueryElement
  nameWithType: TrackingQueryElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement
  isExternal: false
  name: StateMachineStateQueryElement()
  nameWithType: StateMachineStateQueryElement.StateMachineStateQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.StateMachineStateQueryElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.ActivityName
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement
  isExternal: false
  name: ActivityName
  nameWithType: StateMachineStateQueryElement.ActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.ActivityName
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement
  isExternal: false
  name: NewTrackingQuery()
  nameWithType: StateMachineStateQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.NewTrackingQuery()
- uid: System.Activities.Tracking.TrackingQuery
  parent: System.Activities.Tracking
  isExternal: false
  name: TrackingQuery
  nameWithType: TrackingQuery
  fullName: System.Activities.Tracking.TrackingQuery
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement
  isExternal: false
  name: Properties
  nameWithType: StateMachineStateQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement
  isExternal: false
  name: StateMachineStateQueryElement
  nameWithType: StateMachineStateQueryElement.StateMachineStateQueryElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.StateMachineStateQueryElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateMachineStateQueryElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.ActivityName*
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement
  isExternal: false
  name: ActivityName
  nameWithType: StateMachineStateQueryElement.ActivityName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.ActivityName
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateMachineStateQueryElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.NewTrackingQuery*
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement
  isExternal: false
  name: NewTrackingQuery
  nameWithType: StateMachineStateQueryElement.NewTrackingQuery
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.NewTrackingQuery
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateMachineStateQueryElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement
  isExternal: false
  name: Properties
  nameWithType: StateMachineStateQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateMachineStateQueryElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/StateMachineStateQueryElement.xml
