### YamlMime:ManagedReference
items:
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup
  commentId: T:System.Xml.Serialization.Configuration.SerializationSectionGroup
  id: SerializationSectionGroup
  children:
  - System.Xml.Serialization.Configuration.SerializationSectionGroup.#ctor
  - System.Xml.Serialization.Configuration.SerializationSectionGroup.DateTimeSerialization
  - System.Xml.Serialization.Configuration.SerializationSectionGroup.SchemaImporterExtensions
  - System.Xml.Serialization.Configuration.SerializationSectionGroup.XmlSerializer
  langs:
  - csharp
  name: SerializationSectionGroup
  nameWithType: SerializationSectionGroup
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup
  type: Class
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: Handles the XML elements used to configure XML serialization.
  remarks: This class is used to handle the [\&lt;system.xml.serialization\&gt; Element](~/docs/framework/serialization/system-xml-serialization-element.md).
  syntax:
    content: 'public sealed class SerializationSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/SerializationSectionGroup.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.#ctor
  commentId: M:System.Xml.Serialization.Configuration.SerializationSectionGroup.#ctor
  id: '#ctor'
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  langs:
  - csharp
  name: SerializationSectionGroup()
  nameWithType: SerializationSectionGroup.SerializationSectionGroup()
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.SerializationSectionGroup()
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: Initializes a new instance of the <xref href="System.Xml.Serialization.Configuration.SerializationSectionGroup"></xref> class.
  syntax:
    content: public SerializationSectionGroup ();
    parameters: []
  overload: System.Xml.Serialization.Configuration.SerializationSectionGroup.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/SerializationSectionGroup.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.DateTimeSerialization
  commentId: P:System.Xml.Serialization.Configuration.SerializationSectionGroup.DateTimeSerialization
  id: DateTimeSerialization
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  langs:
  - csharp
  name: DateTimeSerialization
  nameWithType: SerializationSectionGroup.DateTimeSerialization
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.DateTimeSerialization
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: Gets the object that represents the <xref href="System.DateTime"></xref> serialization configuration element.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("dateTimeSerialization")]

      public System.Xml.Serialization.Configuration.DateTimeSerializationSection DateTimeSerialization { get; }
    return:
      type: System.Xml.Serialization.Configuration.DateTimeSerializationSection
      description: The <xref href="System.Xml.Serialization.Configuration.DateTimeSerializationSection"></xref> object that represents the configuration element.
  overload: System.Xml.Serialization.Configuration.SerializationSectionGroup.DateTimeSerialization*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/SerializationSectionGroup.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.SchemaImporterExtensions
  commentId: P:System.Xml.Serialization.Configuration.SerializationSectionGroup.SchemaImporterExtensions
  id: SchemaImporterExtensions
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  langs:
  - csharp
  name: SchemaImporterExtensions
  nameWithType: SerializationSectionGroup.SchemaImporterExtensions
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.SchemaImporterExtensions
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: Gets the object that represents the section that contains configuration elements for the <xref href="System.Xml.Serialization.XmlSchemaImporter"></xref>.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("schemaImporterExtensions")]

      public System.Xml.Serialization.Configuration.SchemaImporterExtensionsSection SchemaImporterExtensions { get; }
    return:
      type: System.Xml.Serialization.Configuration.SchemaImporterExtensionsSection
      description: The <xref href="System.Xml.Serialization.Configuration.SchemaImporterExtensionsSection"></xref> that represents the `schemaImporterExtenstion` element in the configuration file.
  overload: System.Xml.Serialization.Configuration.SerializationSectionGroup.SchemaImporterExtensions*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/SerializationSectionGroup.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.XmlSerializer
  commentId: P:System.Xml.Serialization.Configuration.SerializationSectionGroup.XmlSerializer
  id: XmlSerializer
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  langs:
  - csharp
  name: XmlSerializer
  nameWithType: SerializationSectionGroup.XmlSerializer
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.XmlSerializer
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: Gets the object that represents the configuration group for the <xref href="System.Xml.Serialization.XmlSerializer"></xref>.
  syntax:
    content: public System.Xml.Serialization.Configuration.XmlSerializerSection XmlSerializer { get; }
    return:
      type: System.Xml.Serialization.Configuration.XmlSerializerSection
      description: The <xref href="System.Xml.Serialization.Configuration.XmlSerializerSection"></xref> that represents the <xref href="System.Xml.Serialization.XmlSerializer"></xref>.
  overload: System.Xml.Serialization.Configuration.SerializationSectionGroup.XmlSerializer*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/SerializationSectionGroup.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.Configuration.ConfigurationSectionGroup
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSectionGroup
  nameWithType: ConfigurationSectionGroup
  fullName: System.Configuration.ConfigurationSectionGroup
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.#ctor
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: SerializationSectionGroup()
  nameWithType: SerializationSectionGroup.SerializationSectionGroup()
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.SerializationSectionGroup()
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.DateTimeSerialization
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: DateTimeSerialization
  nameWithType: SerializationSectionGroup.DateTimeSerialization
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.DateTimeSerialization
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  parent: System.Xml.Serialization.Configuration
  isExternal: false
  name: DateTimeSerializationSection
  nameWithType: DateTimeSerializationSection
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.SchemaImporterExtensions
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: SchemaImporterExtensions
  nameWithType: SerializationSectionGroup.SchemaImporterExtensions
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.SchemaImporterExtensions
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionsSection
  parent: System.Xml.Serialization.Configuration
  isExternal: false
  name: SchemaImporterExtensionsSection
  nameWithType: SchemaImporterExtensionsSection
  fullName: System.Xml.Serialization.Configuration.SchemaImporterExtensionsSection
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.XmlSerializer
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: XmlSerializer
  nameWithType: SerializationSectionGroup.XmlSerializer
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.XmlSerializer
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection
  parent: System.Xml.Serialization.Configuration
  isExternal: false
  name: XmlSerializerSection
  nameWithType: XmlSerializerSection
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.#ctor*
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: SerializationSectionGroup
  nameWithType: SerializationSectionGroup.SerializationSectionGroup
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.SerializationSectionGroup
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/SerializationSectionGroup.xml
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.DateTimeSerialization*
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: DateTimeSerialization
  nameWithType: SerializationSectionGroup.DateTimeSerialization
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.DateTimeSerialization
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/SerializationSectionGroup.xml
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.SchemaImporterExtensions*
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: SchemaImporterExtensions
  nameWithType: SerializationSectionGroup.SchemaImporterExtensions
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.SchemaImporterExtensions
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/SerializationSectionGroup.xml
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.XmlSerializer*
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: XmlSerializer
  nameWithType: SerializationSectionGroup.XmlSerializer
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.XmlSerializer
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/SerializationSectionGroup.xml
