### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsLoadedEventArgs
  commentId: T:System.Configuration.SettingsLoadedEventArgs
  id: SettingsLoadedEventArgs
  children:
  - System.Configuration.SettingsLoadedEventArgs.#ctor(System.Configuration.SettingsProvider)
  - System.Configuration.SettingsLoadedEventArgs.Provider
  langs:
  - csharp
  name: SettingsLoadedEventArgs
  nameWithType: SettingsLoadedEventArgs
  fullName: System.Configuration.SettingsLoadedEventArgs
  type: Class
  assemblies:
  - System
  namespace: System.Configuration
  summary: Provides data for the <xref href="System.Configuration.ApplicationSettingsBase.SettingsLoaded"></xref> event.
  remarks: The <xref:System.Configuration.SettingsLoadedEventArgs> class provides data for the <xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded> event, which occurs when settings are retrieved from a provider.
  syntax:
    content: 'public class SettingsLoadedEventArgs : EventArgs'
  inheritance:
  - System.Object
  - System.EventArgs
  implements: []
  inheritedMembers:
  - System.EventArgs.Empty
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsLoadedEventArgs.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.SettingsLoadedEventArgs.#ctor(System.Configuration.SettingsProvider)
  commentId: M:System.Configuration.SettingsLoadedEventArgs.#ctor(System.Configuration.SettingsProvider)
  id: '#ctor(System.Configuration.SettingsProvider)'
  parent: System.Configuration.SettingsLoadedEventArgs
  langs:
  - csharp
  name: SettingsLoadedEventArgs(SettingsProvider)
  nameWithType: SettingsLoadedEventArgs.SettingsLoadedEventArgs(SettingsProvider)
  fullName: System.Configuration.SettingsLoadedEventArgs.SettingsLoadedEventArgs(SettingsProvider)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.SettingsLoadedEventArgs"></xref> class.
  syntax:
    content: public SettingsLoadedEventArgs (System.Configuration.SettingsProvider provider);
    parameters:
    - id: provider
      type: System.Configuration.SettingsProvider
      description: A <xref href="System.Configuration.SettingsProvider"></xref> object from which settings are loaded.
  overload: System.Configuration.SettingsLoadedEventArgs.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsLoadedEventArgs.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.SettingsLoadedEventArgs.Provider
  commentId: P:System.Configuration.SettingsLoadedEventArgs.Provider
  id: Provider
  parent: System.Configuration.SettingsLoadedEventArgs
  langs:
  - csharp
  name: Provider
  nameWithType: SettingsLoadedEventArgs.Provider
  fullName: System.Configuration.SettingsLoadedEventArgs.Provider
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: Gets the settings provider used to store configuration settings.
  syntax:
    content: public System.Configuration.SettingsProvider Provider { get; }
    return:
      type: System.Configuration.SettingsProvider
      description: A settings provider.
  overload: System.Configuration.SettingsLoadedEventArgs.Provider*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsLoadedEventArgs.xml
  ms.author: riande
  manager: wpickett
references:
- uid: System.EventArgs
  parent: System
  isExternal: false
  name: EventArgs
  nameWithType: EventArgs
  fullName: System.EventArgs
- uid: System.Configuration.SettingsLoadedEventArgs.#ctor(System.Configuration.SettingsProvider)
  parent: System.Configuration.SettingsLoadedEventArgs
  isExternal: false
  name: SettingsLoadedEventArgs(SettingsProvider)
  nameWithType: SettingsLoadedEventArgs.SettingsLoadedEventArgs(SettingsProvider)
  fullName: System.Configuration.SettingsLoadedEventArgs.SettingsLoadedEventArgs(SettingsProvider)
- uid: System.Configuration.SettingsProvider
  parent: System.Configuration
  isExternal: false
  name: SettingsProvider
  nameWithType: SettingsProvider
  fullName: System.Configuration.SettingsProvider
- uid: System.Configuration.SettingsLoadedEventArgs.Provider
  parent: System.Configuration.SettingsLoadedEventArgs
  isExternal: false
  name: Provider
  nameWithType: SettingsLoadedEventArgs.Provider
  fullName: System.Configuration.SettingsLoadedEventArgs.Provider
- uid: System.Configuration.SettingsLoadedEventArgs.#ctor*
  parent: System.Configuration.SettingsLoadedEventArgs
  isExternal: false
  name: SettingsLoadedEventArgs
  nameWithType: SettingsLoadedEventArgs.SettingsLoadedEventArgs
  fullName: System.Configuration.SettingsLoadedEventArgs.SettingsLoadedEventArgs
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsLoadedEventArgs.xml
- uid: System.Configuration.SettingsLoadedEventArgs.Provider*
  parent: System.Configuration.SettingsLoadedEventArgs
  isExternal: false
  name: Provider
  nameWithType: SettingsLoadedEventArgs.Provider
  fullName: System.Configuration.SettingsLoadedEventArgs.Provider
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsLoadedEventArgs.xml
