### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConnectionStringsSection
  commentId: T:System.Configuration.ConnectionStringsSection
  id: ConnectionStringsSection
  children:
  - System.Configuration.ConnectionStringsSection.#ctor
  - System.Configuration.ConnectionStringsSection.ConnectionStrings
  - System.Configuration.ConnectionStringsSection.GetRuntimeObject
  - System.Configuration.ConnectionStringsSection.Properties
  langs:
  - csharp
  name: ConnectionStringsSection
  nameWithType: ConnectionStringsSection
  fullName: System.Configuration.ConnectionStringsSection
  type: Class
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Provides programmatic access to the connection strings configuration-file section.
  remarks: The <xref:System.Configuration.ConnectionStringsSection> class allows you to programmatically modify the `connectionStrings` section of the configuration file. The connection strings are provided as a <xref:System.Configuration.ConnectionStringSettingsCollection> of <xref:System.Configuration.ConnectionStringSettings>`add` configuration elements.
  example:
  - "The following example shows how to use the <xref:System.Configuration.ConnectionStringsSection>.  \n  \n [!code-csharp[System.Configuration.ConnectionStrings#1](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Configuration.ConnectionStrings/CS/ConnectionStrings.cs#1)]\n [!code-vb[System.Configuration.ConnectionStrings#1](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Configuration.ConnectionStrings/VB/ConnectionStrings.vb#1)]  \n  \n The following excerpt shows the configuration used by the previous example.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n  <connectionStrings>  \n    <add name=\"ConnStr1\" connectionString=\"LocalSqlServer: data source=127.0.0.1;Integrated Security=SSPI;Initial Catalog=aspnetdb\"  \n      providerName=\"System.Data.SqlClient\" />  \n  </connectionStrings>  \n</configuration>  \n```"
  syntax:
    content: 'public sealed class ConnectionStringsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConnectionStringsSection.xml
- uid: System.Configuration.ConnectionStringsSection.#ctor
  commentId: M:System.Configuration.ConnectionStringsSection.#ctor
  id: '#ctor'
  parent: System.Configuration.ConnectionStringsSection
  langs:
  - csharp
  name: ConnectionStringsSection()
  nameWithType: ConnectionStringsSection.ConnectionStringsSection()
  fullName: ConnectionStringsSection.ConnectionStringsSection()
  type: Constructor
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.ConnectionStringsSection"></xref> class.
  syntax:
    content: public ConnectionStringsSection ();
    parameters: []
  overload: System.Configuration.ConnectionStringsSection.#ctor*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConnectionStringsSection.xml
- uid: System.Configuration.ConnectionStringsSection.ConnectionStrings
  commentId: P:System.Configuration.ConnectionStringsSection.ConnectionStrings
  id: ConnectionStrings
  parent: System.Configuration.ConnectionStringsSection
  langs:
  - csharp
  name: ConnectionStrings
  nameWithType: ConnectionStringsSection.ConnectionStrings
  fullName: ConnectionStringsSection.ConnectionStrings
  type: Property
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Gets a <xref href="System.Configuration.ConnectionStringSettingsCollection"></xref> collection of <xref href="System.Configuration.ConnectionStringSettings"></xref> objects.
  remarks: ''
  example:
  - "The following example shows how to use the <xref:System.Configuration.ConnectionStringsSection.ConnectionStrings%2A> property of the <xref:System.Configuration.ConnectionStringsSection> object.  \n  \n [!code-csharp[System.Configuration.ConnectionStrings#2](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Configuration.ConnectionStrings/CS/ConnectionStrings.cs#2)]\n [!code-vb[System.Configuration.ConnectionStrings#2](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Configuration.ConnectionStrings/VB/ConnectionStrings.vb#2)]"
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("", Options=System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection)]

      public System.Configuration.ConnectionStringSettingsCollection ConnectionStrings { get; }
    return:
      type: System.Configuration.ConnectionStringSettingsCollection
      description: A <xref href="System.Configuration.ConnectionStringSettingsCollection"></xref> collection of <xref href="System.Configuration.ConnectionStringSettings"></xref> objects.
  overload: System.Configuration.ConnectionStringsSection.ConnectionStrings*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConnectionStringsSection.xml
- uid: System.Configuration.ConnectionStringsSection.GetRuntimeObject
  commentId: M:System.Configuration.ConnectionStringsSection.GetRuntimeObject
  id: GetRuntimeObject
  parent: System.Configuration.ConnectionStringsSection
  langs:
  - csharp
  name: GetRuntimeObject()
  nameWithType: ConnectionStringsSection.GetRuntimeObject()
  fullName: ConnectionStringsSection.GetRuntimeObject()
  type: Method
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  syntax:
    content: protected override object GetRuntimeObject ();
    parameters: []
    return:
      type: System.Object
      description: To be added.
  overload: System.Configuration.ConnectionStringsSection.GetRuntimeObject*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConnectionStringsSection.xml
- uid: System.Configuration.ConnectionStringsSection.Properties
  commentId: P:System.Configuration.ConnectionStringsSection.Properties
  id: Properties
  parent: System.Configuration.ConnectionStringsSection
  langs:
  - csharp
  name: Properties
  nameWithType: ConnectionStringsSection.Properties
  fullName: ConnectionStringsSection.Properties
  type: Property
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Configuration.ConnectionStringsSection.Properties*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConnectionStringsSection.xml
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.Configuration.ConnectionStringsSection.#ctor
  parent: System.Configuration.ConnectionStringsSection
  isExternal: false
  name: ConnectionStringsSection()
  nameWithType: ConnectionStringsSection.ConnectionStringsSection()
  fullName: ConnectionStringsSection.ConnectionStringsSection()
- uid: System.Configuration.ConnectionStringsSection.ConnectionStrings
  parent: System.Configuration.ConnectionStringsSection
  isExternal: false
  name: ConnectionStrings
  nameWithType: ConnectionStringsSection.ConnectionStrings
  fullName: ConnectionStringsSection.ConnectionStrings
- uid: System.Configuration.ConnectionStringSettingsCollection
  parent: System.Configuration
  isExternal: false
  name: ConnectionStringSettingsCollection
  nameWithType: ConnectionStringSettingsCollection
  fullName: System.Configuration.ConnectionStringSettingsCollection
- uid: System.Configuration.ConnectionStringsSection.GetRuntimeObject
  parent: System.Configuration.ConnectionStringsSection
  isExternal: false
  name: GetRuntimeObject()
  nameWithType: ConnectionStringsSection.GetRuntimeObject()
  fullName: ConnectionStringsSection.GetRuntimeObject()
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ConnectionStringsSection.Properties
  parent: System.Configuration.ConnectionStringsSection
  isExternal: false
  name: Properties
  nameWithType: ConnectionStringsSection.Properties
  fullName: ConnectionStringsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.ConnectionStringsSection.#ctor*
  parent: System.Configuration.ConnectionStringsSection
  isExternal: false
  name: ConnectionStringsSection
  nameWithType: ConnectionStringsSection.ConnectionStringsSection
  fullName: ConnectionStringsSection.ConnectionStringsSection
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConnectionStringsSection.xml
- uid: System.Configuration.ConnectionStringsSection.ConnectionStrings*
  parent: System.Configuration.ConnectionStringsSection
  isExternal: false
  name: ConnectionStrings
  nameWithType: ConnectionStringsSection.ConnectionStrings
  fullName: ConnectionStringsSection.ConnectionStrings
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConnectionStringsSection.xml
- uid: System.Configuration.ConnectionStringsSection.GetRuntimeObject*
  parent: System.Configuration.ConnectionStringsSection
  isExternal: false
  name: GetRuntimeObject
  nameWithType: ConnectionStringsSection.GetRuntimeObject
  fullName: ConnectionStringsSection.GetRuntimeObject
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConnectionStringsSection.xml
- uid: System.Configuration.ConnectionStringsSection.Properties*
  parent: System.Configuration.ConnectionStringsSection
  isExternal: false
  name: Properties
  nameWithType: ConnectionStringsSection.Properties
  fullName: ConnectionStringsSection.Properties
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConnectionStringsSection.xml
