### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement
  commentId: T:System.ServiceModel.Configuration.SecureConversationServiceElement
  id: SecureConversationServiceElement
  children:
  - System.ServiceModel.Configuration.SecureConversationServiceElement.#ctor
  - System.ServiceModel.Configuration.SecureConversationServiceElement.Copy(System.ServiceModel.Configuration.SecureConversationServiceElement)
  - System.ServiceModel.Configuration.SecureConversationServiceElement.Properties
  - System.ServiceModel.Configuration.SecureConversationServiceElement.SecurityStateEncoderType
  langs:
  - csharp
  name: SecureConversationServiceElement
  nameWithType: SecureConversationServiceElement
  fullName: System.ServiceModel.Configuration.SecureConversationServiceElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a configuration element that specifies the settings for a secure conversation service. This class cannot be inherited.
  syntax:
    content: 'public sealed class SecureConversationServiceElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/SecureConversationServiceElement.xml
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.#ctor
  commentId: M:System.ServiceModel.Configuration.SecureConversationServiceElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  langs:
  - csharp
  name: SecureConversationServiceElement()
  nameWithType: SecureConversationServiceElement.SecureConversationServiceElement()
  fullName: SecureConversationServiceElement.SecureConversationServiceElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.SecureConversationServiceElement"></xref> class.
  syntax:
    content: public SecureConversationServiceElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.SecureConversationServiceElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/SecureConversationServiceElement.xml
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.Copy(System.ServiceModel.Configuration.SecureConversationServiceElement)
  commentId: M:System.ServiceModel.Configuration.SecureConversationServiceElement.Copy(System.ServiceModel.Configuration.SecureConversationServiceElement)
  id: Copy(System.ServiceModel.Configuration.SecureConversationServiceElement)
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  langs:
  - csharp
  name: Copy(SecureConversationServiceElement)
  nameWithType: SecureConversationServiceElement.Copy(SecureConversationServiceElement)
  fullName: SecureConversationServiceElement.Copy(SecureConversationServiceElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Copies the content of the specified configuration element to this configuration element.
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.SecureConversationServiceElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.SecureConversationServiceElement
      description: The configuration element to be copied.
  overload: System.ServiceModel.Configuration.SecureConversationServiceElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: <code>from</code> is `null` or empty.
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: The configuration file is read-only.
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/SecureConversationServiceElement.xml
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.Properties
  commentId: P:System.ServiceModel.Configuration.SecureConversationServiceElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  langs:
  - csharp
  name: Properties
  nameWithType: SecureConversationServiceElement.Properties
  fullName: SecureConversationServiceElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.SecureConversationServiceElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/SecureConversationServiceElement.xml
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.SecurityStateEncoderType
  commentId: P:System.ServiceModel.Configuration.SecureConversationServiceElement.SecurityStateEncoderType
  id: SecurityStateEncoderType
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  langs:
  - csharp
  name: SecurityStateEncoderType
  nameWithType: SecureConversationServiceElement.SecurityStateEncoderType
  fullName: SecureConversationServiceElement.SecurityStateEncoderType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the type of <xref href="System.ServiceModel.Security.SecurityStateEncoder"></xref> to be used.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("securityStateEncoderType", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      [System.Configuration.StringValidator(MinLength=0)]

      public string SecurityStateEncoderType { get; set; }
    return:
      type: System.String
      description: The type of <xref href="System.ServiceModel.Security.SecurityStateEncoder"></xref> to be used.
  overload: System.ServiceModel.Configuration.SecureConversationServiceElement.SecurityStateEncoderType*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/SecureConversationServiceElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  parent: System
  isExternal: false
  name: ArgumentNullException
  nameWithType: ArgumentNullException
  fullName: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.#ctor
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  isExternal: false
  name: SecureConversationServiceElement()
  nameWithType: SecureConversationServiceElement.SecureConversationServiceElement()
  fullName: SecureConversationServiceElement.SecureConversationServiceElement()
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.Copy(System.ServiceModel.Configuration.SecureConversationServiceElement)
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  isExternal: false
  name: Copy(SecureConversationServiceElement)
  nameWithType: SecureConversationServiceElement.Copy(SecureConversationServiceElement)
  fullName: SecureConversationServiceElement.Copy(SecureConversationServiceElement)
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: SecureConversationServiceElement
  nameWithType: SecureConversationServiceElement
  fullName: System.ServiceModel.Configuration.SecureConversationServiceElement
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.Properties
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  isExternal: false
  name: Properties
  nameWithType: SecureConversationServiceElement.Properties
  fullName: SecureConversationServiceElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.SecurityStateEncoderType
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  isExternal: false
  name: SecurityStateEncoderType
  nameWithType: SecureConversationServiceElement.SecurityStateEncoderType
  fullName: SecureConversationServiceElement.SecurityStateEncoderType
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.#ctor*
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  isExternal: false
  name: SecureConversationServiceElement
  nameWithType: SecureConversationServiceElement.SecureConversationServiceElement
  fullName: SecureConversationServiceElement.SecureConversationServiceElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/SecureConversationServiceElement.xml
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.Copy*
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  isExternal: false
  name: Copy
  nameWithType: SecureConversationServiceElement.Copy
  fullName: SecureConversationServiceElement.Copy
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/SecureConversationServiceElement.xml
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.Properties*
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  isExternal: false
  name: Properties
  nameWithType: SecureConversationServiceElement.Properties
  fullName: SecureConversationServiceElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/SecureConversationServiceElement.xml
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.SecurityStateEncoderType*
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  isExternal: false
  name: SecurityStateEncoderType
  nameWithType: SecureConversationServiceElement.SecurityStateEncoderType
  fullName: SecureConversationServiceElement.SecurityStateEncoderType
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/SecureConversationServiceElement.xml
