### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WebScriptEndpointCollectionElement
  commentId: T:System.ServiceModel.Configuration.WebScriptEndpointCollectionElement
  id: WebScriptEndpointCollectionElement
  children:
  - System.ServiceModel.Configuration.WebScriptEndpointCollectionElement.#ctor
  langs:
  - csharp
  name: WebScriptEndpointCollectionElement
  nameWithType: WebScriptEndpointCollectionElement
  fullName: System.ServiceModel.Configuration.WebScriptEndpointCollectionElement
  type: Class
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: Represents a collection of <xref href="System.ServiceModel.Description.WebScriptEndpoint"></xref> objects.
  syntax:
    content: 'public class WebScriptEndpointCollectionElement : System.ServiceModel.Configuration.StandardEndpointCollectionElement<System.ServiceModel.Description.WebScriptEndpoint,System.ServiceModel.Configuration.WebScriptEndpointElement>'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.EndpointCollectionElement
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.ConfiguredEndpoints
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.ContainsKey(System.String)
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.Endpoints
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.EndpointType
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.GetDefaultStandardEndpointElement
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.Properties
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.TryAdd(System.String,System.ServiceModel.Description.ServiceEndpoint,System.Configuration.Configuration)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WebScriptEndpointCollectionElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.WebScriptEndpointCollectionElement.#ctor
  commentId: M:System.ServiceModel.Configuration.WebScriptEndpointCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WebScriptEndpointCollectionElement
  langs:
  - csharp
  name: WebScriptEndpointCollectionElement()
  nameWithType: WebScriptEndpointCollectionElement.WebScriptEndpointCollectionElement()
  fullName: System.ServiceModel.Configuration.WebScriptEndpointCollectionElement.WebScriptEndpointCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: Creates a new instance of the <xref href="System.ServiceModel.Configuration.WebScriptEndpointCollectionElement"></xref> class.
  syntax:
    content: public WebScriptEndpointCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WebScriptEndpointCollectionElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WebScriptEndpointCollectionElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.ServiceModel.Configuration.StandardEndpointCollectionElement`2
  name: StandardEndpointCollectionElement<TStandardEndpoint,TEndpointConfiguration>
  nameWithType: StandardEndpointCollectionElement<TStandardEndpoint,TEndpointConfiguration>
  fullName: System.ServiceModel.Configuration.StandardEndpointCollectionElement<TStandardEndpoint,TEndpointConfiguration>
- uid: System.ServiceModel.Description.WebScriptEndpoint
  name: WebScriptEndpoint
  nameWithType: WebScriptEndpoint
  fullName: System.ServiceModel.Description.WebScriptEndpoint
- uid: System.ServiceModel.Configuration.WebScriptEndpointElement
  name: WebScriptEndpointElement
  nameWithType: WebScriptEndpointElement
  fullName: System.ServiceModel.Configuration.WebScriptEndpointElement
- uid: System.ServiceModel.Configuration.StandardEndpointCollectionElement{System.ServiceModel.Description.WebScriptEndpoint,System.ServiceModel.Configuration.WebScriptEndpointElement}
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: StandardEndpointCollectionElement<WebScriptEndpoint,WebScriptEndpointElement>
  nameWithType: StandardEndpointCollectionElement<WebScriptEndpoint,WebScriptEndpointElement>
  fullName: System.ServiceModel.Configuration.StandardEndpointCollectionElement<System.ServiceModel.Description.WebScriptEndpoint,System.ServiceModel.Configuration.WebScriptEndpointElement>
  spec.csharp:
  - uid: System.ServiceModel.Configuration.StandardEndpointCollectionElement`2
    name: StandardEndpointCollectionElement
    nameWithType: StandardEndpointCollectionElement
    fullName: System.ServiceModel.Configuration.StandardEndpointCollectionElement
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Description.WebScriptEndpoint
    name: WebScriptEndpoint
    nameWithType: WebScriptEndpoint
    fullName: System.ServiceModel.Description.WebScriptEndpoint
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.ServiceModel.Configuration.WebScriptEndpointElement
    name: WebScriptEndpointElement
    nameWithType: WebScriptEndpointElement
    fullName: System.ServiceModel.Configuration.WebScriptEndpointElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.WebScriptEndpointCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.WebScriptEndpointCollectionElement
  isExternal: false
  name: WebScriptEndpointCollectionElement()
  nameWithType: WebScriptEndpointCollectionElement.WebScriptEndpointCollectionElement()
  fullName: System.ServiceModel.Configuration.WebScriptEndpointCollectionElement.WebScriptEndpointCollectionElement()
- uid: System.ServiceModel.Configuration.WebScriptEndpointCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.WebScriptEndpointCollectionElement
  isExternal: false
  name: WebScriptEndpointCollectionElement
  nameWithType: WebScriptEndpointCollectionElement.WebScriptEndpointCollectionElement
  fullName: System.ServiceModel.Configuration.WebScriptEndpointCollectionElement.WebScriptEndpointCollectionElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WebScriptEndpointCollectionElement.xml
