### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NetTcpBindingCollectionElement
  commentId: T:System.ServiceModel.Configuration.NetTcpBindingCollectionElement
  id: NetTcpBindingCollectionElement
  children:
  - System.ServiceModel.Configuration.NetTcpBindingCollectionElement.#ctor
  langs:
  - csharp
  name: NetTcpBindingCollectionElement
  nameWithType: NetTcpBindingCollectionElement
  fullName: System.ServiceModel.Configuration.NetTcpBindingCollectionElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a configuration element that contains a collection of <xref href="System.ServiceModel.Configuration.NetTcpBindingElement"></xref> instances.
  syntax:
    content: 'public class NetTcpBindingCollectionElement : System.ServiceModel.Configuration.StandardBindingCollectionElement<System.ServiceModel.NetTcpBinding,System.ServiceModel.Configuration.NetTcpBindingElement>'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.BindingCollectionElement
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Bindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.BindingType
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ConfiguredBindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ContainsKey(System.String)
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.GetDefault
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Properties
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetTcpBindingCollectionElement.xml
- uid: System.ServiceModel.Configuration.NetTcpBindingCollectionElement.#ctor
  commentId: M:System.ServiceModel.Configuration.NetTcpBindingCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NetTcpBindingCollectionElement
  langs:
  - csharp
  name: NetTcpBindingCollectionElement()
  nameWithType: NetTcpBindingCollectionElement.NetTcpBindingCollectionElement()
  fullName: NetTcpBindingCollectionElement.NetTcpBindingCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.NetTcpBindingCollectionElement"></xref> class.
  syntax:
    content: public NetTcpBindingCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NetTcpBindingCollectionElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetTcpBindingCollectionElement.xml
references:
- uid: System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  name: StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  nameWithType: StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
- uid: System.ServiceModel.NetTcpBinding
  name: NetTcpBinding
  nameWithType: NetTcpBinding
  fullName: System.ServiceModel.NetTcpBinding
- uid: System.ServiceModel.Configuration.NetTcpBindingElement
  name: NetTcpBindingElement
  nameWithType: NetTcpBindingElement
  fullName: System.ServiceModel.Configuration.NetTcpBindingElement
- uid: System.ServiceModel.Configuration.StandardBindingCollectionElement{System.ServiceModel.NetTcpBinding,System.ServiceModel.Configuration.NetTcpBindingElement}
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: StandardBindingCollectionElement<NetTcpBinding,NetTcpBindingElement>
  nameWithType: StandardBindingCollectionElement<NetTcpBinding,NetTcpBindingElement>
  fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement<System.ServiceModel.NetTcpBinding,System.ServiceModel.Configuration.NetTcpBindingElement>
  spec.csharp:
  - uid: System.ServiceModel.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.NetTcpBinding
    name: NetTcpBinding
    nameWithType: NetTcpBinding
    fullName: System.ServiceModel.NetTcpBinding
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.ServiceModel.Configuration.NetTcpBindingElement
    name: NetTcpBindingElement
    nameWithType: NetTcpBindingElement
    fullName: System.ServiceModel.Configuration.NetTcpBindingElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.NetTcpBindingCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.NetTcpBindingCollectionElement
  isExternal: false
  name: NetTcpBindingCollectionElement()
  nameWithType: NetTcpBindingCollectionElement.NetTcpBindingCollectionElement()
  fullName: NetTcpBindingCollectionElement.NetTcpBindingCollectionElement()
- uid: System.ServiceModel.Configuration.NetTcpBindingCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.NetTcpBindingCollectionElement
  isExternal: false
  name: NetTcpBindingCollectionElement
  nameWithType: NetTcpBindingCollectionElement.NetTcpBindingCollectionElement
  fullName: NetTcpBindingCollectionElement.NetTcpBindingCollectionElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetTcpBindingCollectionElement.xml
