### YamlMime:ManagedReference
items:
- uid: System.Web.PreApplicationStartMethodAttribute
  commentId: T:System.Web.PreApplicationStartMethodAttribute
  id: PreApplicationStartMethodAttribute
  children:
  - System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  - System.Web.PreApplicationStartMethodAttribute.MethodName
  - System.Web.PreApplicationStartMethodAttribute.Type
  langs:
  - csharp
  name: PreApplicationStartMethodAttribute
  nameWithType: PreApplicationStartMethodAttribute
  fullName: System.Web.PreApplicationStartMethodAttribute
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Provides expanded support for application startup.
  remarks: "-   There is no guarantee of the order in which the assembly-defined application start methods are called. As a result, each registered start method should be coded to run in isolation and should not depend on side effects from other registered start methods.  \n  \n For more information about using attributes, see [Attributes](http://msdn.microsoft.com/library/30386922-1e00-4602-9ebf-526b271a8b87)."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple=true)]

      public sealed class PreApplicationStartMethodAttribute : Attribute
  inheritance:
  - System.Object
  - System.Attribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.AttributeUsageAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web/PreApplicationStartMethodAttribute.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  commentId: M:System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  id: '#ctor(System.Type,System.String)'
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: PreApplicationStartMethodAttribute(Type, String)
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type, String)
  fullName: System.Web.PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type, String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Initializes a new instance of the <xref href="System.Web.PreApplicationStartMethodAttribute"></xref> class.
  remarks: The method referenced by the `methodName` parameter must be public and can be either an instance method or static method.
  syntax:
    content: public PreApplicationStartMethodAttribute (Type type, string methodName);
    parameters:
    - id: type
      type: System.Type
      description: An object that describes the type of the startup method..
    - id: methodName
      type: System.String
      description: An empty parameter signature that has no return value.
  overload: System.Web.PreApplicationStartMethodAttribute.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web/PreApplicationStartMethodAttribute.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName
  commentId: P:System.Web.PreApplicationStartMethodAttribute.MethodName
  id: MethodName
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
  fullName: System.Web.PreApplicationStartMethodAttribute.MethodName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the associated startup method.
  syntax:
    content: public string MethodName { get; }
    return:
      type: System.String
      description: A string that contains the name of the associated startup method.
  overload: System.Web.PreApplicationStartMethodAttribute.MethodName*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web/PreApplicationStartMethodAttribute.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.PreApplicationStartMethodAttribute.Type
  commentId: P:System.Web.PreApplicationStartMethodAttribute.Type
  id: Type
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
  fullName: System.Web.PreApplicationStartMethodAttribute.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the type that is returned by the associated startup method.
  syntax:
    content: public Type Type { get; }
    return:
      type: System.Type
      description: An object that describes the type of the startup method.
  overload: System.Web.PreApplicationStartMethodAttribute.Type*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web/PreApplicationStartMethodAttribute.xml
  ms.author: riande
  manager: wpickett
references:
- uid: System.Attribute
  parent: System
  isExternal: false
  name: Attribute
  nameWithType: Attribute
  fullName: System.Attribute
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: PreApplicationStartMethodAttribute(Type, String)
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type, String)
  fullName: System.Web.PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type, String)
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
  fullName: System.Web.PreApplicationStartMethodAttribute.MethodName
- uid: System.Web.PreApplicationStartMethodAttribute.Type
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
  fullName: System.Web.PreApplicationStartMethodAttribute.Type
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: PreApplicationStartMethodAttribute
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute
  fullName: System.Web.PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web/PreApplicationStartMethodAttribute.xml
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
  fullName: System.Web.PreApplicationStartMethodAttribute.MethodName
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web/PreApplicationStartMethodAttribute.xml
- uid: System.Web.PreApplicationStartMethodAttribute.Type*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
  fullName: System.Web.PreApplicationStartMethodAttribute.Type
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web/PreApplicationStartMethodAttribute.xml
