### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization
  commentId: T:System.Web.Configuration.WebPartsPersonalizationAuthorization
  id: WebPartsPersonalizationAuthorization
  children:
  - System.Web.Configuration.WebPartsPersonalizationAuthorization.#ctor
  - System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties
  - System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules
  langs:
  - csharp
  name: WebPartsPersonalizationAuthorization
  nameWithType: WebPartsPersonalizationAuthorization
  fullName: System.Web.Configuration.WebPartsPersonalizationAuthorization
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Provides programmatic access to the `authorization` section contained in the `webParts` section of the configuration. This class cannot be inherited.
  remarks: The <xref:System.Web.Configuration.WebPartsPersonalizationAuthorization> class provides configuration support for personalization authorizations for Web Parts. This class can be used to allow or deny access to Web Parts resources.
  example:
  - "The following configuration-file example shows how to declaratively specify values for properties of the <xref:System.Web.Configuration.WebPartsPersonalizationAuthorization> class.  \n  \n```  \n<system.web>  \n  <webParts>  \n    <personalization>  \n      <authorization>  \n        <deny users=\"*\" verbs=\"enterSharedScope\" />  \n        <allow users=\"*\" verbs=\"modifyState\" />  \n      </authorization>  \n    </personalization>  \n  </webParts>  \n</system.web>  \n```"
  syntax:
    content: 'public sealed class WebPartsPersonalizationAuthorization : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/WebPartsPersonalizationAuthorization.xml
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.#ctor
  commentId: M:System.Web.Configuration.WebPartsPersonalizationAuthorization.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  langs:
  - csharp
  name: WebPartsPersonalizationAuthorization()
  nameWithType: WebPartsPersonalizationAuthorization.WebPartsPersonalizationAuthorization()
  fullName: WebPartsPersonalizationAuthorization.WebPartsPersonalizationAuthorization()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Configuration.WebPartsPersonalizationAuthorization"></xref> class.
  remarks: This constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system. An instance of this class is available from the <xref:System.Web.Configuration.WebPartsPersonalizationAuthorization> property.
  syntax:
    content: public WebPartsPersonalizationAuthorization ();
    parameters: []
  overload: System.Web.Configuration.WebPartsPersonalizationAuthorization.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/WebPartsPersonalizationAuthorization.xml
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties
  commentId: P:System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties
  id: Properties
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  langs:
  - csharp
  name: Properties
  nameWithType: WebPartsPersonalizationAuthorization.Properties
  fullName: WebPartsPersonalizationAuthorization.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/WebPartsPersonalizationAuthorization.xml
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules
  commentId: P:System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules
  id: Rules
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  langs:
  - csharp
  name: Rules
  nameWithType: WebPartsPersonalizationAuthorization.Rules
  fullName: WebPartsPersonalizationAuthorization.Rules
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets a collection of rules used for personalization authorization related to Web Parts.
  remarks: The <xref:System.Web.Configuration.AuthorizationRuleCollection> consists of <xref:System.Web.Configuration.AuthorizationRule> objects. An <xref:System.Web.Configuration.AuthorizationRule> object contains an <xref:System.Web.Configuration.AuthorizationRule.Action%2A> property, a <xref:System.Web.Configuration.AuthorizationRule.Users%2A> property, and a <xref:System.Web.Configuration.AuthorizationRule.Verbs%2A> property. These properties can be set to allow or deny access to a Web Parts resource.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("", IsDefaultCollection=true)]

      public System.Web.Configuration.AuthorizationRuleCollection Rules { get; }
    return:
      type: System.Web.Configuration.AuthorizationRuleCollection
      description: An <xref href="System.Web.Configuration.AuthorizationRuleCollection"></xref> object.
  overload: System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/WebPartsPersonalizationAuthorization.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.#ctor
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: WebPartsPersonalizationAuthorization()
  nameWithType: WebPartsPersonalizationAuthorization.WebPartsPersonalizationAuthorization()
  fullName: WebPartsPersonalizationAuthorization.WebPartsPersonalizationAuthorization()
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: Properties
  nameWithType: WebPartsPersonalizationAuthorization.Properties
  fullName: WebPartsPersonalizationAuthorization.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: Rules
  nameWithType: WebPartsPersonalizationAuthorization.Rules
  fullName: WebPartsPersonalizationAuthorization.Rules
- uid: System.Web.Configuration.AuthorizationRuleCollection
  parent: System.Web.Configuration
  isExternal: false
  name: AuthorizationRuleCollection
  nameWithType: AuthorizationRuleCollection
  fullName: System.Web.Configuration.AuthorizationRuleCollection
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.#ctor*
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: WebPartsPersonalizationAuthorization
  nameWithType: WebPartsPersonalizationAuthorization.WebPartsPersonalizationAuthorization
  fullName: WebPartsPersonalizationAuthorization.WebPartsPersonalizationAuthorization
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/WebPartsPersonalizationAuthorization.xml
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties*
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: Properties
  nameWithType: WebPartsPersonalizationAuthorization.Properties
  fullName: WebPartsPersonalizationAuthorization.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/WebPartsPersonalizationAuthorization.xml
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules*
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: Rules
  nameWithType: WebPartsPersonalizationAuthorization.Rules
  fullName: WebPartsPersonalizationAuthorization.Rules
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/WebPartsPersonalizationAuthorization.xml
