### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  commentId: T:System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  id: NonDualMessageSecurityOverHttpElement
  children:
  - System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.#ctor
  - System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  - System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.Properties
  langs:
  - csharp
  name: NonDualMessageSecurityOverHttpElement
  nameWithType: NonDualMessageSecurityOverHttpElement
  fullName: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents the configuration settings for the security of a message sent using HTTP for non-duplex service contracts. This class cannot be inherited.
  syntax:
    content: 'public sealed class NonDualMessageSecurityOverHttpElement : System.ServiceModel.Configuration.MessageSecurityOverHttpElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.MessageSecurityOverHttpElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.MessageSecurityOverHttpElement.AlgorithmSuite
  - System.ServiceModel.Configuration.MessageSecurityOverHttpElement.ClientCredentialType
  - System.ServiceModel.Configuration.MessageSecurityOverHttpElement.NegotiateServiceCredential
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NonDualMessageSecurityOverHttpElement.xml
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.#ctor
  commentId: M:System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  langs:
  - csharp
  name: NonDualMessageSecurityOverHttpElement()
  nameWithType: NonDualMessageSecurityOverHttpElement.NonDualMessageSecurityOverHttpElement()
  fullName: NonDualMessageSecurityOverHttpElement.NonDualMessageSecurityOverHttpElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement"></xref> class.
  syntax:
    content: public NonDualMessageSecurityOverHttpElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NonDualMessageSecurityOverHttpElement.xml
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  commentId: P:System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  id: EstablishSecurityContext
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  langs:
  - csharp
  name: EstablishSecurityContext
  nameWithType: NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  fullName: NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets a boolean value that specifies whether security context is established.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("establishSecurityContext", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public bool EstablishSecurityContext { get; set; }
    return:
      type: System.Boolean
      description: '`true` if security context is established; otherwise, `false`.'
  overload: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NonDualMessageSecurityOverHttpElement.xml
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.Properties
  commentId: P:System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  langs:
  - csharp
  name: Properties
  nameWithType: NonDualMessageSecurityOverHttpElement.Properties
  fullName: NonDualMessageSecurityOverHttpElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NonDualMessageSecurityOverHttpElement.xml
references:
- uid: System.ServiceModel.Configuration.MessageSecurityOverHttpElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: MessageSecurityOverHttpElement
  nameWithType: MessageSecurityOverHttpElement
  fullName: System.ServiceModel.Configuration.MessageSecurityOverHttpElement
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.#ctor
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  isExternal: false
  name: NonDualMessageSecurityOverHttpElement()
  nameWithType: NonDualMessageSecurityOverHttpElement.NonDualMessageSecurityOverHttpElement()
  fullName: NonDualMessageSecurityOverHttpElement.NonDualMessageSecurityOverHttpElement()
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  isExternal: false
  name: EstablishSecurityContext
  nameWithType: NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  fullName: NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.Properties
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  isExternal: false
  name: Properties
  nameWithType: NonDualMessageSecurityOverHttpElement.Properties
  fullName: NonDualMessageSecurityOverHttpElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.#ctor*
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  isExternal: false
  name: NonDualMessageSecurityOverHttpElement
  nameWithType: NonDualMessageSecurityOverHttpElement.NonDualMessageSecurityOverHttpElement
  fullName: NonDualMessageSecurityOverHttpElement.NonDualMessageSecurityOverHttpElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NonDualMessageSecurityOverHttpElement.xml
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext*
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  isExternal: false
  name: EstablishSecurityContext
  nameWithType: NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  fullName: NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NonDualMessageSecurityOverHttpElement.xml
- uid: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement.Properties*
  parent: System.ServiceModel.Configuration.NonDualMessageSecurityOverHttpElement
  isExternal: false
  name: Properties
  nameWithType: NonDualMessageSecurityOverHttpElement.Properties
  fullName: NonDualMessageSecurityOverHttpElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NonDualMessageSecurityOverHttpElement.xml
