### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Routing.Configuration.BackupEndpointElement
  commentId: T:System.ServiceModel.Routing.Configuration.BackupEndpointElement
  id: BackupEndpointElement
  children:
  - System.ServiceModel.Routing.Configuration.BackupEndpointElement.#ctor
  - System.ServiceModel.Routing.Configuration.BackupEndpointElement.EndpointName
  langs:
  - csharp
  name: BackupEndpointElement
  nameWithType: BackupEndpointElement
  fullName: System.ServiceModel.Routing.Configuration.BackupEndpointElement
  type: Class
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: Represents a configuration element that defines a backup endpoint element.
  syntax:
    content: 'public class BackupEndpointElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/BackupEndpointElement.xml
- uid: System.ServiceModel.Routing.Configuration.BackupEndpointElement.#ctor
  commentId: M:System.ServiceModel.Routing.Configuration.BackupEndpointElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Routing.Configuration.BackupEndpointElement
  langs:
  - csharp
  name: BackupEndpointElement()
  nameWithType: BackupEndpointElement.BackupEndpointElement()
  fullName: BackupEndpointElement.BackupEndpointElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: Creates a new instance of the <xref href="System.ServiceModel.Routing.Configuration.BackupEndpointElement"></xref> class.
  syntax:
    content: public BackupEndpointElement ();
    parameters: []
  overload: System.ServiceModel.Routing.Configuration.BackupEndpointElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/BackupEndpointElement.xml
- uid: System.ServiceModel.Routing.Configuration.BackupEndpointElement.EndpointName
  commentId: P:System.ServiceModel.Routing.Configuration.BackupEndpointElement.EndpointName
  id: EndpointName
  parent: System.ServiceModel.Routing.Configuration.BackupEndpointElement
  langs:
  - csharp
  name: EndpointName
  nameWithType: BackupEndpointElement.EndpointName
  fullName: BackupEndpointElement.EndpointName
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: Gets or sets the name used to identify this endpoint in the configuration file.
  remarks: The specified name acts as a key that references a configured client endpoint element that has the same name.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("endpointName", DefaultValue=Mono.Cecil.CustomAttributeArgument, Options=System.Configuration.ConfigurationPropertyOptions.IsRequired)]

      public string EndpointName { get; set; }
    return:
      type: System.String
      description: The name.
  overload: System.ServiceModel.Routing.Configuration.BackupEndpointElement.EndpointName*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/BackupEndpointElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Routing.Configuration.BackupEndpointElement.#ctor
  parent: System.ServiceModel.Routing.Configuration.BackupEndpointElement
  isExternal: false
  name: BackupEndpointElement()
  nameWithType: BackupEndpointElement.BackupEndpointElement()
  fullName: BackupEndpointElement.BackupEndpointElement()
- uid: System.ServiceModel.Routing.Configuration.BackupEndpointElement.EndpointName
  parent: System.ServiceModel.Routing.Configuration.BackupEndpointElement
  isExternal: false
  name: EndpointName
  nameWithType: BackupEndpointElement.EndpointName
  fullName: BackupEndpointElement.EndpointName
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Routing.Configuration.BackupEndpointElement.#ctor*
  parent: System.ServiceModel.Routing.Configuration.BackupEndpointElement
  isExternal: false
  name: BackupEndpointElement
  nameWithType: BackupEndpointElement.BackupEndpointElement
  fullName: BackupEndpointElement.BackupEndpointElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/BackupEndpointElement.xml
- uid: System.ServiceModel.Routing.Configuration.BackupEndpointElement.EndpointName*
  parent: System.ServiceModel.Routing.Configuration.BackupEndpointElement
  isExternal: false
  name: EndpointName
  nameWithType: BackupEndpointElement.EndpointName
  fullName: BackupEndpointElement.EndpointName
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/BackupEndpointElement.xml
