### YamlMime:ManagedReference
items:
- uid: System.Configuration.SubclassTypeValidatorAttribute
  commentId: T:System.Configuration.SubclassTypeValidatorAttribute
  id: SubclassTypeValidatorAttribute
  children:
  - System.Configuration.SubclassTypeValidatorAttribute.#ctor(System.Type)
  - System.Configuration.SubclassTypeValidatorAttribute.BaseClass
  - System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: SubclassTypeValidatorAttribute
  nameWithType: SubclassTypeValidatorAttribute
  fullName: System.Configuration.SubclassTypeValidatorAttribute
  type: Class
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Declaratively instructs the .NET Framework to perform validation on a configuration property. This class cannot be inherited.
  remarks: "You use the <xref:System.Configuration.IntegerValidatorAttribute> attribute to decorate a configuration property. This is to instruct the .NET Framework to validate the property using a <xref:System.Configuration.SubclassTypeValidatorAttribute> attribute, and pass to it the value of the decorating parameters.  \n  \n You can apply <xref:System.Configuration.SubclassTypeValidatorAttribute> attributes to property types only."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SubclassTypeValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Object
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.AttributeUsageAttribute
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SubclassTypeValidatorAttribute.xml
- uid: System.Configuration.SubclassTypeValidatorAttribute.#ctor(System.Type)
  commentId: M:System.Configuration.SubclassTypeValidatorAttribute.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.SubclassTypeValidatorAttribute
  langs:
  - csharp
  name: SubclassTypeValidatorAttribute(Type)
  nameWithType: SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute(Type)
  fullName: SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute(Type)
  type: Constructor
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.SubclassTypeValidatorAttribute"></xref> class.
  remarks: You use this constructor in the attributed model to ensure that the value assigned to the related property is a base class.
  syntax:
    content: public SubclassTypeValidatorAttribute (Type baseClass);
    parameters:
    - id: baseClass
      type: System.Type
      description: The base class type.
  overload: System.Configuration.SubclassTypeValidatorAttribute.#ctor*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SubclassTypeValidatorAttribute.xml
- uid: System.Configuration.SubclassTypeValidatorAttribute.BaseClass
  commentId: P:System.Configuration.SubclassTypeValidatorAttribute.BaseClass
  id: BaseClass
  parent: System.Configuration.SubclassTypeValidatorAttribute
  langs:
  - csharp
  name: BaseClass
  nameWithType: SubclassTypeValidatorAttribute.BaseClass
  fullName: SubclassTypeValidatorAttribute.BaseClass
  type: Property
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Gets the base type of the object being validated.
  syntax:
    content: public Type BaseClass { get; }
    return:
      type: System.Type
      description: The base type of the object being validated.
  overload: System.Configuration.SubclassTypeValidatorAttribute.BaseClass*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SubclassTypeValidatorAttribute.xml
- uid: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
  commentId: P:System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.SubclassTypeValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: SubclassTypeValidatorAttribute.ValidatorInstance
  fullName: SubclassTypeValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Gets the validator attribute instance.
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: The current <xref href="System.Configuration.ConfigurationValidatorBase"></xref> instance.
  overload: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SubclassTypeValidatorAttribute.xml
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorAttribute
  nameWithType: ConfigurationValidatorAttribute
  fullName: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.SubclassTypeValidatorAttribute.#ctor(System.Type)
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: SubclassTypeValidatorAttribute(Type)
  nameWithType: SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute(Type)
  fullName: SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute(Type)
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.SubclassTypeValidatorAttribute.BaseClass
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: BaseClass
  nameWithType: SubclassTypeValidatorAttribute.BaseClass
  fullName: SubclassTypeValidatorAttribute.BaseClass
- uid: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: SubclassTypeValidatorAttribute.ValidatorInstance
  fullName: SubclassTypeValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.SubclassTypeValidatorAttribute.#ctor*
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: SubclassTypeValidatorAttribute
  nameWithType: SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute
  fullName: SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SubclassTypeValidatorAttribute.xml
- uid: System.Configuration.SubclassTypeValidatorAttribute.BaseClass*
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: BaseClass
  nameWithType: SubclassTypeValidatorAttribute.BaseClass
  fullName: SubclassTypeValidatorAttribute.BaseClass
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SubclassTypeValidatorAttribute.xml
- uid: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: SubclassTypeValidatorAttribute.ValidatorInstance
  fullName: SubclassTypeValidatorAttribute.ValidatorInstance
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SubclassTypeValidatorAttribute.xml
