### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.Converter
  commentId: T:System.Web.Configuration.Converter
  id: Converter
  children:
  - System.Web.Configuration.Converter.#ctor
  - System.Web.Configuration.Converter.Name
  - System.Web.Configuration.Converter.Properties
  - System.Web.Configuration.Converter.Type
  langs:
  - csharp
  name: Converter
  nameWithType: Converter
  fullName: System.Web.Configuration.Converter
  type: Class
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: Represents a configuration element in a configuration file.
  remarks: "The <xref:System.Web.Configuration.Converter> class enables you to programmatically access and modify the configuration settings related to converters that are used by AJAX-enabled ASP.NET applications.  \n  \n To create custom conversion functionality, you can create a class that inherits from the <xref:System.Web.Script.Serialization.JavaScriptConverter> class. After the converter has been created, you can register it for use in the configuration file of your Web application."
  example:
  - "The following configuration file excerpt shows how to declaratively specify values for properties of the <xref:System.Web.Configuration.Converter> class.  \n  \n```  \n<system.web.extensions>  \n  <scripting>  \n    <webServices>  \n      <jsonSerialization>  \n        <converters>  \n          <add name=\"ConvertMe\" type=\"Acme.SubAcme.ConvertMeTypeConverter\" />  \n        </converters>  \n      </jsonSerialization>  \n    </webServices>  \n  </scripting>  \n</system.web.extensions>  \n```  \n  \n The following example demonstrates how to access <xref:System.Web.Configuration.Converter> programmatically.  \n  \n [!code-csharp[System.Web.Configuration#3](~/samples/snippets/csharp/VS_Snippets_Atlas/System.Web.Configuration/CS/App_Code/ConfigSectionSample.cs#3)]\n [!code-vb[System.Web.Configuration#3](~/samples/snippets/visualbasic/VS_Snippets_Atlas/System.Web.Configuration/VB/App_Code/ConfigSectionSample.vb#3)]"
  syntax:
    content: 'public class Converter : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/Converter.xml
- uid: System.Web.Configuration.Converter.#ctor
  commentId: M:System.Web.Configuration.Converter.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.Converter
  langs:
  - csharp
  name: Converter()
  nameWithType: Converter.Converter()
  fullName: Converter.Converter()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Configuration.Converter"></xref> class.
  syntax:
    content: public Converter ();
    parameters: []
  overload: System.Web.Configuration.Converter.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/Converter.xml
- uid: System.Web.Configuration.Converter.Name
  commentId: P:System.Web.Configuration.Converter.Name
  id: Name
  parent: System.Web.Configuration.Converter
  langs:
  - csharp
  name: Name
  nameWithType: Converter.Name
  fullName: Converter.Name
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: Gets or sets the unique identifier for the converter.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("name", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsKey=true, IsRequired=true)]

      [System.Configuration.StringValidator(MinLength=1)]

      public string Name { get; set; }
    return:
      type: System.String
      description: The unique identifier for the converter.
  overload: System.Web.Configuration.Converter.Name*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/Converter.xml
- uid: System.Web.Configuration.Converter.Properties
  commentId: P:System.Web.Configuration.Converter.Properties
  id: Properties
  parent: System.Web.Configuration.Converter
  langs:
  - csharp
  name: Properties
  nameWithType: Converter.Properties
  fullName: Converter.Properties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: Gets a collection of configuration-element properties.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: A <xref href="System.Configuration.ConfigurationPropertyCollection"></xref> object.
  overload: System.Web.Configuration.Converter.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/Converter.xml
- uid: System.Web.Configuration.Converter.Type
  commentId: P:System.Web.Configuration.Converter.Type
  id: Type
  parent: System.Web.Configuration.Converter
  langs:
  - csharp
  name: Type
  nameWithType: Converter.Type
  fullName: Converter.Type
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: Gets or sets the fully qualified type name of the <xref href="System.Web.Script.Serialization.JavaScriptConverter"></xref> object.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("type", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsRequired=true)]

      [System.Configuration.StringValidator(MinLength=1)]

      public string Type { get; set; }
    return:
      type: System.String
      description: The fully qualified type name of the <xref href="System.Web.Script.Serialization.JavaScriptConverter"></xref> object.
  overload: System.Web.Configuration.Converter.Type*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/Converter.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.Converter.#ctor
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Converter()
  nameWithType: Converter.Converter()
  fullName: Converter.Converter()
- uid: System.Web.Configuration.Converter.Name
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Name
  nameWithType: Converter.Name
  fullName: Converter.Name
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.Converter.Properties
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Properties
  nameWithType: Converter.Properties
  fullName: Converter.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.Converter.Type
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Type
  nameWithType: Converter.Type
  fullName: Converter.Type
- uid: System.Web.Configuration.Converter.#ctor*
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Converter
  nameWithType: Converter.Converter
  fullName: Converter.Converter
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/Converter.xml
- uid: System.Web.Configuration.Converter.Name*
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Name
  nameWithType: Converter.Name
  fullName: Converter.Name
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/Converter.xml
- uid: System.Web.Configuration.Converter.Properties*
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Properties
  nameWithType: Converter.Properties
  fullName: Converter.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/Converter.xml
- uid: System.Web.Configuration.Converter.Type*
  parent: System.Web.Configuration.Converter
  isExternal: false
  name: Type
  nameWithType: Converter.Type
  fullName: Converter.Type
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/Converter.xml
