### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.InstallException
  commentId: T:System.Configuration.Install.InstallException
  id: InstallException
  children:
  - System.Configuration.Install.InstallException.#ctor
  - System.Configuration.Install.InstallException.#ctor(System.String)
  - System.Configuration.Install.InstallException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.Install.InstallException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: InstallException
  nameWithType: InstallException
  fullName: System.Configuration.Install.InstallException
  type: Class
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: The exception that is thrown when an error occurs during the commit, rollback, or uninstall phase of an installation.
  remarks: ''
  example:
  - "The following example, plus the examples in the <xref:System.Configuration.Install.InstallException.%23ctor%2A> constructors, together make up an example showing an assembly having its own installer. The installer is named `MyInstaller`, which has an attribute `RunInstallerAttribute`, indicating that this installer will be invoked by [Installutil.exe (Installer Tool)](~/docs/framework/tools/installutil-exe-installer-tool.md). [Installutil.exe (Installer Tool)](~/docs/framework/tools/installutil-exe-installer-tool.md) calls the methods <xref:System.Configuration.Install.Installer.Commit%2A>, <xref:System.Configuration.Install.Installer.Rollback%2A>, <xref:System.Configuration.Install.Installer.Install%2A> and <xref:System.Configuration.Install.Installer.Uninstall%2A>. The code in <xref:System.Configuration.Install.Installer.Commit%2A> presumes that a file named `FileDoesNotExist.txt` exists before the installation of the assembly can be committed. If the file `FileDoesNotExist.txt` does not exist, <xref:System.Configuration.Install.Installer.Commit%2A> raises an <xref:System.Configuration.Install.InstallException>. The same is the case with <xref:System.Configuration.Install.Installer.Uninstall%2A> in which an uninstallation will only happen if a file named `FileDoesNotExist.txt` exists. Otherwise it raises an <xref:System.Configuration.Install.InstallException>. In <xref:System.Configuration.Install.Installer.Rollback%2A>, a code fragment is executed, which might raise an exception. If the exception is raised, it is caught and an <xref:System.Configuration.Install.InstallException> is raised with that exception being passed to it.  \n  \n> [!NOTE]\n>  Run this example with the help of Installutil.exe. Type this in the command prompt:  \n  \n `Installutil InstallException.exe`  \n  \n -or-  \n  \n `Installutil /u InstallException.exe`  \n  \n [!code-cpp[InstallException#1](~/samples/snippets/cpp/VS_Snippets_CLR/InstallException/CPP/installexception.cpp#1)]\n [!code-csharp[InstallException#1](~/samples/snippets/csharp/VS_Snippets_CLR/InstallException/CS/installexception.cs#1)]\n [!code-vb[InstallException#1](~/samples/snippets/visualbasic/VS_Snippets_CLR/InstallException/VB/installexception.vb#1)]"
  syntax:
    content: 'public class InstallException : SystemException'
  inheritance:
  - System.Object
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers:
  - System.Exception.Data
  - System.Exception.GetBaseException
  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Exception.GetType
  - System.Exception.HelpLink
  - System.Exception.HResult
  - System.Exception.InnerException
  - System.Exception.Message
  - System.Exception.SerializeObjectState
  - System.Exception.Source
  - System.Exception.StackTrace
  - System.Exception.TargetSite
  - System.Exception.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Install/InstallException.xml
- uid: System.Configuration.Install.InstallException.#ctor
  commentId: M:System.Configuration.Install.InstallException.#ctor
  id: '#ctor'
  parent: System.Configuration.Install.InstallException
  langs:
  - csharp
  name: InstallException()
  nameWithType: InstallException.InstallException()
  fullName: InstallException.InstallException()
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: Initializes a new instance of the <xref href="System.Configuration.Install.InstallException"></xref> class.
  remarks: ''
  example:
  - "The following example demonstrates the <xref:System.Configuration.Install.InstallException.%23ctor%2A> constructor. It is a part of the example of the <xref:System.Configuration.Install.InstallException> class.  \n  \n In this example, Installutil.exe calls the <xref:System.Configuration.Install.Installer.Commit%2A> method. The code in <xref:System.Configuration.Install.Installer.Commit%2A> presumes that a file named `FileDoesNotExist.txt` exists before the installation of the assembly can be committed. If the file `FileDoesNotExist.txt` does not exist, <xref:System.Configuration.Install.Installer.Commit%2A> raises an <xref:System.Configuration.Install.InstallException>.  \n  \n> [!NOTE]\n>  This example shows how to use one of the overloaded versions of the <xref:System.Configuration.Install.InstallException> constructor. For other examples that might be available, see the individual overload topics.  \n  \n [!code-cpp[InstallException#2](~/samples/snippets/cpp/VS_Snippets_CLR/InstallException/CPP/installexception.cpp#2)]\n [!code-csharp[InstallException#2](~/samples/snippets/csharp/VS_Snippets_CLR/InstallException/CS/installexception.cs#2)]\n [!code-vb[InstallException#2](~/samples/snippets/visualbasic/VS_Snippets_CLR/InstallException/VB/installexception.vb#2)]"
  syntax:
    content: public InstallException ();
    parameters: []
  overload: System.Configuration.Install.InstallException.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Install/InstallException.xml
- uid: System.Configuration.Install.InstallException.#ctor(System.String)
  commentId: M:System.Configuration.Install.InstallException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.Install.InstallException
  langs:
  - csharp
  name: InstallException(String)
  nameWithType: InstallException.InstallException(String)
  fullName: InstallException.InstallException(String)
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: Initializes a new instance of the <xref href="System.Configuration.Install.InstallException"></xref> class, and specifies the message to display to the user.
  remarks: ''
  example:
  - "The following example demonstrates the <xref:System.Configuration.Install.InstallException.%23ctor%2A> constructor. It is a part of the example of the <xref:System.Configuration.Install.InstallException> class.  \n  \n In this example, Installutil.exe calls the <xref:System.Configuration.Install.Installer.Uninstall%2A> method. Uninstallation will only happen if a file named `FileDoesNotExist.txt` exists. Otherwise it raises an <xref:System.Configuration.Install.InstallException>.  \n  \n> [!NOTE]\n>  This example shows how to use one of the overloaded versions of the <xref:System.Configuration.Install.InstallException> constructor. For other examples that might be available, see the individual overload topics.  \n  \n [!code-cpp[InstallException#4](~/samples/snippets/cpp/VS_Snippets_CLR/InstallException/CPP/installexception.cpp#4)]\n [!code-csharp[InstallException#4](~/samples/snippets/csharp/VS_Snippets_CLR/InstallException/CS/installexception.cs#4)]\n [!code-vb[InstallException#4](~/samples/snippets/visualbasic/VS_Snippets_CLR/InstallException/VB/installexception.vb#4)]"
  syntax:
    content: public InstallException (string message);
    parameters:
    - id: message
      type: System.String
      description: The message to display to the user.
  overload: System.Configuration.Install.InstallException.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Install/InstallException.xml
- uid: System.Configuration.Install.InstallException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  commentId: M:System.Configuration.Install.InstallException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Configuration.Install.InstallException
  langs:
  - csharp
  name: InstallException(SerializationInfo, StreamingContext)
  nameWithType: InstallException.InstallException(SerializationInfo, StreamingContext)
  fullName: InstallException.InstallException(SerializationInfo, StreamingContext)
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: Initializes a new instance of the <xref href="System.Configuration.Install.InstallException"></xref> class with serialized data.
  syntax:
    content: protected InstallException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: The <xref href="System.Runtime.Serialization.SerializationInfo"></xref> that holds the serialized object data about the exception being thrown.
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: The <xref href="System.Runtime.Serialization.StreamingContext"></xref> that contains contextual information about the source or destination.
  overload: System.Configuration.Install.InstallException.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Install/InstallException.xml
- uid: System.Configuration.Install.InstallException.#ctor(System.String,System.Exception)
  commentId: M:System.Configuration.Install.InstallException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Configuration.Install.InstallException
  langs:
  - csharp
  name: InstallException(String, Exception)
  nameWithType: InstallException.InstallException(String, Exception)
  fullName: InstallException.InstallException(String, Exception)
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: Initializes a new instance of the <xref href="System.Configuration.Install.InstallException"></xref> class, and specifies the message to display to the user, and a reference to the inner exception that is the cause of this exception.
  syntax:
    content: public InstallException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: The message to display to the user.
    - id: innerException
      type: System.Exception
      description: The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.
  overload: System.Configuration.Install.InstallException.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Install/InstallException.xml
references:
- uid: System.SystemException
  parent: System
  isExternal: false
  name: SystemException
  nameWithType: SystemException
  fullName: System.SystemException
- uid: System.Configuration.Install.InstallException.#ctor
  parent: System.Configuration.Install.InstallException
  isExternal: false
  name: InstallException()
  nameWithType: InstallException.InstallException()
  fullName: InstallException.InstallException()
- uid: System.Configuration.Install.InstallException.#ctor(System.String)
  parent: System.Configuration.Install.InstallException
  isExternal: false
  name: InstallException(String)
  nameWithType: InstallException.InstallException(String)
  fullName: InstallException.InstallException(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Install.InstallException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.Install.InstallException
  isExternal: false
  name: InstallException(SerializationInfo, StreamingContext)
  nameWithType: InstallException.InstallException(SerializationInfo, StreamingContext)
  fullName: InstallException.InstallException(SerializationInfo, StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: false
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.Install.InstallException.#ctor(System.String,System.Exception)
  parent: System.Configuration.Install.InstallException
  isExternal: false
  name: InstallException(String, Exception)
  nameWithType: InstallException.InstallException(String, Exception)
  fullName: InstallException.InstallException(String, Exception)
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Configuration.Install.InstallException.#ctor*
  parent: System.Configuration.Install.InstallException
  isExternal: false
  name: InstallException
  nameWithType: InstallException.InstallException
  fullName: InstallException.InstallException
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Install/InstallException.xml
