### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  commentId: T:System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  id: ApplicationContainerSettingsElement
  children:
  - System.ServiceModel.Configuration.ApplicationContainerSettingsElement.#ctor
  - System.ServiceModel.Configuration.ApplicationContainerSettingsElement.PackageFullName
  - System.ServiceModel.Configuration.ApplicationContainerSettingsElement.Properties
  - System.ServiceModel.Configuration.ApplicationContainerSettingsElement.SessionId
  langs:
  - csharp
  name: ApplicationContainerSettingsElement
  nameWithType: ApplicationContainerSettingsElement
  fullName: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Specifies settings for the application container settings element.
  syntax:
    content: 'public sealed class ApplicationContainerSettingsElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ApplicationContainerSettingsElement.xml
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.#ctor
  commentId: M:System.ServiceModel.Configuration.ApplicationContainerSettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  langs:
  - csharp
  name: ApplicationContainerSettingsElement()
  nameWithType: ApplicationContainerSettingsElement.ApplicationContainerSettingsElement()
  fullName: ApplicationContainerSettingsElement.ApplicationContainerSettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.ApplicationContainerSettingsElement"></xref> class.
  syntax:
    content: public ApplicationContainerSettingsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ApplicationContainerSettingsElement.xml
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.PackageFullName
  commentId: P:System.ServiceModel.Configuration.ApplicationContainerSettingsElement.PackageFullName
  id: PackageFullName
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  langs:
  - csharp
  name: PackageFullName
  nameWithType: ApplicationContainerSettingsElement.PackageFullName
  fullName: ApplicationContainerSettingsElement.PackageFullName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the full name of the package.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("packageFullName", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      [System.Configuration.StringValidator(MinLength=0)]

      public string PackageFullName { get; set; }
    return:
      type: System.String
      description: The full name of the package.
  overload: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.PackageFullName*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ApplicationContainerSettingsElement.xml
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.Properties
  commentId: P:System.ServiceModel.Configuration.ApplicationContainerSettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: ApplicationContainerSettingsElement.Properties
  fullName: ApplicationContainerSettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ApplicationContainerSettingsElement.xml
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.SessionId
  commentId: P:System.ServiceModel.Configuration.ApplicationContainerSettingsElement.SessionId
  id: SessionId
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  langs:
  - csharp
  name: SessionId
  nameWithType: ApplicationContainerSettingsElement.SessionId
  fullName: ApplicationContainerSettingsElement.SessionId
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the unique session identifier for the <xref href="System.ServiceModel.Configuration.ApplicationContainerSettingsElement"></xref>.
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(System.ServiceModel.Configuration.SessionIdTypeConvertor))]

      [System.Configuration.ConfigurationProperty("sessionId", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public int SessionId { get; set; }
    return:
      type: System.Int32
      description: The unique session identifier.
  overload: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.SessionId*
  exceptions: []
  attributes:
  - type: System.ComponentModel.TypeConverterAttribute
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ApplicationContainerSettingsElement.xml
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.#ctor
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  isExternal: false
  name: ApplicationContainerSettingsElement()
  nameWithType: ApplicationContainerSettingsElement.ApplicationContainerSettingsElement()
  fullName: ApplicationContainerSettingsElement.ApplicationContainerSettingsElement()
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.PackageFullName
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  isExternal: false
  name: PackageFullName
  nameWithType: ApplicationContainerSettingsElement.PackageFullName
  fullName: ApplicationContainerSettingsElement.PackageFullName
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.Properties
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  isExternal: false
  name: Properties
  nameWithType: ApplicationContainerSettingsElement.Properties
  fullName: ApplicationContainerSettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.SessionId
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  isExternal: false
  name: SessionId
  nameWithType: ApplicationContainerSettingsElement.SessionId
  fullName: ApplicationContainerSettingsElement.SessionId
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.#ctor*
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  isExternal: false
  name: ApplicationContainerSettingsElement
  nameWithType: ApplicationContainerSettingsElement.ApplicationContainerSettingsElement
  fullName: ApplicationContainerSettingsElement.ApplicationContainerSettingsElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ApplicationContainerSettingsElement.xml
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.PackageFullName*
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  isExternal: false
  name: PackageFullName
  nameWithType: ApplicationContainerSettingsElement.PackageFullName
  fullName: ApplicationContainerSettingsElement.PackageFullName
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ApplicationContainerSettingsElement.xml
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.Properties*
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  isExternal: false
  name: Properties
  nameWithType: ApplicationContainerSettingsElement.Properties
  fullName: ApplicationContainerSettingsElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ApplicationContainerSettingsElement.xml
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.SessionId*
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  isExternal: false
  name: SessionId
  nameWithType: ApplicationContainerSettingsElement.SessionId
  fullName: ApplicationContainerSettingsElement.SessionId
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ApplicationContainerSettingsElement.xml
