### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ComMethodElementCollection
  commentId: T:System.ServiceModel.Configuration.ComMethodElementCollection
  id: ComMethodElementCollection
  children:
  - System.ServiceModel.Configuration.ComMethodElementCollection.#ctor
  - System.ServiceModel.Configuration.ComMethodElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ComMethodElementCollection.ThrowOnDuplicate
  langs:
  - csharp
  name: ComMethodElementCollection
  nameWithType: ComMethodElementCollection
  fullName: System.ServiceModel.Configuration.ComMethodElementCollection
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Contains a collection of <xref href="System.ServiceModel.Configuration.ComMethodElement"></xref> instances. This class cannot be inherited.
  syntax:
    content: >-
      [System.Configuration.ConfigurationCollection(typeof(System.ServiceModel.Configuration.ComMethodElement))]

      public sealed class ComMethodElementCollection : System.ServiceModel.Configuration.ServiceModelEnhancedConfigurationElementCollection<System.ServiceModel.Configuration.ComMethodElement>
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationElementCollection
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1
  - System.ServiceModel.Configuration.ServiceModelEnhancedConfigurationElementCollection`1
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.AddElementName
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseClear
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseGetAllKeys
  - System.Configuration.ConfigurationElementCollection.BaseGetKey(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseIndexOf(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseIsRemoved(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemove(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemoveAt(System.Int32)
  - System.Configuration.ConfigurationElementCollection.ClearElementName
  - System.Configuration.ConfigurationElementCollection.CopyTo(System.Configuration.ConfigurationElement[],System.Int32)
  - System.Configuration.ConfigurationElementCollection.Count
  - System.Configuration.ConfigurationElementCollection.CreateNewElement(System.String)
  - System.Configuration.ConfigurationElementCollection.EmitClear
  - System.Configuration.ConfigurationElementCollection.Equals(System.Object)
  - System.Configuration.ConfigurationElementCollection.GetEnumerator
  - System.Configuration.ConfigurationElementCollection.GetHashCode
  - System.Configuration.ConfigurationElementCollection.IsElementName(System.String)
  - System.Configuration.ConfigurationElementCollection.IsElementRemovable(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.IsModified
  - System.Configuration.ConfigurationElementCollection.IsReadOnly
  - System.Configuration.ConfigurationElementCollection.IsSynchronized
  - System.Configuration.ConfigurationElementCollection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElementCollection.RemoveElementName
  - System.Configuration.ConfigurationElementCollection.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.ResetModified
  - System.Configuration.ConfigurationElementCollection.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.SetReadOnly
  - System.Configuration.ConfigurationElementCollection.SyncRoot
  - System.Configuration.ConfigurationElementCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Configuration.ConfigurationElementCollection.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Add(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Clear
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CollectionType
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.ContainsKey(System.Object)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CopyTo(`0[],System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.ElementName
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.IndexOf(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Item(System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Item(System.Object)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Remove(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.RemoveAt(System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.RemoveAt(System.Object)
  - System.ServiceModel.Configuration.ServiceModelEnhancedConfigurationElementCollection`1.BaseAdd(System.Configuration.ConfigurationElement)
  extensionMethods:
  - System.Linq.Enumerable.Cast``1(System.Collections.IEnumerable)
  - System.Linq.Enumerable.OfType``1(System.Collections.IEnumerable)
  - System.Linq.ParallelEnumerable.AsParallel(System.Collections.IEnumerable)
  - System.Linq.Queryable.AsQueryable(System.Collections.IEnumerable)
  attributes:
  - type: System.Configuration.ConfigurationCollectionAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ComMethodElementCollection.xml
- uid: System.ServiceModel.Configuration.ComMethodElementCollection.#ctor
  commentId: M:System.ServiceModel.Configuration.ComMethodElementCollection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ComMethodElementCollection
  langs:
  - csharp
  name: ComMethodElementCollection()
  nameWithType: ComMethodElementCollection.ComMethodElementCollection()
  fullName: ComMethodElementCollection.ComMethodElementCollection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.ComMethodElementCollection"></xref> class.
  syntax:
    content: public ComMethodElementCollection ();
    parameters: []
  overload: System.ServiceModel.Configuration.ComMethodElementCollection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ComMethodElementCollection.xml
- uid: System.ServiceModel.Configuration.ComMethodElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  commentId: M:System.ServiceModel.Configuration.ComMethodElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ComMethodElementCollection
  langs:
  - csharp
  name: GetElementKey(ConfigurationElement)
  nameWithType: ComMethodElementCollection.GetElementKey(ConfigurationElement)
  fullName: ComMethodElementCollection.GetElementKey(ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override object GetElementKey (System.Configuration.ConfigurationElement element);
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
      description: To be added.
    return:
      type: System.Object
      description: To be added.
  overload: System.ServiceModel.Configuration.ComMethodElementCollection.GetElementKey*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ComMethodElementCollection.xml
- uid: System.ServiceModel.Configuration.ComMethodElementCollection.ThrowOnDuplicate
  commentId: P:System.ServiceModel.Configuration.ComMethodElementCollection.ThrowOnDuplicate
  id: ThrowOnDuplicate
  parent: System.ServiceModel.Configuration.ComMethodElementCollection
  langs:
  - csharp
  name: ThrowOnDuplicate
  nameWithType: ComMethodElementCollection.ThrowOnDuplicate
  fullName: ComMethodElementCollection.ThrowOnDuplicate
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override bool ThrowOnDuplicate { get; }
    return:
      type: System.Boolean
      description: To be added.
  overload: System.ServiceModel.Configuration.ComMethodElementCollection.ThrowOnDuplicate*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ComMethodElementCollection.xml
references:
- uid: System.ServiceModel.Configuration.ServiceModelEnhancedConfigurationElementCollection`1
  name: ServiceModelEnhancedConfigurationElementCollection<TConfigurationElement>
  nameWithType: ServiceModelEnhancedConfigurationElementCollection<TConfigurationElement>
  fullName: System.ServiceModel.Configuration.ServiceModelEnhancedConfigurationElementCollection<TConfigurationElement>
- uid: System.ServiceModel.Configuration.ComMethodElement
  name: ComMethodElement
  nameWithType: ComMethodElement
  fullName: System.ServiceModel.Configuration.ComMethodElement
- uid: System.ServiceModel.Configuration.ServiceModelEnhancedConfigurationElementCollection{System.ServiceModel.Configuration.ComMethodElement}
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelEnhancedConfigurationElementCollection<ComMethodElement>
  nameWithType: ServiceModelEnhancedConfigurationElementCollection<ComMethodElement>
  fullName: System.ServiceModel.Configuration.ServiceModelEnhancedConfigurationElementCollection<System.ServiceModel.Configuration.ComMethodElement>
  spec.csharp:
  - uid: System.ServiceModel.Configuration.ServiceModelEnhancedConfigurationElementCollection`1
    name: ServiceModelEnhancedConfigurationElementCollection
    nameWithType: ServiceModelEnhancedConfigurationElementCollection
    fullName: System.ServiceModel.Configuration.ServiceModelEnhancedConfigurationElementCollection
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Configuration.ComMethodElement
    name: ComMethodElement
    nameWithType: ComMethodElement
    fullName: System.ServiceModel.Configuration.ComMethodElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.ComMethodElementCollection.#ctor
  parent: System.ServiceModel.Configuration.ComMethodElementCollection
  isExternal: false
  name: ComMethodElementCollection()
  nameWithType: ComMethodElementCollection.ComMethodElementCollection()
  fullName: ComMethodElementCollection.ComMethodElementCollection()
- uid: System.ServiceModel.Configuration.ComMethodElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ComMethodElementCollection
  isExternal: false
  name: GetElementKey(ConfigurationElement)
  nameWithType: ComMethodElementCollection.GetElementKey(ConfigurationElement)
  fullName: ComMethodElementCollection.GetElementKey(ConfigurationElement)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ComMethodElementCollection.ThrowOnDuplicate
  parent: System.ServiceModel.Configuration.ComMethodElementCollection
  isExternal: false
  name: ThrowOnDuplicate
  nameWithType: ComMethodElementCollection.ThrowOnDuplicate
  fullName: ComMethodElementCollection.ThrowOnDuplicate
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.ComMethodElementCollection.#ctor*
  parent: System.ServiceModel.Configuration.ComMethodElementCollection
  isExternal: false
  name: ComMethodElementCollection
  nameWithType: ComMethodElementCollection.ComMethodElementCollection
  fullName: ComMethodElementCollection.ComMethodElementCollection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ComMethodElementCollection.xml
- uid: System.ServiceModel.Configuration.ComMethodElementCollection.GetElementKey*
  parent: System.ServiceModel.Configuration.ComMethodElementCollection
  isExternal: false
  name: GetElementKey
  nameWithType: ComMethodElementCollection.GetElementKey
  fullName: ComMethodElementCollection.GetElementKey
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ComMethodElementCollection.xml
- uid: System.ServiceModel.Configuration.ComMethodElementCollection.ThrowOnDuplicate*
  parent: System.ServiceModel.Configuration.ComMethodElementCollection
  isExternal: false
  name: ThrowOnDuplicate
  nameWithType: ComMethodElementCollection.ThrowOnDuplicate
  fullName: ComMethodElementCollection.ThrowOnDuplicate
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ComMethodElementCollection.xml
- uid: System.Linq.Enumerable.Cast``1(System.Collections.IEnumerable)
  parent: System.Linq.Enumerable
  isExternal: false
  name: Cast<TResult>(IEnumerable)
  nameWithType: Enumerable.Cast<TResult>(IEnumerable)
  fullName: Enumerable.Cast<TResult>(IEnumerable)
- uid: System.Linq.Enumerable.OfType``1(System.Collections.IEnumerable)
  parent: System.Linq.Enumerable
  isExternal: false
  name: OfType<TResult>(IEnumerable)
  nameWithType: Enumerable.OfType<TResult>(IEnumerable)
  fullName: Enumerable.OfType<TResult>(IEnumerable)
- uid: System.Linq.ParallelEnumerable.AsParallel(System.Collections.IEnumerable)
  parent: System.Linq.ParallelEnumerable
  isExternal: false
  name: AsParallel(IEnumerable)
  nameWithType: ParallelEnumerable.AsParallel(IEnumerable)
  fullName: ParallelEnumerable.AsParallel(IEnumerable)
- uid: System.Linq.Queryable.AsQueryable(System.Collections.IEnumerable)
  parent: System.Linq.Queryable
  isExternal: false
  name: AsQueryable(IEnumerable)
  nameWithType: Queryable.AsQueryable(IEnumerable)
  fullName: Queryable.AsQueryable(IEnumerable)
