### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.KnownTypesProvider
  commentId: T:System.Web.ApplicationServices.KnownTypesProvider
  id: KnownTypesProvider
  children:
  - System.Web.ApplicationServices.KnownTypesProvider.GetKnownTypes(System.Reflection.ICustomAttributeProvider)
  langs:
  - csharp
  name: KnownTypesProvider
  nameWithType: KnownTypesProvider
  fullName: System.Web.ApplicationServices.KnownTypesProvider
  type: Class
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: Creates an array of <xref href="System.Type"></xref> objects that contain the types of individual profile properties.
  syntax:
    content: public static class KnownTypesProvider
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.ApplicationServices/KnownTypesProvider.xml
  author: tdykstra
  ms.author: tdykstra
  manager: wpickett
- uid: System.Web.ApplicationServices.KnownTypesProvider.GetKnownTypes(System.Reflection.ICustomAttributeProvider)
  commentId: M:System.Web.ApplicationServices.KnownTypesProvider.GetKnownTypes(System.Reflection.ICustomAttributeProvider)
  id: GetKnownTypes(System.Reflection.ICustomAttributeProvider)
  parent: System.Web.ApplicationServices.KnownTypesProvider
  langs:
  - csharp
  name: GetKnownTypes(ICustomAttributeProvider)
  nameWithType: KnownTypesProvider.GetKnownTypes(ICustomAttributeProvider)
  fullName: System.Web.ApplicationServices.KnownTypesProvider.GetKnownTypes(ICustomAttributeProvider)
  type: Method
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: Creates an array of <xref href="System.Type"></xref> objects that contain the types of individual profile properties.
  syntax:
    content: public static Type[] GetKnownTypes (System.Reflection.ICustomAttributeProvider knownTypeAttributeTarget);
    parameters:
    - id: knownTypeAttributeTarget
      type: System.Reflection.ICustomAttributeProvider
      description: A provider object.
    return:
      type: System.Type[]
      description: An array of types of individual profile properties.
  overload: System.Web.ApplicationServices.KnownTypesProvider.GetKnownTypes*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.ApplicationServices/KnownTypesProvider.xml
  author: tdykstra
  ms.author: tdykstra
  manager: wpickett
references:
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.ApplicationServices.KnownTypesProvider.GetKnownTypes(System.Reflection.ICustomAttributeProvider)
  parent: System.Web.ApplicationServices.KnownTypesProvider
  isExternal: false
  name: GetKnownTypes(ICustomAttributeProvider)
  nameWithType: KnownTypesProvider.GetKnownTypes(ICustomAttributeProvider)
  fullName: System.Web.ApplicationServices.KnownTypesProvider.GetKnownTypes(ICustomAttributeProvider)
- uid: System.Type
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Type[]
  parent: System
  isExternal: false
  name: Type[]
  nameWithType: Type[]
  fullName: System.Type[]
  spec.csharp:
  - uid: System.Type
    name: Type
    nameWithType: Type
    fullName: System.Type
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Reflection.ICustomAttributeProvider
  parent: System.Reflection
  isExternal: false
  name: ICustomAttributeProvider
  nameWithType: ICustomAttributeProvider
  fullName: System.Reflection.ICustomAttributeProvider
- uid: System.Web.ApplicationServices.KnownTypesProvider.GetKnownTypes*
  parent: System.Web.ApplicationServices.KnownTypesProvider
  isExternal: false
  name: GetKnownTypes
  nameWithType: KnownTypesProvider.GetKnownTypes
  fullName: System.Web.ApplicationServices.KnownTypesProvider.GetKnownTypes
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.ApplicationServices/KnownTypesProvider.xml
