### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.BasicHttpSecurity
  commentId: T:System.ServiceModel.BasicHttpSecurity
  id: BasicHttpSecurity
  children:
  - System.ServiceModel.BasicHttpSecurity.#ctor
  - System.ServiceModel.BasicHttpSecurity.Message
  - System.ServiceModel.BasicHttpSecurity.Mode
  - System.ServiceModel.BasicHttpSecurity.ShouldSerializeMessage
  - System.ServiceModel.BasicHttpSecurity.ShouldSerializeTransport
  - System.ServiceModel.BasicHttpSecurity.Transport
  langs:
  - csharp
  name: BasicHttpSecurity
  nameWithType: BasicHttpSecurity
  fullName: System.ServiceModel.BasicHttpSecurity
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Configures the security settings of a `basicHttpBinding` binding.
  remarks: ''
  example:
  - >-
    [!code-csharp[S_UEBasicHttpBinding#8](~/samples/snippets/csharp/VS_Snippets_CFX/s_uebasichttpbinding/cs/snippets.cs#8)]
     [!code-vb[S_UEBasicHttpBinding#8](~/samples/snippets/visualbasic/VS_Snippets_CFX/s_uebasichttpbinding/vb/snippets.vb#8)]
  syntax:
    content: public sealed class BasicHttpSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/BasicHttpSecurity.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.BasicHttpSecurity.#ctor
  commentId: M:System.ServiceModel.BasicHttpSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.BasicHttpSecurity
  langs:
  - csharp
  name: BasicHttpSecurity()
  nameWithType: BasicHttpSecurity.BasicHttpSecurity()
  fullName: System.ServiceModel.BasicHttpSecurity.BasicHttpSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Initializes a new instance of the <xref href="System.ServiceModel.BasicHttpSecurity"></xref> class.
  syntax:
    content: public BasicHttpSecurity ();
    parameters: []
  overload: System.ServiceModel.BasicHttpSecurity.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/BasicHttpSecurity.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.BasicHttpSecurity.Message
  commentId: P:System.ServiceModel.BasicHttpSecurity.Message
  id: Message
  parent: System.ServiceModel.BasicHttpSecurity
  langs:
  - csharp
  name: Message
  nameWithType: BasicHttpSecurity.Message
  fullName: System.ServiceModel.BasicHttpSecurity.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Gets the message-level security settings for a `basicHttpBinding` binding.
  remarks: 'The default security settings are: a <xref:System.ServiceModel.BasicHttpMessageSecurity.ClientCredentialType%2A> of <xref:System.ServiceModel.BasicHttpMessageCredentialType>; and an <xref:System.ServiceModel.BasicHttpMessageSecurity.AlgorithmSuite%2A> of <xref:System.ServiceModel.Security.SecurityAlgorithmSuite.Basic256%2A>.'
  example:
  - >-
    [!code-csharp[S_UEBasicHttpBinding#9](~/samples/snippets/csharp/VS_Snippets_CFX/s_uebasichttpbinding/cs/snippets.cs#9)]
     [!code-vb[S_UEBasicHttpBinding#9](~/samples/snippets/visualbasic/VS_Snippets_CFX/s_uebasichttpbinding/vb/snippets.vb#9)]
  syntax:
    content: public System.ServiceModel.BasicHttpMessageSecurity Message { get; set; }
    return:
      type: System.ServiceModel.BasicHttpMessageSecurity
      description: A <xref href="System.ServiceModel.BasicHttpMessageSecurity"></xref>, which represents the message-level security settings for this binding.
  overload: System.ServiceModel.BasicHttpSecurity.Message*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/BasicHttpSecurity.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.BasicHttpSecurity.Mode
  commentId: P:System.ServiceModel.BasicHttpSecurity.Mode
  id: Mode
  parent: System.ServiceModel.BasicHttpSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: BasicHttpSecurity.Mode
  fullName: System.ServiceModel.BasicHttpSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Gets or sets the security mode for a `basicHttpBinding` binding.
  remarks: The value of this property affects which settings in <xref:System.ServiceModel.BasicHttpSecurity.Transport%2A> or <xref:System.ServiceModel.BasicHttpSecurity.Message%2A> become effective.
  example:
  - >-
    [!code-csharp[S_UEBasicHttpBinding#10](~/samples/snippets/csharp/VS_Snippets_CFX/s_uebasichttpbinding/cs/snippets.cs#10)]
     [!code-vb[S_UEBasicHttpBinding#10](~/samples/snippets/visualbasic/VS_Snippets_CFX/s_uebasichttpbinding/vb/snippets.vb#10)]
  syntax:
    content: public System.ServiceModel.BasicHttpSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.BasicHttpSecurityMode
      description: A value in the <xref href="System.ServiceModel.BasicHttpSecurityMode"></xref> enumeration. The default value for this property is <xref href="System.ServiceModel.BasicHttpSecurityMode.None"></xref>.
  overload: System.ServiceModel.BasicHttpSecurity.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: The value is not a legal value for <xref href="System.ServiceModel.BasicHttpSecurityMode"></xref>.
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/BasicHttpSecurity.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.BasicHttpSecurity.ShouldSerializeMessage
  commentId: M:System.ServiceModel.BasicHttpSecurity.ShouldSerializeMessage
  id: ShouldSerializeMessage
  parent: System.ServiceModel.BasicHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeMessage()
  nameWithType: BasicHttpSecurity.ShouldSerializeMessage()
  fullName: System.ServiceModel.BasicHttpSecurity.ShouldSerializeMessage()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Determines whether a message element should be serialized.
  syntax:
    content: public bool ShouldSerializeMessage ();
    parameters: []
    return:
      type: System.Boolean
      description: '`true` if the message should be serialized; otherwise, `false`.'
  overload: System.ServiceModel.BasicHttpSecurity.ShouldSerializeMessage*
  exceptions: []
  attributes: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/BasicHttpSecurity.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.BasicHttpSecurity.ShouldSerializeTransport
  commentId: M:System.ServiceModel.BasicHttpSecurity.ShouldSerializeTransport
  id: ShouldSerializeTransport
  parent: System.ServiceModel.BasicHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeTransport()
  nameWithType: BasicHttpSecurity.ShouldSerializeTransport()
  fullName: System.ServiceModel.BasicHttpSecurity.ShouldSerializeTransport()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Determines whether the transport element should be serialized.
  syntax:
    content: public bool ShouldSerializeTransport ();
    parameters: []
    return:
      type: System.Boolean
      description: '`true` if the transport element should be serialized; otherwise, `false`.'
  overload: System.ServiceModel.BasicHttpSecurity.ShouldSerializeTransport*
  exceptions: []
  attributes: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/BasicHttpSecurity.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.BasicHttpSecurity.Transport
  commentId: P:System.ServiceModel.BasicHttpSecurity.Transport
  id: Transport
  parent: System.ServiceModel.BasicHttpSecurity
  langs:
  - csharp
  name: Transport
  nameWithType: BasicHttpSecurity.Transport
  fullName: System.ServiceModel.BasicHttpSecurity.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: Gets the transport-level security settings for a `basicHttpBinding` binding.
  remarks: The <xref:System.ServiceModel.HttpTransportSecurity> object returned by this property contains properties that control authentication parameters for the HTTP transport.
  example:
  - >-
    [!code-csharp[S_UEBasicHttpBinding#11](~/samples/snippets/csharp/VS_Snippets_CFX/s_uebasichttpbinding/cs/snippets.cs#11)]
     [!code-vb[S_UEBasicHttpBinding#11](~/samples/snippets/visualbasic/VS_Snippets_CFX/s_uebasichttpbinding/vb/snippets.vb#11)]
  syntax:
    content: public System.ServiceModel.HttpTransportSecurity Transport { get; set; }
    return:
      type: System.ServiceModel.HttpTransportSecurity
      description: The transport-level security settings for a `basicHttpBinding` binding.
  overload: System.ServiceModel.BasicHttpSecurity.Transport*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/BasicHttpSecurity.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ArgumentOutOfRangeException
  parent: System
  isExternal: false
  name: ArgumentOutOfRangeException
  nameWithType: ArgumentOutOfRangeException
  fullName: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.BasicHttpSecurity.#ctor
  parent: System.ServiceModel.BasicHttpSecurity
  isExternal: false
  name: BasicHttpSecurity()
  nameWithType: BasicHttpSecurity.BasicHttpSecurity()
  fullName: System.ServiceModel.BasicHttpSecurity.BasicHttpSecurity()
- uid: System.ServiceModel.BasicHttpSecurity.Message
  parent: System.ServiceModel.BasicHttpSecurity
  isExternal: false
  name: Message
  nameWithType: BasicHttpSecurity.Message
  fullName: System.ServiceModel.BasicHttpSecurity.Message
- uid: System.ServiceModel.BasicHttpMessageSecurity
  parent: System.ServiceModel
  isExternal: false
  name: BasicHttpMessageSecurity
  nameWithType: BasicHttpMessageSecurity
  fullName: System.ServiceModel.BasicHttpMessageSecurity
- uid: System.ServiceModel.BasicHttpSecurity.Mode
  parent: System.ServiceModel.BasicHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: BasicHttpSecurity.Mode
  fullName: System.ServiceModel.BasicHttpSecurity.Mode
- uid: System.ServiceModel.BasicHttpSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: BasicHttpSecurityMode
  nameWithType: BasicHttpSecurityMode
  fullName: System.ServiceModel.BasicHttpSecurityMode
- uid: System.ServiceModel.BasicHttpSecurity.ShouldSerializeMessage
  parent: System.ServiceModel.BasicHttpSecurity
  isExternal: false
  name: ShouldSerializeMessage()
  nameWithType: BasicHttpSecurity.ShouldSerializeMessage()
  fullName: System.ServiceModel.BasicHttpSecurity.ShouldSerializeMessage()
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.BasicHttpSecurity.ShouldSerializeTransport
  parent: System.ServiceModel.BasicHttpSecurity
  isExternal: false
  name: ShouldSerializeTransport()
  nameWithType: BasicHttpSecurity.ShouldSerializeTransport()
  fullName: System.ServiceModel.BasicHttpSecurity.ShouldSerializeTransport()
- uid: System.ServiceModel.BasicHttpSecurity.Transport
  parent: System.ServiceModel.BasicHttpSecurity
  isExternal: false
  name: Transport
  nameWithType: BasicHttpSecurity.Transport
  fullName: System.ServiceModel.BasicHttpSecurity.Transport
- uid: System.ServiceModel.HttpTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: HttpTransportSecurity
  nameWithType: HttpTransportSecurity
  fullName: System.ServiceModel.HttpTransportSecurity
- uid: System.ServiceModel.BasicHttpSecurity.#ctor*
  parent: System.ServiceModel.BasicHttpSecurity
  isExternal: false
  name: BasicHttpSecurity
  nameWithType: BasicHttpSecurity.BasicHttpSecurity
  fullName: System.ServiceModel.BasicHttpSecurity.BasicHttpSecurity
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/BasicHttpSecurity.xml
- uid: System.ServiceModel.BasicHttpSecurity.Message*
  parent: System.ServiceModel.BasicHttpSecurity
  isExternal: false
  name: Message
  nameWithType: BasicHttpSecurity.Message
  fullName: System.ServiceModel.BasicHttpSecurity.Message
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/BasicHttpSecurity.xml
- uid: System.ServiceModel.BasicHttpSecurity.Mode*
  parent: System.ServiceModel.BasicHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: BasicHttpSecurity.Mode
  fullName: System.ServiceModel.BasicHttpSecurity.Mode
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/BasicHttpSecurity.xml
- uid: System.ServiceModel.BasicHttpSecurity.ShouldSerializeMessage*
  parent: System.ServiceModel.BasicHttpSecurity
  isExternal: false
  name: ShouldSerializeMessage
  nameWithType: BasicHttpSecurity.ShouldSerializeMessage
  fullName: System.ServiceModel.BasicHttpSecurity.ShouldSerializeMessage
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/BasicHttpSecurity.xml
- uid: System.ServiceModel.BasicHttpSecurity.ShouldSerializeTransport*
  parent: System.ServiceModel.BasicHttpSecurity
  isExternal: false
  name: ShouldSerializeTransport
  nameWithType: BasicHttpSecurity.ShouldSerializeTransport
  fullName: System.ServiceModel.BasicHttpSecurity.ShouldSerializeTransport
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/BasicHttpSecurity.xml
- uid: System.ServiceModel.BasicHttpSecurity.Transport*
  parent: System.ServiceModel.BasicHttpSecurity
  isExternal: false
  name: Transport
  nameWithType: BasicHttpSecurity.Transport
  fullName: System.ServiceModel.BasicHttpSecurity.Transport
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel/BasicHttpSecurity.xml
