### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FormsAuthenticationUser
  commentId: T:System.Web.Configuration.FormsAuthenticationUser
  id: FormsAuthenticationUser
  children:
  - System.Web.Configuration.FormsAuthenticationUser.#ctor(System.String,System.String)
  - System.Web.Configuration.FormsAuthenticationUser.Name
  - System.Web.Configuration.FormsAuthenticationUser.Password
  - System.Web.Configuration.FormsAuthenticationUser.Properties
  langs:
  - csharp
  name: FormsAuthenticationUser
  nameWithType: FormsAuthenticationUser
  fullName: System.Web.Configuration.FormsAuthenticationUser
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Configures the user's credentials for Web applications that use forms-based authentication.
  remarks: "The <xref:System.Web.Configuration.FormsAuthenticationUser> class provides a way to programmatically access and modify the  section of a configuration file.  \n  \n This type is part of a group that includes the <xref:System.Web.Configuration.FormsAuthenticationCredentials>, the <xref:System.Web.Configuration.FormsAuthenticationUserCollection>, and the <xref:System.Web.Configuration.FormsAuthenticationConfiguration> types. The types other than the collection type directly affect the underlying configuration tags.  \n  \n> [!NOTE]\n>  The <xref:System.Web.Configuration.FormsAuthenticationUser> can write information into the related section of the configuration file at machine, site, or application level only. Any attempt to write in a configuration file at a different level in the hierarchy will result in an error message generated by the parser. However, you can use this class to read configuration information at any level in the hierarchy. For safety and scalability, it is recommended that you use an external repository, such as a database, to keep the users' credentials."
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.FormsAuthenticationUserCollection> to access the <xref:System.Web.Configuration.FormsAuthenticationUser> objects of an existing Web application. The configuration file will contain a setup similar to the following.  \n  \n> [!NOTE]\n>  If you use the [credentials Element for forms for authentication (ASP.NET Settings Schema)](http://msdn.microsoft.com/en-us/e5a001f8-fdbe-4c88-80ca-bfe36df23479) section, be sure to follow the guidelines explained at [ASP.NET Authentication](http://msdn.microsoft.com/library/fc10b0ef-4ce4-4a7f-9174-886325221ee1). For scalability and better security, it is recommended you use an external database to store the users' credentials. For more information about building secure ASP.NET applications, search the Microsoft MSDN Web site (msdn.microsoft.com) for \"Securing Your ASP.NET Application\" and \"Building Secure ASP.NET Applications: Authentication, Authorization, and Secure Communication.\"  \n  \n```  \n<authentication mode=\"Forms\">  \n  <forms name=\"MyAppCookieName\" loginUrl=\"/login.aspx\">  \n    defaultUrl=\"formsdefault.aspx\"  \n    protection=\"Encryption\" timeout=\"5\" path=\"aspnet\"  \n    slidingExpiration=\"false\"  \n    cookieless=\"UseCookies\" domain=\"domainName\">  \n    <credentials passwordFormat=\"SHA1\">  \n      <user name=\"aspnetuser1\"  \n        password=\"5BAA61E4C9B93F3F0682250B6CF8331B7EE68FD8\"/>  \n       <user name=\"aspnetuser2\"  \n         password=\"E38AD214943DAAD1D64C102FAEC29DE4AFE9DA3D\"/>  \n    </credentials>            \n  </forms>  \n</authentication>  \n```  \n  \n [!code-csharp[System.Web.Configuration.FormsAuthenticationUser#1](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.FormsAuthenticationUser/CS/formsauthenticationuser.cs#1)]\n [!code-vb[System.Web.Configuration.FormsAuthenticationUser#1](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.FormsAuthenticationUser/VB/formsauthenticationuser.vb#1)]"
  syntax:
    content: 'public sealed class FormsAuthenticationUser : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/FormsAuthenticationUser.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.FormsAuthenticationUser.#ctor(System.String,System.String)
  commentId: M:System.Web.Configuration.FormsAuthenticationUser.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.FormsAuthenticationUser
  langs:
  - csharp
  name: FormsAuthenticationUser(String, String)
  nameWithType: FormsAuthenticationUser.FormsAuthenticationUser(String, String)
  fullName: System.Web.Configuration.FormsAuthenticationUser.FormsAuthenticationUser(String, String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Configuration.FormsAuthenticationUser"></xref> class using the passed parameters.
  remarks: This constructor creates a <xref:System.Web.Configuration.FormsAuthenticationUser> object using the passed parameters.
  example:
  - "The following code example shows how to create a <xref:System.Web.Configuration.FormsAuthenticationUser> object.  \n  \n [!code-csharp[System.Web.Configuration.FormsAuthenticationUser#3](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.FormsAuthenticationUser/CS/formsauthenticationuser.cs#3)]\n [!code-vb[System.Web.Configuration.FormsAuthenticationUser#3](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.FormsAuthenticationUser/VB/formsauthenticationuser.vb#3)]"
  syntax:
    content: public FormsAuthenticationUser (string name, string password);
    parameters:
    - id: name
      type: System.String
      description: User's name.
    - id: password
      type: System.String
      description: User's password.
  overload: System.Web.Configuration.FormsAuthenticationUser.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/FormsAuthenticationUser.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.FormsAuthenticationUser.Name
  commentId: P:System.Web.Configuration.FormsAuthenticationUser.Name
  id: Name
  parent: System.Web.Configuration.FormsAuthenticationUser
  langs:
  - csharp
  name: Name
  nameWithType: FormsAuthenticationUser.Name
  fullName: System.Web.Configuration.FormsAuthenticationUser.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets or sets the logon user name.
  remarks: ''
  example:
  - "The following code example shows how to use the <xref:System.Web.Configuration.FormsAuthenticationUser.Name%2A> property. Refer to the code example in the <xref:System.Web.Configuration.FormsAuthenticationUser> class topic to learn how to get the section.  \n  \n [!code-csharp[System.Web.Configuration.FormsAuthenticationUser#5](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.FormsAuthenticationUser/CS/formsauthenticationuser.cs#5)]\n [!code-vb[System.Web.Configuration.FormsAuthenticationUser#5](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.FormsAuthenticationUser/VB/formsauthenticationuser.vb#5)]"
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(System.Web.Configuration.LowerCaseStringConverter))]

      [System.Configuration.ConfigurationProperty("name", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsKey=true, IsRequired=true)]

      [System.Configuration.StringValidator]

      public string Name { get; set; }
    return:
      type: System.String
      description: The logon user name required by the application.
  overload: System.Web.Configuration.FormsAuthenticationUser.Name*
  exceptions: []
  attributes:
  - type: System.ComponentModel.TypeConverterAttribute
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/FormsAuthenticationUser.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.FormsAuthenticationUser.Password
  commentId: P:System.Web.Configuration.FormsAuthenticationUser.Password
  id: Password
  parent: System.Web.Configuration.FormsAuthenticationUser
  langs:
  - csharp
  name: Password
  nameWithType: FormsAuthenticationUser.Password
  fullName: System.Web.Configuration.FormsAuthenticationUser.Password
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets or sets the user's password.
  remarks: ''
  example:
  - "The following code example shows how to use the <xref:System.Web.Configuration.FormsAuthenticationUser.Password%2A> property. Refer to the code example in the <xref:System.Web.Configuration.FormsAuthenticationUser> class topic to learn how to get the section.  \n  \n [!code-csharp[System.Web.Configuration.FormsAuthenticationUser#4](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.FormsAuthenticationUser/CS/formsauthenticationuser.cs#4)]\n [!code-vb[System.Web.Configuration.FormsAuthenticationUser#4](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.FormsAuthenticationUser/VB/formsauthenticationuser.vb#4)]"
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("password", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsRequired=true)]

      [System.Configuration.StringValidator]

      public string Password { get; set; }
    return:
      type: System.String
      description: The user's password required by the application.
  overload: System.Web.Configuration.FormsAuthenticationUser.Password*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/FormsAuthenticationUser.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.FormsAuthenticationUser.Properties
  commentId: P:System.Web.Configuration.FormsAuthenticationUser.Properties
  id: Properties
  parent: System.Web.Configuration.FormsAuthenticationUser
  langs:
  - csharp
  name: Properties
  nameWithType: FormsAuthenticationUser.Properties
  fullName: System.Web.Configuration.FormsAuthenticationUser.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.FormsAuthenticationUser.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/FormsAuthenticationUser.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.FormsAuthenticationUser.#ctor(System.String,System.String)
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: FormsAuthenticationUser(String, String)
  nameWithType: FormsAuthenticationUser.FormsAuthenticationUser(String, String)
  fullName: System.Web.Configuration.FormsAuthenticationUser.FormsAuthenticationUser(String, String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.FormsAuthenticationUser.Name
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Name
  nameWithType: FormsAuthenticationUser.Name
  fullName: System.Web.Configuration.FormsAuthenticationUser.Name
- uid: System.Web.Configuration.FormsAuthenticationUser.Password
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Password
  nameWithType: FormsAuthenticationUser.Password
  fullName: System.Web.Configuration.FormsAuthenticationUser.Password
- uid: System.Web.Configuration.FormsAuthenticationUser.Properties
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Properties
  nameWithType: FormsAuthenticationUser.Properties
  fullName: System.Web.Configuration.FormsAuthenticationUser.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.FormsAuthenticationUser.#ctor*
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: FormsAuthenticationUser
  nameWithType: FormsAuthenticationUser.FormsAuthenticationUser
  fullName: System.Web.Configuration.FormsAuthenticationUser.FormsAuthenticationUser
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/FormsAuthenticationUser.xml
- uid: System.Web.Configuration.FormsAuthenticationUser.Name*
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Name
  nameWithType: FormsAuthenticationUser.Name
  fullName: System.Web.Configuration.FormsAuthenticationUser.Name
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/FormsAuthenticationUser.xml
- uid: System.Web.Configuration.FormsAuthenticationUser.Password*
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Password
  nameWithType: FormsAuthenticationUser.Password
  fullName: System.Web.Configuration.FormsAuthenticationUser.Password
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/FormsAuthenticationUser.xml
- uid: System.Web.Configuration.FormsAuthenticationUser.Properties*
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Properties
  nameWithType: FormsAuthenticationUser.Properties
  fullName: System.Web.Configuration.FormsAuthenticationUser.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/FormsAuthenticationUser.xml
