### YamlMime:ManagedReference
items:
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  commentId: T:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  id: ServiceNameElement
  children:
  - System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.#ctor
  - System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name
  - System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Properties
  langs:
  - csharp
  name: ServiceNameElement
  nameWithType: ServiceNameElement
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  type: Class
  assemblies:
  - System
  namespace: System.Security.Authentication.ExtendedProtection.Configuration
  summary: The <xref href="System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement"></xref> class represents a configuration element for a service name used in a <xref href="System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElementCollection"></xref>.
  syntax:
    content: 'public sealed class ServiceNameElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Security.Authentication.ExtendedProtection.Configuration/ServiceNameElement.xml
  ms.author: bobdel
  manager: markl
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.#ctor
  commentId: M:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.#ctor
  id: '#ctor'
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  langs:
  - csharp
  name: ServiceNameElement()
  nameWithType: ServiceNameElement.ServiceNameElement()
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.ServiceNameElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Security.Authentication.ExtendedProtection.Configuration
  summary: Initializes a new instance of the <xref href="System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement"></xref> class.
  remarks: "When this constructor is used to initialize a new instance of the <xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement> class, the <xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name%2A> property is set to `null`.  \n  \n The <xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name%2A> property should be set to an appropriate value for the application before calling the <xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElementCollection.Add%2A> method to add the <xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement> instance to the <xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElementCollection> class."
  syntax:
    content: public ServiceNameElement ();
    parameters: []
  overload: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Security.Authentication.ExtendedProtection.Configuration/ServiceNameElement.xml
  ms.author: bobdel
  manager: markl
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name
  commentId: P:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name
  id: Name
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  langs:
  - csharp
  name: Name
  nameWithType: ServiceNameElement.Name
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name
  type: Property
  assemblies:
  - System
  namespace: System.Security.Authentication.ExtendedProtection.Configuration
  summary: Gets or sets the Service Provider Name (SPN) for this <xref href="System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement"></xref> instance.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("name")]

      public string Name { get; set; }
    return:
      type: System.String
      description: A <xref href="System.String"></xref> that contains the representation of SPN for this <xref href="System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement"></xref> instance.
  overload: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Security.Authentication.ExtendedProtection.Configuration/ServiceNameElement.xml
  ms.author: bobdel
  manager: markl
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Properties
  commentId: P:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Properties
  id: Properties
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  langs:
  - csharp
  name: Properties
  nameWithType: ServiceNameElement.Properties
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Security.Authentication.ExtendedProtection.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Security.Authentication.ExtendedProtection.Configuration/ServiceNameElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.#ctor
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  isExternal: false
  name: ServiceNameElement()
  nameWithType: ServiceNameElement.ServiceNameElement()
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.ServiceNameElement()
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  isExternal: false
  name: Name
  nameWithType: ServiceNameElement.Name
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Properties
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  isExternal: false
  name: Properties
  nameWithType: ServiceNameElement.Properties
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.#ctor*
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  isExternal: false
  name: ServiceNameElement
  nameWithType: ServiceNameElement.ServiceNameElement
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.ServiceNameElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Security.Authentication.ExtendedProtection.Configuration/ServiceNameElement.xml
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name*
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  isExternal: false
  name: Name
  nameWithType: ServiceNameElement.Name
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Name
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Security.Authentication.ExtendedProtection.Configuration/ServiceNameElement.xml
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Properties*
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement
  isExternal: false
  name: Properties
  nameWithType: ServiceNameElement.Properties
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Security.Authentication.ExtendedProtection.Configuration/ServiceNameElement.xml
