### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  commentId: T:System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  id: FilterTableEntryElement
  children:
  - System.ServiceModel.Routing.Configuration.FilterTableEntryElement.#ctor
  - System.ServiceModel.Routing.Configuration.FilterTableEntryElement.BackupList
  - System.ServiceModel.Routing.Configuration.FilterTableEntryElement.EndpointName
  - System.ServiceModel.Routing.Configuration.FilterTableEntryElement.FilterName
  - System.ServiceModel.Routing.Configuration.FilterTableEntryElement.Priority
  langs:
  - csharp
  name: FilterTableEntryElement
  nameWithType: FilterTableEntryElement
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  type: Class
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: Represents a configuration element that defines a filter table entry element. This element contains the association between filters, endpoints and backup endpoints and is used to determine which filter is used to route the message.
  syntax:
    content: 'public class FilterTableEntryElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/FilterTableEntryElement.xml
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.#ctor
  commentId: M:System.ServiceModel.Routing.Configuration.FilterTableEntryElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  langs:
  - csharp
  name: FilterTableEntryElement()
  nameWithType: FilterTableEntryElement.FilterTableEntryElement()
  fullName: FilterTableEntryElement.FilterTableEntryElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: Creates a new instance of the <xref href="System.ServiceModel.Routing.Configuration.FilterTableEntryElement"></xref> class.
  syntax:
    content: public FilterTableEntryElement ();
    parameters: []
  overload: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/FilterTableEntryElement.xml
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.BackupList
  commentId: P:System.ServiceModel.Routing.Configuration.FilterTableEntryElement.BackupList
  id: BackupList
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  langs:
  - csharp
  name: BackupList
  nameWithType: FilterTableEntryElement.BackupList
  fullName: FilterTableEntryElement.BackupList
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: Gets or sets a value that specifies a reference to a backup endpoints element.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("backupList", DefaultValue=Mono.Cecil.CustomAttributeArgument, Options=System.Configuration.ConfigurationPropertyOptions.None)]

      public string BackupList { get; set; }
    return:
      type: System.String
      description: A reference to a backup endpoints element.
  overload: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.BackupList*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/FilterTableEntryElement.xml
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.EndpointName
  commentId: P:System.ServiceModel.Routing.Configuration.FilterTableEntryElement.EndpointName
  id: EndpointName
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  langs:
  - csharp
  name: EndpointName
  nameWithType: FilterTableEntryElement.EndpointName
  fullName: FilterTableEntryElement.EndpointName
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: Gets or sets a value that specifies a reference to a client endpoint that sends messages if the associated message filter matches the message.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("endpointName", DefaultValue=Mono.Cecil.CustomAttributeArgument, Options=System.Configuration.ConfigurationPropertyOptions.IsRequired | System.Configuration.ConfigurationPropertyOptions.IsKey)]

      public string EndpointName { get; set; }
    return:
      type: System.String
      description: A key to a client endpoint.
  overload: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.EndpointName*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/FilterTableEntryElement.xml
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.FilterName
  commentId: P:System.ServiceModel.Routing.Configuration.FilterTableEntryElement.FilterName
  id: FilterName
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  langs:
  - csharp
  name: FilterName
  nameWithType: FilterTableEntryElement.FilterName
  fullName: FilterTableEntryElement.FilterName
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: Gets or sets a value that specifies a reference to the filter element.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("filterName", DefaultValue=Mono.Cecil.CustomAttributeArgument, Options=System.Configuration.ConfigurationPropertyOptions.IsRequired | System.Configuration.ConfigurationPropertyOptions.IsKey)]

      public string FilterName { get; set; }
    return:
      type: System.String
      description: A key to the filter element.
  overload: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.FilterName*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/FilterTableEntryElement.xml
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.Priority
  commentId: P:System.ServiceModel.Routing.Configuration.FilterTableEntryElement.Priority
  id: Priority
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  langs:
  - csharp
  name: Priority
  nameWithType: FilterTableEntryElement.Priority
  fullName: FilterTableEntryElement.Priority
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: Gets or sets a value that specifies the priority of this entry.
  remarks: "The entries in the filter table are evaluated based on priority, with 0 being the lowest priority. All entries for a specific priority are evaluated simultaneously, if no matching entry is found for the current priority, the next priority level is evaluated.  \n  \n This value is optional."
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("priority", DefaultValue=Mono.Cecil.CustomAttributeArgument, Options=System.Configuration.ConfigurationPropertyOptions.None)]

      public int Priority { get; set; }
    return:
      type: System.Int32
      description: The priority of this entry. The default value is 0.
  overload: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.Priority*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/FilterTableEntryElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.#ctor
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: FilterTableEntryElement()
  nameWithType: FilterTableEntryElement.FilterTableEntryElement()
  fullName: FilterTableEntryElement.FilterTableEntryElement()
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.BackupList
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: BackupList
  nameWithType: FilterTableEntryElement.BackupList
  fullName: FilterTableEntryElement.BackupList
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.EndpointName
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: EndpointName
  nameWithType: FilterTableEntryElement.EndpointName
  fullName: FilterTableEntryElement.EndpointName
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.FilterName
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: FilterName
  nameWithType: FilterTableEntryElement.FilterName
  fullName: FilterTableEntryElement.FilterName
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.Priority
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: Priority
  nameWithType: FilterTableEntryElement.Priority
  fullName: FilterTableEntryElement.Priority
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.#ctor*
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: FilterTableEntryElement
  nameWithType: FilterTableEntryElement.FilterTableEntryElement
  fullName: FilterTableEntryElement.FilterTableEntryElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/FilterTableEntryElement.xml
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.BackupList*
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: BackupList
  nameWithType: FilterTableEntryElement.BackupList
  fullName: FilterTableEntryElement.BackupList
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/FilterTableEntryElement.xml
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.EndpointName*
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: EndpointName
  nameWithType: FilterTableEntryElement.EndpointName
  fullName: FilterTableEntryElement.EndpointName
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/FilterTableEntryElement.xml
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.FilterName*
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: FilterName
  nameWithType: FilterTableEntryElement.FilterName
  fullName: FilterTableEntryElement.FilterName
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/FilterTableEntryElement.xml
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.Priority*
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: Priority
  nameWithType: FilterTableEntryElement.Priority
  fullName: FilterTableEntryElement.Priority
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/FilterTableEntryElement.xml
