### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement
  commentId: T:System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement
  id: MexNamedPipeBindingCollectionElement
  children:
  - System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.#ctor
  - System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.GetDefault
  langs:
  - csharp
  name: MexNamedPipeBindingCollectionElement
  nameWithType: MexNamedPipeBindingCollectionElement
  fullName: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a collection of <xref href="System.ServiceModel.Configuration.MexNamedPipeBindingElement"></xref> instances.
  syntax:
    content: 'public class MexNamedPipeBindingCollectionElement : System.ServiceModel.Configuration.MexBindingBindingCollectionElement<System.ServiceModel.Channels.CustomBinding,System.ServiceModel.Configuration.MexNamedPipeBindingElement>'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.BindingCollectionElement
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  - System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  - System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Bindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.BindingType
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ConfiguredBindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ContainsKey(System.String)
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Properties
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexNamedPipeBindingCollectionElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.#ctor
  commentId: M:System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement
  langs:
  - csharp
  name: MexNamedPipeBindingCollectionElement()
  nameWithType: MexNamedPipeBindingCollectionElement.MexNamedPipeBindingCollectionElement()
  fullName: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.MexNamedPipeBindingCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement"></xref> class.
  syntax:
    content: public MexNamedPipeBindingCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexNamedPipeBindingCollectionElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.GetDefault
  commentId: M:System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.GetDefault
  id: GetDefault
  parent: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement
  langs:
  - csharp
  name: GetDefault()
  nameWithType: MexNamedPipeBindingCollectionElement.GetDefault()
  fullName: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.GetDefault()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Retrieves the default values of a configuration element.
  syntax:
    content: protected override System.ServiceModel.Channels.Binding GetDefault ();
    parameters: []
    return:
      type: System.ServiceModel.Channels.Binding
      description: The default binding.
  overload: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.GetDefault*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexNamedPipeBindingCollectionElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2
  name: MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  nameWithType: MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  fullName: System.ServiceModel.Configuration.MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>
- uid: System.ServiceModel.Channels.CustomBinding
  name: CustomBinding
  nameWithType: CustomBinding
  fullName: System.ServiceModel.Channels.CustomBinding
- uid: System.ServiceModel.Configuration.MexNamedPipeBindingElement
  name: MexNamedPipeBindingElement
  nameWithType: MexNamedPipeBindingElement
  fullName: System.ServiceModel.Configuration.MexNamedPipeBindingElement
- uid: System.ServiceModel.Configuration.MexBindingBindingCollectionElement{System.ServiceModel.Channels.CustomBinding,System.ServiceModel.Configuration.MexNamedPipeBindingElement}
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: MexBindingBindingCollectionElement<CustomBinding,MexNamedPipeBindingElement>
  nameWithType: MexBindingBindingCollectionElement<CustomBinding,MexNamedPipeBindingElement>
  fullName: System.ServiceModel.Configuration.MexBindingBindingCollectionElement<System.ServiceModel.Channels.CustomBinding,System.ServiceModel.Configuration.MexNamedPipeBindingElement>
  spec.csharp:
  - uid: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2
    name: MexBindingBindingCollectionElement
    nameWithType: MexBindingBindingCollectionElement
    fullName: System.ServiceModel.Configuration.MexBindingBindingCollectionElement
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Channels.CustomBinding
    name: CustomBinding
    nameWithType: CustomBinding
    fullName: System.ServiceModel.Channels.CustomBinding
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.ServiceModel.Configuration.MexNamedPipeBindingElement
    name: MexNamedPipeBindingElement
    nameWithType: MexNamedPipeBindingElement
    fullName: System.ServiceModel.Configuration.MexNamedPipeBindingElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement
  isExternal: false
  name: MexNamedPipeBindingCollectionElement()
  nameWithType: MexNamedPipeBindingCollectionElement.MexNamedPipeBindingCollectionElement()
  fullName: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.MexNamedPipeBindingCollectionElement()
- uid: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.GetDefault
  parent: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement
  isExternal: false
  name: GetDefault()
  nameWithType: MexNamedPipeBindingCollectionElement.GetDefault()
  fullName: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.GetDefault()
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: false
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement
  isExternal: false
  name: MexNamedPipeBindingCollectionElement
  nameWithType: MexNamedPipeBindingCollectionElement.MexNamedPipeBindingCollectionElement
  fullName: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.MexNamedPipeBindingCollectionElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexNamedPipeBindingCollectionElement.xml
- uid: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.GetDefault*
  parent: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement
  isExternal: false
  name: GetDefault
  nameWithType: MexNamedPipeBindingCollectionElement.GetDefault
  fullName: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.GetDefault
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexNamedPipeBindingCollectionElement.xml
