### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.IgnoreDeviceFilterElement
  commentId: T:System.Web.Configuration.IgnoreDeviceFilterElement
  id: IgnoreDeviceFilterElement
  children:
  - System.Web.Configuration.IgnoreDeviceFilterElement.#ctor(System.String)
  - System.Web.Configuration.IgnoreDeviceFilterElement.ElementProperty
  - System.Web.Configuration.IgnoreDeviceFilterElement.Name
  - System.Web.Configuration.IgnoreDeviceFilterElement.Properties
  langs:
  - csharp
  name: IgnoreDeviceFilterElement
  nameWithType: IgnoreDeviceFilterElement
  fullName: System.Web.Configuration.IgnoreDeviceFilterElement
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Configures a device filter element.
  remarks: Use the <xref:System.Web.Configuration.IgnoreDeviceFilterElement> class to instruct ASP.NET to ignore content that is delimited by the device filter tags you specify.
  example:
  - "The following example shows how to configure the filter tags that identify the device specific content that ASP.NET must ignore when it renders a page by using the `filter` element in a configuration file.  \n  \n```  \n<system.web>  \n  \n  <pages>  \n    <ignoreDeviceFilters>  \n      <filter name=\"TagA\"/>  \n      <filter name=\"TagB\"/>  \n    </ignoreDeviceFilters>  \n  </pages>  \n  \n</system.web>  \n```"
  syntax:
    content: 'public sealed class IgnoreDeviceFilterElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/IgnoreDeviceFilterElement.xml
- uid: System.Web.Configuration.IgnoreDeviceFilterElement.#ctor(System.String)
  commentId: M:System.Web.Configuration.IgnoreDeviceFilterElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Configuration.IgnoreDeviceFilterElement
  langs:
  - csharp
  name: IgnoreDeviceFilterElement(String)
  nameWithType: IgnoreDeviceFilterElement.IgnoreDeviceFilterElement(String)
  fullName: IgnoreDeviceFilterElement.IgnoreDeviceFilterElement(String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Configuration.IgnoreDeviceFilterElement"></xref> class.
  syntax:
    content: public IgnoreDeviceFilterElement (string name);
    parameters:
    - id: name
      type: System.String
      description: The name of the element to ignore.
  overload: System.Web.Configuration.IgnoreDeviceFilterElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/IgnoreDeviceFilterElement.xml
- uid: System.Web.Configuration.IgnoreDeviceFilterElement.ElementProperty
  commentId: P:System.Web.Configuration.IgnoreDeviceFilterElement.ElementProperty
  id: ElementProperty
  parent: System.Web.Configuration.IgnoreDeviceFilterElement
  langs:
  - csharp
  name: ElementProperty
  nameWithType: IgnoreDeviceFilterElement.ElementProperty
  fullName: IgnoreDeviceFilterElement.ElementProperty
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationElementProperty ElementProperty { get; }
    return:
      type: System.Configuration.ConfigurationElementProperty
      description: To be added.
  overload: System.Web.Configuration.IgnoreDeviceFilterElement.ElementProperty*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/IgnoreDeviceFilterElement.xml
- uid: System.Web.Configuration.IgnoreDeviceFilterElement.Name
  commentId: P:System.Web.Configuration.IgnoreDeviceFilterElement.Name
  id: Name
  parent: System.Web.Configuration.IgnoreDeviceFilterElement
  langs:
  - csharp
  name: Name
  nameWithType: IgnoreDeviceFilterElement.Name
  fullName: IgnoreDeviceFilterElement.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets the name of the element to ignore.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("name", IsKey=true, IsRequired=true)]

      [System.Configuration.StringValidator(MinLength=1)]

      public string Name { get; }
    return:
      type: System.String
      description: The name of the element to ignore.
  overload: System.Web.Configuration.IgnoreDeviceFilterElement.Name*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/IgnoreDeviceFilterElement.xml
- uid: System.Web.Configuration.IgnoreDeviceFilterElement.Properties
  commentId: P:System.Web.Configuration.IgnoreDeviceFilterElement.Properties
  id: Properties
  parent: System.Web.Configuration.IgnoreDeviceFilterElement
  langs:
  - csharp
  name: Properties
  nameWithType: IgnoreDeviceFilterElement.Properties
  fullName: IgnoreDeviceFilterElement.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.IgnoreDeviceFilterElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/IgnoreDeviceFilterElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.IgnoreDeviceFilterElement.#ctor(System.String)
  parent: System.Web.Configuration.IgnoreDeviceFilterElement
  isExternal: false
  name: IgnoreDeviceFilterElement(String)
  nameWithType: IgnoreDeviceFilterElement.IgnoreDeviceFilterElement(String)
  fullName: IgnoreDeviceFilterElement.IgnoreDeviceFilterElement(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.IgnoreDeviceFilterElement.ElementProperty
  parent: System.Web.Configuration.IgnoreDeviceFilterElement
  isExternal: false
  name: ElementProperty
  nameWithType: IgnoreDeviceFilterElement.ElementProperty
  fullName: IgnoreDeviceFilterElement.ElementProperty
- uid: System.Configuration.ConfigurationElementProperty
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElementProperty
  nameWithType: ConfigurationElementProperty
  fullName: System.Configuration.ConfigurationElementProperty
- uid: System.Web.Configuration.IgnoreDeviceFilterElement.Name
  parent: System.Web.Configuration.IgnoreDeviceFilterElement
  isExternal: false
  name: Name
  nameWithType: IgnoreDeviceFilterElement.Name
  fullName: IgnoreDeviceFilterElement.Name
- uid: System.Web.Configuration.IgnoreDeviceFilterElement.Properties
  parent: System.Web.Configuration.IgnoreDeviceFilterElement
  isExternal: false
  name: Properties
  nameWithType: IgnoreDeviceFilterElement.Properties
  fullName: IgnoreDeviceFilterElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.IgnoreDeviceFilterElement.#ctor*
  parent: System.Web.Configuration.IgnoreDeviceFilterElement
  isExternal: false
  name: IgnoreDeviceFilterElement
  nameWithType: IgnoreDeviceFilterElement.IgnoreDeviceFilterElement
  fullName: IgnoreDeviceFilterElement.IgnoreDeviceFilterElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/IgnoreDeviceFilterElement.xml
- uid: System.Web.Configuration.IgnoreDeviceFilterElement.ElementProperty*
  parent: System.Web.Configuration.IgnoreDeviceFilterElement
  isExternal: false
  name: ElementProperty
  nameWithType: IgnoreDeviceFilterElement.ElementProperty
  fullName: IgnoreDeviceFilterElement.ElementProperty
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/IgnoreDeviceFilterElement.xml
- uid: System.Web.Configuration.IgnoreDeviceFilterElement.Name*
  parent: System.Web.Configuration.IgnoreDeviceFilterElement
  isExternal: false
  name: Name
  nameWithType: IgnoreDeviceFilterElement.Name
  fullName: IgnoreDeviceFilterElement.Name
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/IgnoreDeviceFilterElement.xml
- uid: System.Web.Configuration.IgnoreDeviceFilterElement.Properties*
  parent: System.Web.Configuration.IgnoreDeviceFilterElement
  isExternal: false
  name: Properties
  nameWithType: IgnoreDeviceFilterElement.Properties
  fullName: IgnoreDeviceFilterElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/IgnoreDeviceFilterElement.xml
