### YamlMime:ManagedReference
items:
- uid: System.Configuration.UserSettingsGroup
  commentId: T:System.Configuration.UserSettingsGroup
  id: UserSettingsGroup
  children:
  - System.Configuration.UserSettingsGroup.#ctor
  langs:
  - csharp
  name: UserSettingsGroup
  nameWithType: UserSettingsGroup
  fullName: System.Configuration.UserSettingsGroup
  type: Class
  assemblies:
  - System
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Represents a grouping of related user settings sections within a configuration file. This class cannot be inherited.
  remarks: Because some configuration sections are related, it is often convenient to group them together within a single section group.
  syntax:
    content: 'public sealed class UserSettingsGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/UserSettingsGroup.xml
- uid: System.Configuration.UserSettingsGroup.#ctor
  commentId: M:System.Configuration.UserSettingsGroup.#ctor
  id: '#ctor'
  parent: System.Configuration.UserSettingsGroup
  langs:
  - csharp
  name: UserSettingsGroup()
  nameWithType: UserSettingsGroup.UserSettingsGroup()
  fullName: UserSettingsGroup.UserSettingsGroup()
  type: Constructor
  assemblies:
  - System
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.UserSettingsGroup"></xref> class.
  syntax:
    content: public UserSettingsGroup ();
    parameters: []
  overload: System.Configuration.UserSettingsGroup.#ctor*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/UserSettingsGroup.xml
references:
- uid: System.Configuration.ConfigurationSectionGroup
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSectionGroup
  nameWithType: ConfigurationSectionGroup
  fullName: System.Configuration.ConfigurationSectionGroup
- uid: System.Configuration.UserSettingsGroup.#ctor
  parent: System.Configuration.UserSettingsGroup
  isExternal: false
  name: UserSettingsGroup()
  nameWithType: UserSettingsGroup.UserSettingsGroup()
  fullName: UserSettingsGroup.UserSettingsGroup()
- uid: System.Configuration.UserSettingsGroup.#ctor*
  parent: System.Configuration.UserSettingsGroup
  isExternal: false
  name: UserSettingsGroup
  nameWithType: UserSettingsGroup.UserSettingsGroup
  fullName: UserSettingsGroup.UserSettingsGroup
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/UserSettingsGroup.xml
