### YamlMime:ManagedReference
items:
- uid: System.Data.Services.Configuration.DataServicesSectionGroup
  commentId: T:System.Data.Services.Configuration.DataServicesSectionGroup
  id: DataServicesSectionGroup
  children:
  - System.Data.Services.Configuration.DataServicesSectionGroup.#ctor
  - System.Data.Services.Configuration.DataServicesSectionGroup.Features
  langs:
  - csharp
  name: DataServicesSectionGroup
  nameWithType: DataServicesSectionGroup
  fullName: System.Data.Services.Configuration.DataServicesSectionGroup
  type: Class
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services.Configuration
  summary: Represents the DataServicesSectionGroup configuration section group.
  syntax:
    content: 'public sealed class DataServicesSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Configuration/DataServicesSectionGroup.xml
  author: JennieHubbard
  ms.author: jhubbard
  manager: jhubbard
- uid: System.Data.Services.Configuration.DataServicesSectionGroup.#ctor
  commentId: M:System.Data.Services.Configuration.DataServicesSectionGroup.#ctor
  id: '#ctor'
  parent: System.Data.Services.Configuration.DataServicesSectionGroup
  langs:
  - csharp
  name: DataServicesSectionGroup()
  nameWithType: DataServicesSectionGroup.DataServicesSectionGroup()
  fullName: System.Data.Services.Configuration.DataServicesSectionGroup.DataServicesSectionGroup()
  type: Constructor
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services.Configuration
  summary: Initializes a new instance of the <xref href="System.Data.Services.Configuration.DataServicesSectionGroup"></xref> class.
  syntax:
    content: public DataServicesSectionGroup ();
    parameters: []
  overload: System.Data.Services.Configuration.DataServicesSectionGroup.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Configuration/DataServicesSectionGroup.xml
  author: JennieHubbard
  ms.author: jhubbard
  manager: jhubbard
- uid: System.Data.Services.Configuration.DataServicesSectionGroup.Features
  commentId: P:System.Data.Services.Configuration.DataServicesSectionGroup.Features
  id: Features
  parent: System.Data.Services.Configuration.DataServicesSectionGroup
  langs:
  - csharp
  name: Features
  nameWithType: DataServicesSectionGroup.Features
  fullName: System.Data.Services.Configuration.DataServicesSectionGroup.Features
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services.Configuration
  summary: Gets the DataServicesFeaturesSection instance associated with the DataServicesSectionGroup.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("features")]

      public System.Data.Services.Configuration.DataServicesFeaturesSection Features { get; }
    return:
      type: System.Data.Services.Configuration.DataServicesFeaturesSection
      description: A DataServicesFeaturesSection instance.
  overload: System.Data.Services.Configuration.DataServicesSectionGroup.Features*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Configuration/DataServicesSectionGroup.xml
  author: JennieHubbard
  ms.author: jhubbard
  manager: jhubbard
references:
- uid: System.Configuration.ConfigurationSectionGroup
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSectionGroup
  nameWithType: ConfigurationSectionGroup
  fullName: System.Configuration.ConfigurationSectionGroup
- uid: System.Data.Services.Configuration.DataServicesSectionGroup.#ctor
  parent: System.Data.Services.Configuration.DataServicesSectionGroup
  isExternal: false
  name: DataServicesSectionGroup()
  nameWithType: DataServicesSectionGroup.DataServicesSectionGroup()
  fullName: System.Data.Services.Configuration.DataServicesSectionGroup.DataServicesSectionGroup()
- uid: System.Data.Services.Configuration.DataServicesSectionGroup.Features
  parent: System.Data.Services.Configuration.DataServicesSectionGroup
  isExternal: false
  name: Features
  nameWithType: DataServicesSectionGroup.Features
  fullName: System.Data.Services.Configuration.DataServicesSectionGroup.Features
- uid: System.Data.Services.Configuration.DataServicesFeaturesSection
  parent: System.Data.Services.Configuration
  isExternal: false
  name: DataServicesFeaturesSection
  nameWithType: DataServicesFeaturesSection
  fullName: System.Data.Services.Configuration.DataServicesFeaturesSection
- uid: System.Data.Services.Configuration.DataServicesSectionGroup.#ctor*
  parent: System.Data.Services.Configuration.DataServicesSectionGroup
  isExternal: false
  name: DataServicesSectionGroup
  nameWithType: DataServicesSectionGroup.DataServicesSectionGroup
  fullName: System.Data.Services.Configuration.DataServicesSectionGroup.DataServicesSectionGroup
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Configuration/DataServicesSectionGroup.xml
- uid: System.Data.Services.Configuration.DataServicesSectionGroup.Features*
  parent: System.Data.Services.Configuration.DataServicesSectionGroup
  isExternal: false
  name: Features
  nameWithType: DataServicesSectionGroup.Features
  fullName: System.Data.Services.Configuration.DataServicesSectionGroup.Features
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Configuration/DataServicesSectionGroup.xml
