### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Discovery.Configuration.ScopeElementCollection
  commentId: T:System.ServiceModel.Discovery.Configuration.ScopeElementCollection
  id: ScopeElementCollection
  children:
  - System.ServiceModel.Discovery.Configuration.ScopeElementCollection.#ctor
  - System.ServiceModel.Discovery.Configuration.ScopeElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  name: ScopeElementCollection
  nameWithType: ScopeElementCollection
  fullName: System.ServiceModel.Discovery.Configuration.ScopeElementCollection
  type: Class
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: A configuration element that contains a collection of scope elements.
  remarks: "The following example shows how to add two scope URIs for an endpoint.  \n  \n```  \n<configuration>  \n    <system.serviceModel>  \n      <services>  \n        <service name=\"Microsoft.Samples.Discovery.CalculatorService\"  \n                 behaviorConfiguration=\"calculatorServiceBehavior\">  \n          <endpoint address=\"\"  \n                    binding=\"wsHttpBinding\"  \n                    contract=\"Microsoft.Samples.Discovery.ICalculatorService\"  \n                    behaviorConfiguration=\"ep1Behavior\" />  \n  \n        </service>  \n      </services>  \n      <behaviors>  \n        <serviceBehaviors>  \n          <behavior name=\"calculatorServiceBehavior\">  \n            <serviceDiscovery />  \n          </behavior>  \n        </serviceBehaviors>  \n        <endpointBehaviors>  \n          <behavior name=\"ep1Behavior\">  \n            <endpointDiscovery>  \n              <scopes>  \n                <add scope=\"http://www.mycalculator.com\"/>  \n                <add scope=\"ldap:///ou=engineering,o=exampleorg,c=us\"/>  \n              </scopes>  \n            </endpointDiscovery>  \n          </behavior>            \n        </endpointBehaviors>  \n      </behaviors>  \n      <extensions>  \n        <behaviorExtensions>  \n          <add name=\"serviceDiscovery\" type=\"System.ServiceModel.Discovery.Configuration.ServiceDiscoveryElement, System.WorkflowServiceModel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\" />  \n          <add name=\"endpointDiscovery\" type=\"System.ServiceModel.Discovery.Configuration.EndpointDiscoveryElement, System.WorkflowServiceModel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\" />  \n        </behaviorExtensions>  \n      </extensions>  \n    </system.serviceModel>  \n</configuration>  \n```"
  syntax:
    content: >-
      [System.Configuration.ConfigurationCollection(typeof(System.ServiceModel.Discovery.Configuration.ScopeElement))]

      public sealed class ScopeElementCollection : System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection<System.ServiceModel.Discovery.Configuration.ScopeElement>
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationElementCollection
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.AddElementName
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseClear
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseGetAllKeys
  - System.Configuration.ConfigurationElementCollection.BaseGetKey(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseIndexOf(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseIsRemoved(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemove(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemoveAt(System.Int32)
  - System.Configuration.ConfigurationElementCollection.ClearElementName
  - System.Configuration.ConfigurationElementCollection.CopyTo(System.Configuration.ConfigurationElement[],System.Int32)
  - System.Configuration.ConfigurationElementCollection.Count
  - System.Configuration.ConfigurationElementCollection.CreateNewElement(System.String)
  - System.Configuration.ConfigurationElementCollection.EmitClear
  - System.Configuration.ConfigurationElementCollection.Equals(System.Object)
  - System.Configuration.ConfigurationElementCollection.GetEnumerator
  - System.Configuration.ConfigurationElementCollection.GetHashCode
  - System.Configuration.ConfigurationElementCollection.IsElementName(System.String)
  - System.Configuration.ConfigurationElementCollection.IsElementRemovable(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.IsModified
  - System.Configuration.ConfigurationElementCollection.IsReadOnly
  - System.Configuration.ConfigurationElementCollection.IsSynchronized
  - System.Configuration.ConfigurationElementCollection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElementCollection.RemoveElementName
  - System.Configuration.ConfigurationElementCollection.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.ResetModified
  - System.Configuration.ConfigurationElementCollection.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.SetReadOnly
  - System.Configuration.ConfigurationElementCollection.SyncRoot
  - System.Configuration.ConfigurationElementCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Configuration.ConfigurationElementCollection.ThrowOnDuplicate
  - System.Configuration.ConfigurationElementCollection.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Add(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.BaseAdd(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Clear
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CollectionType
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.ContainsKey(System.Object)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CopyTo(`0[],System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.ElementName
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.IndexOf(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Item(System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Item(System.Object)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Remove(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.RemoveAt(System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.RemoveAt(System.Object)
  extensionMethods:
  - System.Linq.Enumerable.Cast``1(System.Collections.IEnumerable)
  - System.Linq.Enumerable.OfType``1(System.Collections.IEnumerable)
  - System.Linq.ParallelEnumerable.AsParallel(System.Collections.IEnumerable)
  - System.Linq.Queryable.AsQueryable(System.Collections.IEnumerable)
  attributes:
  - type: System.Configuration.ConfigurationCollectionAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/ScopeElementCollection.xml
- uid: System.ServiceModel.Discovery.Configuration.ScopeElementCollection.#ctor
  commentId: M:System.ServiceModel.Discovery.Configuration.ScopeElementCollection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Discovery.Configuration.ScopeElementCollection
  langs:
  - csharp
  name: ScopeElementCollection()
  nameWithType: ScopeElementCollection.ScopeElementCollection()
  fullName: ScopeElementCollection.ScopeElementCollection()
  type: Constructor
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: Creates a new instance of the <xref href="System.ServiceModel.Discovery.Configuration.ScopeElementCollection.#ctor"></xref> class.
  syntax:
    content: public ScopeElementCollection ();
    parameters: []
  overload: System.ServiceModel.Discovery.Configuration.ScopeElementCollection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/ScopeElementCollection.xml
- uid: System.ServiceModel.Discovery.Configuration.ScopeElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  commentId: M:System.ServiceModel.Discovery.Configuration.ScopeElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Discovery.Configuration.ScopeElementCollection
  langs:
  - csharp
  name: GetElementKey(ConfigurationElement)
  nameWithType: ScopeElementCollection.GetElementKey(ConfigurationElement)
  fullName: ScopeElementCollection.GetElementKey(ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  syntax:
    content: protected override object GetElementKey (System.Configuration.ConfigurationElement element);
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
      description: To be added.
    return:
      type: System.Object
      description: To be added.
  overload: System.ServiceModel.Discovery.Configuration.ScopeElementCollection.GetElementKey*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/ScopeElementCollection.xml
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1
  name: ServiceModelConfigurationElementCollection<ConfigurationElementType>
  nameWithType: ServiceModelConfigurationElementCollection<ConfigurationElementType>
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection<ConfigurationElementType>
- uid: System.ServiceModel.Discovery.Configuration.ScopeElement
  name: ScopeElement
  nameWithType: ScopeElement
  fullName: System.ServiceModel.Discovery.Configuration.ScopeElement
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection{System.ServiceModel.Discovery.Configuration.ScopeElement}
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelConfigurationElementCollection<ScopeElement>
  nameWithType: ServiceModelConfigurationElementCollection<ScopeElement>
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection<System.ServiceModel.Discovery.Configuration.ScopeElement>
  spec.csharp:
  - uid: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Discovery.Configuration.ScopeElement
    name: ScopeElement
    nameWithType: ScopeElement
    fullName: System.ServiceModel.Discovery.Configuration.ScopeElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Discovery.Configuration.ScopeElementCollection.#ctor
  parent: System.ServiceModel.Discovery.Configuration.ScopeElementCollection
  isExternal: false
  name: ScopeElementCollection()
  nameWithType: ScopeElementCollection.ScopeElementCollection()
  fullName: ScopeElementCollection.ScopeElementCollection()
- uid: System.ServiceModel.Discovery.Configuration.ScopeElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Discovery.Configuration.ScopeElementCollection
  isExternal: false
  name: GetElementKey(ConfigurationElement)
  nameWithType: ScopeElementCollection.GetElementKey(ConfigurationElement)
  fullName: ScopeElementCollection.GetElementKey(ConfigurationElement)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Discovery.Configuration.ScopeElementCollection.#ctor*
  parent: System.ServiceModel.Discovery.Configuration.ScopeElementCollection
  isExternal: false
  name: ScopeElementCollection
  nameWithType: ScopeElementCollection.ScopeElementCollection
  fullName: ScopeElementCollection.ScopeElementCollection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/ScopeElementCollection.xml
- uid: System.ServiceModel.Discovery.Configuration.ScopeElementCollection.GetElementKey*
  parent: System.ServiceModel.Discovery.Configuration.ScopeElementCollection
  isExternal: false
  name: GetElementKey
  nameWithType: ScopeElementCollection.GetElementKey
  fullName: ScopeElementCollection.GetElementKey
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/ScopeElementCollection.xml
- uid: System.Linq.Enumerable.Cast``1(System.Collections.IEnumerable)
  parent: System.Linq.Enumerable
  isExternal: false
  name: Cast<TResult>(IEnumerable)
  nameWithType: Enumerable.Cast<TResult>(IEnumerable)
  fullName: Enumerable.Cast<TResult>(IEnumerable)
- uid: System.Linq.Enumerable.OfType``1(System.Collections.IEnumerable)
  parent: System.Linq.Enumerable
  isExternal: false
  name: OfType<TResult>(IEnumerable)
  nameWithType: Enumerable.OfType<TResult>(IEnumerable)
  fullName: Enumerable.OfType<TResult>(IEnumerable)
- uid: System.Linq.ParallelEnumerable.AsParallel(System.Collections.IEnumerable)
  parent: System.Linq.ParallelEnumerable
  isExternal: false
  name: AsParallel(IEnumerable)
  nameWithType: ParallelEnumerable.AsParallel(IEnumerable)
  fullName: ParallelEnumerable.AsParallel(IEnumerable)
- uid: System.Linq.Queryable.AsQueryable(System.Collections.IEnumerable)
  parent: System.Linq.Queryable
  isExternal: false
  name: AsQueryable(IEnumerable)
  nameWithType: Queryable.AsQueryable(IEnumerable)
  fullName: Queryable.AsQueryable(IEnumerable)
