### YamlMime:ManagedReference
items:
- uid: System.Configuration.SingleTagSectionHandler
  commentId: T:System.Configuration.SingleTagSectionHandler
  id: SingleTagSectionHandler
  children:
  - System.Configuration.SingleTagSectionHandler.#ctor
  - System.Configuration.SingleTagSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: SingleTagSectionHandler
  nameWithType: SingleTagSectionHandler
  fullName: System.Configuration.SingleTagSectionHandler
  type: Class
  assemblies:
  - System
  namespace: System.Configuration
  summary: Handles configuration sections that are represented by a single XML tag in the .config file.
  syntax:
    content: 'public class SingleTagSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SingleTagSectionHandler.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.SingleTagSectionHandler.#ctor
  commentId: M:System.Configuration.SingleTagSectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.SingleTagSectionHandler
  langs:
  - csharp
  name: SingleTagSectionHandler()
  nameWithType: SingleTagSectionHandler.SingleTagSectionHandler()
  fullName: System.Configuration.SingleTagSectionHandler.SingleTagSectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.SingleTagSectionHandler"></xref> class.
  syntax:
    content: public SingleTagSectionHandler ();
    parameters: []
  overload: System.Configuration.SingleTagSectionHandler.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SingleTagSectionHandler.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.SingleTagSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  commentId: M:System.Configuration.SingleTagSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.SingleTagSectionHandler
  langs:
  - csharp
  name: Create(Object, Object, XmlNode)
  nameWithType: SingleTagSectionHandler.Create(Object, Object, XmlNode)
  fullName: System.Configuration.SingleTagSectionHandler.Create(Object, Object, XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: Used internally to create a new instance of this object.
  syntax:
    content: public virtual object Create (object parent, object context, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: The parent of this object.
    - id: context
      type: System.Object
      description: The context of this object.
    - id: section
      type: System.Xml.XmlNode
      description: The <xref href="System.Xml.XmlNode"></xref> object in the configuration.
    return:
      type: System.Object
      description: The created object handler.
  overload: System.Configuration.SingleTagSectionHandler.Create*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SingleTagSectionHandler.xml
  ms.author: riande
  manager: wpickett
references:
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.SingleTagSectionHandler.#ctor
  parent: System.Configuration.SingleTagSectionHandler
  isExternal: false
  name: SingleTagSectionHandler()
  nameWithType: SingleTagSectionHandler.SingleTagSectionHandler()
  fullName: System.Configuration.SingleTagSectionHandler.SingleTagSectionHandler()
- uid: System.Configuration.SingleTagSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.SingleTagSectionHandler
  isExternal: false
  name: Create(Object, Object, XmlNode)
  nameWithType: SingleTagSectionHandler.Create(Object, Object, XmlNode)
  fullName: System.Configuration.SingleTagSectionHandler.Create(Object, Object, XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.SingleTagSectionHandler.#ctor*
  parent: System.Configuration.SingleTagSectionHandler
  isExternal: false
  name: SingleTagSectionHandler
  nameWithType: SingleTagSectionHandler.SingleTagSectionHandler
  fullName: System.Configuration.SingleTagSectionHandler.SingleTagSectionHandler
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SingleTagSectionHandler.xml
- uid: System.Configuration.SingleTagSectionHandler.Create*
  parent: System.Configuration.SingleTagSectionHandler
  isExternal: false
  name: Create
  nameWithType: SingleTagSectionHandler.Create
  fullName: System.Configuration.SingleTagSectionHandler.Create
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SingleTagSectionHandler.xml
