### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  commentId: T:System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  id: MessageSecurityOverTcpElement
  children:
  - System.ServiceModel.Configuration.MessageSecurityOverTcpElement.#ctor
  - System.ServiceModel.Configuration.MessageSecurityOverTcpElement.AlgorithmSuite
  - System.ServiceModel.Configuration.MessageSecurityOverTcpElement.ClientCredentialType
  - System.ServiceModel.Configuration.MessageSecurityOverTcpElement.Properties
  langs:
  - csharp
  name: MessageSecurityOverTcpElement
  nameWithType: MessageSecurityOverTcpElement
  fullName: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Defines the configuration settings for the security of a message sent using TCP. This class cannot be inherited.
  syntax:
    content: 'public sealed class MessageSecurityOverTcpElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverTcpElement.xml
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.#ctor
  commentId: M:System.ServiceModel.Configuration.MessageSecurityOverTcpElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  langs:
  - csharp
  name: MessageSecurityOverTcpElement()
  nameWithType: MessageSecurityOverTcpElement.MessageSecurityOverTcpElement()
  fullName: MessageSecurityOverTcpElement.MessageSecurityOverTcpElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.MessageSecurityOverTcpElement"></xref> class.
  syntax:
    content: public MessageSecurityOverTcpElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverTcpElement.xml
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.AlgorithmSuite
  commentId: P:System.ServiceModel.Configuration.MessageSecurityOverTcpElement.AlgorithmSuite
  id: AlgorithmSuite
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  langs:
  - csharp
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverTcpElement.AlgorithmSuite
  fullName: MessageSecurityOverTcpElement.AlgorithmSuite
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the message encryption and key-wrap algorithms used to secure a TCP message.
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(System.ServiceModel.Configuration.SecurityAlgorithmSuiteConverter))]

      [System.Configuration.ConfigurationProperty("algorithmSuite", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.ServiceModel.Security.SecurityAlgorithmSuite AlgorithmSuite { get; set; }
    return:
      type: System.ServiceModel.Security.SecurityAlgorithmSuite
      description: A valid <xref href="System.ServiceModel.Security.SecurityAlgorithmSuite"></xref> value that specifies the message encryption and key-wrap algorithms used to secure a TCP message. The default value is <xref href="System.ServiceModel.Security.SecurityAlgorithmSuite.Basic256"></xref>.
  overload: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.AlgorithmSuite*
  exceptions: []
  attributes:
  - type: System.ComponentModel.TypeConverterAttribute
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverTcpElement.xml
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.ClientCredentialType
  commentId: P:System.ServiceModel.Configuration.MessageSecurityOverTcpElement.ClientCredentialType
  id: ClientCredentialType
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  langs:
  - csharp
  name: ClientCredentialType
  nameWithType: MessageSecurityOverTcpElement.ClientCredentialType
  fullName: MessageSecurityOverTcpElement.ClientCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Specifies the type of credential to be used when performing client authentication using message-based security or `TransportWithMessageCredential`.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("clientCredentialType", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.ServiceModel.MessageCredentialType ClientCredentialType { get; set; }
    return:
      type: System.ServiceModel.MessageCredentialType
      description: A valid <xref href="System.ServiceModel.MessageCredentialType"></xref> value that specifies the type of credential to be used when performing client authentication using message-based security or `TransportWithMessageCredential`. The default value is <xref href="System.ServiceModel.MessageCredentialType.Windows"></xref>.
  overload: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.ClientCredentialType*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverTcpElement.xml
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.Properties
  commentId: P:System.ServiceModel.Configuration.MessageSecurityOverTcpElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  langs:
  - csharp
  name: Properties
  nameWithType: MessageSecurityOverTcpElement.Properties
  fullName: MessageSecurityOverTcpElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverTcpElement.xml
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.#ctor
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  isExternal: false
  name: MessageSecurityOverTcpElement()
  nameWithType: MessageSecurityOverTcpElement.MessageSecurityOverTcpElement()
  fullName: MessageSecurityOverTcpElement.MessageSecurityOverTcpElement()
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.AlgorithmSuite
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverTcpElement.AlgorithmSuite
  fullName: MessageSecurityOverTcpElement.AlgorithmSuite
- uid: System.ServiceModel.Security.SecurityAlgorithmSuite
  parent: System.ServiceModel.Security
  isExternal: false
  name: SecurityAlgorithmSuite
  nameWithType: SecurityAlgorithmSuite
  fullName: System.ServiceModel.Security.SecurityAlgorithmSuite
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.ClientCredentialType
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: MessageSecurityOverTcpElement.ClientCredentialType
  fullName: MessageSecurityOverTcpElement.ClientCredentialType
- uid: System.ServiceModel.MessageCredentialType
  parent: System.ServiceModel
  isExternal: false
  name: MessageCredentialType
  nameWithType: MessageCredentialType
  fullName: System.ServiceModel.MessageCredentialType
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.Properties
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  isExternal: false
  name: Properties
  nameWithType: MessageSecurityOverTcpElement.Properties
  fullName: MessageSecurityOverTcpElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.#ctor*
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  isExternal: false
  name: MessageSecurityOverTcpElement
  nameWithType: MessageSecurityOverTcpElement.MessageSecurityOverTcpElement
  fullName: MessageSecurityOverTcpElement.MessageSecurityOverTcpElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverTcpElement.xml
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.AlgorithmSuite*
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverTcpElement.AlgorithmSuite
  fullName: MessageSecurityOverTcpElement.AlgorithmSuite
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverTcpElement.xml
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.ClientCredentialType*
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: MessageSecurityOverTcpElement.ClientCredentialType
  fullName: MessageSecurityOverTcpElement.ClientCredentialType
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverTcpElement.xml
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement.Properties*
  parent: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  isExternal: false
  name: Properties
  nameWithType: MessageSecurityOverTcpElement.Properties
  fullName: MessageSecurityOverTcpElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverTcpElement.xml
