### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  commentId: T:System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  id: TrackingSection
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Profiles
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Properties
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.TrackingProfiles
  langs:
  - csharp
  name: TrackingSection
  nameWithType: TrackingSection
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  type: Class
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: A configuration section for specifying tracking settings.
  syntax:
    content: 'public class TrackingSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/TrackingSection.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.#ctor
  commentId: M:System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  langs:
  - csharp
  name: TrackingSection()
  nameWithType: TrackingSection.TrackingSection()
  fullName: TrackingSection.TrackingSection()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Activities.Tracking.Configuration.TrackingSection"></xref> class.
  syntax:
    content: public TrackingSection ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/TrackingSection.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Profiles
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Profiles
  id: Profiles
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  langs:
  - csharp
  name: Profiles
  nameWithType: TrackingSection.Profiles
  fullName: TrackingSection.Profiles
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets a collection of <xref href="System.ServiceModel.Activities.Tracking.Configuration.ProfileElement"></xref> elements.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("profiles")]

      public System.ServiceModel.Activities.Tracking.Configuration.ProfileElementCollection Profiles { get; }
    return:
      type: System.ServiceModel.Activities.Tracking.Configuration.ProfileElementCollection
      description: A collection of elements.
  overload: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Profiles*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/TrackingSection.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Properties
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  langs:
  - csharp
  name: Properties
  nameWithType: TrackingSection.Properties
  fullName: TrackingSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets the collection of properties.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: The collection of properties for the element.
  overload: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/TrackingSection.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.TrackingProfiles
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.TrackingProfiles
  id: TrackingProfiles
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  langs:
  - csharp
  name: TrackingProfiles
  nameWithType: TrackingSection.TrackingProfiles
  fullName: TrackingSection.TrackingProfiles
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets a collection of <xref href="System.Activities.Tracking.TrackingProfile"></xref> objects.
  syntax:
    content: public System.Collections.ObjectModel.Collection<System.Activities.Tracking.TrackingProfile> TrackingProfiles { get; }
    return:
      type: System.Collections.ObjectModel.Collection{System.Activities.Tracking.TrackingProfile}
      description: A collection of <xref href="System.Activities.Tracking.TrackingProfile"></xref> objects.
  overload: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.TrackingProfiles*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/TrackingSection.xml
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  isExternal: false
  name: TrackingSection()
  nameWithType: TrackingSection.TrackingSection()
  fullName: TrackingSection.TrackingSection()
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Profiles
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  isExternal: false
  name: Profiles
  nameWithType: TrackingSection.Profiles
  fullName: TrackingSection.Profiles
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElementCollection
  parent: System.ServiceModel.Activities.Tracking.Configuration
  isExternal: false
  name: ProfileElementCollection
  nameWithType: ProfileElementCollection
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElementCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  isExternal: false
  name: Properties
  nameWithType: TrackingSection.Properties
  fullName: TrackingSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.TrackingProfiles
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  isExternal: false
  name: TrackingProfiles
  nameWithType: TrackingSection.TrackingProfiles
  fullName: TrackingSection.TrackingProfiles
- uid: System.Collections.ObjectModel.Collection`1
  name: Collection<T>
  nameWithType: Collection<T>
  fullName: System.Collections.ObjectModel.Collection<T>
- uid: System.Activities.Tracking.TrackingProfile
  name: TrackingProfile
  nameWithType: TrackingProfile
  fullName: System.Activities.Tracking.TrackingProfile
- uid: System.Collections.ObjectModel.Collection{System.Activities.Tracking.TrackingProfile}
  parent: System.Collections.ObjectModel
  isExternal: false
  name: Collection<TrackingProfile>
  nameWithType: Collection<TrackingProfile>
  fullName: System.Collections.ObjectModel.Collection<System.Activities.Tracking.TrackingProfile>
  spec.csharp:
  - uid: System.Collections.ObjectModel.Collection`1
    name: Collection
    nameWithType: Collection
    fullName: System.Collections.ObjectModel.Collection
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Activities.Tracking.TrackingProfile
    name: TrackingProfile
    nameWithType: TrackingProfile
    fullName: System.Activities.Tracking.TrackingProfile
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  isExternal: false
  name: TrackingSection
  nameWithType: TrackingSection.TrackingSection
  fullName: TrackingSection.TrackingSection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/TrackingSection.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Profiles*
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  isExternal: false
  name: Profiles
  nameWithType: TrackingSection.Profiles
  fullName: TrackingSection.Profiles
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/TrackingSection.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  isExternal: false
  name: Properties
  nameWithType: TrackingSection.Properties
  fullName: TrackingSection.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/TrackingSection.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.TrackingProfiles*
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  isExternal: false
  name: TrackingProfiles
  nameWithType: TrackingSection.TrackingProfiles
  fullName: TrackingSection.TrackingProfiles
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/TrackingSection.xml
