### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.XhtmlConformanceSection
  commentId: T:System.Web.Configuration.XhtmlConformanceSection
  id: XhtmlConformanceSection
  children:
  - System.Web.Configuration.XhtmlConformanceSection.#ctor
  - System.Web.Configuration.XhtmlConformanceSection.Mode
  - System.Web.Configuration.XhtmlConformanceSection.Properties
  langs:
  - csharp
  name: XhtmlConformanceSection
  nameWithType: XhtmlConformanceSection
  fullName: System.Web.Configuration.XhtmlConformanceSection
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Configures the `xhtmlConformance` section. This class cannot be inherited.
  remarks: "The <xref:System.Web.Configuration.XhtmlConformanceSection> class provides a way to programmatically access and modify the `xhtmlConformance` section of a configuration file.  \n  \n> [!NOTE]\n>  ASP.NET allows you to create Web pages that are compliant with XHTML 1.1 standards. For more information about the XHTML 1.1 standard, see the W3C site. By default, when you are working with browsers that support HTML 4.0 or later, ASP.NET pages and controls render markup that is compatible with the XHTML 1.0 Transitional standard. However, under some circumstances, you might not want ASP.NET to render XHTML markup. This is typically true when you have existing pages that rely on tags or attributes that would ordinarily be prohibited by XHTML."
  syntax:
    content: 'public sealed class XhtmlConformanceSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/XhtmlConformanceSection.xml
- uid: System.Web.Configuration.XhtmlConformanceSection.#ctor
  commentId: M:System.Web.Configuration.XhtmlConformanceSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.XhtmlConformanceSection
  langs:
  - csharp
  name: XhtmlConformanceSection()
  nameWithType: XhtmlConformanceSection.XhtmlConformanceSection()
  fullName: XhtmlConformanceSection.XhtmlConformanceSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Configuration.XhtmlConformanceSection"></xref> class using default parameters.
  remarks: The <xref:System.Web.Configuration.XhtmlConformanceSection.%23ctor%2A> constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system. You obtain an instance of the <xref:System.Web.Configuration.XhtmlConformanceSection> class by using the <xref:System.Configuration.Configuration.GetSection%2A> method.
  syntax:
    content: public XhtmlConformanceSection ();
    parameters: []
  overload: System.Web.Configuration.XhtmlConformanceSection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/XhtmlConformanceSection.xml
- uid: System.Web.Configuration.XhtmlConformanceSection.Mode
  commentId: P:System.Web.Configuration.XhtmlConformanceSection.Mode
  id: Mode
  parent: System.Web.Configuration.XhtmlConformanceSection
  langs:
  - csharp
  name: Mode
  nameWithType: XhtmlConformanceSection.Mode
  fullName: XhtmlConformanceSection.Mode
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets or sets the <xref href="System.Web.Configuration.XhtmlConformanceSection.Mode"></xref> property.
  remarks: By default, when you are working with browsers that support HTML 4.0 or later, ASP.NET pages and controls render markup that is compatible with the XHTML 1.0 Transitional standard. However, under some circumstances, you might not want ASP.NET to render XHTML markup. This is typically true when you have existing pages that rely on tags or attributes that would ordinarily be prohibited by XHTML.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("mode", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.Web.Configuration.XhtmlConformanceMode Mode { get; set; }
    return:
      type: System.Web.Configuration.XhtmlConformanceMode
      description: One of the <xref href="System.Web.Configuration.XhtmlConformanceMode"></xref> values. The default is <xref href="System.Web.Configuration.XhtmlConformanceMode.Transitional"></xref>.
  overload: System.Web.Configuration.XhtmlConformanceSection.Mode*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/XhtmlConformanceSection.xml
- uid: System.Web.Configuration.XhtmlConformanceSection.Properties
  commentId: P:System.Web.Configuration.XhtmlConformanceSection.Properties
  id: Properties
  parent: System.Web.Configuration.XhtmlConformanceSection
  langs:
  - csharp
  name: Properties
  nameWithType: XhtmlConformanceSection.Properties
  fullName: XhtmlConformanceSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.XhtmlConformanceSection.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/XhtmlConformanceSection.xml
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.XhtmlConformanceSection.#ctor
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: XhtmlConformanceSection()
  nameWithType: XhtmlConformanceSection.XhtmlConformanceSection()
  fullName: XhtmlConformanceSection.XhtmlConformanceSection()
- uid: System.Web.Configuration.XhtmlConformanceSection.Mode
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Mode
  nameWithType: XhtmlConformanceSection.Mode
  fullName: XhtmlConformanceSection.Mode
- uid: System.Web.Configuration.XhtmlConformanceMode
  parent: System.Web.Configuration
  isExternal: false
  name: XhtmlConformanceMode
  nameWithType: XhtmlConformanceMode
  fullName: System.Web.Configuration.XhtmlConformanceMode
- uid: System.Web.Configuration.XhtmlConformanceSection.Properties
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Properties
  nameWithType: XhtmlConformanceSection.Properties
  fullName: XhtmlConformanceSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.XhtmlConformanceSection.#ctor*
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: XhtmlConformanceSection
  nameWithType: XhtmlConformanceSection.XhtmlConformanceSection
  fullName: XhtmlConformanceSection.XhtmlConformanceSection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/XhtmlConformanceSection.xml
- uid: System.Web.Configuration.XhtmlConformanceSection.Mode*
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Mode
  nameWithType: XhtmlConformanceSection.Mode
  fullName: XhtmlConformanceSection.Mode
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/XhtmlConformanceSection.xml
- uid: System.Web.Configuration.XhtmlConformanceSection.Properties*
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Properties
  nameWithType: XhtmlConformanceSection.Properties
  fullName: XhtmlConformanceSection.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/XhtmlConformanceSection.xml
