### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BaseAddressElement
  commentId: T:System.ServiceModel.Configuration.BaseAddressElement
  id: BaseAddressElement
  children:
  - System.ServiceModel.Configuration.BaseAddressElement.#ctor
  - System.ServiceModel.Configuration.BaseAddressElement.BaseAddress
  - System.ServiceModel.Configuration.BaseAddressElement.Properties
  langs:
  - csharp
  name: BaseAddressElement
  nameWithType: BaseAddressElement
  fullName: System.ServiceModel.Configuration.BaseAddressElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a configuration element that specifies the base addresses used by the service host. This class cannot be inherited.
  syntax:
    content: 'public sealed class BaseAddressElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BaseAddressElement.xml
- uid: System.ServiceModel.Configuration.BaseAddressElement.#ctor
  commentId: M:System.ServiceModel.Configuration.BaseAddressElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BaseAddressElement
  langs:
  - csharp
  name: BaseAddressElement()
  nameWithType: BaseAddressElement.BaseAddressElement()
  fullName: BaseAddressElement.BaseAddressElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.BaseAddressElement"></xref> class.
  syntax:
    content: public BaseAddressElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.BaseAddressElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BaseAddressElement.xml
- uid: System.ServiceModel.Configuration.BaseAddressElement.BaseAddress
  commentId: P:System.ServiceModel.Configuration.BaseAddressElement.BaseAddress
  id: BaseAddress
  parent: System.ServiceModel.Configuration.BaseAddressElement
  langs:
  - csharp
  name: BaseAddress
  nameWithType: BaseAddressElement.BaseAddress
  fullName: BaseAddressElement.BaseAddress
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets a base address used by the service host.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("baseAddress", Options=System.Configuration.ConfigurationPropertyOptions.IsRequired | System.Configuration.ConfigurationPropertyOptions.IsKey)]

      [System.Configuration.StringValidator(MinLength=1)]

      public string BaseAddress { get; set; }
    return:
      type: System.String
      description: A base address used by the service host.
  overload: System.ServiceModel.Configuration.BaseAddressElement.BaseAddress*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BaseAddressElement.xml
- uid: System.ServiceModel.Configuration.BaseAddressElement.Properties
  commentId: P:System.ServiceModel.Configuration.BaseAddressElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.BaseAddressElement
  langs:
  - csharp
  name: Properties
  nameWithType: BaseAddressElement.Properties
  fullName: BaseAddressElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.BaseAddressElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BaseAddressElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.BaseAddressElement.#ctor
  parent: System.ServiceModel.Configuration.BaseAddressElement
  isExternal: false
  name: BaseAddressElement()
  nameWithType: BaseAddressElement.BaseAddressElement()
  fullName: BaseAddressElement.BaseAddressElement()
- uid: System.ServiceModel.Configuration.BaseAddressElement.BaseAddress
  parent: System.ServiceModel.Configuration.BaseAddressElement
  isExternal: false
  name: BaseAddress
  nameWithType: BaseAddressElement.BaseAddress
  fullName: BaseAddressElement.BaseAddress
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.BaseAddressElement.Properties
  parent: System.ServiceModel.Configuration.BaseAddressElement
  isExternal: false
  name: Properties
  nameWithType: BaseAddressElement.Properties
  fullName: BaseAddressElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.BaseAddressElement.#ctor*
  parent: System.ServiceModel.Configuration.BaseAddressElement
  isExternal: false
  name: BaseAddressElement
  nameWithType: BaseAddressElement.BaseAddressElement
  fullName: BaseAddressElement.BaseAddressElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BaseAddressElement.xml
- uid: System.ServiceModel.Configuration.BaseAddressElement.BaseAddress*
  parent: System.ServiceModel.Configuration.BaseAddressElement
  isExternal: false
  name: BaseAddress
  nameWithType: BaseAddressElement.BaseAddress
  fullName: BaseAddressElement.BaseAddress
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BaseAddressElement.xml
- uid: System.ServiceModel.Configuration.BaseAddressElement.Properties*
  parent: System.ServiceModel.Configuration.BaseAddressElement
  isExternal: false
  name: Properties
  nameWithType: BaseAddressElement.Properties
  fullName: BaseAddressElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BaseAddressElement.xml
