### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup
  commentId: T:System.Web.Configuration.ScriptingWebServicesSectionGroup
  id: ScriptingWebServicesSectionGroup
  children:
  - System.Web.Configuration.ScriptingWebServicesSectionGroup.#ctor
  - System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService
  - System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization
  - System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService
  - System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService
  langs:
  - csharp
  name: ScriptingWebServicesSectionGroup
  nameWithType: ScriptingWebServicesSectionGroup
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup
  type: Class
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: Represents a group of related sections in a configuration file.
  remarks: Use the <xref:System.Web.Configuration.ScriptingWebServicesSectionGroup> class to programmatically set and retrieve the values of the `webServices` section of the configuration file.
  syntax:
    content: 'public sealed class ScriptingWebServicesSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingWebServicesSectionGroup.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.#ctor
  commentId: M:System.Web.Configuration.ScriptingWebServicesSectionGroup.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  langs:
  - csharp
  name: ScriptingWebServicesSectionGroup()
  nameWithType: ScriptingWebServicesSectionGroup.ScriptingWebServicesSectionGroup()
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.ScriptingWebServicesSectionGroup()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Configuration.ScriptingWebServicesSectionGroup"></xref> class.
  syntax:
    content: public ScriptingWebServicesSectionGroup ();
    parameters: []
  overload: System.Web.Configuration.ScriptingWebServicesSectionGroup.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingWebServicesSectionGroup.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService
  commentId: P:System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService
  id: AuthenticationService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  langs:
  - csharp
  name: AuthenticationService
  nameWithType: ScriptingWebServicesSectionGroup.AuthenticationService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: Gets the `authenticationService` section that is contained in the configuration file.
  remarks: The <xref:System.Web.Configuration.ScriptingAuthenticationServiceSection> object refers to the `authenticationService` section of the configuration file.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("authenticationService")]

      public System.Web.Configuration.ScriptingAuthenticationServiceSection AuthenticationService { get; }
    return:
      type: System.Web.Configuration.ScriptingAuthenticationServiceSection
      description: A <xref href="System.Web.Configuration.ScriptingAuthenticationServiceSection"></xref> object.
  overload: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingWebServicesSectionGroup.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization
  commentId: P:System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization
  id: JsonSerialization
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  langs:
  - csharp
  name: JsonSerialization
  nameWithType: ScriptingWebServicesSectionGroup.JsonSerialization
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: Gets the `jsonSerialization` section that is contained in the configuration file.
  remarks: The <xref:System.Web.Configuration.ScriptingJsonSerializationSection> object refers to the `jsonSerialization` section of the configuration file.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("jsonSerialization")]

      public System.Web.Configuration.ScriptingJsonSerializationSection JsonSerialization { get; }
    return:
      type: System.Web.Configuration.ScriptingJsonSerializationSection
      description: A <xref href="System.Web.Configuration.ScriptingJsonSerializationSection"></xref> object.
  overload: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingWebServicesSectionGroup.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService
  commentId: P:System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService
  id: ProfileService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  langs:
  - csharp
  name: ProfileService
  nameWithType: ScriptingWebServicesSectionGroup.ProfileService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: Gets the `profileService` section that is contained in the configuration file.
  remarks: The <xref:System.Web.Configuration.ScriptingProfileServiceSection> object refers to the `profileService` section of the configuration file.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("profileService")]

      public System.Web.Configuration.ScriptingProfileServiceSection ProfileService { get; }
    return:
      type: System.Web.Configuration.ScriptingProfileServiceSection
      description: A <xref href="System.Web.Configuration.ScriptingProfileServiceSection"></xref> object.
  overload: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingWebServicesSectionGroup.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService
  commentId: P:System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService
  id: RoleService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  langs:
  - csharp
  name: RoleService
  nameWithType: ScriptingWebServicesSectionGroup.RoleService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: Gets the `roleService` section that is contained in the configuration file.
  remarks: The <xref:System.Web.Configuration.ScriptingRoleServiceSection> object refers to the `roleService` section of the configuration file.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("roleService")]

      public System.Web.Configuration.ScriptingRoleServiceSection RoleService { get; }
    return:
      type: System.Web.Configuration.ScriptingRoleServiceSection
      description: A <xref href="System.Web.Configuration.ScriptingRoleServiceSection"></xref> object.
  overload: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingWebServicesSectionGroup.xml
  ms.author: riande
  manager: wpickett
references:
- uid: System.Configuration.ConfigurationSectionGroup
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSectionGroup
  nameWithType: ConfigurationSectionGroup
  fullName: System.Configuration.ConfigurationSectionGroup
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.#ctor
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: ScriptingWebServicesSectionGroup()
  nameWithType: ScriptingWebServicesSectionGroup.ScriptingWebServicesSectionGroup()
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.ScriptingWebServicesSectionGroup()
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: AuthenticationService
  nameWithType: ScriptingWebServicesSectionGroup.AuthenticationService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService
- uid: System.Web.Configuration.ScriptingAuthenticationServiceSection
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingAuthenticationServiceSection
  nameWithType: ScriptingAuthenticationServiceSection
  fullName: System.Web.Configuration.ScriptingAuthenticationServiceSection
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: JsonSerialization
  nameWithType: ScriptingWebServicesSectionGroup.JsonSerialization
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization
- uid: System.Web.Configuration.ScriptingJsonSerializationSection
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingJsonSerializationSection
  nameWithType: ScriptingJsonSerializationSection
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: ProfileService
  nameWithType: ScriptingWebServicesSectionGroup.ProfileService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService
- uid: System.Web.Configuration.ScriptingProfileServiceSection
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingProfileServiceSection
  nameWithType: ScriptingProfileServiceSection
  fullName: System.Web.Configuration.ScriptingProfileServiceSection
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: RoleService
  nameWithType: ScriptingWebServicesSectionGroup.RoleService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService
- uid: System.Web.Configuration.ScriptingRoleServiceSection
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingRoleServiceSection
  nameWithType: ScriptingRoleServiceSection
  fullName: System.Web.Configuration.ScriptingRoleServiceSection
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.#ctor*
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: ScriptingWebServicesSectionGroup
  nameWithType: ScriptingWebServicesSectionGroup.ScriptingWebServicesSectionGroup
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.ScriptingWebServicesSectionGroup
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingWebServicesSectionGroup.xml
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService*
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: AuthenticationService
  nameWithType: ScriptingWebServicesSectionGroup.AuthenticationService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingWebServicesSectionGroup.xml
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization*
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: JsonSerialization
  nameWithType: ScriptingWebServicesSectionGroup.JsonSerialization
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingWebServicesSectionGroup.xml
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService*
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: ProfileService
  nameWithType: ScriptingWebServicesSectionGroup.ProfileService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingWebServicesSectionGroup.xml
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService*
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: RoleService
  nameWithType: ScriptingWebServicesSectionGroup.RoleService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingWebServicesSectionGroup.xml
