### YamlMime:ManagedReference
items:
- uid: System.Configuration.IriParsingElement
  commentId: T:System.Configuration.IriParsingElement
  id: IriParsingElement
  children:
  - System.Configuration.IriParsingElement.#ctor
  - System.Configuration.IriParsingElement.Enabled
  - System.Configuration.IriParsingElement.Equals(System.Object)
  - System.Configuration.IriParsingElement.GetHashCode
  - System.Configuration.IriParsingElement.Properties
  langs:
  - csharp
  name: IriParsingElement
  nameWithType: IriParsingElement
  fullName: System.Configuration.IriParsingElement
  type: Class
  assemblies:
  - System
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Provides the configuration setting for International Resource Identifier (IRI) processing in the <xref href="System.Uri"></xref> class.
  remarks: "The existing <xref:System.Uri?displayProperty=fullName> class has been extended to provide support for International Resource Identifiers (IRI) based on RFC 3987. Current users will not see any change from the .NET Framework 2.0 behavior unless they specifically enable IRI. This ensures application compatibility with prior versions of the .NET Framework.  \n  \n The configuration setting for the <xref:System.Configuration.IriParsingElement> will be read once when the first <xref:System.Uri?displayProperty=fullName> class is constructed. Changes to configuration settings after that time are ignored.  \n  \n For more information on IRI support, see the Remarks section for the <xref:System.Uri?displayProperty=fullName> class."
  syntax:
    content: 'public sealed class IriParsingElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/IriParsingElement.xml
- uid: System.Configuration.IriParsingElement.#ctor
  commentId: M:System.Configuration.IriParsingElement.#ctor
  id: '#ctor'
  parent: System.Configuration.IriParsingElement
  langs:
  - csharp
  name: IriParsingElement()
  nameWithType: IriParsingElement.IriParsingElement()
  fullName: IriParsingElement.IriParsingElement()
  type: Constructor
  assemblies:
  - System
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.IriParsingElement"></xref> class.
  remarks: This constructor creates a <xref:System.Configuration.IriParsingElement> instance.
  syntax:
    content: public IriParsingElement ();
    parameters: []
  overload: System.Configuration.IriParsingElement.#ctor*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/IriParsingElement.xml
- uid: System.Configuration.IriParsingElement.Enabled
  commentId: P:System.Configuration.IriParsingElement.Enabled
  id: Enabled
  parent: System.Configuration.IriParsingElement
  langs:
  - csharp
  name: Enabled
  nameWithType: IriParsingElement.Enabled
  fullName: IriParsingElement.Enabled
  type: Property
  assemblies:
  - System
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Gets or sets the value of the <xref href="System.Configuration.IriParsingElement"></xref> configuration setting.
  remarks: "The <xref:System.Configuration.IriParsingElement> configuration setting controls IRI processing in the <xref:System.Uri?displayProperty=fullName> class. This setting also indirectly controls International Domain Name (IDN) processing set with the <xref:System.Configuration.IdnElement?displayProperty=fullName> class. IRI processing must be enabled for IDN processing to be possible. If IRI processing is disabled, then IDN processing will be set to the default setting where the .NET Framework 2.0 behavior is used for compatibility and IDN names are not used.  \n  \n The configuration setting for the <xref:System.Configuration.IriParsingElement> will be read once when the first <xref:System.Uri?displayProperty=fullName> class is constructed. Changes to configuration settings after that time are ignored.  \n  \n For more information on IRI support, see the Remarks section for the <xref:System.Uri?displayProperty=fullName> class."
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("enabled", DefaultValue=Mono.Cecil.CustomAttributeArgument, Options=System.Configuration.ConfigurationPropertyOptions.IsRequired | System.Configuration.ConfigurationPropertyOptions.IsKey)]

      public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: A Boolean that indicates if International Resource Identifier (IRI) processing is enabled.
  overload: System.Configuration.IriParsingElement.Enabled*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/IriParsingElement.xml
- uid: System.Configuration.IriParsingElement.Equals(System.Object)
  commentId: M:System.Configuration.IriParsingElement.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Configuration.IriParsingElement
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: IriParsingElement.Equals(Object)
  fullName: IriParsingElement.Equals(Object)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  syntax:
    content: public override bool Equals (object o);
    parameters:
    - id: o
      type: System.Object
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  overload: System.Configuration.IriParsingElement.Equals*
  exceptions: []
  version:
  - xamarinmac-3.0
  monikers:
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/IriParsingElement.xml
- uid: System.Configuration.IriParsingElement.GetHashCode
  commentId: M:System.Configuration.IriParsingElement.GetHashCode
  id: GetHashCode
  parent: System.Configuration.IriParsingElement
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: IriParsingElement.GetHashCode()
  fullName: IriParsingElement.GetHashCode()
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: To be added.
  overload: System.Configuration.IriParsingElement.GetHashCode*
  exceptions: []
  version:
  - xamarinmac-3.0
  monikers:
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/IriParsingElement.xml
- uid: System.Configuration.IriParsingElement.Properties
  commentId: P:System.Configuration.IriParsingElement.Properties
  id: Properties
  parent: System.Configuration.IriParsingElement
  langs:
  - csharp
  name: Properties
  nameWithType: IriParsingElement.Properties
  fullName: IriParsingElement.Properties
  type: Property
  assemblies:
  - System
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Configuration.IriParsingElement.Properties*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/IriParsingElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Configuration.IriParsingElement.#ctor
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: IriParsingElement()
  nameWithType: IriParsingElement.IriParsingElement()
  fullName: IriParsingElement.IriParsingElement()
- uid: System.Configuration.IriParsingElement.Enabled
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: Enabled
  nameWithType: IriParsingElement.Enabled
  fullName: IriParsingElement.Enabled
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.IriParsingElement.Equals(System.Object)
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: Equals(Object)
  nameWithType: IriParsingElement.Equals(Object)
  fullName: IriParsingElement.Equals(Object)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.IriParsingElement.GetHashCode
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: GetHashCode()
  nameWithType: IriParsingElement.GetHashCode()
  fullName: IriParsingElement.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.IriParsingElement.Properties
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: Properties
  nameWithType: IriParsingElement.Properties
  fullName: IriParsingElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.IriParsingElement.#ctor*
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: IriParsingElement
  nameWithType: IriParsingElement.IriParsingElement
  fullName: IriParsingElement.IriParsingElement
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/IriParsingElement.xml
- uid: System.Configuration.IriParsingElement.Enabled*
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: Enabled
  nameWithType: IriParsingElement.Enabled
  fullName: IriParsingElement.Enabled
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/IriParsingElement.xml
- uid: System.Configuration.IriParsingElement.Equals*
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: Equals
  nameWithType: IriParsingElement.Equals
  fullName: IriParsingElement.Equals
  monikers:
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/IriParsingElement.xml
- uid: System.Configuration.IriParsingElement.GetHashCode*
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: GetHashCode
  nameWithType: IriParsingElement.GetHashCode
  fullName: IriParsingElement.GetHashCode
  monikers:
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/IriParsingElement.xml
- uid: System.Configuration.IriParsingElement.Properties*
  parent: System.Configuration.IriParsingElement
  isExternal: false
  name: Properties
  nameWithType: IriParsingElement.Properties
  fullName: IriParsingElement.Properties
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/IriParsingElement.xml
