### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.CodeSubDirectory
  commentId: T:System.Web.Configuration.CodeSubDirectory
  id: CodeSubDirectory
  children:
  - System.Web.Configuration.CodeSubDirectory.#ctor(System.String)
  - System.Web.Configuration.CodeSubDirectory.DirectoryName
  - System.Web.Configuration.CodeSubDirectory.Properties
  langs:
  - csharp
  name: CodeSubDirectory
  nameWithType: CodeSubDirectory
  fullName: System.Web.Configuration.CodeSubDirectory
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: References a directory location that is used during compilation of a dynamic resource. This class cannot be inherited.
  remarks: "A <xref:System.Web.Configuration.CodeSubDirectory> is referenced as an attribute of the `Add` element within the `codeSubDirectories` node of the `compilation` section of the configuration.  \n  \n The build order is inferred from the top-down order of the `codeSubDirectories` in the configuration. The `\\App_Code` directory is built last. However, there are no build-order dependencies, which means the build order does not matter here."
  syntax:
    content: 'public sealed class CodeSubDirectory : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/CodeSubDirectory.xml
- uid: System.Web.Configuration.CodeSubDirectory.#ctor(System.String)
  commentId: M:System.Web.Configuration.CodeSubDirectory.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Configuration.CodeSubDirectory
  langs:
  - csharp
  name: CodeSubDirectory(String)
  nameWithType: CodeSubDirectory.CodeSubDirectory(String)
  fullName: CodeSubDirectory.CodeSubDirectory(String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Configuration.CodeSubDirectory"></xref> class.
  syntax:
    content: public CodeSubDirectory (string directoryName);
    parameters:
    - id: directoryName
      type: System.String
      description: A string value specifying the <xref href="System.Web.Configuration.CodeSubDirectory"></xref> reference.
  overload: System.Web.Configuration.CodeSubDirectory.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/CodeSubDirectory.xml
- uid: System.Web.Configuration.CodeSubDirectory.DirectoryName
  commentId: P:System.Web.Configuration.CodeSubDirectory.DirectoryName
  id: DirectoryName
  parent: System.Web.Configuration.CodeSubDirectory
  langs:
  - csharp
  name: DirectoryName
  nameWithType: CodeSubDirectory.DirectoryName
  fullName: CodeSubDirectory.DirectoryName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets or sets the name of the directory that contains files compiled at run time.
  remarks: A `directoryName` attribute of an `add` element of the configuration is searched only from the `\App_Code` path; therefore, adding `directoryName="\App_Code\Applogic"` is not valid.
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(System.Configuration.WhiteSpaceTrimStringConverter))]

      [System.Configuration.ConfigurationProperty("directoryName", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsKey=true, IsRequired=true)]

      public string DirectoryName { get; set; }
    return:
      type: System.String
      description: A string value specifying the name of the directory reference used during compilation.
  overload: System.Web.Configuration.CodeSubDirectory.DirectoryName*
  exceptions: []
  attributes:
  - type: System.ComponentModel.TypeConverterAttribute
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/CodeSubDirectory.xml
- uid: System.Web.Configuration.CodeSubDirectory.Properties
  commentId: P:System.Web.Configuration.CodeSubDirectory.Properties
  id: Properties
  parent: System.Web.Configuration.CodeSubDirectory
  langs:
  - csharp
  name: Properties
  nameWithType: CodeSubDirectory.Properties
  fullName: CodeSubDirectory.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.CodeSubDirectory.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/CodeSubDirectory.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.CodeSubDirectory.#ctor(System.String)
  parent: System.Web.Configuration.CodeSubDirectory
  isExternal: false
  name: CodeSubDirectory(String)
  nameWithType: CodeSubDirectory.CodeSubDirectory(String)
  fullName: CodeSubDirectory.CodeSubDirectory(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.CodeSubDirectory.DirectoryName
  parent: System.Web.Configuration.CodeSubDirectory
  isExternal: false
  name: DirectoryName
  nameWithType: CodeSubDirectory.DirectoryName
  fullName: CodeSubDirectory.DirectoryName
- uid: System.Web.Configuration.CodeSubDirectory.Properties
  parent: System.Web.Configuration.CodeSubDirectory
  isExternal: false
  name: Properties
  nameWithType: CodeSubDirectory.Properties
  fullName: CodeSubDirectory.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.CodeSubDirectory.#ctor*
  parent: System.Web.Configuration.CodeSubDirectory
  isExternal: false
  name: CodeSubDirectory
  nameWithType: CodeSubDirectory.CodeSubDirectory
  fullName: CodeSubDirectory.CodeSubDirectory
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/CodeSubDirectory.xml
- uid: System.Web.Configuration.CodeSubDirectory.DirectoryName*
  parent: System.Web.Configuration.CodeSubDirectory
  isExternal: false
  name: DirectoryName
  nameWithType: CodeSubDirectory.DirectoryName
  fullName: CodeSubDirectory.DirectoryName
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/CodeSubDirectory.xml
- uid: System.Web.Configuration.CodeSubDirectory.Properties*
  parent: System.Web.Configuration.CodeSubDirectory
  isExternal: false
  name: Properties
  nameWithType: CodeSubDirectory.Properties
  fullName: CodeSubDirectory.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/CodeSubDirectory.xml
