### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection
  commentId: T:System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection
  id: IssuedTokenClientBehaviorsElementCollection
  children:
  - System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection.#ctor
  - System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  name: IssuedTokenClientBehaviorsElementCollection
  nameWithType: IssuedTokenClientBehaviorsElementCollection
  fullName: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a collection of <xref href="System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement"></xref> instances. This class cannot be inherited.
  syntax:
    content: >-
      [System.Configuration.ConfigurationCollection(typeof(System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement))]

      public sealed class IssuedTokenClientBehaviorsElementCollection : System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection<System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement>
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationElementCollection
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.AddElementName
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseClear
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseGetAllKeys
  - System.Configuration.ConfigurationElementCollection.BaseGetKey(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseIndexOf(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseIsRemoved(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemove(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemoveAt(System.Int32)
  - System.Configuration.ConfigurationElementCollection.ClearElementName
  - System.Configuration.ConfigurationElementCollection.CopyTo(System.Configuration.ConfigurationElement[],System.Int32)
  - System.Configuration.ConfigurationElementCollection.Count
  - System.Configuration.ConfigurationElementCollection.CreateNewElement(System.String)
  - System.Configuration.ConfigurationElementCollection.EmitClear
  - System.Configuration.ConfigurationElementCollection.Equals(System.Object)
  - System.Configuration.ConfigurationElementCollection.GetEnumerator
  - System.Configuration.ConfigurationElementCollection.GetHashCode
  - System.Configuration.ConfigurationElementCollection.IsElementName(System.String)
  - System.Configuration.ConfigurationElementCollection.IsElementRemovable(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.IsModified
  - System.Configuration.ConfigurationElementCollection.IsReadOnly
  - System.Configuration.ConfigurationElementCollection.IsSynchronized
  - System.Configuration.ConfigurationElementCollection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElementCollection.RemoveElementName
  - System.Configuration.ConfigurationElementCollection.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.ResetModified
  - System.Configuration.ConfigurationElementCollection.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.SetReadOnly
  - System.Configuration.ConfigurationElementCollection.SyncRoot
  - System.Configuration.ConfigurationElementCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Configuration.ConfigurationElementCollection.ThrowOnDuplicate
  - System.Configuration.ConfigurationElementCollection.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Add(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.BaseAdd(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Clear
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CollectionType
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.ContainsKey(System.Object)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CopyTo(`0[],System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.ElementName
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.IndexOf(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Item(System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Item(System.Object)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Remove(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.RemoveAt(System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.RemoveAt(System.Object)
  extensionMethods:
  - System.Linq.Enumerable.Cast``1(System.Collections.IEnumerable)
  - System.Linq.Enumerable.OfType``1(System.Collections.IEnumerable)
  - System.Linq.ParallelEnumerable.AsParallel(System.Collections.IEnumerable)
  - System.Linq.Queryable.AsQueryable(System.Collections.IEnumerable)
  attributes:
  - type: System.Configuration.ConfigurationCollectionAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenClientBehaviorsElementCollection.xml
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection.#ctor
  commentId: M:System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection
  langs:
  - csharp
  name: IssuedTokenClientBehaviorsElementCollection()
  nameWithType: IssuedTokenClientBehaviorsElementCollection.IssuedTokenClientBehaviorsElementCollection()
  fullName: IssuedTokenClientBehaviorsElementCollection.IssuedTokenClientBehaviorsElementCollection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection"></xref> class.
  syntax:
    content: public IssuedTokenClientBehaviorsElementCollection ();
    parameters: []
  overload: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenClientBehaviorsElementCollection.xml
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  commentId: M:System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection
  langs:
  - csharp
  name: GetElementKey(ConfigurationElement)
  nameWithType: IssuedTokenClientBehaviorsElementCollection.GetElementKey(ConfigurationElement)
  fullName: IssuedTokenClientBehaviorsElementCollection.GetElementKey(ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override object GetElementKey (System.Configuration.ConfigurationElement element);
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
      description: To be added.
    return:
      type: System.Object
      description: To be added.
  overload: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection.GetElementKey*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenClientBehaviorsElementCollection.xml
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1
  name: ServiceModelConfigurationElementCollection<ConfigurationElementType>
  nameWithType: ServiceModelConfigurationElementCollection<ConfigurationElementType>
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection<ConfigurationElementType>
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
  name: IssuedTokenClientBehaviorsElement
  nameWithType: IssuedTokenClientBehaviorsElement
  fullName: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection{System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement}
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelConfigurationElementCollection<IssuedTokenClientBehaviorsElement>
  nameWithType: ServiceModelConfigurationElementCollection<IssuedTokenClientBehaviorsElement>
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection<System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement>
  spec.csharp:
  - uid: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
    name: IssuedTokenClientBehaviorsElement
    nameWithType: IssuedTokenClientBehaviorsElement
    fullName: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection.#ctor
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection
  isExternal: false
  name: IssuedTokenClientBehaviorsElementCollection()
  nameWithType: IssuedTokenClientBehaviorsElementCollection.IssuedTokenClientBehaviorsElementCollection()
  fullName: IssuedTokenClientBehaviorsElementCollection.IssuedTokenClientBehaviorsElementCollection()
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection
  isExternal: false
  name: GetElementKey(ConfigurationElement)
  nameWithType: IssuedTokenClientBehaviorsElementCollection.GetElementKey(ConfigurationElement)
  fullName: IssuedTokenClientBehaviorsElementCollection.GetElementKey(ConfigurationElement)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection.#ctor*
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection
  isExternal: false
  name: IssuedTokenClientBehaviorsElementCollection
  nameWithType: IssuedTokenClientBehaviorsElementCollection.IssuedTokenClientBehaviorsElementCollection
  fullName: IssuedTokenClientBehaviorsElementCollection.IssuedTokenClientBehaviorsElementCollection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenClientBehaviorsElementCollection.xml
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection.GetElementKey*
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElementCollection
  isExternal: false
  name: GetElementKey
  nameWithType: IssuedTokenClientBehaviorsElementCollection.GetElementKey
  fullName: IssuedTokenClientBehaviorsElementCollection.GetElementKey
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenClientBehaviorsElementCollection.xml
- uid: System.Linq.Enumerable.Cast``1(System.Collections.IEnumerable)
  parent: System.Linq.Enumerable
  isExternal: false
  name: Cast<TResult>(IEnumerable)
  nameWithType: Enumerable.Cast<TResult>(IEnumerable)
  fullName: Enumerable.Cast<TResult>(IEnumerable)
- uid: System.Linq.Enumerable.OfType``1(System.Collections.IEnumerable)
  parent: System.Linq.Enumerable
  isExternal: false
  name: OfType<TResult>(IEnumerable)
  nameWithType: Enumerable.OfType<TResult>(IEnumerable)
  fullName: Enumerable.OfType<TResult>(IEnumerable)
- uid: System.Linq.ParallelEnumerable.AsParallel(System.Collections.IEnumerable)
  parent: System.Linq.ParallelEnumerable
  isExternal: false
  name: AsParallel(IEnumerable)
  nameWithType: ParallelEnumerable.AsParallel(IEnumerable)
  fullName: ParallelEnumerable.AsParallel(IEnumerable)
- uid: System.Linq.Queryable.AsQueryable(System.Collections.IEnumerable)
  parent: System.Linq.Queryable
  isExternal: false
  name: AsQueryable(IEnumerable)
  nameWithType: Queryable.AsQueryable(IEnumerable)
  fullName: Queryable.AsQueryable(IEnumerable)
