### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Metadata.ApplicationServiceDescriptor
  commentId: T:System.IdentityModel.Metadata.ApplicationServiceDescriptor
  id: ApplicationServiceDescriptor
  children:
  - System.IdentityModel.Metadata.ApplicationServiceDescriptor.#ctor
  - System.IdentityModel.Metadata.ApplicationServiceDescriptor.Endpoints
  - System.IdentityModel.Metadata.ApplicationServiceDescriptor.PassiveRequestorEndpoints
  langs:
  - csharp
  name: ApplicationServiceDescriptor
  nameWithType: ApplicationServiceDescriptor
  fullName: System.IdentityModel.Metadata.ApplicationServiceDescriptor
  type: Class
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Metadata
  summary: Defines the application service descriptor and its endpoints.
  syntax:
    content: 'public class ApplicationServiceDescriptor : System.IdentityModel.Metadata.WebServiceDescriptor'
  inheritance:
  - System.Object
  - System.IdentityModel.Metadata.RoleDescriptor
  - System.IdentityModel.Metadata.WebServiceDescriptor
  implements: []
  inheritedMembers:
  - System.IdentityModel.Metadata.RoleDescriptor.Contacts
  - System.IdentityModel.Metadata.RoleDescriptor.ErrorUrl
  - System.IdentityModel.Metadata.RoleDescriptor.Keys
  - System.IdentityModel.Metadata.RoleDescriptor.Organization
  - System.IdentityModel.Metadata.RoleDescriptor.ProtocolsSupported
  - System.IdentityModel.Metadata.RoleDescriptor.ValidUntil
  - System.IdentityModel.Metadata.WebServiceDescriptor.ClaimTypesOffered
  - System.IdentityModel.Metadata.WebServiceDescriptor.ClaimTypesRequested
  - System.IdentityModel.Metadata.WebServiceDescriptor.ServiceDescription
  - System.IdentityModel.Metadata.WebServiceDescriptor.ServiceDisplayName
  - System.IdentityModel.Metadata.WebServiceDescriptor.TargetScopes
  - System.IdentityModel.Metadata.WebServiceDescriptor.TokenTypesOffered
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Metadata/ApplicationServiceDescriptor.xml
  ms.author: v-jibran
  manager: markgal
- uid: System.IdentityModel.Metadata.ApplicationServiceDescriptor.#ctor
  commentId: M:System.IdentityModel.Metadata.ApplicationServiceDescriptor.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Metadata.ApplicationServiceDescriptor
  langs:
  - csharp
  name: ApplicationServiceDescriptor()
  nameWithType: ApplicationServiceDescriptor.ApplicationServiceDescriptor()
  fullName: System.IdentityModel.Metadata.ApplicationServiceDescriptor.ApplicationServiceDescriptor()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Metadata
  summary: Initializes an instance of the <xref href="System.IdentityModel.Metadata.ApplicationServiceDescriptor"></xref> class.
  syntax:
    content: public ApplicationServiceDescriptor ();
    parameters: []
  overload: System.IdentityModel.Metadata.ApplicationServiceDescriptor.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Metadata/ApplicationServiceDescriptor.xml
  ms.author: v-jibran
  manager: markgal
- uid: System.IdentityModel.Metadata.ApplicationServiceDescriptor.Endpoints
  commentId: P:System.IdentityModel.Metadata.ApplicationServiceDescriptor.Endpoints
  id: Endpoints
  parent: System.IdentityModel.Metadata.ApplicationServiceDescriptor
  langs:
  - csharp
  name: Endpoints
  nameWithType: ApplicationServiceDescriptor.Endpoints
  fullName: System.IdentityModel.Metadata.ApplicationServiceDescriptor.Endpoints
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Metadata
  summary: Gets the endpoints of this application service.
  syntax:
    content: public System.Collections.Generic.ICollection<System.IdentityModel.Protocols.WSTrust.EndpointReference> Endpoints { get; }
    return:
      type: System.Collections.Generic.ICollection{System.IdentityModel.Protocols.WSTrust.EndpointReference}
      description: The collection of endpoints for the application service.
  overload: System.IdentityModel.Metadata.ApplicationServiceDescriptor.Endpoints*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Metadata/ApplicationServiceDescriptor.xml
  ms.author: v-jibran
  manager: markgal
- uid: System.IdentityModel.Metadata.ApplicationServiceDescriptor.PassiveRequestorEndpoints
  commentId: P:System.IdentityModel.Metadata.ApplicationServiceDescriptor.PassiveRequestorEndpoints
  id: PassiveRequestorEndpoints
  parent: System.IdentityModel.Metadata.ApplicationServiceDescriptor
  langs:
  - csharp
  name: PassiveRequestorEndpoints
  nameWithType: ApplicationServiceDescriptor.PassiveRequestorEndpoints
  fullName: System.IdentityModel.Metadata.ApplicationServiceDescriptor.PassiveRequestorEndpoints
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Metadata
  summary: Gets the passive requestor endpoints of this application service.
  syntax:
    content: public System.Collections.Generic.ICollection<System.IdentityModel.Protocols.WSTrust.EndpointReference> PassiveRequestorEndpoints { get; }
    return:
      type: System.Collections.Generic.ICollection{System.IdentityModel.Protocols.WSTrust.EndpointReference}
      description: The collection of passive requestor endpoints for the application service.
  overload: System.IdentityModel.Metadata.ApplicationServiceDescriptor.PassiveRequestorEndpoints*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Metadata/ApplicationServiceDescriptor.xml
  ms.author: v-jibran
  manager: markgal
references:
- uid: System.IdentityModel.Metadata.WebServiceDescriptor
  parent: System.IdentityModel.Metadata
  isExternal: false
  name: WebServiceDescriptor
  nameWithType: WebServiceDescriptor
  fullName: System.IdentityModel.Metadata.WebServiceDescriptor
- uid: System.IdentityModel.Metadata.ApplicationServiceDescriptor.#ctor
  parent: System.IdentityModel.Metadata.ApplicationServiceDescriptor
  isExternal: false
  name: ApplicationServiceDescriptor()
  nameWithType: ApplicationServiceDescriptor.ApplicationServiceDescriptor()
  fullName: System.IdentityModel.Metadata.ApplicationServiceDescriptor.ApplicationServiceDescriptor()
- uid: System.IdentityModel.Metadata.ApplicationServiceDescriptor.Endpoints
  parent: System.IdentityModel.Metadata.ApplicationServiceDescriptor
  isExternal: false
  name: Endpoints
  nameWithType: ApplicationServiceDescriptor.Endpoints
  fullName: System.IdentityModel.Metadata.ApplicationServiceDescriptor.Endpoints
- uid: System.Collections.Generic.ICollection`1
  name: ICollection<T>
  nameWithType: ICollection<T>
  fullName: System.Collections.Generic.ICollection<T>
- uid: System.IdentityModel.Protocols.WSTrust.EndpointReference
  name: EndpointReference
  nameWithType: EndpointReference
  fullName: System.IdentityModel.Protocols.WSTrust.EndpointReference
- uid: System.Collections.Generic.ICollection{System.IdentityModel.Protocols.WSTrust.EndpointReference}
  parent: System.Collections.Generic
  isExternal: false
  name: ICollection<EndpointReference>
  nameWithType: ICollection<EndpointReference>
  fullName: System.Collections.Generic.ICollection<System.IdentityModel.Protocols.WSTrust.EndpointReference>
  spec.csharp:
  - uid: System.Collections.Generic.ICollection`1
    name: ICollection
    nameWithType: ICollection
    fullName: System.Collections.Generic.ICollection
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.IdentityModel.Protocols.WSTrust.EndpointReference
    name: EndpointReference
    nameWithType: EndpointReference
    fullName: System.IdentityModel.Protocols.WSTrust.EndpointReference
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.IdentityModel.Metadata.ApplicationServiceDescriptor.PassiveRequestorEndpoints
  parent: System.IdentityModel.Metadata.ApplicationServiceDescriptor
  isExternal: false
  name: PassiveRequestorEndpoints
  nameWithType: ApplicationServiceDescriptor.PassiveRequestorEndpoints
  fullName: System.IdentityModel.Metadata.ApplicationServiceDescriptor.PassiveRequestorEndpoints
- uid: System.IdentityModel.Metadata.ApplicationServiceDescriptor.#ctor*
  parent: System.IdentityModel.Metadata.ApplicationServiceDescriptor
  isExternal: false
  name: ApplicationServiceDescriptor
  nameWithType: ApplicationServiceDescriptor.ApplicationServiceDescriptor
  fullName: System.IdentityModel.Metadata.ApplicationServiceDescriptor.ApplicationServiceDescriptor
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Metadata/ApplicationServiceDescriptor.xml
- uid: System.IdentityModel.Metadata.ApplicationServiceDescriptor.Endpoints*
  parent: System.IdentityModel.Metadata.ApplicationServiceDescriptor
  isExternal: false
  name: Endpoints
  nameWithType: ApplicationServiceDescriptor.Endpoints
  fullName: System.IdentityModel.Metadata.ApplicationServiceDescriptor.Endpoints
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Metadata/ApplicationServiceDescriptor.xml
- uid: System.IdentityModel.Metadata.ApplicationServiceDescriptor.PassiveRequestorEndpoints*
  parent: System.IdentityModel.Metadata.ApplicationServiceDescriptor
  isExternal: false
  name: PassiveRequestorEndpoints
  nameWithType: ApplicationServiceDescriptor.PassiveRequestorEndpoints
  fullName: System.IdentityModel.Metadata.ApplicationServiceDescriptor.PassiveRequestorEndpoints
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Metadata/ApplicationServiceDescriptor.xml
