### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IInternalConfigClientHost
  commentId: T:System.Configuration.Internal.IInternalConfigClientHost
  id: IInternalConfigClientHost
  children:
  - System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath
  - System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath
  - System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath
  - System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(System.String)
  - System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(System.String)
  - System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(System.String)
  langs:
  - csharp
  name: IInternalConfigClientHost
  nameWithType: IInternalConfigClientHost
  fullName: System.Configuration.Internal.IInternalConfigClientHost
  type: Interface
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: Defines interfaces that allow the internal .NET Framework infrastructure to customize configuration.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigClientHost
  implements: []
  attributes:
  - type: System.Runtime.InteropServices.ComVisibleAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IInternalConfigClientHost.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath
  commentId: M:System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath
  id: GetExeConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: GetExeConfigPath()
  nameWithType: IInternalConfigClientHost.GetExeConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: Returns the path to the application configuration file.
  syntax:
    content: public string GetExeConfigPath ();
    parameters: []
    return:
      type: System.String
      description: A string representing the path to the application configuration file.
  overload: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IInternalConfigClientHost.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath
  commentId: M:System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath
  id: GetLocalUserConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: GetLocalUserConfigPath()
  nameWithType: IInternalConfigClientHost.GetLocalUserConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: Returns a string representing the path to the known local user configuration file.
  syntax:
    content: public string GetLocalUserConfigPath ();
    parameters: []
    return:
      type: System.String
      description: A string representing the path to the known local user configuration file.
  overload: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IInternalConfigClientHost.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath
  commentId: M:System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath
  id: GetRoamingUserConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: GetRoamingUserConfigPath()
  nameWithType: IInternalConfigClientHost.GetRoamingUserConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: Returns a string representing the path to the known roaming user configuration file.
  syntax:
    content: public string GetRoamingUserConfigPath ();
    parameters: []
    return:
      type: System.String
      description: A string representing the path to the known roaming user configuration file.
  overload: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IInternalConfigClientHost.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(System.String)
  commentId: M:System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(System.String)
  id: IsExeConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: IsExeConfig(String)
  nameWithType: IInternalConfigClientHost.IsExeConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: Returns a value indicating whether a configuration file path is the same as a currently known application configuration file path.
  syntax:
    content: public bool IsExeConfig (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: A string representing the path to the application configuration file.
    return:
      type: System.Boolean
      description: '`true` if a string representing a configuration path is the same as a path to the application configuration file; `false` if a string representing a configuration path is not the same as a path to the application configuration file.'
  overload: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IInternalConfigClientHost.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(System.String)
  commentId: M:System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(System.String)
  id: IsLocalUserConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: IsLocalUserConfig(String)
  nameWithType: IInternalConfigClientHost.IsLocalUserConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: Returns a value indicating whether a configuration file path is the same as the configuration file path for the currently known local user.
  syntax:
    content: public bool IsLocalUserConfig (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: A string representing the path to the application configuration file.
    return:
      type: System.Boolean
      description: '`true` if a string representing a configuration path is the same as a path to a known local user configuration file; otherwise, `false`.'
  overload: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IInternalConfigClientHost.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(System.String)
  commentId: M:System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(System.String)
  id: IsRoamingUserConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  langs:
  - csharp
  name: IsRoamingUserConfig(String)
  nameWithType: IInternalConfigClientHost.IsRoamingUserConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: Returns a value indicating whether a configuration file path is the same as the configuration file path for the currently known roaming user.
  syntax:
    content: public bool IsRoamingUserConfig (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: A string representing the path to an application configuration file.
    return:
      type: System.Boolean
      description: '`true` if a string representing a configuration path is the same as a path to a known roaming user configuration file; otherwise, `false`.'
  overload: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IInternalConfigClientHost.xml
  ms.author: riande
  manager: wpickett
references:
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetExeConfigPath()
  nameWithType: IInternalConfigClientHost.GetExeConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath()
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetLocalUserConfigPath()
  nameWithType: IInternalConfigClientHost.GetLocalUserConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath()
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetRoamingUserConfigPath()
  nameWithType: IInternalConfigClientHost.GetRoamingUserConfigPath()
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath()
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsExeConfig(String)
  nameWithType: IInternalConfigClientHost.IsExeConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig(String)
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsLocalUserConfig(String)
  nameWithType: IInternalConfigClientHost.IsLocalUserConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig(String)
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsRoamingUserConfig(String)
  nameWithType: IInternalConfigClientHost.IsRoamingUserConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig(String)
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetExeConfigPath
  nameWithType: IInternalConfigClientHost.GetExeConfigPath
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetExeConfigPath
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IInternalConfigClientHost.xml
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetLocalUserConfigPath
  nameWithType: IInternalConfigClientHost.GetLocalUserConfigPath
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetLocalUserConfigPath
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IInternalConfigClientHost.xml
- uid: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: GetRoamingUserConfigPath
  nameWithType: IInternalConfigClientHost.GetRoamingUserConfigPath
  fullName: System.Configuration.Internal.IInternalConfigClientHost.GetRoamingUserConfigPath
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IInternalConfigClientHost.xml
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsExeConfig
  nameWithType: IInternalConfigClientHost.IsExeConfig
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsExeConfig
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IInternalConfigClientHost.xml
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsLocalUserConfig
  nameWithType: IInternalConfigClientHost.IsLocalUserConfig
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsLocalUserConfig
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IInternalConfigClientHost.xml
- uid: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig*
  parent: System.Configuration.Internal.IInternalConfigClientHost
  isExternal: false
  name: IsRoamingUserConfig
  nameWithType: IInternalConfigClientHost.IsRoamingUserConfig
  fullName: System.Configuration.Internal.IInternalConfigClientHost.IsRoamingUserConfig
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IInternalConfigClientHost.xml
