### YamlMime:ManagedReference
items:
- uid: System.Configuration.TypeNameConverter
  commentId: T:System.Configuration.TypeNameConverter
  id: TypeNameConverter
  children:
  - System.Configuration.TypeNameConverter.#ctor
  - System.Configuration.TypeNameConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.TypeNameConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: TypeNameConverter
  nameWithType: TypeNameConverter
  fullName: System.Configuration.TypeNameConverter
  type: Class
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Converts between type and string values. This class cannot be inherited.
  remarks: "This type, like all the other configuration converter types, converts strings found in the configuration file to and from the related strongly typed properties.  \n  \n In particular, the <xref:System.Configuration.TypeNameConverter> class converts a <xref:System.String> value, assigned to a configuration type, to a <xref:System.Type> value and vice versa. The type referred to is the class responsible for processing the configuration it is associated with."
  example:
  - "The following example shows how to obtain a type associated with a custom section. For the implementation of the custom section, refer to the code example in the <xref:System.Configuration.ConfigurationConverterBase> class reference.  \n  \n [!code-csharp[System.Configuration.TypeNameConverter#1](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Configuration.TypeNameConverter/CS/TypeNameConverter.cs#1)]\n [!code-vb[System.Configuration.TypeNameConverter#1](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Configuration.TypeNameConverter/VB/TypeNameConverter.vb#1)]  \n  \n The following example is a configuration excerpt used by the previous example.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n  \n  <configSections>  \n    <section name=\"CustomSection\"   \n      type=\"Samples.AspNet.CustomSection,   \n      ConfigurationConverters,   \n      Version=1.0.0.0, Culture=neutral,   \n      PublicKeyToken=null\"   \n      allowDefinition=\"Everywhere\"   \n      allowExeDefinition=\"MachineToApplication\"   \n      restartOnExternalChanges=\"true\" />  \n  </configSections>  \n  \n  <CustomSection fileName=\"default.txt\" maxIdleTime=\"90\"   \n    timeDelay=\"infinite\" cdStr=\"str0, str1\" permission=\"Read\"  \n    maxUsers=\"Infinite\"/>  \n  \n</configuration>  \n```"
  syntax:
    content: 'public sealed class TypeNameConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/TypeNameConverter.xml
- uid: System.Configuration.TypeNameConverter.#ctor
  commentId: M:System.Configuration.TypeNameConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.TypeNameConverter
  langs:
  - csharp
  name: TypeNameConverter()
  nameWithType: TypeNameConverter.TypeNameConverter()
  fullName: TypeNameConverter.TypeNameConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.TypeNameConverter"></xref> class.
  remarks: Normally, you use the converter types provided by the system. The only time you need to use the <xref:System.Configuration.TypeNameConverter.%23ctor%2A> constructor is when you create your own conversion type.
  syntax:
    content: public TypeNameConverter ();
    parameters: []
  overload: System.Configuration.TypeNameConverter.#ctor*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/TypeNameConverter.xml
- uid: System.Configuration.TypeNameConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  commentId: M:System.Configuration.TypeNameConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TypeNameConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
  nameWithType: TypeNameConverter.ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
  fullName: TypeNameConverter.ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
  type: Method
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Converts a <xref href="System.String"></xref> object to a <xref href="System.Type"></xref> object.
  remarks: The system uses the <xref:System.Configuration.TypeNameConverter.ConvertFrom%2A> method when reading from a configuration file to convert a <xref:System.String> value to a <xref:System.Type> value.
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: The <xref href="System.ComponentModel.ITypeDescriptorContext"></xref> object used for type conversions.
    - id: ci
      type: System.Globalization.CultureInfo
      description: The <xref href="System.Globalization.CultureInfo"></xref> object used during conversion.
    - id: data
      type: System.Object
      description: The <xref href="System.String"></xref> object to convert.
    return:
      type: System.Object
      description: The <xref href="System.Type"></xref> that represents the <code>data</code> parameter.
  overload: System.Configuration.TypeNameConverter.ConvertFrom*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: The <xref href="System.Type"></xref> value cannot be resolved.
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/TypeNameConverter.xml
- uid: System.Configuration.TypeNameConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  commentId: M:System.Configuration.TypeNameConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TypeNameConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
  nameWithType: TypeNameConverter.ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
  fullName: TypeNameConverter.ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
  type: Method
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Converts a <xref href="System.Type"></xref> object to a <xref href="System.String"></xref> object.
  remarks: The system uses the <xref:System.Configuration.TypeNameConverter.ConvertTo%2A> method when writing to a configuration file to convert a <xref:System.Type> value to a <xref:System.String> value.
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: The <xref href="System.ComponentModel.ITypeDescriptorContext"></xref> object used for type conversions.
    - id: ci
      type: System.Globalization.CultureInfo
      description: The <xref href="System.Globalization.CultureInfo"></xref> object used during conversion.
    - id: value
      type: System.Object
      description: The value to convert to.
    - id: type
      type: System.Type
      description: The type to convert to.
    return:
      type: System.Object
      description: The <xref href="System.String"></xref> that represents the <code>value</code> parameter.
  overload: System.Configuration.TypeNameConverter.ConvertTo*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/TypeNameConverter.xml
references:
- uid: System.Configuration.ConfigurationConverterBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationConverterBase
  nameWithType: ConfigurationConverterBase
  fullName: System.Configuration.ConfigurationConverterBase
- uid: System.ArgumentException
  parent: System
  isExternal: false
  name: ArgumentException
  nameWithType: ArgumentException
  fullName: System.ArgumentException
- uid: System.Configuration.TypeNameConverter.#ctor
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: TypeNameConverter()
  nameWithType: TypeNameConverter.TypeNameConverter()
  fullName: TypeNameConverter.TypeNameConverter()
- uid: System.Configuration.TypeNameConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
  nameWithType: TypeNameConverter.ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
  fullName: TypeNameConverter.ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: false
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.TypeNameConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
  nameWithType: TypeNameConverter.ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
  fullName: TypeNameConverter.ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.TypeNameConverter.#ctor*
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: TypeNameConverter
  nameWithType: TypeNameConverter.TypeNameConverter
  fullName: TypeNameConverter.TypeNameConverter
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/TypeNameConverter.xml
- uid: System.Configuration.TypeNameConverter.ConvertFrom*
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: TypeNameConverter.ConvertFrom
  fullName: TypeNameConverter.ConvertFrom
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/TypeNameConverter.xml
- uid: System.Configuration.TypeNameConverter.ConvertTo*
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: ConvertTo
  nameWithType: TypeNameConverter.ConvertTo
  fullName: TypeNameConverter.ConvertTo
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/TypeNameConverter.xml
