### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationAbortedEventArgs
  commentId: T:System.Activities.WorkflowApplicationAbortedEventArgs
  id: WorkflowApplicationAbortedEventArgs
  children:
  - System.Activities.WorkflowApplicationAbortedEventArgs.Reason
  langs:
  - csharp
  name: WorkflowApplicationAbortedEventArgs
  nameWithType: WorkflowApplicationAbortedEventArgs
  fullName: System.Activities.WorkflowApplicationAbortedEventArgs
  type: Class
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: Provides data about an aborted workflow instance.
  remarks: When a workflow hosted by a <xref:System.Activities.WorkflowApplication> is aborted, the <xref:System.Activities.WorkflowApplication.Aborted%2A> handler is invoked and the <xref:System.Activities.WorkflowApplication.Completed%2A> handler is not invoked.
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationAbortedEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Aborted%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about why workflow was aborted.  \n  \n [!code-csharp[CFX_WorkflowApplicationExample#5](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#5)]"
  syntax:
    content: 'public class WorkflowApplicationAbortedEventArgs : System.Activities.WorkflowApplicationEventArgs'
  inheritance:
  - System.Object
  - System.EventArgs
  - System.Activities.WorkflowApplicationEventArgs
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  - System.Activities.WorkflowApplicationEventArgs.InstanceId
  - System.EventArgs.Empty
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationAbortedEventArgs.xml
- uid: System.Activities.WorkflowApplicationAbortedEventArgs.Reason
  commentId: P:System.Activities.WorkflowApplicationAbortedEventArgs.Reason
  id: Reason
  parent: System.Activities.WorkflowApplicationAbortedEventArgs
  langs:
  - csharp
  name: Reason
  nameWithType: WorkflowApplicationAbortedEventArgs.Reason
  fullName: WorkflowApplicationAbortedEventArgs.Reason
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: Gets the exception that provides information about why the workflow instance was aborted
  remarks: When a workflow hosted by a <xref:System.Activities.WorkflowApplication> is aborted, the <xref:System.Activities.WorkflowApplication.Aborted%2A> handler is invoked and the <xref:System.Activities.WorkflowApplication.Completed%2A> handler is not invoked.
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationAbortedEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Aborted%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about why workflow was aborted.  \n  \n [!code-csharp[CFX_WorkflowApplicationExample#5](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#5)]"
  syntax:
    content: public Exception Reason { get; }
    return:
      type: System.Exception
      description: The exception that provides information about why the workflow instance was aborted.
  overload: System.Activities.WorkflowApplicationAbortedEventArgs.Reason*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationAbortedEventArgs.xml
references:
- uid: System.Activities.WorkflowApplicationEventArgs
  parent: System.Activities
  isExternal: false
  name: WorkflowApplicationEventArgs
  nameWithType: WorkflowApplicationEventArgs
  fullName: System.Activities.WorkflowApplicationEventArgs
- uid: System.Activities.WorkflowApplicationAbortedEventArgs.Reason
  parent: System.Activities.WorkflowApplicationAbortedEventArgs
  isExternal: false
  name: Reason
  nameWithType: WorkflowApplicationAbortedEventArgs.Reason
  fullName: WorkflowApplicationAbortedEventArgs.Reason
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Activities.WorkflowApplicationAbortedEventArgs.Reason*
  parent: System.Activities.WorkflowApplicationAbortedEventArgs
  isExternal: false
  name: Reason
  nameWithType: WorkflowApplicationAbortedEventArgs.Reason
  fullName: WorkflowApplicationAbortedEventArgs.Reason
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationAbortedEventArgs.xml
