### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement
  commentId: T:System.ServiceModel.Routing.Configuration.NamespaceElement
  id: NamespaceElement
  children:
  - System.ServiceModel.Routing.Configuration.NamespaceElement.#ctor
  - System.ServiceModel.Routing.Configuration.NamespaceElement.Namespace
  - System.ServiceModel.Routing.Configuration.NamespaceElement.Prefix
  langs:
  - csharp
  name: NamespaceElement
  nameWithType: NamespaceElement
  fullName: System.ServiceModel.Routing.Configuration.NamespaceElement
  type: Class
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: Represents a configuration element that defines the namespace element. This contains namespaces to namespace prefix mappings that can then be used in XPath filters.
  remarks: "The default namespaces and prefixes that are understood are shown in the following table.  \n  \n|Prefix|Namespace|  \n|-|-|  \n|s11|http://schemas.xmlsoap.org/soap/envelope|  \n|s12|http://www.w3.org/2003/05/soap-envelope|  \n|wsaAugust2004|http://schemas.xmlsoap.org/ws/2004/08/addressing|  \n|wsa10|http://www.w3.org/2005/08/addressing|  \n|sm|http://schemas.microsoft.com/serviceModel/2004/05/xpathfunctions|  \n|tempuri|http://tempuri.org|  \n|ser|http://schemas.microsoft.com/2003/10/Serialization|"
  syntax:
    content: 'public class NamespaceElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/NamespaceElement.xml
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.#ctor
  commentId: M:System.ServiceModel.Routing.Configuration.NamespaceElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  langs:
  - csharp
  name: NamespaceElement()
  nameWithType: NamespaceElement.NamespaceElement()
  fullName: NamespaceElement.NamespaceElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Routing.Configuration.NamespaceElement"></xref>.
  syntax:
    content: public NamespaceElement ();
    parameters: []
  overload: System.ServiceModel.Routing.Configuration.NamespaceElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/NamespaceElement.xml
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.Namespace
  commentId: P:System.ServiceModel.Routing.Configuration.NamespaceElement.Namespace
  id: Namespace
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  langs:
  - csharp
  name: Namespace
  nameWithType: NamespaceElement.Namespace
  fullName: NamespaceElement.Namespace
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: Gets or sets the namespace for this configuration element.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("namespace", DefaultValue=Mono.Cecil.CustomAttributeArgument, Options=System.Configuration.ConfigurationPropertyOptions.IsRequired)]

      public string Namespace { get; set; }
    return:
      type: System.String
      description: The namespace of this element.
  overload: System.ServiceModel.Routing.Configuration.NamespaceElement.Namespace*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/NamespaceElement.xml
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.Prefix
  commentId: P:System.ServiceModel.Routing.Configuration.NamespaceElement.Prefix
  id: Prefix
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  langs:
  - csharp
  name: Prefix
  nameWithType: NamespaceElement.Prefix
  fullName: NamespaceElement.Prefix
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: Gets or sets the namespace prefix for this configuration element.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("prefix", DefaultValue=Mono.Cecil.CustomAttributeArgument, Options=System.Configuration.ConfigurationPropertyOptions.IsRequired | System.Configuration.ConfigurationPropertyOptions.IsKey)]

      public string Prefix { get; set; }
    return:
      type: System.String
      description: The namespace prefix of this element.
  overload: System.ServiceModel.Routing.Configuration.NamespaceElement.Prefix*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/NamespaceElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.#ctor
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  isExternal: false
  name: NamespaceElement()
  nameWithType: NamespaceElement.NamespaceElement()
  fullName: NamespaceElement.NamespaceElement()
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.Namespace
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  isExternal: false
  name: Namespace
  nameWithType: NamespaceElement.Namespace
  fullName: NamespaceElement.Namespace
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.Prefix
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  isExternal: false
  name: Prefix
  nameWithType: NamespaceElement.Prefix
  fullName: NamespaceElement.Prefix
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.#ctor*
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  isExternal: false
  name: NamespaceElement
  nameWithType: NamespaceElement.NamespaceElement
  fullName: NamespaceElement.NamespaceElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/NamespaceElement.xml
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.Namespace*
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  isExternal: false
  name: Namespace
  nameWithType: NamespaceElement.Namespace
  fullName: NamespaceElement.Namespace
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/NamespaceElement.xml
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.Prefix*
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  isExternal: false
  name: Prefix
  nameWithType: NamespaceElement.Prefix
  fullName: NamespaceElement.Prefix
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Routing.Configuration/NamespaceElement.xml
