### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WebHttpBindingCollectionElement
  commentId: T:System.ServiceModel.Configuration.WebHttpBindingCollectionElement
  id: WebHttpBindingCollectionElement
  children:
  - System.ServiceModel.Configuration.WebHttpBindingCollectionElement.#ctor
  - System.ServiceModel.Configuration.WebHttpBindingCollectionElement.GetDefault
  langs:
  - csharp
  name: WebHttpBindingCollectionElement
  nameWithType: WebHttpBindingCollectionElement
  fullName: System.ServiceModel.Configuration.WebHttpBindingCollectionElement
  type: Class
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: Represents a configuration element that contains sub-elements that specify settings for using the <xref href="System.ServiceModel.WebHttpBinding"></xref> binding.
  remarks: Use this collection to manipulate configuration programmatically.
  syntax:
    content: 'public class WebHttpBindingCollectionElement : System.ServiceModel.Configuration.StandardBindingCollectionElement<System.ServiceModel.WebHttpBinding,System.ServiceModel.Configuration.WebHttpBindingElement>'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.BindingCollectionElement
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Bindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.BindingType
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ConfiguredBindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ContainsKey(System.String)
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Properties
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WebHttpBindingCollectionElement.xml
- uid: System.ServiceModel.Configuration.WebHttpBindingCollectionElement.#ctor
  commentId: M:System.ServiceModel.Configuration.WebHttpBindingCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WebHttpBindingCollectionElement
  langs:
  - csharp
  name: WebHttpBindingCollectionElement()
  nameWithType: WebHttpBindingCollectionElement.WebHttpBindingCollectionElement()
  fullName: WebHttpBindingCollectionElement.WebHttpBindingCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.WebHttpBindingCollectionElement"></xref> class.
  syntax:
    content: public WebHttpBindingCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WebHttpBindingCollectionElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WebHttpBindingCollectionElement.xml
- uid: System.ServiceModel.Configuration.WebHttpBindingCollectionElement.GetDefault
  commentId: M:System.ServiceModel.Configuration.WebHttpBindingCollectionElement.GetDefault
  id: GetDefault
  parent: System.ServiceModel.Configuration.WebHttpBindingCollectionElement
  langs:
  - csharp
  name: GetDefault()
  nameWithType: WebHttpBindingCollectionElement.GetDefault()
  fullName: WebHttpBindingCollectionElement.GetDefault()
  type: Method
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: Gets the default binding used.
  syntax:
    content: protected override System.ServiceModel.Channels.Binding GetDefault ();
    parameters: []
    return:
      type: System.ServiceModel.Channels.Binding
      description: A <xref href="System.ServiceModel.Channels.Binding"></xref> object that represents the default binding.
  overload: System.ServiceModel.Configuration.WebHttpBindingCollectionElement.GetDefault*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WebHttpBindingCollectionElement.xml
references:
- uid: System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  name: StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  nameWithType: StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
- uid: System.ServiceModel.WebHttpBinding
  name: WebHttpBinding
  nameWithType: WebHttpBinding
  fullName: System.ServiceModel.WebHttpBinding
- uid: System.ServiceModel.Configuration.WebHttpBindingElement
  name: WebHttpBindingElement
  nameWithType: WebHttpBindingElement
  fullName: System.ServiceModel.Configuration.WebHttpBindingElement
- uid: System.ServiceModel.Configuration.StandardBindingCollectionElement{System.ServiceModel.WebHttpBinding,System.ServiceModel.Configuration.WebHttpBindingElement}
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: StandardBindingCollectionElement<WebHttpBinding,WebHttpBindingElement>
  nameWithType: StandardBindingCollectionElement<WebHttpBinding,WebHttpBindingElement>
  fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement<System.ServiceModel.WebHttpBinding,System.ServiceModel.Configuration.WebHttpBindingElement>
  spec.csharp:
  - uid: System.ServiceModel.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.WebHttpBinding
    name: WebHttpBinding
    nameWithType: WebHttpBinding
    fullName: System.ServiceModel.WebHttpBinding
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.ServiceModel.Configuration.WebHttpBindingElement
    name: WebHttpBindingElement
    nameWithType: WebHttpBindingElement
    fullName: System.ServiceModel.Configuration.WebHttpBindingElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.WebHttpBindingCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.WebHttpBindingCollectionElement
  isExternal: false
  name: WebHttpBindingCollectionElement()
  nameWithType: WebHttpBindingCollectionElement.WebHttpBindingCollectionElement()
  fullName: WebHttpBindingCollectionElement.WebHttpBindingCollectionElement()
- uid: System.ServiceModel.Configuration.WebHttpBindingCollectionElement.GetDefault
  parent: System.ServiceModel.Configuration.WebHttpBindingCollectionElement
  isExternal: false
  name: GetDefault()
  nameWithType: WebHttpBindingCollectionElement.GetDefault()
  fullName: WebHttpBindingCollectionElement.GetDefault()
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: false
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.Configuration.WebHttpBindingCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.WebHttpBindingCollectionElement
  isExternal: false
  name: WebHttpBindingCollectionElement
  nameWithType: WebHttpBindingCollectionElement.WebHttpBindingCollectionElement
  fullName: WebHttpBindingCollectionElement.WebHttpBindingCollectionElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WebHttpBindingCollectionElement.xml
- uid: System.ServiceModel.Configuration.WebHttpBindingCollectionElement.GetDefault*
  parent: System.ServiceModel.Configuration.WebHttpBindingCollectionElement
  isExternal: false
  name: GetDefault
  nameWithType: WebHttpBindingCollectionElement.GetDefault
  fullName: WebHttpBindingCollectionElement.GetDefault
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WebHttpBindingCollectionElement.xml
