### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsDescriptionAttribute
  commentId: T:System.Configuration.SettingsDescriptionAttribute
  id: SettingsDescriptionAttribute
  children:
  - System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  - System.Configuration.SettingsDescriptionAttribute.Description
  langs:
  - csharp
  name: SettingsDescriptionAttribute
  nameWithType: SettingsDescriptionAttribute
  fullName: System.Configuration.SettingsDescriptionAttribute
  type: Class
  assemblies:
  - System
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Provides a string that describes an individual configuration property. This class cannot be inherited.
  remarks: "The <xref:System.Configuration.SettingsDescriptionAttribute> is intended to assist both design time tools and administrative run time tools in identifying and describing the associated configuration property.  \n  \n This attribute is optional and can only be applied at the individual configuration property level."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SettingsDescriptionAttribute : Attribute
  inheritance:
  - System.Object
  - System.Attribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.AttributeUsageAttribute
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsDescriptionAttribute.xml
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  commentId: M:System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsDescriptionAttribute
  langs:
  - csharp
  name: SettingsDescriptionAttribute(String)
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  fullName: SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  type: Constructor
  assemblies:
  - System
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Initializes an instance of the <xref href="System.Configuration.SettingsDescriptionAttribute"></xref> class.
  remarks: "Although the description has a theoretical maximum length of the <xref:System.String> class, whose length is represented by a <xref:System.Int32>, the following two practical considerations will limit the size of the `description` parameter:  \n  \n-   Large text descriptions are difficult to display in a user interface (UI) and difficult for the user to read.  \n  \n-   Settings providers may enforce overall usage quotas and are required to enforce user configuration quotas."
  syntax:
    content: public SettingsDescriptionAttribute (string description);
    parameters:
    - id: description
      type: System.String
      description: The <xref href="System.String"></xref> used as descriptive text.
  overload: System.Configuration.SettingsDescriptionAttribute.#ctor*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsDescriptionAttribute.xml
- uid: System.Configuration.SettingsDescriptionAttribute.Description
  commentId: P:System.Configuration.SettingsDescriptionAttribute.Description
  id: Description
  parent: System.Configuration.SettingsDescriptionAttribute
  langs:
  - csharp
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
  fullName: SettingsDescriptionAttribute.Description
  type: Property
  assemblies:
  - System
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Gets the descriptive text for the associated configuration property.
  remarks: The <xref:System.Configuration.SettingsDescriptionAttribute.Description%2A> property is set by the <xref:System.Configuration.SettingsDescriptionAttribute.%23ctor%2A> constructor.
  syntax:
    content: public string Description { get; }
    return:
      type: System.String
      description: A <xref href="System.String"></xref> containing the descriptive text for the associated configuration property.
  overload: System.Configuration.SettingsDescriptionAttribute.Description*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsDescriptionAttribute.xml
references:
- uid: System.Attribute
  parent: System
  isExternal: false
  name: Attribute
  nameWithType: Attribute
  fullName: System.Attribute
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: SettingsDescriptionAttribute(String)
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  fullName: SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsDescriptionAttribute.Description
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
  fullName: SettingsDescriptionAttribute.Description
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor*
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: SettingsDescriptionAttribute
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute
  fullName: SettingsDescriptionAttribute.SettingsDescriptionAttribute
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsDescriptionAttribute.xml
- uid: System.Configuration.SettingsDescriptionAttribute.Description*
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
  fullName: SettingsDescriptionAttribute.Description
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsDescriptionAttribute.xml
