### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.AdapterDictionary
  commentId: T:System.Web.Configuration.AdapterDictionary
  id: AdapterDictionary
  children:
  - System.Web.Configuration.AdapterDictionary.#ctor
  - System.Web.Configuration.AdapterDictionary.Item(System.String)
  langs:
  - csharp
  name: AdapterDictionary
  nameWithType: AdapterDictionary
  fullName: System.Web.Configuration.AdapterDictionary
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Used internally at run time by the configuration system to contain the names of the available adapters used to render server controls on different browsers.
  syntax:
    content: 'public class AdapterDictionary : System.Collections.Specialized.OrderedDictionary'
  inheritance:
  - System.Object
  - System.Collections.Specialized.OrderedDictionary
  implements: []
  inheritedMembers:
  - System.Collections.Specialized.OrderedDictionary.Add(System.Object,System.Object)
  - System.Collections.Specialized.OrderedDictionary.AsReadOnly
  - System.Collections.Specialized.OrderedDictionary.Clear
  - System.Collections.Specialized.OrderedDictionary.Contains(System.Object)
  - System.Collections.Specialized.OrderedDictionary.CopyTo(System.Array,System.Int32)
  - System.Collections.Specialized.OrderedDictionary.Count
  - System.Collections.Specialized.OrderedDictionary.GetEnumerator
  - System.Collections.Specialized.OrderedDictionary.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Collections.Specialized.OrderedDictionary.Insert(System.Int32,System.Object,System.Object)
  - System.Collections.Specialized.OrderedDictionary.IsReadOnly
  - System.Collections.Specialized.OrderedDictionary.Item(System.Int32)
  - System.Collections.Specialized.OrderedDictionary.Item(System.Object)
  - System.Collections.Specialized.OrderedDictionary.Keys
  - System.Collections.Specialized.OrderedDictionary.OnDeserialization(System.Object)
  - System.Collections.Specialized.OrderedDictionary.Remove(System.Object)
  - System.Collections.Specialized.OrderedDictionary.RemoveAt(System.Int32)
  - System.Collections.Specialized.OrderedDictionary.System#Collections#ICollection#IsSynchronized
  - System.Collections.Specialized.OrderedDictionary.System#Collections#ICollection#SyncRoot
  - System.Collections.Specialized.OrderedDictionary.System#Collections#IDictionary#IsFixedSize
  - System.Collections.Specialized.OrderedDictionary.System#Collections#IEnumerable#GetEnumerator
  - System.Collections.Specialized.OrderedDictionary.System#Runtime#Serialization#IDeserializationCallback#OnDeserialization(System.Object)
  - System.Collections.Specialized.OrderedDictionary.Values
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  extensionMethods:
  - System.Linq.Enumerable.Cast``1(System.Collections.IEnumerable)
  - System.Linq.Enumerable.OfType``1(System.Collections.IEnumerable)
  - System.Linq.ParallelEnumerable.AsParallel(System.Collections.IEnumerable)
  - System.Linq.Queryable.AsQueryable(System.Collections.IEnumerable)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  internal_use_only: true
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AdapterDictionary.xml
- uid: System.Web.Configuration.AdapterDictionary.#ctor
  commentId: M:System.Web.Configuration.AdapterDictionary.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.AdapterDictionary
  langs:
  - csharp
  name: AdapterDictionary()
  nameWithType: AdapterDictionary.AdapterDictionary()
  fullName: AdapterDictionary.AdapterDictionary()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Used internally at run time by the configuration system to create a new instance of this class.
  syntax:
    content: public AdapterDictionary ();
    parameters: []
  overload: System.Web.Configuration.AdapterDictionary.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  internal_use_only: true
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AdapterDictionary.xml
- uid: System.Web.Configuration.AdapterDictionary.Item(System.String)
  commentId: P:System.Web.Configuration.AdapterDictionary.Item(System.String)
  id: Item(System.String)
  parent: System.Web.Configuration.AdapterDictionary
  langs:
  - csharp
  name: Item(String)
  nameWithType: AdapterDictionary.Item(String)
  fullName: AdapterDictionary.Item(String)
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Used internally at run time by the configuration system to get or set a specified adapter name.
  syntax:
    content: public string this[string key] { get; set; }
    parameters:
    - id: key
      type: System.String
      description: Key of the specified adapter.
    return:
      type: System.String
      description: The name of the specified adapter.
  overload: System.Web.Configuration.AdapterDictionary.Item*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  internal_use_only: true
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AdapterDictionary.xml
references:
- uid: System.Collections.Specialized.OrderedDictionary
  parent: System.Collections.Specialized
  isExternal: false
  name: OrderedDictionary
  nameWithType: OrderedDictionary
  fullName: System.Collections.Specialized.OrderedDictionary
- uid: System.Web.Configuration.AdapterDictionary.#ctor
  parent: System.Web.Configuration.AdapterDictionary
  isExternal: false
  name: AdapterDictionary()
  nameWithType: AdapterDictionary.AdapterDictionary()
  fullName: AdapterDictionary.AdapterDictionary()
- uid: System.Web.Configuration.AdapterDictionary.Item(System.String)
  parent: System.Web.Configuration.AdapterDictionary
  isExternal: false
  name: Item(String)
  nameWithType: AdapterDictionary.Item(String)
  fullName: AdapterDictionary.Item(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.AdapterDictionary.#ctor*
  parent: System.Web.Configuration.AdapterDictionary
  isExternal: false
  name: AdapterDictionary
  nameWithType: AdapterDictionary.AdapterDictionary
  fullName: AdapterDictionary.AdapterDictionary
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AdapterDictionary.xml
- uid: System.Web.Configuration.AdapterDictionary.Item*
  parent: System.Web.Configuration.AdapterDictionary
  isExternal: false
  name: Item
  nameWithType: AdapterDictionary.Item
  fullName: AdapterDictionary.Item
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AdapterDictionary.xml
- uid: System.Linq.Enumerable.Cast``1(System.Collections.IEnumerable)
  parent: System.Linq.Enumerable
  isExternal: false
  name: Cast<TResult>(IEnumerable)
  nameWithType: Enumerable.Cast<TResult>(IEnumerable)
  fullName: Enumerable.Cast<TResult>(IEnumerable)
- uid: System.Linq.Enumerable.OfType``1(System.Collections.IEnumerable)
  parent: System.Linq.Enumerable
  isExternal: false
  name: OfType<TResult>(IEnumerable)
  nameWithType: Enumerable.OfType<TResult>(IEnumerable)
  fullName: Enumerable.OfType<TResult>(IEnumerable)
- uid: System.Linq.ParallelEnumerable.AsParallel(System.Collections.IEnumerable)
  parent: System.Linq.ParallelEnumerable
  isExternal: false
  name: AsParallel(IEnumerable)
  nameWithType: ParallelEnumerable.AsParallel(IEnumerable)
  fullName: ParallelEnumerable.AsParallel(IEnumerable)
- uid: System.Linq.Queryable.AsQueryable(System.Collections.IEnumerable)
  parent: System.Linq.Queryable
  isExternal: false
  name: AsQueryable(IEnumerable)
  nameWithType: Queryable.AsQueryable(IEnumerable)
  fullName: Queryable.AsQueryable(IEnumerable)
