### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.WsiProfilesElement
  commentId: T:System.Web.Services.Configuration.WsiProfilesElement
  id: WsiProfilesElement
  children:
  - System.Web.Services.Configuration.WsiProfilesElement.#ctor
  - System.Web.Services.Configuration.WsiProfilesElement.#ctor(System.Web.Services.WsiProfiles)
  - System.Web.Services.Configuration.WsiProfilesElement.Name
  - System.Web.Services.Configuration.WsiProfilesElement.Properties
  langs:
  - csharp
  name: WsiProfilesElement
  nameWithType: WsiProfilesElement
  fullName: System.Web.Services.Configuration.WsiProfilesElement
  type: Class
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Represents the `WsiProfiles` element in the configuration file.
  remarks: The WsiProfiles element describes the Web Services Interoperability (WSI) specification to which a Web service declares that it conforms.
  syntax:
    content: 'public sealed class WsiProfilesElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsiProfilesElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.Web.Services.Configuration.WsiProfilesElement.#ctor
  commentId: M:System.Web.Services.Configuration.WsiProfilesElement.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.WsiProfilesElement
  langs:
  - csharp
  name: WsiProfilesElement()
  nameWithType: WsiProfilesElement.WsiProfilesElement()
  fullName: System.Web.Services.Configuration.WsiProfilesElement.WsiProfilesElement()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Initializes and instance of the <xref href="System.Web.Services.Configuration.WsiProfilesElement"></xref> class.
  syntax:
    content: public WsiProfilesElement ();
    parameters: []
  overload: System.Web.Services.Configuration.WsiProfilesElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsiProfilesElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.Web.Services.Configuration.WsiProfilesElement.#ctor(System.Web.Services.WsiProfiles)
  commentId: M:System.Web.Services.Configuration.WsiProfilesElement.#ctor(System.Web.Services.WsiProfiles)
  id: '#ctor(System.Web.Services.WsiProfiles)'
  parent: System.Web.Services.Configuration.WsiProfilesElement
  langs:
  - csharp
  name: WsiProfilesElement(WsiProfiles)
  nameWithType: WsiProfilesElement.WsiProfilesElement(WsiProfiles)
  fullName: System.Web.Services.Configuration.WsiProfilesElement.WsiProfilesElement(WsiProfiles)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Initializes and instance of the <xref href="System.Web.Services.Configuration.WsiProfilesElement"></xref> class, using the specified <xref href="System.Web.Services.WsiProfiles"></xref> enumeration value.
  syntax:
    content: public WsiProfilesElement (System.Web.Services.WsiProfiles name);
    parameters:
    - id: name
      type: System.Web.Services.WsiProfiles
      description: A <xref href="System.Web.Services.WsiProfiles"></xref> object that specifies whether the Web service conforms to the WSI Basic Profile version 1.1.
  overload: System.Web.Services.Configuration.WsiProfilesElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsiProfilesElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.Web.Services.Configuration.WsiProfilesElement.Name
  commentId: P:System.Web.Services.Configuration.WsiProfilesElement.Name
  id: Name
  parent: System.Web.Services.Configuration.WsiProfilesElement
  langs:
  - csharp
  name: Name
  nameWithType: WsiProfilesElement.Name
  fullName: System.Web.Services.Configuration.WsiProfilesElement.Name
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Gets or sets whether the Web service conforms to the WSI Basic Profile version 1.1.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("name", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsKey=true)]

      public System.Web.Services.WsiProfiles Name { get; set; }
    return:
      type: System.Web.Services.WsiProfiles
      description: A <xref href="System.Web.Services.WsiProfiles"></xref> object that specifies whether the Web service conforms to the WSI Basic Profile version 1.1.
  overload: System.Web.Services.Configuration.WsiProfilesElement.Name*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsiProfilesElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.Web.Services.Configuration.WsiProfilesElement.Properties
  commentId: P:System.Web.Services.Configuration.WsiProfilesElement.Properties
  id: Properties
  parent: System.Web.Services.Configuration.WsiProfilesElement
  langs:
  - csharp
  name: Properties
  nameWithType: WsiProfilesElement.Properties
  fullName: System.Web.Services.Configuration.WsiProfilesElement.Properties
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Services.Configuration.WsiProfilesElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsiProfilesElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Services.Configuration.WsiProfilesElement.#ctor
  parent: System.Web.Services.Configuration.WsiProfilesElement
  isExternal: false
  name: WsiProfilesElement()
  nameWithType: WsiProfilesElement.WsiProfilesElement()
  fullName: System.Web.Services.Configuration.WsiProfilesElement.WsiProfilesElement()
- uid: System.Web.Services.Configuration.WsiProfilesElement.#ctor(System.Web.Services.WsiProfiles)
  parent: System.Web.Services.Configuration.WsiProfilesElement
  isExternal: false
  name: WsiProfilesElement(WsiProfiles)
  nameWithType: WsiProfilesElement.WsiProfilesElement(WsiProfiles)
  fullName: System.Web.Services.Configuration.WsiProfilesElement.WsiProfilesElement(WsiProfiles)
- uid: System.Web.Services.WsiProfiles
  parent: System.Web.Services
  isExternal: false
  name: WsiProfiles
  nameWithType: WsiProfiles
  fullName: System.Web.Services.WsiProfiles
- uid: System.Web.Services.Configuration.WsiProfilesElement.Name
  parent: System.Web.Services.Configuration.WsiProfilesElement
  isExternal: false
  name: Name
  nameWithType: WsiProfilesElement.Name
  fullName: System.Web.Services.Configuration.WsiProfilesElement.Name
- uid: System.Web.Services.Configuration.WsiProfilesElement.Properties
  parent: System.Web.Services.Configuration.WsiProfilesElement
  isExternal: false
  name: Properties
  nameWithType: WsiProfilesElement.Properties
  fullName: System.Web.Services.Configuration.WsiProfilesElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Services.Configuration.WsiProfilesElement.#ctor*
  parent: System.Web.Services.Configuration.WsiProfilesElement
  isExternal: false
  name: WsiProfilesElement
  nameWithType: WsiProfilesElement.WsiProfilesElement
  fullName: System.Web.Services.Configuration.WsiProfilesElement.WsiProfilesElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsiProfilesElement.xml
- uid: System.Web.Services.Configuration.WsiProfilesElement.Name*
  parent: System.Web.Services.Configuration.WsiProfilesElement
  isExternal: false
  name: Name
  nameWithType: WsiProfilesElement.Name
  fullName: System.Web.Services.Configuration.WsiProfilesElement.Name
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsiProfilesElement.xml
- uid: System.Web.Services.Configuration.WsiProfilesElement.Properties*
  parent: System.Web.Services.Configuration.WsiProfilesElement
  isExternal: false
  name: Properties
  nameWithType: WsiProfilesElement.Properties
  fullName: System.Web.Services.Configuration.WsiProfilesElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsiProfilesElement.xml
