### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Discovery.Configuration.ScopeElement
  commentId: T:System.ServiceModel.Discovery.Configuration.ScopeElement
  id: ScopeElement
  children:
  - System.ServiceModel.Discovery.Configuration.ScopeElement.#ctor
  - System.ServiceModel.Discovery.Configuration.ScopeElement.Properties
  - System.ServiceModel.Discovery.Configuration.ScopeElement.Scope
  langs:
  - csharp
  name: ScopeElement
  nameWithType: ScopeElement
  fullName: System.ServiceModel.Discovery.Configuration.ScopeElement
  type: Class
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: Represents a scope URI for an endpoint.
  remarks: "This class is used to represent a scope URI in configuration files. The following example shows how it is used in a configuration file.  \n  \n```  \n<endpointBehaviors>  \n    <behavior name=\"ep1Behavior\">  \n        <endpointDiscovery>  \n            <scopes>  \n                <add scope=\"http://www.microsoft.com/building42/floor1\"/>  \n                <add scope=\"ldap:///ou=engineeringo=examplecomc=us\"/>  \n                <add scope=\"mailto:vipulm@microsoft.com\"/>  \n             </scopes>  \n        </endpointDiscovery>  \n    </behavior>  \n</endpointBehaviors>  \n```  \n  \n Each of the items under the \\<scopes> element correspond to a <xref:System.ServiceModel.Discovery.Configuration.ScopeElement>."
  syntax:
    content: 'public sealed class ScopeElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/ScopeElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Discovery.Configuration.ScopeElement.#ctor
  commentId: M:System.ServiceModel.Discovery.Configuration.ScopeElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Discovery.Configuration.ScopeElement
  langs:
  - csharp
  name: ScopeElement()
  nameWithType: ScopeElement.ScopeElement()
  fullName: System.ServiceModel.Discovery.Configuration.ScopeElement.ScopeElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: Creates a new instance of the <xref href="System.ServiceModel.Discovery.Configuration.ScopeElement"></xref> class.
  syntax:
    content: public ScopeElement ();
    parameters: []
  overload: System.ServiceModel.Discovery.Configuration.ScopeElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/ScopeElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Discovery.Configuration.ScopeElement.Properties
  commentId: P:System.ServiceModel.Discovery.Configuration.ScopeElement.Properties
  id: Properties
  parent: System.ServiceModel.Discovery.Configuration.ScopeElement
  langs:
  - csharp
  name: Properties
  nameWithType: ScopeElement.Properties
  fullName: System.ServiceModel.Discovery.Configuration.ScopeElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Discovery.Configuration.ScopeElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/ScopeElement.xml
- uid: System.ServiceModel.Discovery.Configuration.ScopeElement.Scope
  commentId: P:System.ServiceModel.Discovery.Configuration.ScopeElement.Scope
  id: Scope
  parent: System.ServiceModel.Discovery.Configuration.ScopeElement
  langs:
  - csharp
  name: Scope
  nameWithType: ScopeElement.Scope
  fullName: System.ServiceModel.Discovery.Configuration.ScopeElement.Scope
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: Gets or sets the scope URI.
  syntax:
    content: >-
      [System.Configuration.CallbackValidator(CallbackMethodName="ScopeValidatorCallback", Type=typeof(System.ServiceModel.Discovery.Configuration.ScopeElement))]

      [System.Configuration.ConfigurationProperty("scope", Options=System.Configuration.ConfigurationPropertyOptions.IsRequired | System.Configuration.ConfigurationPropertyOptions.IsKey)]

      public Uri Scope { get; set; }
    return:
      type: System.Uri
      description: The scope URI.
  overload: System.ServiceModel.Discovery.Configuration.ScopeElement.Scope*
  exceptions: []
  attributes:
  - type: System.Configuration.CallbackValidatorAttribute
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/ScopeElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Discovery.Configuration.ScopeElement.#ctor
  parent: System.ServiceModel.Discovery.Configuration.ScopeElement
  isExternal: false
  name: ScopeElement()
  nameWithType: ScopeElement.ScopeElement()
  fullName: System.ServiceModel.Discovery.Configuration.ScopeElement.ScopeElement()
- uid: System.ServiceModel.Discovery.Configuration.ScopeElement.Properties
  parent: System.ServiceModel.Discovery.Configuration.ScopeElement
  isExternal: false
  name: Properties
  nameWithType: ScopeElement.Properties
  fullName: System.ServiceModel.Discovery.Configuration.ScopeElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Discovery.Configuration.ScopeElement.Scope
  parent: System.ServiceModel.Discovery.Configuration.ScopeElement
  isExternal: false
  name: Scope
  nameWithType: ScopeElement.Scope
  fullName: System.ServiceModel.Discovery.Configuration.ScopeElement.Scope
- uid: System.Uri
  parent: System
  isExternal: false
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.ServiceModel.Discovery.Configuration.ScopeElement.#ctor*
  parent: System.ServiceModel.Discovery.Configuration.ScopeElement
  isExternal: false
  name: ScopeElement
  nameWithType: ScopeElement.ScopeElement
  fullName: System.ServiceModel.Discovery.Configuration.ScopeElement.ScopeElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/ScopeElement.xml
- uid: System.ServiceModel.Discovery.Configuration.ScopeElement.Properties*
  parent: System.ServiceModel.Discovery.Configuration.ScopeElement
  isExternal: false
  name: Properties
  nameWithType: ScopeElement.Properties
  fullName: System.ServiceModel.Discovery.Configuration.ScopeElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/ScopeElement.xml
- uid: System.ServiceModel.Discovery.Configuration.ScopeElement.Scope*
  parent: System.ServiceModel.Discovery.Configuration.ScopeElement
  isExternal: false
  name: Scope
  nameWithType: ScopeElement.Scope
  fullName: System.ServiceModel.Discovery.Configuration.ScopeElement.Scope
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/ScopeElement.xml
