### YamlMime:ManagedReference
items:
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup
  commentId: T:System.Runtime.Caching.Configuration.CachingSectionGroup
  id: CachingSectionGroup
  children:
  - System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor
  - System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  langs:
  - csharp
  name: CachingSectionGroup
  nameWithType: CachingSectionGroup
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup
  type: Class
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  summary: Defines a configuration section for.NET Framework caching. This class cannot be inherited.
  remarks: The <xref:System.Runtime.Caching.Configuration.CachingSectionGroup> class defines a caching section (`system.runtime.caching`) for configuration files. This section contains elements that are used to configure various types of caches. In ASP.NET, the only element that is available in the caching section is the  element. This element configures caches that are based on the <xref:System.Runtime.Caching.MemoryCache> class.
  syntax:
    content: 'public sealed class CachingSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Caching.Configuration/CachingSectionGroup.xml
  author: Erikre
  ms.author: erikre
  manager: ghogen
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor
  commentId: M:System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor
  id: '#ctor'
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  langs:
  - csharp
  name: CachingSectionGroup()
  nameWithType: CachingSectionGroup.CachingSectionGroup()
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.CachingSectionGroup()
  type: Constructor
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  summary: Initializes a new instance of the <xref href="System.Runtime.Caching.Configuration.CachingSectionGroup"></xref> class.
  syntax:
    content: public CachingSectionGroup ();
    parameters: []
  overload: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Caching.Configuration/CachingSectionGroup.xml
  author: Erikre
  ms.author: erikre
  manager: ghogen
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  commentId: P:System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  id: MemoryCaches
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  langs:
  - csharp
  name: MemoryCaches
  nameWithType: CachingSectionGroup.MemoryCaches
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  type: Property
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  summary: Gets the collection of <xref href="System.Runtime.Caching.Configuration.MemoryCacheElement"></xref> objects.
  remarks: The <xref:System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches%2A> property returns the collection of <xref:System.Runtime.Caching.Configuration.MemoryCacheSection> objects from the parent caching section.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("memoryCache")]

      public System.Runtime.Caching.Configuration.MemoryCacheSection MemoryCaches { get; }
    return:
      type: System.Runtime.Caching.Configuration.MemoryCacheSection
      description: The collection of cache-section objects.
  overload: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Caching.Configuration/CachingSectionGroup.xml
  author: Erikre
  ms.author: erikre
  manager: ghogen
references:
- uid: System.Configuration.ConfigurationSectionGroup
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSectionGroup
  nameWithType: ConfigurationSectionGroup
  fullName: System.Configuration.ConfigurationSectionGroup
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: CachingSectionGroup()
  nameWithType: CachingSectionGroup.CachingSectionGroup()
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.CachingSectionGroup()
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: MemoryCaches
  nameWithType: CachingSectionGroup.MemoryCaches
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection
  parent: System.Runtime.Caching.Configuration
  isExternal: false
  name: MemoryCacheSection
  nameWithType: MemoryCacheSection
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor*
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: CachingSectionGroup
  nameWithType: CachingSectionGroup.CachingSectionGroup
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.CachingSectionGroup
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Caching.Configuration/CachingSectionGroup.xml
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches*
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: MemoryCaches
  nameWithType: CachingSectionGroup.MemoryCaches
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Caching.Configuration/CachingSectionGroup.xml
