### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  commentId: T:System.Configuration.TimeSpanMinutesOrInfiniteConverter
  id: TimeSpanMinutesOrInfiniteConverter
  children:
  - System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor
  - System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: TimeSpanMinutesOrInfiniteConverter
  nameWithType: TimeSpanMinutesOrInfiniteConverter
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  type: Class
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Converts a <xref href="System.TimeSpan"></xref> expressed in minutes or as a standard infinite time span.
  remarks: "This type, like all the other configuration converter types, converts strings found in the configuration file to and from the related strongly typed properties.  \n  \n In particular, the <xref:System.Configuration.TimeSpanMinutesOrInfiniteConverter> class converts <xref:System.String> minutes, assigned to a configuration property, to <xref:System.TimeSpan> minutes and vice versa. If the configuration property has a <xref:System.String> value of \"infinite\", it converts this value to <xref:System.TimeSpan> and vice versa.  \n  \n The infinite <xref:System.TimeSpan> value is represented by the <xref:System.TimeSpan.MaxValue> enumeration value."
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: 'public sealed class TimeSpanMinutesOrInfiniteConverter : System.Configuration.TimeSpanMinutesConverter'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  - System.Configuration.TimeSpanMinutesConverter
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/TimeSpanMinutesOrInfiniteConverter.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor
  commentId: M:System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  langs:
  - csharp
  name: TimeSpanMinutesOrInfiniteConverter()
  nameWithType: TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter()
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.TimeSpanMinutesOrInfiniteConverter"></xref> class.
  remarks: Normally, you use the converter types provided by the system. The only time you need to use the <xref:System.Configuration.TimeSpanMinutesOrInfiniteConverter.%23ctor%2A> constructor is when you create your own conversion type.
  syntax:
    content: public TimeSpanMinutesOrInfiniteConverter ();
    parameters: []
  overload: System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/TimeSpanMinutesOrInfiniteConverter.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  commentId: M:System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Converts a <xref href="System.String"></xref> to a <xref href="System.TimeSpan"></xref>.
  remarks: The system uses the <xref:System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom%2A> method when reading from a configuration file to convert a <xref:System.String> value to <xref:System.TimeSpan>, or the <xref:System.String> "infinite" to <xref:System.TimeSpan.MaxValue>.
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: The <xref href="System.ComponentModel.ITypeDescriptorContext"></xref> object used for type conversions.
    - id: ci
      type: System.Globalization.CultureInfo
      description: The <xref href="System.Globalization.CultureInfo"></xref> object used during conversion.
    - id: data
      type: System.Object
      description: The <xref href="System.String"></xref> object to convert.
    return:
      type: System.Object
      description: The <xref href="System.TimeSpan.MaxValue"></xref>, if the <code>data</code> parameter is the <xref href="System.String"></xref> "infinite"; otherwise, the <xref href="System.TimeSpan"></xref> representing the <code>data</code> parameter in minutes.
  overload: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/TimeSpanMinutesOrInfiniteConverter.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  commentId: M:System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Converts a <xref href="System.TimeSpan"></xref> to a <xref href="System.String"></xref>.
  remarks: The system uses the <xref:System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo%2A> method when writing to a configuration file to convert a <xref:System.TimeSpan> value or <xref:System.TimeSpan.MaxValue> to a <xref:System.String>.
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: The <xref href="System.ComponentModel.ITypeDescriptorContext"></xref> object used for type conversions.
    - id: ci
      type: System.Globalization.CultureInfo
      description: The <xref href="System.Globalization.CultureInfo"></xref> object used during conversion.
    - id: value
      type: System.Object
      description: The value to convert.
    - id: type
      type: System.Type
      description: The conversion type.
    return:
      type: System.Object
      description: The <xref href="System.String"></xref> "infinite", if the <code>value</code> parameter is <xref href="System.TimeSpan.MaxValue"></xref>; otherwise, the <xref href="System.String"></xref> representing the <code>value</code> parameter in minutes.
  overload: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/TimeSpanMinutesOrInfiniteConverter.xml
  ms.author: riande
  manager: wpickett
references:
- uid: System.Configuration.TimeSpanMinutesConverter
  parent: System.Configuration
  isExternal: false
  name: TimeSpanMinutesConverter
  nameWithType: TimeSpanMinutesConverter
  fullName: System.Configuration.TimeSpanMinutesConverter
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: TimeSpanMinutesOrInfiniteConverter()
  nameWithType: TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter()
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter()
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: false
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor*
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: TimeSpanMinutesOrInfiniteConverter
  nameWithType: TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/TimeSpanMinutesOrInfiniteConverter.xml
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom*
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertFrom
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/TimeSpanMinutesOrInfiniteConverter.xml
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo*
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: ConvertTo
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertTo
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/TimeSpanMinutesOrInfiniteConverter.xml
