### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement
  commentId: T:System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement
  id: NetHttpWebSocketTransportSettingsElement
  children:
  - System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.#ctor
  - System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.Properties
  - System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.SubProtocol
  - System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.TransportUsage
  langs:
  - csharp
  name: NetHttpWebSocketTransportSettingsElement
  nameWithType: NetHttpWebSocketTransportSettingsElement
  fullName: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents NetHttpWebSocketTransportSettingsElement for WebSocketTransportSettings.
  syntax:
    content: 'public sealed class NetHttpWebSocketTransportSettingsElement : System.ServiceModel.Configuration.WebSocketTransportSettingsElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.WebSocketTransportSettingsElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.WebSocketTransportSettingsElement.ApplyConfiguration(System.ServiceModel.Channels.WebSocketTransportSettings)
  - System.ServiceModel.Configuration.WebSocketTransportSettingsElement.CreateNotificationOnConnection
  - System.ServiceModel.Configuration.WebSocketTransportSettingsElement.DisablePayloadMasking
  - System.ServiceModel.Configuration.WebSocketTransportSettingsElement.InitializeFrom(System.ServiceModel.Channels.WebSocketTransportSettings)
  - System.ServiceModel.Configuration.WebSocketTransportSettingsElement.KeepAliveInterval
  - System.ServiceModel.Configuration.WebSocketTransportSettingsElement.MaxPendingConnections
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetHttpWebSocketTransportSettingsElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.#ctor
  commentId: M:System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement
  langs:
  - csharp
  name: NetHttpWebSocketTransportSettingsElement()
  nameWithType: NetHttpWebSocketTransportSettingsElement.NetHttpWebSocketTransportSettingsElement()
  fullName: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.NetHttpWebSocketTransportSettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement"></xref> class.
  syntax:
    content: public NetHttpWebSocketTransportSettingsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetHttpWebSocketTransportSettingsElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.Properties
  commentId: P:System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: NetHttpWebSocketTransportSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetHttpWebSocketTransportSettingsElement.xml
- uid: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.SubProtocol
  commentId: P:System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.SubProtocol
  id: SubProtocol
  parent: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement
  langs:
  - csharp
  name: SubProtocol
  nameWithType: NetHttpWebSocketTransportSettingsElement.SubProtocol
  fullName: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.SubProtocol
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the web socket sub protocol.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("subProtocol", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      [System.Configuration.StringValidator(MinLength=0)]

      public override string SubProtocol { get; set; }
    return:
      type: System.String
      description: The web socket sub protocol.
  overload: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.SubProtocol*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetHttpWebSocketTransportSettingsElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.TransportUsage
  commentId: P:System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.TransportUsage
  id: TransportUsage
  parent: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement
  langs:
  - csharp
  name: TransportUsage
  nameWithType: NetHttpWebSocketTransportSettingsElement.TransportUsage
  fullName: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.TransportUsage
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the transport usage.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("transportUsage", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public override System.ServiceModel.Channels.WebSocketTransportUsage TransportUsage { get; set; }
    return:
      type: System.ServiceModel.Channels.WebSocketTransportUsage
      description: The transport usage.
  overload: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.TransportUsage*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetHttpWebSocketTransportSettingsElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.ServiceModel.Configuration.WebSocketTransportSettingsElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: WebSocketTransportSettingsElement
  nameWithType: WebSocketTransportSettingsElement
  fullName: System.ServiceModel.Configuration.WebSocketTransportSettingsElement
- uid: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.#ctor
  parent: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement
  isExternal: false
  name: NetHttpWebSocketTransportSettingsElement()
  nameWithType: NetHttpWebSocketTransportSettingsElement.NetHttpWebSocketTransportSettingsElement()
  fullName: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.NetHttpWebSocketTransportSettingsElement()
- uid: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.Properties
  parent: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement
  isExternal: false
  name: Properties
  nameWithType: NetHttpWebSocketTransportSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.SubProtocol
  parent: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement
  isExternal: false
  name: SubProtocol
  nameWithType: NetHttpWebSocketTransportSettingsElement.SubProtocol
  fullName: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.SubProtocol
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.TransportUsage
  parent: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement
  isExternal: false
  name: TransportUsage
  nameWithType: NetHttpWebSocketTransportSettingsElement.TransportUsage
  fullName: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.TransportUsage
- uid: System.ServiceModel.Channels.WebSocketTransportUsage
  parent: System.ServiceModel.Channels
  isExternal: false
  name: WebSocketTransportUsage
  nameWithType: WebSocketTransportUsage
  fullName: System.ServiceModel.Channels.WebSocketTransportUsage
- uid: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.#ctor*
  parent: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement
  isExternal: false
  name: NetHttpWebSocketTransportSettingsElement
  nameWithType: NetHttpWebSocketTransportSettingsElement.NetHttpWebSocketTransportSettingsElement
  fullName: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.NetHttpWebSocketTransportSettingsElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetHttpWebSocketTransportSettingsElement.xml
- uid: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.Properties*
  parent: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement
  isExternal: false
  name: Properties
  nameWithType: NetHttpWebSocketTransportSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetHttpWebSocketTransportSettingsElement.xml
- uid: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.SubProtocol*
  parent: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement
  isExternal: false
  name: SubProtocol
  nameWithType: NetHttpWebSocketTransportSettingsElement.SubProtocol
  fullName: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.SubProtocol
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetHttpWebSocketTransportSettingsElement.xml
- uid: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.TransportUsage*
  parent: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement
  isExternal: false
  name: TransportUsage
  nameWithType: NetHttpWebSocketTransportSettingsElement.TransportUsage
  fullName: System.ServiceModel.Configuration.NetHttpWebSocketTransportSettingsElement.TransportUsage
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetHttpWebSocketTransportSettingsElement.xml
