### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.AudienceUriElement
  commentId: T:System.IdentityModel.Configuration.AudienceUriElement
  id: AudienceUriElement
  children:
  - System.IdentityModel.Configuration.AudienceUriElement.#ctor
  - System.IdentityModel.Configuration.AudienceUriElement.Properties
  - System.IdentityModel.Configuration.AudienceUriElement.Value
  langs:
  - csharp
  name: AudienceUriElement
  nameWithType: AudienceUriElement
  fullName: System.IdentityModel.Configuration.AudienceUriElement
  type: Class
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: Represents an audience URI value configured under an `<audienceUris>` element.
  remarks: "The `<audienceUris>` element is represented by the <xref:System.IdentityModel.Configuration.AudienceUriElementCollection> class It specifies the set of URIs which are acceptable as identifying a relying party. Tokens will not be accepted unless they are scoped for one of the allowed audience URIs.  \n  \n The <xref:System.IdentityModel.Configuration.AudienceUriElement> class represents a single audience URI value that has been added to the collection."
  syntax:
    content: 'public sealed class AudienceUriElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/AudienceUriElement.xml
  ms.author: v-jibran
  manager: markgal
- uid: System.IdentityModel.Configuration.AudienceUriElement.#ctor
  commentId: M:System.IdentityModel.Configuration.AudienceUriElement.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.AudienceUriElement
  langs:
  - csharp
  name: AudienceUriElement()
  nameWithType: AudienceUriElement.AudienceUriElement()
  fullName: System.IdentityModel.Configuration.AudienceUriElement.AudienceUriElement()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: Initializes a new instance of the <xref href="System.IdentityModel.Configuration.AudienceUriElement"></xref> class.
  syntax:
    content: public AudienceUriElement ();
    parameters: []
  overload: System.IdentityModel.Configuration.AudienceUriElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/AudienceUriElement.xml
  ms.author: v-jibran
  manager: markgal
- uid: System.IdentityModel.Configuration.AudienceUriElement.Properties
  commentId: P:System.IdentityModel.Configuration.AudienceUriElement.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.AudienceUriElement
  langs:
  - csharp
  name: Properties
  nameWithType: AudienceUriElement.Properties
  fullName: System.IdentityModel.Configuration.AudienceUriElement.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.IdentityModel.Configuration.AudienceUriElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/AudienceUriElement.xml
- uid: System.IdentityModel.Configuration.AudienceUriElement.Value
  commentId: P:System.IdentityModel.Configuration.AudienceUriElement.Value
  id: Value
  parent: System.IdentityModel.Configuration.AudienceUriElement
  langs:
  - csharp
  name: Value
  nameWithType: AudienceUriElement.Value
  fullName: System.IdentityModel.Configuration.AudienceUriElement.Value
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: Gets or sets the audience URI.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("value", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsKey=true, IsRequired=true)]

      [System.Configuration.StringValidator(MinLength=1)]

      public string Value { get; set; }
    return:
      type: System.String
      description: The audience URI.
  overload: System.IdentityModel.Configuration.AudienceUriElement.Value*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/AudienceUriElement.xml
  ms.author: v-jibran
  manager: markgal
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.IdentityModel.Configuration.AudienceUriElement.#ctor
  parent: System.IdentityModel.Configuration.AudienceUriElement
  isExternal: false
  name: AudienceUriElement()
  nameWithType: AudienceUriElement.AudienceUriElement()
  fullName: System.IdentityModel.Configuration.AudienceUriElement.AudienceUriElement()
- uid: System.IdentityModel.Configuration.AudienceUriElement.Properties
  parent: System.IdentityModel.Configuration.AudienceUriElement
  isExternal: false
  name: Properties
  nameWithType: AudienceUriElement.Properties
  fullName: System.IdentityModel.Configuration.AudienceUriElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.AudienceUriElement.Value
  parent: System.IdentityModel.Configuration.AudienceUriElement
  isExternal: false
  name: Value
  nameWithType: AudienceUriElement.Value
  fullName: System.IdentityModel.Configuration.AudienceUriElement.Value
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Configuration.AudienceUriElement.#ctor*
  parent: System.IdentityModel.Configuration.AudienceUriElement
  isExternal: false
  name: AudienceUriElement
  nameWithType: AudienceUriElement.AudienceUriElement
  fullName: System.IdentityModel.Configuration.AudienceUriElement.AudienceUriElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/AudienceUriElement.xml
- uid: System.IdentityModel.Configuration.AudienceUriElement.Properties*
  parent: System.IdentityModel.Configuration.AudienceUriElement
  isExternal: false
  name: Properties
  nameWithType: AudienceUriElement.Properties
  fullName: System.IdentityModel.Configuration.AudienceUriElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/AudienceUriElement.xml
- uid: System.IdentityModel.Configuration.AudienceUriElement.Value*
  parent: System.IdentityModel.Configuration.AudienceUriElement
  isExternal: false
  name: Value
  nameWithType: AudienceUriElement.Value
  fullName: System.IdentityModel.Configuration.AudienceUriElement.Value
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/AudienceUriElement.xml
