### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.PerformanceCountersElement
  commentId: T:System.Net.Configuration.PerformanceCountersElement
  id: PerformanceCountersElement
  children:
  - System.Net.Configuration.PerformanceCountersElement.#ctor
  - System.Net.Configuration.PerformanceCountersElement.Enabled
  - System.Net.Configuration.PerformanceCountersElement.Properties
  langs:
  - csharp
  name: PerformanceCountersElement
  nameWithType: PerformanceCountersElement
  fullName: System.Net.Configuration.PerformanceCountersElement
  type: Class
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Represents the performance counter element in the `System.Net` configuration file that determines whether networking performance counters are enabled. This class cannot be inherited.
  remarks: This class corresponds to the [\&lt;performanceCounter\&gt; Element (Network Settings)](~/docs/framework/configure-apps/file-schema/network/performancecounter-element-network-settings.md) configuration element. This class provides programmatic access to information that can be stored in configuration files.
  syntax:
    content: 'public sealed class PerformanceCountersElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/PerformanceCountersElement.xml
  ms.author: bobdel
  manager: markl
- uid: System.Net.Configuration.PerformanceCountersElement.#ctor
  commentId: M:System.Net.Configuration.PerformanceCountersElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.PerformanceCountersElement
  langs:
  - csharp
  name: PerformanceCountersElement()
  nameWithType: PerformanceCountersElement.PerformanceCountersElement()
  fullName: System.Net.Configuration.PerformanceCountersElement.PerformanceCountersElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Instantiates a <xref href="System.Net.Configuration.PerformanceCountersElement"></xref> object.
  syntax:
    content: public PerformanceCountersElement ();
    parameters: []
  overload: System.Net.Configuration.PerformanceCountersElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/PerformanceCountersElement.xml
  ms.author: bobdel
  manager: markl
- uid: System.Net.Configuration.PerformanceCountersElement.Enabled
  commentId: P:System.Net.Configuration.PerformanceCountersElement.Enabled
  id: Enabled
  parent: System.Net.Configuration.PerformanceCountersElement
  langs:
  - csharp
  name: Enabled
  nameWithType: PerformanceCountersElement.Enabled
  fullName: System.Net.Configuration.PerformanceCountersElement.Enabled
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Gets or sets whether performance counters are enabled.
  remarks: The default value for this property is `false`.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("enabled", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: '`true` if performance counters are enabled; otherwise, `false`.'
  overload: System.Net.Configuration.PerformanceCountersElement.Enabled*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/PerformanceCountersElement.xml
  ms.author: bobdel
  manager: markl
- uid: System.Net.Configuration.PerformanceCountersElement.Properties
  commentId: P:System.Net.Configuration.PerformanceCountersElement.Properties
  id: Properties
  parent: System.Net.Configuration.PerformanceCountersElement
  langs:
  - csharp
  name: Properties
  nameWithType: PerformanceCountersElement.Properties
  fullName: System.Net.Configuration.PerformanceCountersElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Net.Configuration.PerformanceCountersElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/PerformanceCountersElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.PerformanceCountersElement.#ctor
  parent: System.Net.Configuration.PerformanceCountersElement
  isExternal: false
  name: PerformanceCountersElement()
  nameWithType: PerformanceCountersElement.PerformanceCountersElement()
  fullName: System.Net.Configuration.PerformanceCountersElement.PerformanceCountersElement()
- uid: System.Net.Configuration.PerformanceCountersElement.Enabled
  parent: System.Net.Configuration.PerformanceCountersElement
  isExternal: false
  name: Enabled
  nameWithType: PerformanceCountersElement.Enabled
  fullName: System.Net.Configuration.PerformanceCountersElement.Enabled
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Net.Configuration.PerformanceCountersElement.Properties
  parent: System.Net.Configuration.PerformanceCountersElement
  isExternal: false
  name: Properties
  nameWithType: PerformanceCountersElement.Properties
  fullName: System.Net.Configuration.PerformanceCountersElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.PerformanceCountersElement.#ctor*
  parent: System.Net.Configuration.PerformanceCountersElement
  isExternal: false
  name: PerformanceCountersElement
  nameWithType: PerformanceCountersElement.PerformanceCountersElement
  fullName: System.Net.Configuration.PerformanceCountersElement.PerformanceCountersElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/PerformanceCountersElement.xml
- uid: System.Net.Configuration.PerformanceCountersElement.Enabled*
  parent: System.Net.Configuration.PerformanceCountersElement
  isExternal: false
  name: Enabled
  nameWithType: PerformanceCountersElement.Enabled
  fullName: System.Net.Configuration.PerformanceCountersElement.Enabled
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/PerformanceCountersElement.xml
- uid: System.Net.Configuration.PerformanceCountersElement.Properties*
  parent: System.Net.Configuration.PerformanceCountersElement
  isExternal: false
  name: Properties
  nameWithType: PerformanceCountersElement.Properties
  fullName: System.Net.Configuration.PerformanceCountersElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/PerformanceCountersElement.xml
