### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.ProtocolElement
  commentId: T:System.Web.Services.Configuration.ProtocolElement
  id: ProtocolElement
  children:
  - System.Web.Services.Configuration.ProtocolElement.#ctor
  - System.Web.Services.Configuration.ProtocolElement.#ctor(System.Web.Services.Configuration.WebServiceProtocols)
  - System.Web.Services.Configuration.ProtocolElement.Name
  - System.Web.Services.Configuration.ProtocolElement.Properties
  langs:
  - csharp
  name: ProtocolElement
  nameWithType: ProtocolElement
  fullName: System.Web.Services.Configuration.ProtocolElement
  type: Class
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Represents a `protocol` element in the Web Services configuration file. The class cannot be inherited.
  syntax:
    content: 'public sealed class ProtocolElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/ProtocolElement.xml
- uid: System.Web.Services.Configuration.ProtocolElement.#ctor
  commentId: M:System.Web.Services.Configuration.ProtocolElement.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.ProtocolElement
  langs:
  - csharp
  name: ProtocolElement()
  nameWithType: ProtocolElement.ProtocolElement()
  fullName: ProtocolElement.ProtocolElement()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Creates an instance of this class.
  syntax:
    content: public ProtocolElement ();
    parameters: []
  overload: System.Web.Services.Configuration.ProtocolElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/ProtocolElement.xml
- uid: System.Web.Services.Configuration.ProtocolElement.#ctor(System.Web.Services.Configuration.WebServiceProtocols)
  commentId: M:System.Web.Services.Configuration.ProtocolElement.#ctor(System.Web.Services.Configuration.WebServiceProtocols)
  id: '#ctor(System.Web.Services.Configuration.WebServiceProtocols)'
  parent: System.Web.Services.Configuration.ProtocolElement
  langs:
  - csharp
  name: ProtocolElement(WebServiceProtocols)
  nameWithType: ProtocolElement.ProtocolElement(WebServiceProtocols)
  fullName: ProtocolElement.ProtocolElement(WebServiceProtocols)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Creates an instance of this class, and initializes the <xref href="System.Web.Services.Configuration.ProtocolElement.Name"></xref> property.
  syntax:
    content: public ProtocolElement (System.Web.Services.Configuration.WebServiceProtocols protocol);
    parameters:
    - id: protocol
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: The value to initialize <xref href="System.Web.Services.Configuration.ProtocolElement.Name"></xref>.
  overload: System.Web.Services.Configuration.ProtocolElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/ProtocolElement.xml
- uid: System.Web.Services.Configuration.ProtocolElement.Name
  commentId: P:System.Web.Services.Configuration.ProtocolElement.Name
  id: Name
  parent: System.Web.Services.Configuration.ProtocolElement
  langs:
  - csharp
  name: Name
  nameWithType: ProtocolElement.Name
  fullName: ProtocolElement.Name
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Gets or sets the protocol name.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("name", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsKey=true)]

      public System.Web.Services.Configuration.WebServiceProtocols Name { get; set; }
    return:
      type: System.Web.Services.Configuration.WebServiceProtocols
      description: A <xref href="System.Web.Services.Configuration.WebServiceProtocols"></xref> object that represents the protocol name.
  overload: System.Web.Services.Configuration.ProtocolElement.Name*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/ProtocolElement.xml
- uid: System.Web.Services.Configuration.ProtocolElement.Properties
  commentId: P:System.Web.Services.Configuration.ProtocolElement.Properties
  id: Properties
  parent: System.Web.Services.Configuration.ProtocolElement
  langs:
  - csharp
  name: Properties
  nameWithType: ProtocolElement.Properties
  fullName: ProtocolElement.Properties
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Services.Configuration.ProtocolElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/ProtocolElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Services.Configuration.ProtocolElement.#ctor
  parent: System.Web.Services.Configuration.ProtocolElement
  isExternal: false
  name: ProtocolElement()
  nameWithType: ProtocolElement.ProtocolElement()
  fullName: ProtocolElement.ProtocolElement()
- uid: System.Web.Services.Configuration.ProtocolElement.#ctor(System.Web.Services.Configuration.WebServiceProtocols)
  parent: System.Web.Services.Configuration.ProtocolElement
  isExternal: false
  name: ProtocolElement(WebServiceProtocols)
  nameWithType: ProtocolElement.ProtocolElement(WebServiceProtocols)
  fullName: ProtocolElement.ProtocolElement(WebServiceProtocols)
- uid: System.Web.Services.Configuration.WebServiceProtocols
  parent: System.Web.Services.Configuration
  isExternal: false
  name: WebServiceProtocols
  nameWithType: WebServiceProtocols
  fullName: System.Web.Services.Configuration.WebServiceProtocols
- uid: System.Web.Services.Configuration.ProtocolElement.Name
  parent: System.Web.Services.Configuration.ProtocolElement
  isExternal: false
  name: Name
  nameWithType: ProtocolElement.Name
  fullName: ProtocolElement.Name
- uid: System.Web.Services.Configuration.ProtocolElement.Properties
  parent: System.Web.Services.Configuration.ProtocolElement
  isExternal: false
  name: Properties
  nameWithType: ProtocolElement.Properties
  fullName: ProtocolElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Services.Configuration.ProtocolElement.#ctor*
  parent: System.Web.Services.Configuration.ProtocolElement
  isExternal: false
  name: ProtocolElement
  nameWithType: ProtocolElement.ProtocolElement
  fullName: ProtocolElement.ProtocolElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/ProtocolElement.xml
- uid: System.Web.Services.Configuration.ProtocolElement.Name*
  parent: System.Web.Services.Configuration.ProtocolElement
  isExternal: false
  name: Name
  nameWithType: ProtocolElement.Name
  fullName: ProtocolElement.Name
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/ProtocolElement.xml
- uid: System.Web.Services.Configuration.ProtocolElement.Properties*
  parent: System.Web.Services.Configuration.ProtocolElement
  isExternal: false
  name: Properties
  nameWithType: ProtocolElement.Properties
  fullName: ProtocolElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/ProtocolElement.xml
