### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NetPeerTcpBindingCollectionElement
  commentId: T:System.ServiceModel.Configuration.NetPeerTcpBindingCollectionElement
  id: NetPeerTcpBindingCollectionElement
  children:
  - System.ServiceModel.Configuration.NetPeerTcpBindingCollectionElement.#ctor
  langs:
  - csharp
  name: NetPeerTcpBindingCollectionElement
  nameWithType: NetPeerTcpBindingCollectionElement
  fullName: System.ServiceModel.Configuration.NetPeerTcpBindingCollectionElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a configuration element that contains elements specific to peer channel TCP message bindings.
  syntax:
    content: >-
      [System.Obsolete("PeerChannel feature is obsolete and will be removed in the future.", false)]

      public class NetPeerTcpBindingCollectionElement : System.ServiceModel.Configuration.StandardBindingCollectionElement<System.ServiceModel.NetPeerTcpBinding,System.ServiceModel.Configuration.NetPeerTcpBindingElement>
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.BindingCollectionElement
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Bindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.BindingType
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ConfiguredBindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ContainsKey(System.String)
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.GetDefault
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Properties
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  attributes:
  - type: System.ObsoleteAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetPeerTcpBindingCollectionElement.xml
  manager: ghogen
- uid: System.ServiceModel.Configuration.NetPeerTcpBindingCollectionElement.#ctor
  commentId: M:System.ServiceModel.Configuration.NetPeerTcpBindingCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NetPeerTcpBindingCollectionElement
  langs:
  - csharp
  name: NetPeerTcpBindingCollectionElement()
  nameWithType: NetPeerTcpBindingCollectionElement.NetPeerTcpBindingCollectionElement()
  fullName: System.ServiceModel.Configuration.NetPeerTcpBindingCollectionElement.NetPeerTcpBindingCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.NetPeerTcpBindingCollectionElement"></xref> class.
  syntax:
    content: public NetPeerTcpBindingCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NetPeerTcpBindingCollectionElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetPeerTcpBindingCollectionElement.xml
  manager: ghogen
references:
- uid: System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  name: StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  nameWithType: StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
- uid: System.ServiceModel.NetPeerTcpBinding
  name: NetPeerTcpBinding
  nameWithType: NetPeerTcpBinding
  fullName: System.ServiceModel.NetPeerTcpBinding
- uid: System.ServiceModel.Configuration.NetPeerTcpBindingElement
  name: NetPeerTcpBindingElement
  nameWithType: NetPeerTcpBindingElement
  fullName: System.ServiceModel.Configuration.NetPeerTcpBindingElement
- uid: System.ServiceModel.Configuration.StandardBindingCollectionElement{System.ServiceModel.NetPeerTcpBinding,System.ServiceModel.Configuration.NetPeerTcpBindingElement}
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: StandardBindingCollectionElement<NetPeerTcpBinding,NetPeerTcpBindingElement>
  nameWithType: StandardBindingCollectionElement<NetPeerTcpBinding,NetPeerTcpBindingElement>
  fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement<System.ServiceModel.NetPeerTcpBinding,System.ServiceModel.Configuration.NetPeerTcpBindingElement>
  spec.csharp:
  - uid: System.ServiceModel.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.NetPeerTcpBinding
    name: NetPeerTcpBinding
    nameWithType: NetPeerTcpBinding
    fullName: System.ServiceModel.NetPeerTcpBinding
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.ServiceModel.Configuration.NetPeerTcpBindingElement
    name: NetPeerTcpBindingElement
    nameWithType: NetPeerTcpBindingElement
    fullName: System.ServiceModel.Configuration.NetPeerTcpBindingElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.NetPeerTcpBindingCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.NetPeerTcpBindingCollectionElement
  isExternal: false
  name: NetPeerTcpBindingCollectionElement()
  nameWithType: NetPeerTcpBindingCollectionElement.NetPeerTcpBindingCollectionElement()
  fullName: System.ServiceModel.Configuration.NetPeerTcpBindingCollectionElement.NetPeerTcpBindingCollectionElement()
- uid: System.ServiceModel.Configuration.NetPeerTcpBindingCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.NetPeerTcpBindingCollectionElement
  isExternal: false
  name: NetPeerTcpBindingCollectionElement
  nameWithType: NetPeerTcpBindingCollectionElement.NetPeerTcpBindingCollectionElement
  fullName: System.ServiceModel.Configuration.NetPeerTcpBindingCollectionElement.NetPeerTcpBindingCollectionElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetPeerTcpBindingCollectionElement.xml
