### YamlMime:ManagedReference
items:
- uid: System.Configuration.ProtectedProviderSettings
  commentId: T:System.Configuration.ProtectedProviderSettings
  id: ProtectedProviderSettings
  children:
  - System.Configuration.ProtectedProviderSettings.#ctor
  - System.Configuration.ProtectedProviderSettings.Properties
  - System.Configuration.ProtectedProviderSettings.Providers
  langs:
  - csharp
  name: ProtectedProviderSettings
  nameWithType: ProtectedProviderSettings
  fullName: System.Configuration.ProtectedProviderSettings
  type: Class
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Represents a group of configuration elements that configure the providers for the `<configProtectedData>` configuration section.
  syntax:
    content: 'public class ProtectedProviderSettings : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ProtectedProviderSettings.xml
- uid: System.Configuration.ProtectedProviderSettings.#ctor
  commentId: M:System.Configuration.ProtectedProviderSettings.#ctor
  id: '#ctor'
  parent: System.Configuration.ProtectedProviderSettings
  langs:
  - csharp
  name: ProtectedProviderSettings()
  nameWithType: ProtectedProviderSettings.ProtectedProviderSettings()
  fullName: ProtectedProviderSettings.ProtectedProviderSettings()
  type: Constructor
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.ProtectedProviderSettings"></xref> class.
  syntax:
    content: public ProtectedProviderSettings ();
    parameters: []
  overload: System.Configuration.ProtectedProviderSettings.#ctor*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ProtectedProviderSettings.xml
- uid: System.Configuration.ProtectedProviderSettings.Properties
  commentId: P:System.Configuration.ProtectedProviderSettings.Properties
  id: Properties
  parent: System.Configuration.ProtectedProviderSettings
  langs:
  - csharp
  name: Properties
  nameWithType: ProtectedProviderSettings.Properties
  fullName: ProtectedProviderSettings.Properties
  type: Property
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Gets a <xref href="System.Configuration.ConfigurationPropertyCollection"></xref> collection that represents the properties of the providers for the protected configuration data.
  remarks: Use the <xref:System.Configuration.ProtectedProviderSettings.Providers%2A> property to access the properties of the providers for protected configuration data.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: A <xref href="System.Configuration.ConfigurationPropertyCollection"></xref> that represents the properties of the providers for the protected configuration data.
  overload: System.Configuration.ProtectedProviderSettings.Properties*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ProtectedProviderSettings.xml
- uid: System.Configuration.ProtectedProviderSettings.Providers
  commentId: P:System.Configuration.ProtectedProviderSettings.Providers
  id: Providers
  parent: System.Configuration.ProtectedProviderSettings
  langs:
  - csharp
  name: Providers
  nameWithType: ProtectedProviderSettings.Providers
  fullName: ProtectedProviderSettings.Providers
  type: Property
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Gets a collection of <xref href="System.Configuration.ProviderSettings"></xref> objects that represent the properties of the providers for the protected configuration data.
  remarks: Use this property to access the properties of the providers for protected configuration data instead of the <xref:System.Configuration.ProtectedProviderSettings.Properties%2A> property.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("", Options=System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection)]

      public System.Configuration.ProviderSettingsCollection Providers { get; }
    return:
      type: System.Configuration.ProviderSettingsCollection
      description: A collection of <xref href="System.Configuration.ProviderSettings"></xref> objects that represent the properties of the providers for the protected configuration data.
  overload: System.Configuration.ProtectedProviderSettings.Providers*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ProtectedProviderSettings.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Configuration.ProtectedProviderSettings.#ctor
  parent: System.Configuration.ProtectedProviderSettings
  isExternal: false
  name: ProtectedProviderSettings()
  nameWithType: ProtectedProviderSettings.ProtectedProviderSettings()
  fullName: ProtectedProviderSettings.ProtectedProviderSettings()
- uid: System.Configuration.ProtectedProviderSettings.Properties
  parent: System.Configuration.ProtectedProviderSettings
  isExternal: false
  name: Properties
  nameWithType: ProtectedProviderSettings.Properties
  fullName: ProtectedProviderSettings.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.ProtectedProviderSettings.Providers
  parent: System.Configuration.ProtectedProviderSettings
  isExternal: false
  name: Providers
  nameWithType: ProtectedProviderSettings.Providers
  fullName: ProtectedProviderSettings.Providers
- uid: System.Configuration.ProviderSettingsCollection
  parent: System.Configuration
  isExternal: false
  name: ProviderSettingsCollection
  nameWithType: ProviderSettingsCollection
  fullName: System.Configuration.ProviderSettingsCollection
- uid: System.Configuration.ProtectedProviderSettings.#ctor*
  parent: System.Configuration.ProtectedProviderSettings
  isExternal: false
  name: ProtectedProviderSettings
  nameWithType: ProtectedProviderSettings.ProtectedProviderSettings
  fullName: ProtectedProviderSettings.ProtectedProviderSettings
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ProtectedProviderSettings.xml
- uid: System.Configuration.ProtectedProviderSettings.Properties*
  parent: System.Configuration.ProtectedProviderSettings
  isExternal: false
  name: Properties
  nameWithType: ProtectedProviderSettings.Properties
  fullName: ProtectedProviderSettings.Properties
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ProtectedProviderSettings.xml
- uid: System.Configuration.ProtectedProviderSettings.Providers*
  parent: System.Configuration.ProtectedProviderSettings
  isExternal: false
  name: Providers
  nameWithType: ProtectedProviderSettings.Providers
  fullName: ProtectedProviderSettings.Providers
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ProtectedProviderSettings.xml
