### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  commentId: T:System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  id: MessageSecurityOverMsmqElement
  children:
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  langs:
  - csharp
  name: MessageSecurityOverMsmqElement
  nameWithType: MessageSecurityOverMsmqElement
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Enables setting message-level security properties on the <xref href="System.ServiceModel.NetMsmqBinding"></xref> binding.
  syntax:
    content: 'public sealed class MessageSecurityOverMsmqElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverMsmqElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor
  commentId: M:System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: MessageSecurityOverMsmqElement()
  nameWithType: MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.MessageSecurityOverMsmqElement"></xref> class.
  syntax:
    content: public MessageSecurityOverMsmqElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverMsmqElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  commentId: P:System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  id: AlgorithmSuite
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverMsmqElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Specifies the algorithm suite used for security messages at the SOAP level.
  remarks: <xref:System.ServiceModel.Security.SecurityAlgorithmSuite> defines a variety of algorithms, such as Canonicalization, Digest, KeyWrap, Signature, Encryption, and KeyDerivation. This property is most relevant when working with a platform that uses a set of algorithms different than the default. You should be aware of the strengths and weaknesses of the relevant algorithms when making modifications to this property.
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(System.ServiceModel.Configuration.SecurityAlgorithmSuiteConverter))]

      [System.Configuration.ConfigurationProperty("algorithmSuite", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.ServiceModel.Security.SecurityAlgorithmSuite AlgorithmSuite { get; set; }
    return:
      type: System.ServiceModel.Security.SecurityAlgorithmSuite
      description: The <xref href="System.ServiceModel.Security.SecurityAlgorithmSuite"></xref> setting for messages sent over the <xref href="System.ServiceModel.NetMsmqBinding"></xref> binding.
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite*
  exceptions: []
  attributes:
  - type: System.ComponentModel.TypeConverterAttribute
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverMsmqElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  commentId: P:System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  id: ClientCredentialType
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: ClientCredentialType
  nameWithType: MessageSecurityOverMsmqElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the <xref href="System.ServiceModel.MessageCredentialType"></xref> security setting for messages sent over the MSMQ transport.
  remarks: "This property can be set to one of the following values:  \n  \n-   None: This allows the service to interact with anonymous clients. Neither the service nor the client requires a credential.  \n  \n-   Windows: This enables the SOAP exchanges to be under the authenticated context of a Windows credential. This always performs Kerberos-based authentication.  \n  \n-   UserName: This enables the service to require that the client be authenticated using a UserName credential. This credential needs to be specified using <xref:System.ServiceModel.Description.ClientCredentials> class.  \n  \n    > [!NOTE]\n    >  [!INCLUDE[indigo2](~/includes/indigo2-md.md)] does not support sending a password digest or deriving keys using password and using such keys for message security. As such, [!INCLUDE[indigo2](~/includes/indigo2-md.md)] enforces that the exchange is secured when using UserName credentials. This mode requires that the service certificate be specified on the client side using ClientCredential behavior and serviceCertificate.  \n  \n-   Certificate: This enables the service to require that the client be authenticated using a certificate. The client credential in this case needs to be specified using the <xref:System.ServiceModel.Description.ClientCredentials> class or ClientCredentials behavior. The service credential in this case needs to be specified using the <xref:System.ServiceModel.Description.ClientCredentials> class or ClientCredentials behavior by specifying the serviceCertificate.  \n  \n-   CardSpace: This allows the service to require that the client be authenticated using a [!INCLUDE[infocard1](~/includes/infocard1-md.md)]. The serviceCertiifcate must be provisioned in the ClientCredential behavior.  \n  \n The Certificate credential for the `MessageSecurityOverMsmq` is relevant only when the security mode is set to `Both` or `Message`."
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("clientCredentialType", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.ServiceModel.MessageCredentialType ClientCredentialType { get; set; }
    return:
      type: System.ServiceModel.MessageCredentialType
      description: The <xref href="System.ServiceModel.MessageCredentialType"></xref> security setting for messages sent over the MSMQ transport.
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverMsmqElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  commentId: P:System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: Properties
  nameWithType: MessageSecurityOverMsmqElement.Properties
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverMsmqElement.xml
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: MessageSecurityOverMsmqElement()
  nameWithType: MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverMsmqElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
- uid: System.ServiceModel.Security.SecurityAlgorithmSuite
  parent: System.ServiceModel.Security
  isExternal: false
  name: SecurityAlgorithmSuite
  nameWithType: SecurityAlgorithmSuite
  fullName: System.ServiceModel.Security.SecurityAlgorithmSuite
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: MessageSecurityOverMsmqElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
- uid: System.ServiceModel.MessageCredentialType
  parent: System.ServiceModel
  isExternal: false
  name: MessageCredentialType
  nameWithType: MessageCredentialType
  fullName: System.ServiceModel.MessageCredentialType
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: Properties
  nameWithType: MessageSecurityOverMsmqElement.Properties
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: MessageSecurityOverMsmqElement
  nameWithType: MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverMsmqElement.xml
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverMsmqElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverMsmqElement.xml
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: MessageSecurityOverMsmqElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverMsmqElement.xml
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: Properties
  nameWithType: MessageSecurityOverMsmqElement.Properties
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MessageSecurityOverMsmqElement.xml
