### YamlMime:ManagedReference
items:
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  commentId: T:System.Activities.Presentation.PropertyEditing.PropertyValueSource
  id: PropertyValueSource
  children:
  - System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor
  langs:
  - csharp
  name: PropertyValueSource
  nameWithType: PropertyValueSource
  fullName: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  type: Class
  assemblies:
  - System.Activities.Presentation
  namespace: System.Activities.Presentation.PropertyEditing
  summary: Represents the origin of a property value.
  remarks: Examples of property value sources can include inherited values, parent template values, default values, implicit style references, trigger-based values, and others.
  example:
  - '<!-- TODO: review snippet reference  [!CODE [WFD_PropertyValueSource#0](WFD_PropertyValueSource#0)]  -->'
  syntax:
    content: public abstract class PropertyValueSource
  inheritance:
  - System.Object
  derivedClasses:
  - System.Activities.Presentation.PropertyEditing.DependencyPropertyValueSource
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities.Presentation.PropertyEditing/PropertyValueSource.xml
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor
  commentId: M:System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor
  id: '#ctor'
  parent: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  langs:
  - csharp
  name: PropertyValueSource()
  nameWithType: PropertyValueSource.PropertyValueSource()
  fullName: PropertyValueSource.PropertyValueSource()
  type: Constructor
  assemblies:
  - System.Activities.Presentation
  namespace: System.Activities.Presentation.PropertyEditing
  summary: Creates a new instance of the <xref href="System.Activities.Presentation.PropertyEditing.PropertyValueSource"></xref> class.
  syntax:
    content: protected PropertyValueSource ();
    parameters: []
  overload: System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities.Presentation.PropertyEditing/PropertyValueSource.xml
references:
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor
  parent: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  isExternal: false
  name: PropertyValueSource()
  nameWithType: PropertyValueSource.PropertyValueSource()
  fullName: PropertyValueSource.PropertyValueSource()
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor*
  parent: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  isExternal: false
  name: PropertyValueSource
  nameWithType: PropertyValueSource.PropertyValueSource
  fullName: PropertyValueSource.PropertyValueSource
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities.Presentation.PropertyEditing/PropertyValueSource.xml
