### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  commentId: T:System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  id: AnnotationElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Name
  - System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Properties
  - System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Value
  langs:
  - csharp
  name: AnnotationElement
  nameWithType: AnnotationElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  type: Class
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: A configuration element that represents an annotation that is added to an emitted tracking record.
  syntax:
    content: 'public class AnnotationElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/AnnotationElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.#ctor
  commentId: M:System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  langs:
  - csharp
  name: AnnotationElement()
  nameWithType: AnnotationElement.AnnotationElement()
  fullName: AnnotationElement.AnnotationElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement"></xref> class.
  syntax:
    content: public AnnotationElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/AnnotationElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.ElementKey
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.ElementKey
  id: ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  langs:
  - csharp
  name: ElementKey
  nameWithType: AnnotationElement.ElementKey
  fullName: AnnotationElement.ElementKey
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets a key that uniquely identifies the annotation.
  syntax:
    content: public override object ElementKey { get; }
    return:
      type: System.Object
      description: The element key.
  overload: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.ElementKey*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/AnnotationElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Name
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Name
  id: Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  langs:
  - csharp
  name: Name
  nameWithType: AnnotationElement.Name
  fullName: AnnotationElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets or sets the name of the annotation.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("name", IsKey=true, IsRequired=true)]

      [System.Configuration.StringValidator(MinLength=0)]

      public string Name { get; set; }
    return:
      type: System.String
      description: The name of the annotation.
  overload: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Name*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/AnnotationElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Properties
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  langs:
  - csharp
  name: Properties
  nameWithType: AnnotationElement.Properties
  fullName: AnnotationElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets a <xref href="System.Configuration.ConfigurationPropertyCollection"></xref> that contains the properties for the configuration element.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: The collection of properties.
  overload: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/AnnotationElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Value
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Value
  id: Value
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  langs:
  - csharp
  name: Value
  nameWithType: AnnotationElement.Value
  fullName: AnnotationElement.Value
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets or sets the value of the annotation.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("value", IsRequired=true)]

      [System.Configuration.StringValidator(MinLength=0)]

      public string Value { get; set; }
    return:
      type: System.String
      description: The value of the annotation.
  overload: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Value*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/AnnotationElement.xml
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  parent: System.ServiceModel.Activities.Tracking.Configuration
  isExternal: false
  name: TrackingConfigurationElement
  nameWithType: TrackingConfigurationElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: AnnotationElement()
  nameWithType: AnnotationElement.AnnotationElement()
  fullName: AnnotationElement.AnnotationElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: ElementKey
  nameWithType: AnnotationElement.ElementKey
  fullName: AnnotationElement.ElementKey
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: Name
  nameWithType: AnnotationElement.Name
  fullName: AnnotationElement.Name
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: Properties
  nameWithType: AnnotationElement.Properties
  fullName: AnnotationElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Value
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: Value
  nameWithType: AnnotationElement.Value
  fullName: AnnotationElement.Value
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: AnnotationElement
  nameWithType: AnnotationElement.AnnotationElement
  fullName: AnnotationElement.AnnotationElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/AnnotationElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.ElementKey*
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: ElementKey
  nameWithType: AnnotationElement.ElementKey
  fullName: AnnotationElement.ElementKey
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/AnnotationElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Name*
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: Name
  nameWithType: AnnotationElement.Name
  fullName: AnnotationElement.Name
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/AnnotationElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: Properties
  nameWithType: AnnotationElement.Properties
  fullName: AnnotationElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/AnnotationElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Value*
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: Value
  nameWithType: AnnotationElement.Value
  fullName: AnnotationElement.Value
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/AnnotationElement.xml
