### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection
  commentId: T:System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection
  id: CancelRequestedQueryElementCollection
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection.ElementName
  langs:
  - csharp
  name: CancelRequestedQueryElementCollection
  nameWithType: CancelRequestedQueryElementCollection
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection
  type: Class
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: A configuration element that contains <xref href="System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement"></xref> elements.
  syntax:
    content: >-
      [System.Configuration.ConfigurationCollection(typeof(System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement), AddItemName="cancelRequestedQuery", CollectionType=System.Configuration.ConfigurationElementCollectionType.BasicMap)]

      public class CancelRequestedQueryElementCollection : System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection<System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement>
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationElementCollection
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.AddElementName
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseClear
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseGetAllKeys
  - System.Configuration.ConfigurationElementCollection.BaseGetKey(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseIndexOf(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseIsRemoved(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemove(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemoveAt(System.Int32)
  - System.Configuration.ConfigurationElementCollection.ClearElementName
  - System.Configuration.ConfigurationElementCollection.CopyTo(System.Configuration.ConfigurationElement[],System.Int32)
  - System.Configuration.ConfigurationElementCollection.Count
  - System.Configuration.ConfigurationElementCollection.CreateNewElement(System.String)
  - System.Configuration.ConfigurationElementCollection.EmitClear
  - System.Configuration.ConfigurationElementCollection.Equals(System.Object)
  - System.Configuration.ConfigurationElementCollection.GetEnumerator
  - System.Configuration.ConfigurationElementCollection.GetHashCode
  - System.Configuration.ConfigurationElementCollection.IsElementName(System.String)
  - System.Configuration.ConfigurationElementCollection.IsElementRemovable(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.IsModified
  - System.Configuration.ConfigurationElementCollection.IsReadOnly
  - System.Configuration.ConfigurationElementCollection.IsSynchronized
  - System.Configuration.ConfigurationElementCollection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElementCollection.RemoveElementName
  - System.Configuration.ConfigurationElementCollection.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.ResetModified
  - System.Configuration.ConfigurationElementCollection.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.SetReadOnly
  - System.Configuration.ConfigurationElementCollection.SyncRoot
  - System.Configuration.ConfigurationElementCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Configuration.ConfigurationElementCollection.ThrowOnDuplicate
  - System.Configuration.ConfigurationElementCollection.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.Add(`0)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.Clear
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.CollectionType
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.CreateNewElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.GetElementKey(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.IndexOf(`0)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.Item(System.Int32)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.Remove(`0)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.RemoveAt(System.Int32)
  extensionMethods:
  - System.Linq.Enumerable.Cast``1(System.Collections.IEnumerable)
  - System.Linq.Enumerable.OfType``1(System.Collections.IEnumerable)
  - System.Linq.ParallelEnumerable.AsParallel(System.Collections.IEnumerable)
  - System.Linq.Queryable.AsQueryable(System.Collections.IEnumerable)
  attributes:
  - type: System.Configuration.ConfigurationCollectionAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/CancelRequestedQueryElementCollection.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection.#ctor
  commentId: M:System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection
  langs:
  - csharp
  name: CancelRequestedQueryElementCollection()
  nameWithType: CancelRequestedQueryElementCollection.CancelRequestedQueryElementCollection()
  fullName: CancelRequestedQueryElementCollection.CancelRequestedQueryElementCollection()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection"></xref> class.
  syntax:
    content: public CancelRequestedQueryElementCollection ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/CancelRequestedQueryElementCollection.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection.ElementName
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection.ElementName
  id: ElementName
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection
  langs:
  - csharp
  name: ElementName
  nameWithType: CancelRequestedQueryElementCollection.ElementName
  fullName: CancelRequestedQueryElementCollection.ElementName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets the configuration element name.
  syntax:
    content: protected override string ElementName { get; }
    return:
      type: System.String
      description: The configuration element name.
  overload: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection.ElementName*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/CancelRequestedQueryElementCollection.xml
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1
  name: TrackingConfigurationCollection<TConfigurationElement>
  nameWithType: TrackingConfigurationCollection<TConfigurationElement>
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection<TConfigurationElement>
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  name: CancelRequestedQueryElement
  nameWithType: CancelRequestedQueryElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection{System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement}
  parent: System.ServiceModel.Activities.Tracking.Configuration
  isExternal: false
  name: TrackingConfigurationCollection<CancelRequestedQueryElement>
  nameWithType: TrackingConfigurationCollection<CancelRequestedQueryElement>
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection<System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement>
  spec.csharp:
  - uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1
    name: TrackingConfigurationCollection
    nameWithType: TrackingConfigurationCollection
    fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
    name: CancelRequestedQueryElement
    nameWithType: CancelRequestedQueryElement
    fullName: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection
  isExternal: false
  name: CancelRequestedQueryElementCollection()
  nameWithType: CancelRequestedQueryElementCollection.CancelRequestedQueryElementCollection()
  fullName: CancelRequestedQueryElementCollection.CancelRequestedQueryElementCollection()
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection.ElementName
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection
  isExternal: false
  name: ElementName
  nameWithType: CancelRequestedQueryElementCollection.ElementName
  fullName: CancelRequestedQueryElementCollection.ElementName
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection
  isExternal: false
  name: CancelRequestedQueryElementCollection
  nameWithType: CancelRequestedQueryElementCollection.CancelRequestedQueryElementCollection
  fullName: CancelRequestedQueryElementCollection.CancelRequestedQueryElementCollection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/CancelRequestedQueryElementCollection.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection.ElementName*
  parent: System.ServiceModel.Activities.Tracking.Configuration.CancelRequestedQueryElementCollection
  isExternal: false
  name: ElementName
  nameWithType: CancelRequestedQueryElementCollection.ElementName
  fullName: CancelRequestedQueryElementCollection.ElementName
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/CancelRequestedQueryElementCollection.xml
- uid: System.Linq.Enumerable.Cast``1(System.Collections.IEnumerable)
  parent: System.Linq.Enumerable
  isExternal: false
  name: Cast<TResult>(IEnumerable)
  nameWithType: Enumerable.Cast<TResult>(IEnumerable)
  fullName: Enumerable.Cast<TResult>(IEnumerable)
- uid: System.Linq.Enumerable.OfType``1(System.Collections.IEnumerable)
  parent: System.Linq.Enumerable
  isExternal: false
  name: OfType<TResult>(IEnumerable)
  nameWithType: Enumerable.OfType<TResult>(IEnumerable)
  fullName: Enumerable.OfType<TResult>(IEnumerable)
- uid: System.Linq.ParallelEnumerable.AsParallel(System.Collections.IEnumerable)
  parent: System.Linq.ParallelEnumerable
  isExternal: false
  name: AsParallel(IEnumerable)
  nameWithType: ParallelEnumerable.AsParallel(IEnumerable)
  fullName: ParallelEnumerable.AsParallel(IEnumerable)
- uid: System.Linq.Queryable.AsQueryable(System.Collections.IEnumerable)
  parent: System.Linq.Queryable
  isExternal: false
  name: AsQueryable(IEnumerable)
  nameWithType: Queryable.AsQueryable(IEnumerable)
  fullName: Queryable.AsQueryable(IEnumerable)
