### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NetTcpSecurityElement
  commentId: T:System.ServiceModel.Configuration.NetTcpSecurityElement
  id: NetTcpSecurityElement
  children:
  - System.ServiceModel.Configuration.NetTcpSecurityElement.#ctor
  - System.ServiceModel.Configuration.NetTcpSecurityElement.Message
  - System.ServiceModel.Configuration.NetTcpSecurityElement.Mode
  - System.ServiceModel.Configuration.NetTcpSecurityElement.Properties
  - System.ServiceModel.Configuration.NetTcpSecurityElement.Transport
  langs:
  - csharp
  name: NetTcpSecurityElement
  nameWithType: NetTcpSecurityElement
  fullName: System.ServiceModel.Configuration.NetTcpSecurityElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Defines the security settings for the netTcpBinding binding. This class cannot be inherited.
  syntax:
    content: 'public sealed class NetTcpSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetTcpSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.NetTcpSecurityElement.#ctor
  commentId: M:System.ServiceModel.Configuration.NetTcpSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NetTcpSecurityElement
  langs:
  - csharp
  name: NetTcpSecurityElement()
  nameWithType: NetTcpSecurityElement.NetTcpSecurityElement()
  fullName: System.ServiceModel.Configuration.NetTcpSecurityElement.NetTcpSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.NetTcpSecurityElement"></xref> class.
  syntax:
    content: public NetTcpSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NetTcpSecurityElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetTcpSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.NetTcpSecurityElement.Message
  commentId: P:System.ServiceModel.Configuration.NetTcpSecurityElement.Message
  id: Message
  parent: System.ServiceModel.Configuration.NetTcpSecurityElement
  langs:
  - csharp
  name: Message
  nameWithType: NetTcpSecurityElement.Message
  fullName: System.ServiceModel.Configuration.NetTcpSecurityElement.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets the security settings for the message.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("message")]

      public System.ServiceModel.Configuration.MessageSecurityOverTcpElement Message { get; }
    return:
      type: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
      description: A <xref href="System.ServiceModel.Configuration.MessageSecurityOverTcpElement"></xref> that specifies the security settings for the message.
  overload: System.ServiceModel.Configuration.NetTcpSecurityElement.Message*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetTcpSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.NetTcpSecurityElement.Mode
  commentId: P:System.ServiceModel.Configuration.NetTcpSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.NetTcpSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: NetTcpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.NetTcpSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the type of security that is applied.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("mode", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.ServiceModel.SecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.SecurityMode
      description: A <xref href="System.ServiceModel.SecurityMode"></xref> that specifies the type of security that is applied. The default value is Transport.
  overload: System.ServiceModel.Configuration.NetTcpSecurityElement.Mode*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetTcpSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.NetTcpSecurityElement.Properties
  commentId: P:System.ServiceModel.Configuration.NetTcpSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.NetTcpSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: NetTcpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NetTcpSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.NetTcpSecurityElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetTcpSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetTcpSecurityElement.Transport
  commentId: P:System.ServiceModel.Configuration.NetTcpSecurityElement.Transport
  id: Transport
  parent: System.ServiceModel.Configuration.NetTcpSecurityElement
  langs:
  - csharp
  name: Transport
  nameWithType: NetTcpSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.NetTcpSecurityElement.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets the security settings for the transport.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("transport")]

      public System.ServiceModel.Configuration.TcpTransportSecurityElement Transport { get; }
    return:
      type: System.ServiceModel.Configuration.TcpTransportSecurityElement
      description: A <xref href="System.ServiceModel.Configuration.TcpTransportSecurityElement"></xref> that specifies the security settings for the transport.
  overload: System.ServiceModel.Configuration.NetTcpSecurityElement.Transport*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetTcpSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.NetTcpSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.NetTcpSecurityElement
  isExternal: false
  name: NetTcpSecurityElement()
  nameWithType: NetTcpSecurityElement.NetTcpSecurityElement()
  fullName: System.ServiceModel.Configuration.NetTcpSecurityElement.NetTcpSecurityElement()
- uid: System.ServiceModel.Configuration.NetTcpSecurityElement.Message
  parent: System.ServiceModel.Configuration.NetTcpSecurityElement
  isExternal: false
  name: Message
  nameWithType: NetTcpSecurityElement.Message
  fullName: System.ServiceModel.Configuration.NetTcpSecurityElement.Message
- uid: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: MessageSecurityOverTcpElement
  nameWithType: MessageSecurityOverTcpElement
  fullName: System.ServiceModel.Configuration.MessageSecurityOverTcpElement
- uid: System.ServiceModel.Configuration.NetTcpSecurityElement.Mode
  parent: System.ServiceModel.Configuration.NetTcpSecurityElement
  isExternal: false
  name: Mode
  nameWithType: NetTcpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.NetTcpSecurityElement.Mode
- uid: System.ServiceModel.SecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: SecurityMode
  nameWithType: SecurityMode
  fullName: System.ServiceModel.SecurityMode
- uid: System.ServiceModel.Configuration.NetTcpSecurityElement.Properties
  parent: System.ServiceModel.Configuration.NetTcpSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NetTcpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NetTcpSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.NetTcpSecurityElement.Transport
  parent: System.ServiceModel.Configuration.NetTcpSecurityElement
  isExternal: false
  name: Transport
  nameWithType: NetTcpSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.NetTcpSecurityElement.Transport
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: TcpTransportSecurityElement
  nameWithType: TcpTransportSecurityElement
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement
- uid: System.ServiceModel.Configuration.NetTcpSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.NetTcpSecurityElement
  isExternal: false
  name: NetTcpSecurityElement
  nameWithType: NetTcpSecurityElement.NetTcpSecurityElement
  fullName: System.ServiceModel.Configuration.NetTcpSecurityElement.NetTcpSecurityElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetTcpSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetTcpSecurityElement.Message*
  parent: System.ServiceModel.Configuration.NetTcpSecurityElement
  isExternal: false
  name: Message
  nameWithType: NetTcpSecurityElement.Message
  fullName: System.ServiceModel.Configuration.NetTcpSecurityElement.Message
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetTcpSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetTcpSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.NetTcpSecurityElement
  isExternal: false
  name: Mode
  nameWithType: NetTcpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.NetTcpSecurityElement.Mode
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetTcpSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetTcpSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.NetTcpSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NetTcpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NetTcpSecurityElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetTcpSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetTcpSecurityElement.Transport*
  parent: System.ServiceModel.Configuration.NetTcpSecurityElement
  isExternal: false
  name: Transport
  nameWithType: NetTcpSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.NetTcpSecurityElement.Transport
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetTcpSecurityElement.xml
