### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.WebUtilityElement
  commentId: T:System.Net.Configuration.WebUtilityElement
  id: WebUtilityElement
  children:
  - System.Net.Configuration.WebUtilityElement.#ctor
  - System.Net.Configuration.WebUtilityElement.Properties
  - System.Net.Configuration.WebUtilityElement.UnicodeDecodingConformance
  - System.Net.Configuration.WebUtilityElement.UnicodeEncodingConformance
  langs:
  - csharp
  name: WebUtilityElement
  nameWithType: WebUtilityElement
  fullName: System.Net.Configuration.WebUtilityElement
  type: Class
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Represents the WebUtility element in the configuration file.
  remarks: This class corresponds to the \<webUtility> Element (Network Settings) configuration element. This class provides programmatic access to information that can be stored in configuration files.
  syntax:
    content: 'public sealed class WebUtilityElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/WebUtilityElement.xml
- uid: System.Net.Configuration.WebUtilityElement.#ctor
  commentId: M:System.Net.Configuration.WebUtilityElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.WebUtilityElement
  langs:
  - csharp
  name: WebUtilityElement()
  nameWithType: WebUtilityElement.WebUtilityElement()
  fullName: WebUtilityElement.WebUtilityElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Initializes a new instance of the <xref href="System.Net.Configuration.WebUtilityElement"></xref> class.
  syntax:
    content: public WebUtilityElement ();
    parameters: []
  overload: System.Net.Configuration.WebUtilityElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/WebUtilityElement.xml
- uid: System.Net.Configuration.WebUtilityElement.Properties
  commentId: P:System.Net.Configuration.WebUtilityElement.Properties
  id: Properties
  parent: System.Net.Configuration.WebUtilityElement
  langs:
  - csharp
  name: Properties
  nameWithType: WebUtilityElement.Properties
  fullName: WebUtilityElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Net.Configuration.WebUtilityElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/WebUtilityElement.xml
- uid: System.Net.Configuration.WebUtilityElement.UnicodeDecodingConformance
  commentId: P:System.Net.Configuration.WebUtilityElement.UnicodeDecodingConformance
  id: UnicodeDecodingConformance
  parent: System.Net.Configuration.WebUtilityElement
  langs:
  - csharp
  name: UnicodeDecodingConformance
  nameWithType: WebUtilityElement.UnicodeDecodingConformance
  fullName: WebUtilityElement.UnicodeDecodingConformance
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Gets the default Unicode decoding conformance behavior used for an <xref href="System.Net.WebUtility"></xref> object.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("unicodeDecodingConformance", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.Net.Configuration.UnicodeDecodingConformance UnicodeDecodingConformance { get; set; }
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Returns <xref href=\"System.Net.Configuration.UnicodeDecodingConformance\"></xref>.  \n  \n The default Unicode decoding behavior."
  overload: System.Net.Configuration.WebUtilityElement.UnicodeDecodingConformance*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/WebUtilityElement.xml
- uid: System.Net.Configuration.WebUtilityElement.UnicodeEncodingConformance
  commentId: P:System.Net.Configuration.WebUtilityElement.UnicodeEncodingConformance
  id: UnicodeEncodingConformance
  parent: System.Net.Configuration.WebUtilityElement
  langs:
  - csharp
  name: UnicodeEncodingConformance
  nameWithType: WebUtilityElement.UnicodeEncodingConformance
  fullName: WebUtilityElement.UnicodeEncodingConformance
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Gets the default Unicode encoding conformance behavior used for an <xref href="System.Net.WebUtility"></xref> object.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("unicodeEncodingConformance", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.Net.Configuration.UnicodeEncodingConformance UnicodeEncodingConformance { get; set; }
    return:
      type: System.Net.Configuration.UnicodeEncodingConformance
      description: "Returns <xref href=\"System.Net.Configuration.UnicodeEncodingConformance\"></xref>.  \n  \n The default Unicode encoding behavior."
  overload: System.Net.Configuration.WebUtilityElement.UnicodeEncodingConformance*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/WebUtilityElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.WebUtilityElement.#ctor
  parent: System.Net.Configuration.WebUtilityElement
  isExternal: false
  name: WebUtilityElement()
  nameWithType: WebUtilityElement.WebUtilityElement()
  fullName: WebUtilityElement.WebUtilityElement()
- uid: System.Net.Configuration.WebUtilityElement.Properties
  parent: System.Net.Configuration.WebUtilityElement
  isExternal: false
  name: Properties
  nameWithType: WebUtilityElement.Properties
  fullName: WebUtilityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.WebUtilityElement.UnicodeDecodingConformance
  parent: System.Net.Configuration.WebUtilityElement
  isExternal: false
  name: UnicodeDecodingConformance
  nameWithType: WebUtilityElement.UnicodeDecodingConformance
  fullName: WebUtilityElement.UnicodeDecodingConformance
- uid: System.Net.Configuration.UnicodeDecodingConformance
  parent: System.Net.Configuration
  isExternal: false
  name: UnicodeDecodingConformance
  nameWithType: UnicodeDecodingConformance
  fullName: System.Net.Configuration.UnicodeDecodingConformance
- uid: System.Net.Configuration.WebUtilityElement.UnicodeEncodingConformance
  parent: System.Net.Configuration.WebUtilityElement
  isExternal: false
  name: UnicodeEncodingConformance
  nameWithType: WebUtilityElement.UnicodeEncodingConformance
  fullName: WebUtilityElement.UnicodeEncodingConformance
- uid: System.Net.Configuration.UnicodeEncodingConformance
  parent: System.Net.Configuration
  isExternal: false
  name: UnicodeEncodingConformance
  nameWithType: UnicodeEncodingConformance
  fullName: System.Net.Configuration.UnicodeEncodingConformance
- uid: System.Net.Configuration.WebUtilityElement.#ctor*
  parent: System.Net.Configuration.WebUtilityElement
  isExternal: false
  name: WebUtilityElement
  nameWithType: WebUtilityElement.WebUtilityElement
  fullName: WebUtilityElement.WebUtilityElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/WebUtilityElement.xml
- uid: System.Net.Configuration.WebUtilityElement.Properties*
  parent: System.Net.Configuration.WebUtilityElement
  isExternal: false
  name: Properties
  nameWithType: WebUtilityElement.Properties
  fullName: WebUtilityElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/WebUtilityElement.xml
- uid: System.Net.Configuration.WebUtilityElement.UnicodeDecodingConformance*
  parent: System.Net.Configuration.WebUtilityElement
  isExternal: false
  name: UnicodeDecodingConformance
  nameWithType: WebUtilityElement.UnicodeDecodingConformance
  fullName: WebUtilityElement.UnicodeDecodingConformance
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/WebUtilityElement.xml
- uid: System.Net.Configuration.WebUtilityElement.UnicodeEncodingConformance*
  parent: System.Net.Configuration.WebUtilityElement
  isExternal: false
  name: UnicodeEncodingConformance
  nameWithType: WebUtilityElement.UnicodeEncodingConformance
  fullName: WebUtilityElement.UnicodeEncodingConformance
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/WebUtilityElement.xml
