### YamlMime:ManagedReference
items:
- uid: System.Configuration.ExeContext
  commentId: T:System.Configuration.ExeContext
  id: ExeContext
  children:
  - System.Configuration.ExeContext.ExePath
  - System.Configuration.ExeContext.UserLevel
  langs:
  - csharp
  name: ExeContext
  nameWithType: ExeContext
  fullName: System.Configuration.ExeContext
  type: Class
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Manages the path context for the current application. This class cannot be inherited.
  syntax:
    content: public sealed class ExeContext
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ExeContext.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.ExeContext.ExePath
  commentId: P:System.Configuration.ExeContext.ExePath
  id: ExePath
  parent: System.Configuration.ExeContext
  langs:
  - csharp
  name: ExePath
  nameWithType: ExeContext.ExePath
  fullName: System.Configuration.ExeContext.ExePath
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets the current path for the application.
  syntax:
    content: public string ExePath { get; }
    return:
      type: System.String
      description: A string value containing the current path.
  overload: System.Configuration.ExeContext.ExePath*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ExeContext.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.ExeContext.UserLevel
  commentId: P:System.Configuration.ExeContext.UserLevel
  id: UserLevel
  parent: System.Configuration.ExeContext
  langs:
  - csharp
  name: UserLevel
  nameWithType: ExeContext.UserLevel
  fullName: System.Configuration.ExeContext.UserLevel
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets an object representing the path level of the current application.
  syntax:
    content: public System.Configuration.ConfigurationUserLevel UserLevel { get; }
    return:
      type: System.Configuration.ConfigurationUserLevel
      description: A <xref href="System.Configuration.ConfigurationUserLevel"></xref> object representing the path level of the current application.
  overload: System.Configuration.ExeContext.UserLevel*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ExeContext.xml
  ms.author: riande
  manager: wpickett
references:
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ExeContext.ExePath
  parent: System.Configuration.ExeContext
  isExternal: false
  name: ExePath
  nameWithType: ExeContext.ExePath
  fullName: System.Configuration.ExeContext.ExePath
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ExeContext.UserLevel
  parent: System.Configuration.ExeContext
  isExternal: false
  name: UserLevel
  nameWithType: ExeContext.UserLevel
  fullName: System.Configuration.ExeContext.UserLevel
- uid: System.Configuration.ConfigurationUserLevel
  parent: System.Configuration
  isExternal: false
  name: ConfigurationUserLevel
  nameWithType: ConfigurationUserLevel
  fullName: System.Configuration.ConfigurationUserLevel
- uid: System.Configuration.ExeContext.ExePath*
  parent: System.Configuration.ExeContext
  isExternal: false
  name: ExePath
  nameWithType: ExeContext.ExePath
  fullName: System.Configuration.ExeContext.ExePath
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ExeContext.xml
- uid: System.Configuration.ExeContext.UserLevel*
  parent: System.Configuration.ExeContext
  isExternal: false
  name: UserLevel
  nameWithType: ExeContext.UserLevel
  fullName: System.Configuration.ExeContext.UserLevel
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ExeContext.xml
