### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
  commentId: T:System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
  id: IssuedTokenClientBehaviorsElement
  children:
  - System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.#ctor
  - System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.BehaviorConfiguration
  - System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.IssuerAddress
  - System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.Properties
  langs:
  - csharp
  name: IssuedTokenClientBehaviorsElement
  nameWithType: IssuedTokenClientBehaviorsElement
  fullName: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents the configuration element that specifies the current issued token for a client credential. This class cannot be inherited.
  syntax:
    content: 'public sealed class IssuedTokenClientBehaviorsElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenClientBehaviorsElement.xml
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.#ctor
  commentId: M:System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
  langs:
  - csharp
  name: IssuedTokenClientBehaviorsElement()
  nameWithType: IssuedTokenClientBehaviorsElement.IssuedTokenClientBehaviorsElement()
  fullName: IssuedTokenClientBehaviorsElement.IssuedTokenClientBehaviorsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement"></xref> class.
  syntax:
    content: public IssuedTokenClientBehaviorsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenClientBehaviorsElement.xml
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.BehaviorConfiguration
  commentId: P:System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.BehaviorConfiguration
  id: BehaviorConfiguration
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
  langs:
  - csharp
  name: BehaviorConfiguration
  nameWithType: IssuedTokenClientBehaviorsElement.BehaviorConfiguration
  fullName: IssuedTokenClientBehaviorsElement.BehaviorConfiguration
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the behavior that this configuration applies to.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("behaviorConfiguration", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      [System.Configuration.StringValidator(MinLength=0)]

      public string BehaviorConfiguration { get; set; }
    return:
      type: System.String
      description: The name of the behavior that this configuration applies to. The default is an empty string.
  overload: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.BehaviorConfiguration*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenClientBehaviorsElement.xml
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.IssuerAddress
  commentId: P:System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.IssuerAddress
  id: IssuerAddress
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
  langs:
  - csharp
  name: IssuerAddress
  nameWithType: IssuedTokenClientBehaviorsElement.IssuerAddress
  fullName: IssuedTokenClientBehaviorsElement.IssuerAddress
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the address of the token issuer.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("issuerAddress", DefaultValue=Mono.Cecil.CustomAttributeArgument, Options=System.Configuration.ConfigurationPropertyOptions.IsRequired | System.Configuration.ConfigurationPropertyOptions.IsKey)]

      [System.Configuration.StringValidator(MinLength=0)]

      public string IssuerAddress { get; set; }
    return:
      type: System.String
      description: The address of the token issuer. The default is an empty string.
  overload: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.IssuerAddress*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenClientBehaviorsElement.xml
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.Properties
  commentId: P:System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
  langs:
  - csharp
  name: Properties
  nameWithType: IssuedTokenClientBehaviorsElement.Properties
  fullName: IssuedTokenClientBehaviorsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenClientBehaviorsElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.#ctor
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
  isExternal: false
  name: IssuedTokenClientBehaviorsElement()
  nameWithType: IssuedTokenClientBehaviorsElement.IssuedTokenClientBehaviorsElement()
  fullName: IssuedTokenClientBehaviorsElement.IssuedTokenClientBehaviorsElement()
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.BehaviorConfiguration
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
  isExternal: false
  name: BehaviorConfiguration
  nameWithType: IssuedTokenClientBehaviorsElement.BehaviorConfiguration
  fullName: IssuedTokenClientBehaviorsElement.BehaviorConfiguration
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.IssuerAddress
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
  isExternal: false
  name: IssuerAddress
  nameWithType: IssuedTokenClientBehaviorsElement.IssuerAddress
  fullName: IssuedTokenClientBehaviorsElement.IssuerAddress
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.Properties
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
  isExternal: false
  name: Properties
  nameWithType: IssuedTokenClientBehaviorsElement.Properties
  fullName: IssuedTokenClientBehaviorsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.#ctor*
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
  isExternal: false
  name: IssuedTokenClientBehaviorsElement
  nameWithType: IssuedTokenClientBehaviorsElement.IssuedTokenClientBehaviorsElement
  fullName: IssuedTokenClientBehaviorsElement.IssuedTokenClientBehaviorsElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenClientBehaviorsElement.xml
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.BehaviorConfiguration*
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
  isExternal: false
  name: BehaviorConfiguration
  nameWithType: IssuedTokenClientBehaviorsElement.BehaviorConfiguration
  fullName: IssuedTokenClientBehaviorsElement.BehaviorConfiguration
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenClientBehaviorsElement.xml
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.IssuerAddress*
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
  isExternal: false
  name: IssuerAddress
  nameWithType: IssuedTokenClientBehaviorsElement.IssuerAddress
  fullName: IssuedTokenClientBehaviorsElement.IssuerAddress
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenClientBehaviorsElement.xml
- uid: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement.Properties*
  parent: System.ServiceModel.Configuration.IssuedTokenClientBehaviorsElement
  isExternal: false
  name: Properties
  nameWithType: IssuedTokenClientBehaviorsElement.Properties
  fullName: IssuedTokenClientBehaviorsElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenClientBehaviorsElement.xml
