### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.TrustLevel
  commentId: T:System.Web.Configuration.TrustLevel
  id: TrustLevel
  children:
  - System.Web.Configuration.TrustLevel.#ctor(System.String,System.String)
  - System.Web.Configuration.TrustLevel.Name
  - System.Web.Configuration.TrustLevel.PolicyFile
  - System.Web.Configuration.TrustLevel.Properties
  langs:
  - csharp
  name: TrustLevel
  nameWithType: TrustLevel
  fullName: System.Web.Configuration.TrustLevel
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Defines the mapping of specific security levels to named policy files. This class cannot be inherited.
  remarks: You can extend the security of your Web application by creating your own named <xref:System.Web.Configuration.TrustLevel> object that is mapped to a file specified by the `policyFile` attribute.
  example:
  - "The following code example demonstrates how to use the <xref:System.Web.Configuration.TrustLevel> type.  \n  \n [!code-csharp[System.Web.Configuration.TrustLevel#1](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.TrustLevel/CS/trustlevel.cs#1)]\n [!code-vb[System.Web.Configuration.TrustLevel#1](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.TrustLevel/VB/trustlevel.vb#1)]"
  syntax:
    content: 'public sealed class TrustLevel : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/TrustLevel.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.TrustLevel.#ctor(System.String,System.String)
  commentId: M:System.Web.Configuration.TrustLevel.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.TrustLevel
  langs:
  - csharp
  name: TrustLevel(String, String)
  nameWithType: TrustLevel.TrustLevel(String, String)
  fullName: System.Web.Configuration.TrustLevel.TrustLevel(String, String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Creates an instance of the <xref href="System.Web.Configuration.TrustLevel"></xref> class that is initialized based on the provided values, which define the mapping of specific security levels to named policy files.
  remarks: The <xref:System.Web.Configuration.TrustLevel.%23ctor%2A> constructor creates a <xref:System.Web.Configuration.TrustLevel> object by using the supplied parameters.
  example:
  - "The following code example demonstrates how to use the <xref:System.Web.Configuration.TrustLevel.%23ctor%2A> constructor. This code example is part of a larger example provided for the <xref:System.Web.Configuration.TrustLevel> class.  \n  \n [!code-csharp[System.Web.Configuration.TrustLevel#4](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.TrustLevel/CS/trustlevel.cs#4)]\n [!code-vb[System.Web.Configuration.TrustLevel#4](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.TrustLevel/VB/trustlevel.vb#4)]"
  syntax:
    content: public TrustLevel (string name, string policyFile);
    parameters:
    - id: name
      type: System.String
      description: A named security level that is mapped to a policy file.
    - id: policyFile
      type: System.String
      description: The configuration file that contains security policy settings for the named security level.
  overload: System.Web.Configuration.TrustLevel.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/TrustLevel.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.TrustLevel.Name
  commentId: P:System.Web.Configuration.TrustLevel.Name
  id: Name
  parent: System.Web.Configuration.TrustLevel
  langs:
  - csharp
  name: Name
  nameWithType: TrustLevel.Name
  fullName: System.Web.Configuration.TrustLevel.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets or sets a named security level that is mapped to a policy file.
  remarks: ''
  example:
  - "The following code example demonstrates how to use the <xref:System.Web.Configuration.TrustLevel.Name%2A> property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.TrustLevel> class.  \n  \n [!code-csharp[System.Web.Configuration.TrustLevel#3](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.TrustLevel/CS/trustlevel.cs#3)]\n [!code-vb[System.Web.Configuration.TrustLevel#3](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.TrustLevel/VB/trustlevel.vb#3)]"
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("name", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsKey=true, IsRequired=true)]

      [System.Configuration.StringValidator(MinLength=1)]

      public string Name { get; set; }
    return:
      type: System.String
      description: The <xref href="System.Web.Configuration.TrustLevel.Name"></xref> that is mapped to a policy file.
  overload: System.Web.Configuration.TrustLevel.Name*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/TrustLevel.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.TrustLevel.PolicyFile
  commentId: P:System.Web.Configuration.TrustLevel.PolicyFile
  id: PolicyFile
  parent: System.Web.Configuration.TrustLevel
  langs:
  - csharp
  name: PolicyFile
  nameWithType: TrustLevel.PolicyFile
  fullName: System.Web.Configuration.TrustLevel.PolicyFile
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets or sets the configuration file reference that contains the security policy settings for the named security level.
  remarks: ''
  example:
  - "The following code example demonstrates how to use the <xref:System.Web.Configuration.TrustLevel.PolicyFile%2A> property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.TrustLevel> class.  \n  \n [!code-csharp[System.Web.Configuration.TrustLevel#5](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.TrustLevel/CS/trustlevel.cs#5)]\n [!code-vb[System.Web.Configuration.TrustLevel#5](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.TrustLevel/VB/trustlevel.vb#5)]"
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("policyFile", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsRequired=true)]

      public string PolicyFile { get; set; }
    return:
      type: System.String
      description: The configuration file reference that contains the security policy settings for the associated security level.
  overload: System.Web.Configuration.TrustLevel.PolicyFile*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/TrustLevel.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.TrustLevel.Properties
  commentId: P:System.Web.Configuration.TrustLevel.Properties
  id: Properties
  parent: System.Web.Configuration.TrustLevel
  langs:
  - csharp
  name: Properties
  nameWithType: TrustLevel.Properties
  fullName: System.Web.Configuration.TrustLevel.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.TrustLevel.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/TrustLevel.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.TrustLevel.#ctor(System.String,System.String)
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: TrustLevel(String, String)
  nameWithType: TrustLevel.TrustLevel(String, String)
  fullName: System.Web.Configuration.TrustLevel.TrustLevel(String, String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.TrustLevel.Name
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: Name
  nameWithType: TrustLevel.Name
  fullName: System.Web.Configuration.TrustLevel.Name
- uid: System.Web.Configuration.TrustLevel.PolicyFile
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: PolicyFile
  nameWithType: TrustLevel.PolicyFile
  fullName: System.Web.Configuration.TrustLevel.PolicyFile
- uid: System.Web.Configuration.TrustLevel.Properties
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: Properties
  nameWithType: TrustLevel.Properties
  fullName: System.Web.Configuration.TrustLevel.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.TrustLevel.#ctor*
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: TrustLevel
  nameWithType: TrustLevel.TrustLevel
  fullName: System.Web.Configuration.TrustLevel.TrustLevel
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/TrustLevel.xml
- uid: System.Web.Configuration.TrustLevel.Name*
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: Name
  nameWithType: TrustLevel.Name
  fullName: System.Web.Configuration.TrustLevel.Name
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/TrustLevel.xml
- uid: System.Web.Configuration.TrustLevel.PolicyFile*
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: PolicyFile
  nameWithType: TrustLevel.PolicyFile
  fullName: System.Web.Configuration.TrustLevel.PolicyFile
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/TrustLevel.xml
- uid: System.Web.Configuration.TrustLevel.Properties*
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: Properties
  nameWithType: TrustLevel.Properties
  fullName: System.Web.Configuration.TrustLevel.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/TrustLevel.xml
