### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.HostTimeoutsElement
  commentId: T:System.ServiceModel.Configuration.HostTimeoutsElement
  id: HostTimeoutsElement
  children:
  - System.ServiceModel.Configuration.HostTimeoutsElement.#ctor
  - System.ServiceModel.Configuration.HostTimeoutsElement.CloseTimeout
  - System.ServiceModel.Configuration.HostTimeoutsElement.OpenTimeout
  - System.ServiceModel.Configuration.HostTimeoutsElement.Properties
  langs:
  - csharp
  name: HostTimeoutsElement
  nameWithType: HostTimeoutsElement
  fullName: System.ServiceModel.Configuration.HostTimeoutsElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a configuration element that specifies the interval of time allowed for the service host to open or close. This class cannot be inherited.
  syntax:
    content: 'public sealed class HostTimeoutsElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostTimeoutsElement.xml
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.#ctor
  commentId: M:System.ServiceModel.Configuration.HostTimeoutsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  langs:
  - csharp
  name: HostTimeoutsElement()
  nameWithType: HostTimeoutsElement.HostTimeoutsElement()
  fullName: HostTimeoutsElement.HostTimeoutsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.HostTimeoutsElement"></xref> class.
  syntax:
    content: public HostTimeoutsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.HostTimeoutsElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostTimeoutsElement.xml
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.CloseTimeout
  commentId: P:System.ServiceModel.Configuration.HostTimeoutsElement.CloseTimeout
  id: CloseTimeout
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  langs:
  - csharp
  name: CloseTimeout
  nameWithType: HostTimeoutsElement.CloseTimeout
  fullName: HostTimeoutsElement.CloseTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the interval of time allowed for the service host to close.
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(System.ServiceModel.Configuration.TimeSpanOrInfiniteConverter))]

      [System.Configuration.ConfigurationProperty("closeTimeout", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public TimeSpan CloseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: The <xref href="System.TimeSpan"></xref> that specifies the interval of time allowed for the service host to close
  overload: System.ServiceModel.Configuration.HostTimeoutsElement.CloseTimeout*
  exceptions: []
  attributes:
  - type: System.ComponentModel.TypeConverterAttribute
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostTimeoutsElement.xml
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.OpenTimeout
  commentId: P:System.ServiceModel.Configuration.HostTimeoutsElement.OpenTimeout
  id: OpenTimeout
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  langs:
  - csharp
  name: OpenTimeout
  nameWithType: HostTimeoutsElement.OpenTimeout
  fullName: HostTimeoutsElement.OpenTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the interval of time allowed for the service host to open.
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(System.ServiceModel.Configuration.TimeSpanOrInfiniteConverter))]

      [System.Configuration.ConfigurationProperty("openTimeout", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public TimeSpan OpenTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: The <xref href="System.TimeSpan"></xref> that specifies the interval of time allowed for the service host to open.
  overload: System.ServiceModel.Configuration.HostTimeoutsElement.OpenTimeout*
  exceptions: []
  attributes:
  - type: System.ComponentModel.TypeConverterAttribute
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostTimeoutsElement.xml
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.Properties
  commentId: P:System.ServiceModel.Configuration.HostTimeoutsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  langs:
  - csharp
  name: Properties
  nameWithType: HostTimeoutsElement.Properties
  fullName: HostTimeoutsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.HostTimeoutsElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostTimeoutsElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.#ctor
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  isExternal: false
  name: HostTimeoutsElement()
  nameWithType: HostTimeoutsElement.HostTimeoutsElement()
  fullName: HostTimeoutsElement.HostTimeoutsElement()
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.CloseTimeout
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  isExternal: false
  name: CloseTimeout
  nameWithType: HostTimeoutsElement.CloseTimeout
  fullName: HostTimeoutsElement.CloseTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: false
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.OpenTimeout
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  isExternal: false
  name: OpenTimeout
  nameWithType: HostTimeoutsElement.OpenTimeout
  fullName: HostTimeoutsElement.OpenTimeout
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.Properties
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  isExternal: false
  name: Properties
  nameWithType: HostTimeoutsElement.Properties
  fullName: HostTimeoutsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.#ctor*
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  isExternal: false
  name: HostTimeoutsElement
  nameWithType: HostTimeoutsElement.HostTimeoutsElement
  fullName: HostTimeoutsElement.HostTimeoutsElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostTimeoutsElement.xml
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.CloseTimeout*
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  isExternal: false
  name: CloseTimeout
  nameWithType: HostTimeoutsElement.CloseTimeout
  fullName: HostTimeoutsElement.CloseTimeout
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostTimeoutsElement.xml
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.OpenTimeout*
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  isExternal: false
  name: OpenTimeout
  nameWithType: HostTimeoutsElement.OpenTimeout
  fullName: HostTimeoutsElement.OpenTimeout
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostTimeoutsElement.xml
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.Properties*
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  isExternal: false
  name: Properties
  nameWithType: HostTimeoutsElement.Properties
  fullName: HostTimeoutsElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostTimeoutsElement.xml
