### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement
  commentId: T:System.IdentityModel.Configuration.TokenReplayDetectionElement
  id: TokenReplayDetectionElement
  children:
  - System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor
  - System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
  - System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
  - System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
  langs:
  - csharp
  name: TokenReplayDetectionElement
  nameWithType: TokenReplayDetectionElement
  fullName: System.IdentityModel.Configuration.TokenReplayDetectionElement
  type: Class
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: Represents a `<tokenReplayDetection>` element in a configuration file. This class cannot be inherited.
  remarks: "The `<tokenReplayDetection>` element allows you to enable the detection logic for token replays. When enabled, WIF caches the security tokens that were received for the authentication and uses the cache for replay detection. A token remains in the cache until the expiration period specified by the <xref:System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod%2A> property expires.  \n  \n The token replay cache that WIF uses is specified by the `<caches>` element, which is represented by the <xref:System.IdentityModel.Configuration.TokenReplayDetectionElement> class. The token replay cache is configured through the <xref:System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache%2A> property."
  syntax:
    content: 'public sealed class TokenReplayDetectionElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/TokenReplayDetectionElement.xml
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor
  commentId: M:System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  langs:
  - csharp
  name: TokenReplayDetectionElement()
  nameWithType: TokenReplayDetectionElement.TokenReplayDetectionElement()
  fullName: TokenReplayDetectionElement.TokenReplayDetectionElement()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: Initializes a new instance of the <xref href="System.IdentityModel.Configuration.TokenReplayDetectionElement"></xref> class
  syntax:
    content: public TokenReplayDetectionElement ();
    parameters: []
  overload: System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/TokenReplayDetectionElement.xml
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
  commentId: P:System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
  id: Enabled
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  langs:
  - csharp
  name: Enabled
  nameWithType: TokenReplayDetectionElement.Enabled
  fullName: TokenReplayDetectionElement.Enabled
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: Gets or sets a value that indicates if replay detection should be performed.
  remarks: This property is optional. It represents the `enabled` attribute of the `<tokenReplayDetection>` element.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("enabled", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsRequired=false)]

      public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: '`true` to perform replay detection; otherwise, `false`.'
  overload: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/TokenReplayDetectionElement.xml
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
  commentId: P:System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
  id: ExpirationPeriod
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  langs:
  - csharp
  name: ExpirationPeriod
  nameWithType: TokenReplayDetectionElement.ExpirationPeriod
  fullName: TokenReplayDetectionElement.ExpirationPeriod
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: Gets or sets the maximum amount of time before an item is considered expired and removed from the cache.
  remarks: This property is optional. It represents the `expirationPeriod` attribute of the `<tokenReplayDetection>` element.
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(System.IdentityModel.Configuration.TimeSpanOrInfiniteConverter))]

      [System.Configuration.ConfigurationProperty("expirationPeriod", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsRequired=false)]

      public TimeSpan ExpirationPeriod { get; set; }
    return:
      type: System.TimeSpan
      description: The maximum amount of time before an item is considered expired and removed from the cache.
  overload: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod*
  exceptions: []
  attributes:
  - type: System.ComponentModel.TypeConverterAttribute
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/TokenReplayDetectionElement.xml
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
  commentId: P:System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  langs:
  - csharp
  name: Properties
  nameWithType: TokenReplayDetectionElement.Properties
  fullName: TokenReplayDetectionElement.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/TokenReplayDetectionElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: TokenReplayDetectionElement()
  nameWithType: TokenReplayDetectionElement.TokenReplayDetectionElement()
  fullName: TokenReplayDetectionElement.TokenReplayDetectionElement()
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: Enabled
  nameWithType: TokenReplayDetectionElement.Enabled
  fullName: TokenReplayDetectionElement.Enabled
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: ExpirationPeriod
  nameWithType: TokenReplayDetectionElement.ExpirationPeriod
  fullName: TokenReplayDetectionElement.ExpirationPeriod
- uid: System.TimeSpan
  parent: System
  isExternal: false
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: Properties
  nameWithType: TokenReplayDetectionElement.Properties
  fullName: TokenReplayDetectionElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.#ctor*
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: TokenReplayDetectionElement
  nameWithType: TokenReplayDetectionElement.TokenReplayDetectionElement
  fullName: TokenReplayDetectionElement.TokenReplayDetectionElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/TokenReplayDetectionElement.xml
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Enabled*
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: Enabled
  nameWithType: TokenReplayDetectionElement.Enabled
  fullName: TokenReplayDetectionElement.Enabled
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/TokenReplayDetectionElement.xml
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.ExpirationPeriod*
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: ExpirationPeriod
  nameWithType: TokenReplayDetectionElement.ExpirationPeriod
  fullName: TokenReplayDetectionElement.ExpirationPeriod
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/TokenReplayDetectionElement.xml
- uid: System.IdentityModel.Configuration.TokenReplayDetectionElement.Properties*
  parent: System.IdentityModel.Configuration.TokenReplayDetectionElement
  isExternal: false
  name: Properties
  nameWithType: TokenReplayDetectionElement.Properties
  fullName: TokenReplayDetectionElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/TokenReplayDetectionElement.xml
