### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  commentId: T:System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  id: NamedPipeTransportSecurityElement
  children:
  - System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.#ctor
  - System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.Properties
  - System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.ProtectionLevel
  langs:
  - csharp
  name: NamedPipeTransportSecurityElement
  nameWithType: NamedPipeTransportSecurityElement
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Specifies the transport security for a named pipe. This class cannot be inherited.
  syntax:
    content: 'public sealed class NamedPipeTransportSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NamedPipeTransportSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.#ctor
  commentId: M:System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  langs:
  - csharp
  name: NamedPipeTransportSecurityElement()
  nameWithType: NamedPipeTransportSecurityElement.NamedPipeTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.NamedPipeTransportSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.NamedPipeTransportSecurityElement"></xref> class.
  syntax:
    content: public NamedPipeTransportSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NamedPipeTransportSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.Properties
  commentId: P:System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: NamedPipeTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NamedPipeTransportSecurityElement.xml
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.ProtectionLevel
  commentId: P:System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.ProtectionLevel
  id: ProtectionLevel
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  langs:
  - csharp
  name: ProtectionLevel
  nameWithType: NamedPipeTransportSecurityElement.ProtectionLevel
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.ProtectionLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Specifies the protection for this named pipe.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("protectionLevel", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.Net.Security.ProtectionLevel ProtectionLevel { get; set; }
    return:
      type: System.Net.Security.ProtectionLevel
      description: A <xref href="System.Net.Security.ProtectionLevel"></xref>. The default is <xref href="System.Net.Security.ProtectionLevel.EncryptAndSign"></xref>.
  overload: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.ProtectionLevel*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NamedPipeTransportSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  isExternal: false
  name: NamedPipeTransportSecurityElement()
  nameWithType: NamedPipeTransportSecurityElement.NamedPipeTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.NamedPipeTransportSecurityElement()
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.Properties
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NamedPipeTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.ProtectionLevel
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  isExternal: false
  name: ProtectionLevel
  nameWithType: NamedPipeTransportSecurityElement.ProtectionLevel
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.ProtectionLevel
- uid: System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  isExternal: false
  name: NamedPipeTransportSecurityElement
  nameWithType: NamedPipeTransportSecurityElement.NamedPipeTransportSecurityElement
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.NamedPipeTransportSecurityElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NamedPipeTransportSecurityElement.xml
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NamedPipeTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NamedPipeTransportSecurityElement.xml
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.ProtectionLevel*
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  isExternal: false
  name: ProtectionLevel
  nameWithType: NamedPipeTransportSecurityElement.ProtectionLevel
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.ProtectionLevel
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NamedPipeTransportSecurityElement.xml
