### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.HostElement
  commentId: T:System.ServiceModel.Configuration.HostElement
  id: HostElement
  children:
  - System.ServiceModel.Configuration.HostElement.#ctor
  - System.ServiceModel.Configuration.HostElement.BaseAddresses
  - System.ServiceModel.Configuration.HostElement.Properties
  - System.ServiceModel.Configuration.HostElement.Timeouts
  langs:
  - csharp
  name: HostElement
  nameWithType: HostElement
  fullName: System.ServiceModel.Configuration.HostElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a configuration element that specifies settings for a service host. This class cannot be inherited.
  syntax:
    content: 'public sealed class HostElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostElement.xml
- uid: System.ServiceModel.Configuration.HostElement.#ctor
  commentId: M:System.ServiceModel.Configuration.HostElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.HostElement
  langs:
  - csharp
  name: HostElement()
  nameWithType: HostElement.HostElement()
  fullName: HostElement.HostElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.HostElement"></xref> class.
  syntax:
    content: public HostElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.HostElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostElement.xml
- uid: System.ServiceModel.Configuration.HostElement.BaseAddresses
  commentId: P:System.ServiceModel.Configuration.HostElement.BaseAddresses
  id: BaseAddresses
  parent: System.ServiceModel.Configuration.HostElement
  langs:
  - csharp
  name: BaseAddresses
  nameWithType: HostElement.BaseAddresses
  fullName: HostElement.BaseAddresses
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets the base addresses used by the service host.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("baseAddresses", Options=System.Configuration.ConfigurationPropertyOptions.None)]

      public System.ServiceModel.Configuration.BaseAddressElementCollection BaseAddresses { get; }
    return:
      type: System.ServiceModel.Configuration.BaseAddressElementCollection
      description: A collection of base addresses.
  overload: System.ServiceModel.Configuration.HostElement.BaseAddresses*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostElement.xml
- uid: System.ServiceModel.Configuration.HostElement.Properties
  commentId: P:System.ServiceModel.Configuration.HostElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.HostElement
  langs:
  - csharp
  name: Properties
  nameWithType: HostElement.Properties
  fullName: HostElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.HostElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostElement.xml
- uid: System.ServiceModel.Configuration.HostElement.Timeouts
  commentId: P:System.ServiceModel.Configuration.HostElement.Timeouts
  id: Timeouts
  parent: System.ServiceModel.Configuration.HostElement
  langs:
  - csharp
  name: Timeouts
  nameWithType: HostElement.Timeouts
  fullName: HostElement.Timeouts
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets a configuration element that specifies the interval of time allowed for the service host to open or close.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("timeouts", Options=System.Configuration.ConfigurationPropertyOptions.None)]

      public System.ServiceModel.Configuration.HostTimeoutsElement Timeouts { get; }
    return:
      type: System.ServiceModel.Configuration.HostTimeoutsElement
      description: A configuration element that specifies the interval of time allowed for the service host to open or close.
  overload: System.ServiceModel.Configuration.HostElement.Timeouts*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.HostElement.#ctor
  parent: System.ServiceModel.Configuration.HostElement
  isExternal: false
  name: HostElement()
  nameWithType: HostElement.HostElement()
  fullName: HostElement.HostElement()
- uid: System.ServiceModel.Configuration.HostElement.BaseAddresses
  parent: System.ServiceModel.Configuration.HostElement
  isExternal: false
  name: BaseAddresses
  nameWithType: HostElement.BaseAddresses
  fullName: HostElement.BaseAddresses
- uid: System.ServiceModel.Configuration.BaseAddressElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: BaseAddressElementCollection
  nameWithType: BaseAddressElementCollection
  fullName: System.ServiceModel.Configuration.BaseAddressElementCollection
- uid: System.ServiceModel.Configuration.HostElement.Properties
  parent: System.ServiceModel.Configuration.HostElement
  isExternal: false
  name: Properties
  nameWithType: HostElement.Properties
  fullName: HostElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.HostElement.Timeouts
  parent: System.ServiceModel.Configuration.HostElement
  isExternal: false
  name: Timeouts
  nameWithType: HostElement.Timeouts
  fullName: HostElement.Timeouts
- uid: System.ServiceModel.Configuration.HostTimeoutsElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: HostTimeoutsElement
  nameWithType: HostTimeoutsElement
  fullName: System.ServiceModel.Configuration.HostTimeoutsElement
- uid: System.ServiceModel.Configuration.HostElement.#ctor*
  parent: System.ServiceModel.Configuration.HostElement
  isExternal: false
  name: HostElement
  nameWithType: HostElement.HostElement
  fullName: HostElement.HostElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostElement.xml
- uid: System.ServiceModel.Configuration.HostElement.BaseAddresses*
  parent: System.ServiceModel.Configuration.HostElement
  isExternal: false
  name: BaseAddresses
  nameWithType: HostElement.BaseAddresses
  fullName: HostElement.BaseAddresses
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostElement.xml
- uid: System.ServiceModel.Configuration.HostElement.Properties*
  parent: System.ServiceModel.Configuration.HostElement
  isExternal: false
  name: Properties
  nameWithType: HostElement.Properties
  fullName: HostElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostElement.xml
- uid: System.ServiceModel.Configuration.HostElement.Timeouts*
  parent: System.ServiceModel.Configuration.HostElement
  isExternal: false
  name: Timeouts
  nameWithType: HostElement.Timeouts
  fullName: HostElement.Timeouts
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HostElement.xml
