### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.UseManagedPresentationElement
  commentId: T:System.ServiceModel.Configuration.UseManagedPresentationElement
  id: UseManagedPresentationElement
  children:
  - System.ServiceModel.Configuration.UseManagedPresentationElement.#ctor
  - System.ServiceModel.Configuration.UseManagedPresentationElement.BindingElementType
  - System.ServiceModel.Configuration.UseManagedPresentationElement.CreateBindingElement
  langs:
  - csharp
  name: UseManagedPresentationElement
  nameWithType: UseManagedPresentationElement
  fullName: System.ServiceModel.Configuration.UseManagedPresentationElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a binding element that manages presentation.
  syntax:
    content: 'public class UseManagedPresentationElement : System.ServiceModel.Configuration.BindingElementExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BindingElementExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.BindingElementExtensionElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  - System.ServiceModel.Configuration.BindingElementExtensionElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/UseManagedPresentationElement.xml
- uid: System.ServiceModel.Configuration.UseManagedPresentationElement.#ctor
  commentId: M:System.ServiceModel.Configuration.UseManagedPresentationElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.UseManagedPresentationElement
  langs:
  - csharp
  name: UseManagedPresentationElement()
  nameWithType: UseManagedPresentationElement.UseManagedPresentationElement()
  fullName: UseManagedPresentationElement.UseManagedPresentationElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.UseManagedPresentationElement"></xref> class.
  syntax:
    content: public UseManagedPresentationElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.UseManagedPresentationElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/UseManagedPresentationElement.xml
- uid: System.ServiceModel.Configuration.UseManagedPresentationElement.BindingElementType
  commentId: P:System.ServiceModel.Configuration.UseManagedPresentationElement.BindingElementType
  id: BindingElementType
  parent: System.ServiceModel.Configuration.UseManagedPresentationElement
  langs:
  - csharp
  name: BindingElementType
  nameWithType: UseManagedPresentationElement.BindingElementType
  fullName: UseManagedPresentationElement.BindingElementType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets the <xref href="System.Type"></xref> object that represents the binding element.
  syntax:
    content: public override Type BindingElementType { get; }
    return:
      type: System.Type
      description: A <xref href="System.Type"></xref> object that represents the binding element.
  overload: System.ServiceModel.Configuration.UseManagedPresentationElement.BindingElementType*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/UseManagedPresentationElement.xml
- uid: System.ServiceModel.Configuration.UseManagedPresentationElement.CreateBindingElement
  commentId: M:System.ServiceModel.Configuration.UseManagedPresentationElement.CreateBindingElement
  id: CreateBindingElement
  parent: System.ServiceModel.Configuration.UseManagedPresentationElement
  langs:
  - csharp
  name: CreateBindingElement()
  nameWithType: UseManagedPresentationElement.CreateBindingElement()
  fullName: UseManagedPresentationElement.CreateBindingElement()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Creates a new custom binding element object whose properties are copied from the settings of this configuration element.
  syntax:
    content: protected override System.ServiceModel.Channels.BindingElement CreateBindingElement ();
    parameters: []
    return:
      type: System.ServiceModel.Channels.BindingElement
      description: A custom <xref href="System.ServiceModel.Channels.BindingElement"></xref> object.
  overload: System.ServiceModel.Configuration.UseManagedPresentationElement.CreateBindingElement*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/UseManagedPresentationElement.xml
references:
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: BindingElementExtensionElement
  nameWithType: BindingElementExtensionElement
  fullName: System.ServiceModel.Configuration.BindingElementExtensionElement
- uid: System.ServiceModel.Configuration.UseManagedPresentationElement.#ctor
  parent: System.ServiceModel.Configuration.UseManagedPresentationElement
  isExternal: false
  name: UseManagedPresentationElement()
  nameWithType: UseManagedPresentationElement.UseManagedPresentationElement()
  fullName: UseManagedPresentationElement.UseManagedPresentationElement()
- uid: System.ServiceModel.Configuration.UseManagedPresentationElement.BindingElementType
  parent: System.ServiceModel.Configuration.UseManagedPresentationElement
  isExternal: false
  name: BindingElementType
  nameWithType: UseManagedPresentationElement.BindingElementType
  fullName: UseManagedPresentationElement.BindingElementType
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.UseManagedPresentationElement.CreateBindingElement
  parent: System.ServiceModel.Configuration.UseManagedPresentationElement
  isExternal: false
  name: CreateBindingElement()
  nameWithType: UseManagedPresentationElement.CreateBindingElement()
  fullName: UseManagedPresentationElement.CreateBindingElement()
- uid: System.ServiceModel.Channels.BindingElement
  parent: System.ServiceModel.Channels
  isExternal: false
  name: BindingElement
  nameWithType: BindingElement
  fullName: System.ServiceModel.Channels.BindingElement
- uid: System.ServiceModel.Configuration.UseManagedPresentationElement.#ctor*
  parent: System.ServiceModel.Configuration.UseManagedPresentationElement
  isExternal: false
  name: UseManagedPresentationElement
  nameWithType: UseManagedPresentationElement.UseManagedPresentationElement
  fullName: UseManagedPresentationElement.UseManagedPresentationElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/UseManagedPresentationElement.xml
- uid: System.ServiceModel.Configuration.UseManagedPresentationElement.BindingElementType*
  parent: System.ServiceModel.Configuration.UseManagedPresentationElement
  isExternal: false
  name: BindingElementType
  nameWithType: UseManagedPresentationElement.BindingElementType
  fullName: UseManagedPresentationElement.BindingElementType
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/UseManagedPresentationElement.xml
- uid: System.ServiceModel.Configuration.UseManagedPresentationElement.CreateBindingElement*
  parent: System.ServiceModel.Configuration.UseManagedPresentationElement
  isExternal: false
  name: CreateBindingElement
  nameWithType: UseManagedPresentationElement.CreateBindingElement
  fullName: UseManagedPresentationElement.CreateBindingElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/UseManagedPresentationElement.xml
