### YamlMime:ManagedReference
items:
- uid: System.Configuration.DictionarySectionHandler
  commentId: T:System.Configuration.DictionarySectionHandler
  id: DictionarySectionHandler
  children:
  - System.Configuration.DictionarySectionHandler.#ctor
  - System.Configuration.DictionarySectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  - System.Configuration.DictionarySectionHandler.KeyAttributeName
  - System.Configuration.DictionarySectionHandler.ValueAttributeName
  langs:
  - csharp
  name: DictionarySectionHandler
  nameWithType: DictionarySectionHandler
  fullName: System.Configuration.DictionarySectionHandler
  type: Class
  assemblies:
  - System
  namespace: System.Configuration
  summary: Provides key/value pair configuration information from a configuration section.
  remarks: This class implements the `IConfigSectionHandler` interface. The <xref:System.Configuration.DictionarySectionHandler> defines rules for manipulating XML configuration sections.
  syntax:
    content: 'public class DictionarySectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/DictionarySectionHandler.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.DictionarySectionHandler.#ctor
  commentId: M:System.Configuration.DictionarySectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: DictionarySectionHandler()
  nameWithType: DictionarySectionHandler.DictionarySectionHandler()
  fullName: System.Configuration.DictionarySectionHandler.DictionarySectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.DictionarySectionHandler"></xref> class.
  syntax:
    content: public DictionarySectionHandler ();
    parameters: []
  overload: System.Configuration.DictionarySectionHandler.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/DictionarySectionHandler.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.DictionarySectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  commentId: M:System.Configuration.DictionarySectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: Create(Object, Object, XmlNode)
  nameWithType: DictionarySectionHandler.Create(Object, Object, XmlNode)
  fullName: System.Configuration.DictionarySectionHandler.Create(Object, Object, XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: Creates a new configuration handler and adds it to the section-handler collection based on the specified parameters.
  remarks: The `parent` object parameter acts as the configuration settings in the corresponding parent configuration section. The `context` object parameter is the virtual path for which the configuration section handler computes configuration values. Normally this parameter is reserved and is `null`.  The `section` parameter is the <xref:System.Xml.XmlNode> that contains the configuration information to be handled. The `section` parameter provides direct access to the XML contents of the configuration section.
  syntax:
    content: public virtual object Create (object parent, object context, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: Parent object.
    - id: context
      type: System.Object
      description: Configuration context object.
    - id: section
      type: System.Xml.XmlNode
      description: Section XML node.
    return:
      type: System.Object
      description: A configuration object.
  overload: System.Configuration.DictionarySectionHandler.Create*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/DictionarySectionHandler.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.DictionarySectionHandler.KeyAttributeName
  commentId: P:System.Configuration.DictionarySectionHandler.KeyAttributeName
  id: KeyAttributeName
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: KeyAttributeName
  nameWithType: DictionarySectionHandler.KeyAttributeName
  fullName: System.Configuration.DictionarySectionHandler.KeyAttributeName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: Gets the XML attribute name to use as the key in a key/value pair.
  syntax:
    content: protected virtual string KeyAttributeName { get; }
    return:
      type: System.String
      description: A string value containing the name of the key attribute.
  overload: System.Configuration.DictionarySectionHandler.KeyAttributeName*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/DictionarySectionHandler.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.DictionarySectionHandler.ValueAttributeName
  commentId: P:System.Configuration.DictionarySectionHandler.ValueAttributeName
  id: ValueAttributeName
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: ValueAttributeName
  nameWithType: DictionarySectionHandler.ValueAttributeName
  fullName: System.Configuration.DictionarySectionHandler.ValueAttributeName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: Gets the XML attribute name to use as the value in a key/value pair.
  syntax:
    content: protected virtual string ValueAttributeName { get; }
    return:
      type: System.String
      description: A string value containing the name of the value attribute.
  overload: System.Configuration.DictionarySectionHandler.ValueAttributeName*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/DictionarySectionHandler.xml
  ms.author: riande
  manager: wpickett
references:
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.DictionarySectionHandler.#ctor
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: DictionarySectionHandler()
  nameWithType: DictionarySectionHandler.DictionarySectionHandler()
  fullName: System.Configuration.DictionarySectionHandler.DictionarySectionHandler()
- uid: System.Configuration.DictionarySectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: Create(Object, Object, XmlNode)
  nameWithType: DictionarySectionHandler.Create(Object, Object, XmlNode)
  fullName: System.Configuration.DictionarySectionHandler.Create(Object, Object, XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.DictionarySectionHandler.KeyAttributeName
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: KeyAttributeName
  nameWithType: DictionarySectionHandler.KeyAttributeName
  fullName: System.Configuration.DictionarySectionHandler.KeyAttributeName
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.DictionarySectionHandler.ValueAttributeName
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: ValueAttributeName
  nameWithType: DictionarySectionHandler.ValueAttributeName
  fullName: System.Configuration.DictionarySectionHandler.ValueAttributeName
- uid: System.Configuration.DictionarySectionHandler.#ctor*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: DictionarySectionHandler
  nameWithType: DictionarySectionHandler.DictionarySectionHandler
  fullName: System.Configuration.DictionarySectionHandler.DictionarySectionHandler
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/DictionarySectionHandler.xml
- uid: System.Configuration.DictionarySectionHandler.Create*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: Create
  nameWithType: DictionarySectionHandler.Create
  fullName: System.Configuration.DictionarySectionHandler.Create
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/DictionarySectionHandler.xml
- uid: System.Configuration.DictionarySectionHandler.KeyAttributeName*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: KeyAttributeName
  nameWithType: DictionarySectionHandler.KeyAttributeName
  fullName: System.Configuration.DictionarySectionHandler.KeyAttributeName
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/DictionarySectionHandler.xml
- uid: System.Configuration.DictionarySectionHandler.ValueAttributeName*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: ValueAttributeName
  nameWithType: DictionarySectionHandler.ValueAttributeName
  fullName: System.Configuration.DictionarySectionHandler.ValueAttributeName
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/DictionarySectionHandler.xml
