### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  commentId: T:System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  id: WorkflowUnhandledExceptionElement
  children:
  - System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.#ctor
  - System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.Action
  - System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.BehaviorType
  - System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.CreateBehavior
  - System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.Properties
  langs:
  - csharp
  name: WorkflowUnhandledExceptionElement
  nameWithType: WorkflowUnhandledExceptionElement
  fullName: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  type: Class
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: Handles the properties of an unhandled exception that occurs during a workflow service operation.  This is a sealed class.
  syntax:
    content: 'public sealed class WorkflowUnhandledExceptionElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/WorkflowUnhandledExceptionElement.xml
- uid: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.#ctor
  commentId: M:System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  langs:
  - csharp
  name: WorkflowUnhandledExceptionElement()
  nameWithType: WorkflowUnhandledExceptionElement.WorkflowUnhandledExceptionElement()
  fullName: WorkflowUnhandledExceptionElement.WorkflowUnhandledExceptionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: Creates a new instance of the <xref href="System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement"></xref> class.
  syntax:
    content: public WorkflowUnhandledExceptionElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/WorkflowUnhandledExceptionElement.xml
- uid: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.Action
  commentId: P:System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.Action
  id: Action
  parent: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  langs:
  - csharp
  name: Action
  nameWithType: WorkflowUnhandledExceptionElement.Action
  fullName: WorkflowUnhandledExceptionElement.Action
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: Gets or sets the process that is invoked when the unhandled exception occurs.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("action", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction Action { get; set; }
    return:
      type: System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction
      description: An action.
  overload: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.Action*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/WorkflowUnhandledExceptionElement.xml
- uid: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.BehaviorType
  commentId: P:System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: WorkflowUnhandledExceptionElement.BehaviorType
  fullName: WorkflowUnhandledExceptionElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: Gets the type of the unhandled exception behavior.
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: A type object.
  overload: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.BehaviorType*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/WorkflowUnhandledExceptionElement.xml
- uid: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.CreateBehavior
  commentId: M:System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: WorkflowUnhandledExceptionElement.CreateBehavior()
  fullName: WorkflowUnhandledExceptionElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: To be added.
  overload: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.CreateBehavior*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/WorkflowUnhandledExceptionElement.xml
- uid: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.Properties
  commentId: P:System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  langs:
  - csharp
  name: Properties
  nameWithType: WorkflowUnhandledExceptionElement.Properties
  fullName: WorkflowUnhandledExceptionElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/WorkflowUnhandledExceptionElement.xml
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: BehaviorExtensionElement
  nameWithType: BehaviorExtensionElement
  fullName: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.#ctor
  parent: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  isExternal: false
  name: WorkflowUnhandledExceptionElement()
  nameWithType: WorkflowUnhandledExceptionElement.WorkflowUnhandledExceptionElement()
  fullName: WorkflowUnhandledExceptionElement.WorkflowUnhandledExceptionElement()
- uid: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.Action
  parent: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  isExternal: false
  name: Action
  nameWithType: WorkflowUnhandledExceptionElement.Action
  fullName: WorkflowUnhandledExceptionElement.Action
- uid: System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction
  parent: System.ServiceModel.Activities.Description
  isExternal: false
  name: WorkflowUnhandledExceptionAction
  nameWithType: WorkflowUnhandledExceptionAction
  fullName: System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction
- uid: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.BehaviorType
  parent: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  isExternal: false
  name: BehaviorType
  nameWithType: WorkflowUnhandledExceptionElement.BehaviorType
  fullName: WorkflowUnhandledExceptionElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.CreateBehavior
  parent: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: WorkflowUnhandledExceptionElement.CreateBehavior()
  fullName: WorkflowUnhandledExceptionElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.Properties
  parent: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  isExternal: false
  name: Properties
  nameWithType: WorkflowUnhandledExceptionElement.Properties
  fullName: WorkflowUnhandledExceptionElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.#ctor*
  parent: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  isExternal: false
  name: WorkflowUnhandledExceptionElement
  nameWithType: WorkflowUnhandledExceptionElement.WorkflowUnhandledExceptionElement
  fullName: WorkflowUnhandledExceptionElement.WorkflowUnhandledExceptionElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/WorkflowUnhandledExceptionElement.xml
- uid: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.Action*
  parent: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  isExternal: false
  name: Action
  nameWithType: WorkflowUnhandledExceptionElement.Action
  fullName: WorkflowUnhandledExceptionElement.Action
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/WorkflowUnhandledExceptionElement.xml
- uid: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.BehaviorType*
  parent: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  isExternal: false
  name: BehaviorType
  nameWithType: WorkflowUnhandledExceptionElement.BehaviorType
  fullName: WorkflowUnhandledExceptionElement.BehaviorType
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/WorkflowUnhandledExceptionElement.xml
- uid: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.CreateBehavior*
  parent: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  isExternal: false
  name: CreateBehavior
  nameWithType: WorkflowUnhandledExceptionElement.CreateBehavior
  fullName: WorkflowUnhandledExceptionElement.CreateBehavior
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/WorkflowUnhandledExceptionElement.xml
- uid: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement.Properties*
  parent: System.ServiceModel.Activities.Configuration.WorkflowUnhandledExceptionElement
  isExternal: false
  name: Properties
  nameWithType: WorkflowUnhandledExceptionElement.Properties
  fullName: WorkflowUnhandledExceptionElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Configuration/WorkflowUnhandledExceptionElement.xml
