### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SecurityPolicySection
  commentId: T:System.Web.Configuration.SecurityPolicySection
  id: SecurityPolicySection
  children:
  - System.Web.Configuration.SecurityPolicySection.#ctor
  - System.Web.Configuration.SecurityPolicySection.Properties
  - System.Web.Configuration.SecurityPolicySection.TrustLevels
  langs:
  - csharp
  name: SecurityPolicySection
  nameWithType: SecurityPolicySection
  fullName: System.Web.Configuration.SecurityPolicySection
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Defines configuration settings that are used to support the security infrastructure of a Web application. This class cannot be inherited.
  remarks: The <xref:System.Web.Configuration.SecurityPolicySection> class provides a way to programmatically access and modify the content of the `securityPolicy` section of the configuration file.
  example:
  - "This example demonstrates how to specify values declaratively within the `securityPolicy` section, which can also be accessed as members of the <xref:System.Web.Configuration.SecurityPolicySection> class.  \n  \n The following configuration file example shows how to specify values declaratively for the `securityPolicy` section.  \n  \n```  \n<system.web>  \n  <securityPolicy>  \n    <trustLevel name=\"Full\" policyFile=\"internal\" />  \n    <trustLevel name=\"High\" policyFile=\"web_hightrust.config\" />  \n    <trustLevel name=\"Medium\" policyFile=\"web_mediumtrust.config\" />  \n    <trustLevel name=\"Low\" policyFile=\"web_lowtrust.config\" />  \n    <trustLevel name=\"Minimal\" policyFile=\"web_minimaltrust.config\" />  \n  </securityPolicy>  \n</system.web>  \n```  \n  \n The following code example demonstrates how to use the <xref:System.Web.Configuration.SecurityPolicySection> class.  \n  \n [!code-csharp[System.Web.Configuration.SecurityPolicySection#1](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.SecurityPolicySection/CS/securitypolicysection.cs#1)]\n [!code-vb[System.Web.Configuration.SecurityPolicySection#1](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.SecurityPolicySection/VB/securitypolicysection.vb#1)]"
  syntax:
    content: 'public sealed class SecurityPolicySection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SecurityPolicySection.xml
- uid: System.Web.Configuration.SecurityPolicySection.#ctor
  commentId: M:System.Web.Configuration.SecurityPolicySection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.SecurityPolicySection
  langs:
  - csharp
  name: SecurityPolicySection()
  nameWithType: SecurityPolicySection.SecurityPolicySection()
  fullName: SecurityPolicySection.SecurityPolicySection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Configuration.SecurityPolicySection"></xref> class by using default settings.
  remarks: The <xref:System.Web.Configuration.SecurityPolicySection.%23ctor%2A> constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system. You obtain an instance of the <xref:System.Web.Configuration.SecurityPolicySection> class by using the <xref:System.Configuration.Configuration.GetSection%2A> method.
  syntax:
    content: public SecurityPolicySection ();
    parameters: []
  overload: System.Web.Configuration.SecurityPolicySection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SecurityPolicySection.xml
- uid: System.Web.Configuration.SecurityPolicySection.Properties
  commentId: P:System.Web.Configuration.SecurityPolicySection.Properties
  id: Properties
  parent: System.Web.Configuration.SecurityPolicySection
  langs:
  - csharp
  name: Properties
  nameWithType: SecurityPolicySection.Properties
  fullName: SecurityPolicySection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.SecurityPolicySection.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SecurityPolicySection.xml
- uid: System.Web.Configuration.SecurityPolicySection.TrustLevels
  commentId: P:System.Web.Configuration.SecurityPolicySection.TrustLevels
  id: TrustLevels
  parent: System.Web.Configuration.SecurityPolicySection
  langs:
  - csharp
  name: TrustLevels
  nameWithType: SecurityPolicySection.TrustLevels
  fullName: SecurityPolicySection.TrustLevels
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets the <xref href="System.Web.Configuration.SecurityPolicySection.TrustLevels"></xref> collection.
  remarks: The default values for the <xref:System.Web.Configuration.SecurityPolicySection.TrustLevels%2A> property are `Full`, `High`, `Medium`, `Low`, and `Minimal`. The items of the <xref:System.Web.Configuration.SecurityPolicySection.TrustLevels%2A> collection each specify a security-level name and an associated policy file. You can extend the security system by providing your own named trust-level element mapped to a file specified by the `policyFile` attribute. For information about creating trust-level elements, see [trustLevel Element for securityPolicy (ASP.NET Settings Schema)](http://msdn.microsoft.com/en-us/729ab04c-03da-4ee5-86b1-be9d08a09369).
  example:
  - "The following code example demonstrates how to use the <xref:System.Web.Configuration.SecurityPolicySection.TrustLevels%2A> property, add a trust-level element to the configuration file, and update the configuration file. This code example is part of a larger example provided for the <xref:System.Web.Configuration.SecurityPolicySection> class.  \n  \n [!code-csharp[System.Web.Configuration.SecurityPolicySection#2](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.SecurityPolicySection/CS/securitypolicysection.cs#2)]\n [!code-vb[System.Web.Configuration.SecurityPolicySection#2](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.SecurityPolicySection/VB/securitypolicysection.vb#2)]"
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("", IsDefaultCollection=true)]

      public System.Web.Configuration.TrustLevelCollection TrustLevels { get; }
    return:
      type: System.Web.Configuration.TrustLevelCollection
      description: A collection of <xref href="System.Web.Configuration.SecurityPolicySection.TrustLevels"></xref> objects.
  overload: System.Web.Configuration.SecurityPolicySection.TrustLevels*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SecurityPolicySection.xml
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.SecurityPolicySection.#ctor
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: SecurityPolicySection()
  nameWithType: SecurityPolicySection.SecurityPolicySection()
  fullName: SecurityPolicySection.SecurityPolicySection()
- uid: System.Web.Configuration.SecurityPolicySection.Properties
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: Properties
  nameWithType: SecurityPolicySection.Properties
  fullName: SecurityPolicySection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.SecurityPolicySection.TrustLevels
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: TrustLevels
  nameWithType: SecurityPolicySection.TrustLevels
  fullName: SecurityPolicySection.TrustLevels
- uid: System.Web.Configuration.TrustLevelCollection
  parent: System.Web.Configuration
  isExternal: false
  name: TrustLevelCollection
  nameWithType: TrustLevelCollection
  fullName: System.Web.Configuration.TrustLevelCollection
- uid: System.Web.Configuration.SecurityPolicySection.#ctor*
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: SecurityPolicySection
  nameWithType: SecurityPolicySection.SecurityPolicySection
  fullName: SecurityPolicySection.SecurityPolicySection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SecurityPolicySection.xml
- uid: System.Web.Configuration.SecurityPolicySection.Properties*
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: Properties
  nameWithType: SecurityPolicySection.Properties
  fullName: SecurityPolicySection.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SecurityPolicySection.xml
- uid: System.Web.Configuration.SecurityPolicySection.TrustLevels*
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: TrustLevels
  nameWithType: SecurityPolicySection.TrustLevels
  fullName: SecurityPolicySection.TrustLevels
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SecurityPolicySection.xml
