### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NetHttpBindingCollectionElement
  commentId: T:System.ServiceModel.Configuration.NetHttpBindingCollectionElement
  id: NetHttpBindingCollectionElement
  children:
  - System.ServiceModel.Configuration.NetHttpBindingCollectionElement.#ctor
  langs:
  - csharp
  name: NetHttpBindingCollectionElement
  nameWithType: NetHttpBindingCollectionElement
  fullName: System.ServiceModel.Configuration.NetHttpBindingCollectionElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a net http binding collection element.
  syntax:
    content: 'public class NetHttpBindingCollectionElement : System.ServiceModel.Configuration.StandardBindingCollectionElement<System.ServiceModel.NetHttpBinding,System.ServiceModel.Configuration.NetHttpBindingElement>'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.BindingCollectionElement
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Bindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.BindingType
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ConfiguredBindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ContainsKey(System.String)
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.GetDefault
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Properties
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetHttpBindingCollectionElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.NetHttpBindingCollectionElement.#ctor
  commentId: M:System.ServiceModel.Configuration.NetHttpBindingCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NetHttpBindingCollectionElement
  langs:
  - csharp
  name: NetHttpBindingCollectionElement()
  nameWithType: NetHttpBindingCollectionElement.NetHttpBindingCollectionElement()
  fullName: System.ServiceModel.Configuration.NetHttpBindingCollectionElement.NetHttpBindingCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of <xref href="System.ServiceModel.Configuration.NetHttpBindingCollectionElement"></xref> class.
  syntax:
    content: public NetHttpBindingCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NetHttpBindingCollectionElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetHttpBindingCollectionElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  name: StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  nameWithType: StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
- uid: System.ServiceModel.NetHttpBinding
  name: NetHttpBinding
  nameWithType: NetHttpBinding
  fullName: System.ServiceModel.NetHttpBinding
- uid: System.ServiceModel.Configuration.NetHttpBindingElement
  name: NetHttpBindingElement
  nameWithType: NetHttpBindingElement
  fullName: System.ServiceModel.Configuration.NetHttpBindingElement
- uid: System.ServiceModel.Configuration.StandardBindingCollectionElement{System.ServiceModel.NetHttpBinding,System.ServiceModel.Configuration.NetHttpBindingElement}
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: StandardBindingCollectionElement<NetHttpBinding,NetHttpBindingElement>
  nameWithType: StandardBindingCollectionElement<NetHttpBinding,NetHttpBindingElement>
  fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement<System.ServiceModel.NetHttpBinding,System.ServiceModel.Configuration.NetHttpBindingElement>
  spec.csharp:
  - uid: System.ServiceModel.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.NetHttpBinding
    name: NetHttpBinding
    nameWithType: NetHttpBinding
    fullName: System.ServiceModel.NetHttpBinding
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.ServiceModel.Configuration.NetHttpBindingElement
    name: NetHttpBindingElement
    nameWithType: NetHttpBindingElement
    fullName: System.ServiceModel.Configuration.NetHttpBindingElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.NetHttpBindingCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.NetHttpBindingCollectionElement
  isExternal: false
  name: NetHttpBindingCollectionElement()
  nameWithType: NetHttpBindingCollectionElement.NetHttpBindingCollectionElement()
  fullName: System.ServiceModel.Configuration.NetHttpBindingCollectionElement.NetHttpBindingCollectionElement()
- uid: System.ServiceModel.Configuration.NetHttpBindingCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.NetHttpBindingCollectionElement
  isExternal: false
  name: NetHttpBindingCollectionElement
  nameWithType: NetHttpBindingCollectionElement.NetHttpBindingCollectionElement
  fullName: System.ServiceModel.Configuration.NetHttpBindingCollectionElement.NetHttpBindingCollectionElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetHttpBindingCollectionElement.xml
