### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  commentId: T:System.ServiceModel.Configuration.ServiceModelConfigurationElement
  id: ServiceModelConfigurationElement
  children:
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.#ctor
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  langs:
  - csharp
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a service model configuration element.
  syntax:
    content: 'public abstract class ServiceModelConfigurationElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  derivedClasses:
  - System.ServiceModel.Configuration.AddressHeaderCollectionElement
  - System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  - System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  - System.ServiceModel.Configuration.BasicHttpSecurityElement
  - System.ServiceModel.Configuration.BasicHttpsSecurityElement
  - System.ServiceModel.Configuration.ChannelPoolSettingsElement
  - System.ServiceModel.Configuration.EndpointAddressElementBase
  - System.ServiceModel.Configuration.FederatedMessageSecurityOverHttpElement
  - System.ServiceModel.Configuration.HttpTransportSecurityElement
  - System.ServiceModel.Configuration.IssuedTokenParametersElement
  - System.ServiceModel.Configuration.LocalClientSecuritySettingsElement
  - System.ServiceModel.Configuration.LocalServiceSecuritySettingsElement
  - System.ServiceModel.Configuration.MessageSecurityOverHttpElement
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  - System.ServiceModel.Configuration.MessageSecurityOverTcpElement
  - System.ServiceModel.Configuration.MsmqIntegrationSecurityElement
  - System.ServiceModel.Configuration.MsmqTransportSecurityElement
  - System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  - System.ServiceModel.Configuration.NamedPipeSettingsElement
  - System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  - System.ServiceModel.Configuration.NetMsmqSecurityElement
  - System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  - System.ServiceModel.Configuration.NetTcpSecurityElement
  - System.ServiceModel.Configuration.PeerCustomResolverElement
  - System.ServiceModel.Configuration.PeerResolverElement
  - System.ServiceModel.Configuration.PeerSecurityElement
  - System.ServiceModel.Configuration.PeerTransportSecurityElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.StandardBindingElement
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  - System.ServiceModel.Configuration.TcpTransportSecurityElement
  - System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  - System.ServiceModel.Configuration.WebHttpSecurityElement
  - System.ServiceModel.Configuration.WebSocketTransportSettingsElement
  - System.ServiceModel.Configuration.WSDualHttpSecurityElement
  - System.ServiceModel.Configuration.WSFederationHttpSecurityElement
  - System.ServiceModel.Configuration.WSHttpSecurityElement
  - System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  - System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ServiceModelConfigurationElement.xml
  manager: ghogen
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement.#ctor
  commentId: M:System.ServiceModel.Configuration.ServiceModelConfigurationElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  langs:
  - csharp
  name: ServiceModelConfigurationElement()
  nameWithType: ServiceModelConfigurationElement.ServiceModelConfigurationElement()
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement.ServiceModelConfigurationElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.ServiceModelConfigurationElement"></xref> class.
  syntax:
    content: protected ServiceModelConfigurationElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ServiceModelConfigurationElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ServiceModelConfigurationElement.xml
  manager: ghogen
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  commentId: M:System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  id: SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  parent: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  langs:
  - csharp
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Sets the property value for the configuration element if the value is not the default value.
  syntax:
    content: protected void SetPropertyValueIfNotDefaultValue<T> (string propertyName, T value);
    parameters:
    - id: propertyName
      type: System.String
      description: The name of the property.
    - id: value
      type: T
      description: The property value to be set.
  overload: System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ServiceModelConfigurationElement.xml
  manager: ghogen
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement.#ctor
  parent: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: ServiceModelConfigurationElement()
  nameWithType: ServiceModelConfigurationElement.ServiceModelConfigurationElement()
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement.ServiceModelConfigurationElement()
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  parent: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: T
  isExternal: true
  name: T
  nameWithType: T
  fullName: T
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement.#ctor*
  parent: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement.ServiceModelConfigurationElement
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement.ServiceModelConfigurationElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ServiceModelConfigurationElement.xml
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1*
  parent: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: SetPropertyValueIfNotDefaultValue<T>
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/ServiceModelConfigurationElement.xml
