### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.ConnectionManagementElement
  commentId: T:System.Net.Configuration.ConnectionManagementElement
  id: ConnectionManagementElement
  children:
  - System.Net.Configuration.ConnectionManagementElement.#ctor
  - System.Net.Configuration.ConnectionManagementElement.#ctor(System.String,System.Int32)
  - System.Net.Configuration.ConnectionManagementElement.Address
  - System.Net.Configuration.ConnectionManagementElement.MaxConnection
  - System.Net.Configuration.ConnectionManagementElement.Properties
  langs:
  - csharp
  name: ConnectionManagementElement
  nameWithType: ConnectionManagementElement
  fullName: System.Net.Configuration.ConnectionManagementElement
  type: Class
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Represents the maximum number of connections to a remote computer. This class cannot be inherited.
  remarks: "This class corresponds to the [\\&lt;add\\&gt; Element for connectionManagement (Network Settings)](~/docs/framework/configure-apps/file-schema/network/add-element-for-connectionmanagement-network-settings.md) configuration element.  \n  \n This class is used to specify the maximum number of simultaneous connections to a remote computer.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class ConnectionManagementElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ConnectionManagementElement.xml
  ms.author: bobdel
  manager: markl
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor
  commentId: M:System.Net.Configuration.ConnectionManagementElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: ConnectionManagementElement()
  nameWithType: ConnectionManagementElement.ConnectionManagementElement()
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Initializes a new instance of the <xref href="System.Net.Configuration.ConnectionManagementElement"></xref> class.
  syntax:
    content: public ConnectionManagementElement ();
    parameters: []
  overload: System.Net.Configuration.ConnectionManagementElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ConnectionManagementElement.xml
  ms.author: bobdel
  manager: markl
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor(System.String,System.Int32)
  commentId: M:System.Net.Configuration.ConnectionManagementElement.#ctor(System.String,System.Int32)
  id: '#ctor(System.String,System.Int32)'
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: ConnectionManagementElement(String, Int32)
  nameWithType: ConnectionManagementElement.ConnectionManagementElement(String, Int32)
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement(String, Int32)
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Initializes a new instance of the <xref href="System.Net.Configuration.ConnectionManagementElement"></xref> class with the specified address and connection limit information.
  remarks: This constructor sets the <xref:System.Net.Configuration.ConnectionManagementElement.Address%2A> property to `address` and the <xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A> property to `maxConnection`.
  syntax:
    content: public ConnectionManagementElement (string address, int maxConnection);
    parameters:
    - id: address
      type: System.String
      description: A string that identifies the address of a remote computer.
    - id: maxConnection
      type: System.Int32
      description: An integer that identifies the maximum number of connections allowed to <code>address</code> from the local computer.
  overload: System.Net.Configuration.ConnectionManagementElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ConnectionManagementElement.xml
  ms.author: bobdel
  manager: markl
- uid: System.Net.Configuration.ConnectionManagementElement.Address
  commentId: P:System.Net.Configuration.ConnectionManagementElement.Address
  id: Address
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: Address
  nameWithType: ConnectionManagementElement.Address
  fullName: System.Net.Configuration.ConnectionManagementElement.Address
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Gets or sets the address for remote computers.
  remarks: "You can set this property using an asterisk (*) to set the default number of connections for unspecified computers.  \n  \n This property identifies one or more remote computers and the <xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A> property specifies how many simultaneous connections are allowed between the local computer and the remote computers."
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("address", Options=System.Configuration.ConfigurationPropertyOptions.IsRequired | System.Configuration.ConfigurationPropertyOptions.IsKey)]

      public string Address { get; set; }
    return:
      type: System.String
      description: A string that contains a regular expression describing an IP address or DNS name.
  overload: System.Net.Configuration.ConnectionManagementElement.Address*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ConnectionManagementElement.xml
  ms.author: bobdel
  manager: markl
- uid: System.Net.Configuration.ConnectionManagementElement.MaxConnection
  commentId: P:System.Net.Configuration.ConnectionManagementElement.MaxConnection
  id: MaxConnection
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: MaxConnection
  nameWithType: ConnectionManagementElement.MaxConnection
  fullName: System.Net.Configuration.ConnectionManagementElement.MaxConnection
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Gets or sets the maximum number of connections that can be made to a remote computer.
  remarks: "This property specifies how many simultaneous connections are allowed between the local computer and the remote computer. The remote computer is specified using the <xref:System.Net.Configuration.ConnectionManagementElement.Address%2A> property.  \n  \n The <xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A> property is per <xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName>. If an application is not changing <xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName> from the default, then the <xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A> property applies to the entire application domain. If only a single application domain is running in your application, then the <xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A> property setting is application-wide."
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("maxconnection", DefaultValue=Mono.Cecil.CustomAttributeArgument, Options=System.Configuration.ConfigurationPropertyOptions.IsRequired)]

      public int MaxConnection { get; set; }
    return:
      type: System.Int32
      description: An integer that specifies the maximum number of connections.
  overload: System.Net.Configuration.ConnectionManagementElement.MaxConnection*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ConnectionManagementElement.xml
  ms.author: bobdel
  manager: markl
- uid: System.Net.Configuration.ConnectionManagementElement.Properties
  commentId: P:System.Net.Configuration.ConnectionManagementElement.Properties
  id: Properties
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: Properties
  nameWithType: ConnectionManagementElement.Properties
  fullName: System.Net.Configuration.ConnectionManagementElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Net.Configuration.ConnectionManagementElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ConnectionManagementElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: ConnectionManagementElement()
  nameWithType: ConnectionManagementElement.ConnectionManagementElement()
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement()
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor(System.String,System.Int32)
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: ConnectionManagementElement(String, Int32)
  nameWithType: ConnectionManagementElement.ConnectionManagementElement(String, Int32)
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement(String, Int32)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Net.Configuration.ConnectionManagementElement.Address
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Address
  nameWithType: ConnectionManagementElement.Address
  fullName: System.Net.Configuration.ConnectionManagementElement.Address
- uid: System.Net.Configuration.ConnectionManagementElement.MaxConnection
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: MaxConnection
  nameWithType: ConnectionManagementElement.MaxConnection
  fullName: System.Net.Configuration.ConnectionManagementElement.MaxConnection
- uid: System.Net.Configuration.ConnectionManagementElement.Properties
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Properties
  nameWithType: ConnectionManagementElement.Properties
  fullName: System.Net.Configuration.ConnectionManagementElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: ConnectionManagementElement
  nameWithType: ConnectionManagementElement.ConnectionManagementElement
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ConnectionManagementElement.xml
- uid: System.Net.Configuration.ConnectionManagementElement.Address*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Address
  nameWithType: ConnectionManagementElement.Address
  fullName: System.Net.Configuration.ConnectionManagementElement.Address
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ConnectionManagementElement.xml
- uid: System.Net.Configuration.ConnectionManagementElement.MaxConnection*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: MaxConnection
  nameWithType: ConnectionManagementElement.MaxConnection
  fullName: System.Net.Configuration.ConnectionManagementElement.MaxConnection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ConnectionManagementElement.xml
- uid: System.Net.Configuration.ConnectionManagementElement.Properties*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Properties
  nameWithType: ConnectionManagementElement.Properties
  fullName: System.Net.Configuration.ConnectionManagementElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ConnectionManagementElement.xml
