### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationCompletedEventArgs
  commentId: T:System.Activities.WorkflowApplicationCompletedEventArgs
  id: WorkflowApplicationCompletedEventArgs
  children:
  - System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  - System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  - System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  langs:
  - csharp
  name: WorkflowApplicationCompletedEventArgs
  nameWithType: WorkflowApplicationCompletedEventArgs
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs
  type: Class
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: Provides information about a workflow instance that has completed its execution.
  remarks: ''
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationCompletedEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Completed%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about how the workflow completed.  \n  \n [!code-csharp[CFX_WorkflowApplicationExample#4](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#4)]"
  syntax:
    content: 'public class WorkflowApplicationCompletedEventArgs : System.Activities.WorkflowApplicationEventArgs'
  inheritance:
  - System.Object
  - System.EventArgs
  - System.Activities.WorkflowApplicationEventArgs
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  - System.Activities.WorkflowApplicationEventArgs.InstanceId
  - System.EventArgs.Empty
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationCompletedEventArgs.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  commentId: P:System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  id: CompletionState
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  langs:
  - csharp
  name: CompletionState
  nameWithType: WorkflowApplicationCompletedEventArgs.CompletionState
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: Gets the completion state of the workflow instance, which indicates whether the workflow instance completed successfully, was canceled, or faulted.
  remarks: ''
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationCompletedEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Completed%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about how the workflow completed.  \n  \n [!code-csharp[CFX_WorkflowApplicationExample#4](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#4)]"
  syntax:
    content: public System.Activities.ActivityInstanceState CompletionState { get; }
    return:
      type: System.Activities.ActivityInstanceState
      description: The completion state of the workflow instance, which indicates whether the workflow instance completed successfully, was canceled, or faulted.
  overload: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationCompletedEventArgs.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  commentId: P:System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  id: Outputs
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  langs:
  - csharp
  name: Outputs
  nameWithType: WorkflowApplicationCompletedEventArgs.Outputs
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: Gets a dictionary that contains the values of <xref href="System.Activities.OutArgument"></xref>s of the workflow instance’s root activity, keyed by argument name.
  remarks: ''
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationCompletedEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Completed%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about how the workflow completed.  \n  \n [!code-csharp[CFX_WorkflowApplicationExample#4](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#4)]"
  syntax:
    content: public System.Collections.Generic.IDictionary<string,object> Outputs { get; }
    return:
      type: System.Collections.Generic.IDictionary{System.String,System.Object}
      description: A dictionary that contains the values of <xref href="System.Activities.OutArgument"></xref>s of the workflow instance’s root activity, keyed by argument name.
  overload: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationCompletedEventArgs.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  commentId: P:System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  id: TerminationException
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  langs:
  - csharp
  name: TerminationException
  nameWithType: WorkflowApplicationCompletedEventArgs.TerminationException
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: Gets the exception associated with the termination of the workflow instance.
  remarks: ''
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationCompletedEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Completed%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about how the workflow completed.  \n  \n [!code-csharp[CFX_WorkflowApplicationExample#4](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#4)]"
  syntax:
    content: public Exception TerminationException { get; }
    return:
      type: System.Exception
      description: The exception associated with the termination of the workflow instance.
  overload: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationCompletedEventArgs.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.Activities.WorkflowApplicationEventArgs
  parent: System.Activities
  isExternal: false
  name: WorkflowApplicationEventArgs
  nameWithType: WorkflowApplicationEventArgs
  fullName: System.Activities.WorkflowApplicationEventArgs
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: CompletionState
  nameWithType: WorkflowApplicationCompletedEventArgs.CompletionState
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
- uid: System.Activities.ActivityInstanceState
  parent: System.Activities
  isExternal: false
  name: ActivityInstanceState
  nameWithType: ActivityInstanceState
  fullName: System.Activities.ActivityInstanceState
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: Outputs
  nameWithType: WorkflowApplicationCompletedEventArgs.Outputs
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
- uid: System.Collections.Generic.IDictionary`2
  name: IDictionary<TKey,TValue>
  nameWithType: IDictionary<TKey,TValue>
  fullName: System.Collections.Generic.IDictionary<TKey,TValue>
- uid: System.String
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Collections.Generic.IDictionary{System.String,System.Object}
  parent: System.Collections.Generic
  isExternal: false
  name: IDictionary<String,Object>
  nameWithType: IDictionary<String,Object>
  fullName: System.Collections.Generic.IDictionary<System.String,System.Object>
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: System.Collections.Generic.IDictionary
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: TerminationException
  nameWithType: WorkflowApplicationCompletedEventArgs.TerminationException
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState*
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: CompletionState
  nameWithType: WorkflowApplicationCompletedEventArgs.CompletionState
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationCompletedEventArgs.xml
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs*
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: Outputs
  nameWithType: WorkflowApplicationCompletedEventArgs.Outputs
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationCompletedEventArgs.xml
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException*
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: TerminationException
  nameWithType: WorkflowApplicationCompletedEventArgs.TerminationException
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationCompletedEventArgs.xml
