### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpModulesSection
  commentId: T:System.Web.Configuration.HttpModulesSection
  id: HttpModulesSection
  children:
  - System.Web.Configuration.HttpModulesSection.#ctor
  - System.Web.Configuration.HttpModulesSection.Modules
  - System.Web.Configuration.HttpModulesSection.Properties
  langs:
  - csharp
  name: HttpModulesSection
  nameWithType: HttpModulesSection
  fullName: System.Web.Configuration.HttpModulesSection
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Configures an HTTP module for a Web application. This class cannot be inherited.
  remarks: "The <xref:System.Web.Configuration.HttpModulesSection> class provides a way to programmatically access and modify the `httpModules` section of a configuration file.  \n  \n This type is part of a group that includes the <xref:System.Web.Configuration.HttpModuleAction> and the <xref:System.Web.Configuration.HttpModuleActionCollection> types.  \n  \n> [!NOTE]\n>  The <xref:System.Web.Configuration.HttpModulesSection> can read and write information from and to the related section of the configuration file according to the section property <xref:System.Configuration.SectionInformation.AllowDefinition%2A> whose value is <xref:System.Configuration.ConfigurationAllowDefinition>."
  example:
  - "This example demonstrates how to specify values declaratively for attributes of the `add` element within the `httpModules` section, which can also be accessed as members of the <xref:System.Web.Configuration.HttpModulesSection> class.  \n  \n The following configuration file example shows how to specify values declaratively for the [httpModules Element (ASP.NET Settings Schema)](http://msdn.microsoft.com/en-us/5e28e921-ab9b-4584-a2f9-0f9aa08372e3) section.  \n  \n```  \n<httpModules>  \n    <add name=\"TimerModule\"   \n      type=\"Samples.Aspnet.Configuration.RequestTimeInterval, RequestTimeInterval Version=1.0.1557.23158, Culture=neutral,  \n      PublicKeyToken=7bfb33146a87b52e, processorArchitecture=MSIL\"/>  \n</httpModules>  \n```  \n  \n The following code example demonstrates how to use the <xref:System.Web.Configuration.HttpModulesSection> class.  \n  \n [!code-csharp[System.Web.Configuration.HttpModulesSection#1](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.HttpModulesSection/CS/httpmodulessection.cs#1)]\n [!code-vb[System.Web.Configuration.HttpModulesSection#1](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.HttpModulesSection/VB/httpmodulessection.vb#1)]"
  syntax:
    content: 'public sealed class HttpModulesSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModulesSection.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.HttpModulesSection.#ctor
  commentId: M:System.Web.Configuration.HttpModulesSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpModulesSection
  langs:
  - csharp
  name: HttpModulesSection()
  nameWithType: HttpModulesSection.HttpModulesSection()
  fullName: System.Web.Configuration.HttpModulesSection.HttpModulesSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Configuration.HttpModulesSection"></xref> class.
  remarks: The <xref:System.Web.Configuration.HttpModulesSection.%23ctor%2A> constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system. You obtain an instance of the <xref:System.Web.Configuration.HttpModulesSection> class by using the <xref:System.Configuration.Configuration.GetSection%2A> method.
  syntax:
    content: public HttpModulesSection ();
    parameters: []
  overload: System.Web.Configuration.HttpModulesSection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModulesSection.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.HttpModulesSection.Modules
  commentId: P:System.Web.Configuration.HttpModulesSection.Modules
  id: Modules
  parent: System.Web.Configuration.HttpModulesSection
  langs:
  - csharp
  name: Modules
  nameWithType: HttpModulesSection.Modules
  fullName: System.Web.Configuration.HttpModulesSection.Modules
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets the <xref href="System.Web.Configuration.HttpModuleActionCollection"></xref> of <xref href="System.Web.Configuration.HttpModuleAction"></xref> modules contained by the <xref href="System.Web.Configuration.HttpModulesSection"></xref>.
  remarks: The collection returned by this method does not refer to any actual element in the underlying configuration file. It is an ASP.NET infrastructure construct that allows easy access to the modules it contains. This is a common pattern for handling the elements of a configuration file.
  example:
  - "The following code example shows how to access the <xref:System.Web.Configuration.HttpModuleAction> modules.  \n  \n [!code-csharp[System.Web.Configuration.HttpModulesSection#3](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.HttpModulesSection/CS/httpmodulessection.cs#3)]\n [!code-vb[System.Web.Configuration.HttpModulesSection#3](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.HttpModulesSection/VB/httpmodulessection.vb#3)]"
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("", IsDefaultCollection=true)]

      public System.Web.Configuration.HttpModuleActionCollection Modules { get; }
    return:
      type: System.Web.Configuration.HttpModuleActionCollection
      description: A <xref href="System.Web.Configuration.HttpModuleActionCollection"></xref> that contains the <xref href="System.Web.Configuration.HttpModuleAction"></xref> objects, or modules, defined by the <xref href="System.Web.Configuration.HttpModulesSection"></xref>.
  overload: System.Web.Configuration.HttpModulesSection.Modules*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModulesSection.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.HttpModulesSection.Properties
  commentId: P:System.Web.Configuration.HttpModulesSection.Properties
  id: Properties
  parent: System.Web.Configuration.HttpModulesSection
  langs:
  - csharp
  name: Properties
  nameWithType: HttpModulesSection.Properties
  fullName: System.Web.Configuration.HttpModulesSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.HttpModulesSection.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModulesSection.xml
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.HttpModulesSection.#ctor
  parent: System.Web.Configuration.HttpModulesSection
  isExternal: false
  name: HttpModulesSection()
  nameWithType: HttpModulesSection.HttpModulesSection()
  fullName: System.Web.Configuration.HttpModulesSection.HttpModulesSection()
- uid: System.Web.Configuration.HttpModulesSection.Modules
  parent: System.Web.Configuration.HttpModulesSection
  isExternal: false
  name: Modules
  nameWithType: HttpModulesSection.Modules
  fullName: System.Web.Configuration.HttpModulesSection.Modules
- uid: System.Web.Configuration.HttpModuleActionCollection
  parent: System.Web.Configuration
  isExternal: false
  name: HttpModuleActionCollection
  nameWithType: HttpModuleActionCollection
  fullName: System.Web.Configuration.HttpModuleActionCollection
- uid: System.Web.Configuration.HttpModulesSection.Properties
  parent: System.Web.Configuration.HttpModulesSection
  isExternal: false
  name: Properties
  nameWithType: HttpModulesSection.Properties
  fullName: System.Web.Configuration.HttpModulesSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.HttpModulesSection.#ctor*
  parent: System.Web.Configuration.HttpModulesSection
  isExternal: false
  name: HttpModulesSection
  nameWithType: HttpModulesSection.HttpModulesSection
  fullName: System.Web.Configuration.HttpModulesSection.HttpModulesSection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModulesSection.xml
- uid: System.Web.Configuration.HttpModulesSection.Modules*
  parent: System.Web.Configuration.HttpModulesSection
  isExternal: false
  name: Modules
  nameWithType: HttpModulesSection.Modules
  fullName: System.Web.Configuration.HttpModulesSection.Modules
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModulesSection.xml
- uid: System.Web.Configuration.HttpModulesSection.Properties*
  parent: System.Web.Configuration.HttpModulesSection
  isExternal: false
  name: Properties
  nameWithType: HttpModulesSection.Properties
  fullName: System.Web.Configuration.HttpModulesSection.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModulesSection.xml
