### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.DiagnosticsElement
  commentId: T:System.Web.Services.Configuration.DiagnosticsElement
  id: DiagnosticsElement
  children:
  - System.Web.Services.Configuration.DiagnosticsElement.#ctor
  - System.Web.Services.Configuration.DiagnosticsElement.Properties
  - System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
  langs:
  - csharp
  name: DiagnosticsElement
  nameWithType: DiagnosticsElement
  fullName: System.Web.Services.Configuration.DiagnosticsElement
  type: Class
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Represents the [<diagnostics>](http://msdn.microsoft.com/en-us/e4ca05d1-1e10-4873-9ef6-75e55851d888) element in the Web.config configuration file.
  remarks: The <xref:System.Web.Services.Configuration.DiagnosticsElement> class represents the [\<diagnostics>](http://msdn.microsoft.com/en-us/e4ca05d1-1e10-4873-9ef6-75e55851d888) element in a Web.config file. Set the <xref:System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions%2A> property to true in order to return exceptions to the client for debugging purposes.
  syntax:
    content: 'public sealed class DiagnosticsElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/DiagnosticsElement.xml
- uid: System.Web.Services.Configuration.DiagnosticsElement.#ctor
  commentId: M:System.Web.Services.Configuration.DiagnosticsElement.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.DiagnosticsElement
  langs:
  - csharp
  name: DiagnosticsElement()
  nameWithType: DiagnosticsElement.DiagnosticsElement()
  fullName: DiagnosticsElement.DiagnosticsElement()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Services.Configuration.DiagnosticsElement"></xref> class.
  syntax:
    content: public DiagnosticsElement ();
    parameters: []
  overload: System.Web.Services.Configuration.DiagnosticsElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/DiagnosticsElement.xml
- uid: System.Web.Services.Configuration.DiagnosticsElement.Properties
  commentId: P:System.Web.Services.Configuration.DiagnosticsElement.Properties
  id: Properties
  parent: System.Web.Services.Configuration.DiagnosticsElement
  langs:
  - csharp
  name: Properties
  nameWithType: DiagnosticsElement.Properties
  fullName: DiagnosticsElement.Properties
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Services.Configuration.DiagnosticsElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/DiagnosticsElement.xml
- uid: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
  commentId: P:System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
  id: SuppressReturningExceptions
  parent: System.Web.Services.Configuration.DiagnosticsElement
  langs:
  - csharp
  name: SuppressReturningExceptions
  nameWithType: DiagnosticsElement.SuppressReturningExceptions
  fullName: DiagnosticsElement.SuppressReturningExceptions
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Gets or sets a value that indicates whether the service returns exceptions.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("suppressReturningExceptions", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public bool SuppressReturningExceptions { get; set; }
    return:
      type: System.Boolean
      description: '`true` if the service returns exceptions; otherwise, `false`. The default is `false`.'
  overload: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/DiagnosticsElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Services.Configuration.DiagnosticsElement.#ctor
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: DiagnosticsElement()
  nameWithType: DiagnosticsElement.DiagnosticsElement()
  fullName: DiagnosticsElement.DiagnosticsElement()
- uid: System.Web.Services.Configuration.DiagnosticsElement.Properties
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: Properties
  nameWithType: DiagnosticsElement.Properties
  fullName: DiagnosticsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: SuppressReturningExceptions
  nameWithType: DiagnosticsElement.SuppressReturningExceptions
  fullName: DiagnosticsElement.SuppressReturningExceptions
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Services.Configuration.DiagnosticsElement.#ctor*
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: DiagnosticsElement
  nameWithType: DiagnosticsElement.DiagnosticsElement
  fullName: DiagnosticsElement.DiagnosticsElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/DiagnosticsElement.xml
- uid: System.Web.Services.Configuration.DiagnosticsElement.Properties*
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: Properties
  nameWithType: DiagnosticsElement.Properties
  fullName: DiagnosticsElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/DiagnosticsElement.xml
- uid: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions*
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: SuppressReturningExceptions
  nameWithType: DiagnosticsElement.SuppressReturningExceptions
  fullName: DiagnosticsElement.SuppressReturningExceptions
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/DiagnosticsElement.xml
