### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement
  commentId: T:System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement
  id: HttpMessageHandlerFactoryElement
  children:
  - System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.#ctor
  - System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Handlers
  - System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Properties
  - System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Type
  langs:
  - csharp
  name: HttpMessageHandlerFactoryElement
  nameWithType: HttpMessageHandlerFactoryElement
  fullName: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a HttpMessageHandlerFactoryElement for HttpMessageHandlerFactory.
  syntax:
    content: 'public sealed class HttpMessageHandlerFactoryElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HttpMessageHandlerFactoryElement.xml
- uid: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.#ctor
  commentId: M:System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement
  langs:
  - csharp
  name: HttpMessageHandlerFactoryElement()
  nameWithType: HttpMessageHandlerFactoryElement.HttpMessageHandlerFactoryElement()
  fullName: HttpMessageHandlerFactoryElement.HttpMessageHandlerFactoryElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement"></xref> class.
  syntax:
    content: public HttpMessageHandlerFactoryElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HttpMessageHandlerFactoryElement.xml
- uid: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Handlers
  commentId: P:System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Handlers
  id: Handlers
  parent: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement
  langs:
  - csharp
  name: Handlers
  nameWithType: HttpMessageHandlerFactoryElement.Handlers
  fullName: HttpMessageHandlerFactoryElement.Handlers
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets a collection of handlers from the configuration.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("handlers")]

      public System.ServiceModel.Configuration.DelegatingHandlerElementCollection Handlers { get; }
    return:
      type: System.ServiceModel.Configuration.DelegatingHandlerElementCollection
      description: a collection of handlers from the configuration.
  overload: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Handlers*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HttpMessageHandlerFactoryElement.xml
- uid: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Properties
  commentId: P:System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement
  langs:
  - csharp
  name: Properties
  nameWithType: HttpMessageHandlerFactoryElement.Properties
  fullName: HttpMessageHandlerFactoryElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HttpMessageHandlerFactoryElement.xml
- uid: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Type
  commentId: P:System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Type
  id: Type
  parent: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement
  langs:
  - csharp
  name: Type
  nameWithType: HttpMessageHandlerFactoryElement.Type
  fullName: HttpMessageHandlerFactoryElement.Type
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the type of the <xref href="System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement"></xref> object.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("type")]

      [System.Configuration.StringValidator(MinLength=0)]

      public string Type { get; set; }
    return:
      type: System.String
      description: The type of the <xref href="System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement"></xref> object.
  overload: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Type*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HttpMessageHandlerFactoryElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.#ctor
  parent: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement
  isExternal: false
  name: HttpMessageHandlerFactoryElement()
  nameWithType: HttpMessageHandlerFactoryElement.HttpMessageHandlerFactoryElement()
  fullName: HttpMessageHandlerFactoryElement.HttpMessageHandlerFactoryElement()
- uid: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Handlers
  parent: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement
  isExternal: false
  name: Handlers
  nameWithType: HttpMessageHandlerFactoryElement.Handlers
  fullName: HttpMessageHandlerFactoryElement.Handlers
- uid: System.ServiceModel.Configuration.DelegatingHandlerElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: DelegatingHandlerElementCollection
  nameWithType: DelegatingHandlerElementCollection
  fullName: System.ServiceModel.Configuration.DelegatingHandlerElementCollection
- uid: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Properties
  parent: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement
  isExternal: false
  name: Properties
  nameWithType: HttpMessageHandlerFactoryElement.Properties
  fullName: HttpMessageHandlerFactoryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Type
  parent: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement
  isExternal: false
  name: Type
  nameWithType: HttpMessageHandlerFactoryElement.Type
  fullName: HttpMessageHandlerFactoryElement.Type
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.#ctor*
  parent: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement
  isExternal: false
  name: HttpMessageHandlerFactoryElement
  nameWithType: HttpMessageHandlerFactoryElement.HttpMessageHandlerFactoryElement
  fullName: HttpMessageHandlerFactoryElement.HttpMessageHandlerFactoryElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HttpMessageHandlerFactoryElement.xml
- uid: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Handlers*
  parent: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement
  isExternal: false
  name: Handlers
  nameWithType: HttpMessageHandlerFactoryElement.Handlers
  fullName: HttpMessageHandlerFactoryElement.Handlers
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HttpMessageHandlerFactoryElement.xml
- uid: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Properties*
  parent: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement
  isExternal: false
  name: Properties
  nameWithType: HttpMessageHandlerFactoryElement.Properties
  fullName: HttpMessageHandlerFactoryElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HttpMessageHandlerFactoryElement.xml
- uid: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement.Type*
  parent: System.ServiceModel.Configuration.HttpMessageHandlerFactoryElement
  isExternal: false
  name: Type
  nameWithType: HttpMessageHandlerFactoryElement.Type
  fullName: HttpMessageHandlerFactoryElement.Type
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/HttpMessageHandlerFactoryElement.xml
