### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpHandlersSection
  commentId: T:System.Web.Configuration.HttpHandlersSection
  id: HttpHandlersSection
  children:
  - System.Web.Configuration.HttpHandlersSection.#ctor
  - System.Web.Configuration.HttpHandlersSection.Handlers
  - System.Web.Configuration.HttpHandlersSection.Properties
  langs:
  - csharp
  name: HttpHandlersSection
  nameWithType: HttpHandlersSection
  fullName: System.Web.Configuration.HttpHandlersSection
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Configures an HTTP handler for a Web application. This class cannot be inherited.
  remarks: "The <xref:System.Web.Configuration.HttpHandlersSection> class provides a way to programmatically access and modify the `httpHandlers` section of a configuration file. This type is part of a group that includes the <xref:System.Web.Configuration.HttpHandlerAction> and the <xref:System.Web.Configuration.HttpHandlerActionCollection> types.  \n  \n> [!NOTE]\n>  The <xref:System.Web.Configuration.HttpHandlersSection> can read and write information from and to the related section of the configuration file according to the <xref:System.Configuration.SectionInformation.AllowDefinition%2A> section property whose value is <xref:System.Configuration.ConfigurationAllowDefinition>."
  example:
  - "The following code example shows how to use the <xref:System.Web.Configuration.HttpHandlersSection> class to access the `httpHandlers` section of an existing Web application.  \n  \n [!code-csharp[System.Web.Configuration.HttpHandlers#1](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.HttpHandlers/CS/httphandlers.cs#1)]\n [!code-vb[System.Web.Configuration.HttpHandlers#1](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.HttpHandlers/VB/httphandlers.vb#1)]  \n  \n The following configuration excerpt shows how to specify values declaratively for the `httpHandlers` section.  \n  \n```  \n<httpHandlers>  \n  <add path=\"Calculator.custom\"  \n    type=\"Samples.Aspnet.SystemWebConfiguration.Calculator, CalculatorHandler\"  \n    verb=\"GET\" validate=\"false\" />  \n</httpHandlers>   \n```"
  syntax:
    content: 'public sealed class HttpHandlersSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpHandlersSection.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.HttpHandlersSection.#ctor
  commentId: M:System.Web.Configuration.HttpHandlersSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpHandlersSection
  langs:
  - csharp
  name: HttpHandlersSection()
  nameWithType: HttpHandlersSection.HttpHandlersSection()
  fullName: System.Web.Configuration.HttpHandlersSection.HttpHandlersSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Configuration.HttpHandlersSection"></xref> class.
  remarks: The <xref:System.Web.Configuration.HttpHandlersSection.%23ctor%2A> constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system. You obtain an instance of the <xref:System.Web.Configuration.HttpHandlersSection> class by using the <xref:System.Configuration.Configuration.GetSection%2A> method.
  syntax:
    content: public HttpHandlersSection ();
    parameters: []
  overload: System.Web.Configuration.HttpHandlersSection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpHandlersSection.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.HttpHandlersSection.Handlers
  commentId: P:System.Web.Configuration.HttpHandlersSection.Handlers
  id: Handlers
  parent: System.Web.Configuration.HttpHandlersSection
  langs:
  - csharp
  name: Handlers
  nameWithType: HttpHandlersSection.Handlers
  fullName: System.Web.Configuration.HttpHandlersSection.Handlers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets the <xref href="System.Web.Configuration.HttpHandlerActionCollection"></xref> collection of <xref href="System.Web.Configuration.HttpHandlerAction"></xref> objects contained by the <xref href="System.Web.Configuration.HttpHandlersSection"></xref> object.
  remarks: The <xref:System.Web.Configuration.HttpHandlersSection.Handlers%2A> property collection returned by this method does not refer to any actual element in the underlying configuration file. It is a <xref:System.Web.Configuration> construct that allows easy access to the handlers it contains. This is a common pattern for handling the elements of a configuration file.
  example:
  - "The following code example shows how to access the <xref:System.Web.Configuration.HttpHandlerAction> handlers.  \n  \n [!code-csharp[System.Web.Configuration.HttpHandlers#4](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.HttpHandlers/CS/httphandlers.cs#4)]\n [!code-vb[System.Web.Configuration.HttpHandlers#4](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.HttpHandlers/VB/httphandlers.vb#4)]"
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("", IsDefaultCollection=true)]

      public System.Web.Configuration.HttpHandlerActionCollection Handlers { get; }
    return:
      type: System.Web.Configuration.HttpHandlerActionCollection
      description: An <xref href="System.Web.Configuration.HttpHandlerActionCollection"></xref> that contains the <xref href="System.Web.Configuration.HttpHandlerAction"></xref> objects, or handlers.
  overload: System.Web.Configuration.HttpHandlersSection.Handlers*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpHandlersSection.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.HttpHandlersSection.Properties
  commentId: P:System.Web.Configuration.HttpHandlersSection.Properties
  id: Properties
  parent: System.Web.Configuration.HttpHandlersSection
  langs:
  - csharp
  name: Properties
  nameWithType: HttpHandlersSection.Properties
  fullName: System.Web.Configuration.HttpHandlersSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.HttpHandlersSection.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpHandlersSection.xml
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.HttpHandlersSection.#ctor
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: HttpHandlersSection()
  nameWithType: HttpHandlersSection.HttpHandlersSection()
  fullName: System.Web.Configuration.HttpHandlersSection.HttpHandlersSection()
- uid: System.Web.Configuration.HttpHandlersSection.Handlers
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: Handlers
  nameWithType: HttpHandlersSection.Handlers
  fullName: System.Web.Configuration.HttpHandlersSection.Handlers
- uid: System.Web.Configuration.HttpHandlerActionCollection
  parent: System.Web.Configuration
  isExternal: false
  name: HttpHandlerActionCollection
  nameWithType: HttpHandlerActionCollection
  fullName: System.Web.Configuration.HttpHandlerActionCollection
- uid: System.Web.Configuration.HttpHandlersSection.Properties
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: Properties
  nameWithType: HttpHandlersSection.Properties
  fullName: System.Web.Configuration.HttpHandlersSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.HttpHandlersSection.#ctor*
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: HttpHandlersSection
  nameWithType: HttpHandlersSection.HttpHandlersSection
  fullName: System.Web.Configuration.HttpHandlersSection.HttpHandlersSection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpHandlersSection.xml
- uid: System.Web.Configuration.HttpHandlersSection.Handlers*
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: Handlers
  nameWithType: HttpHandlersSection.Handlers
  fullName: System.Web.Configuration.HttpHandlersSection.Handlers
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpHandlersSection.xml
- uid: System.Web.Configuration.HttpHandlersSection.Properties*
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: Properties
  nameWithType: HttpHandlersSection.Properties
  fullName: System.Web.Configuration.HttpHandlersSection.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpHandlersSection.xml
