### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ExpressionBuilder
  commentId: T:System.Web.Configuration.ExpressionBuilder
  id: ExpressionBuilder
  children:
  - System.Web.Configuration.ExpressionBuilder.#ctor(System.String,System.String)
  - System.Web.Configuration.ExpressionBuilder.ExpressionPrefix
  - System.Web.Configuration.ExpressionBuilder.Properties
  - System.Web.Configuration.ExpressionBuilder.Type
  langs:
  - csharp
  name: ExpressionBuilder
  nameWithType: ExpressionBuilder
  fullName: System.Web.Configuration.ExpressionBuilder
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Retrieves a dynamic resource during compilation.
  remarks: "ASP.NET automatically evaluates expressions during page parsing using the <xref:System.Web.Configuration.ExpressionBuilder> class. The <xref:System.Web.Configuration.ExpressionBuilderCollection> collection, which is made up of the `expressionBuilders` elements contained in the `compilation` section of the configuration. The <xref:System.Web.Configuration.ExpressionBuilder> contains specific values in key/value pairs.  \n  \n A value is retrieved by including an expression of the form  \n  \n `<%$ ExpressionPrefix: ExpressionKey %>`  \n  \n within the page. The `ExpressionPrefix` maps the type of expression to be retrieved as either a common expression-builder type (that is, <xref:System.Web.Compilation.AppSettingsExpressionBuilder>) or a custom expression builder type. The `ExpressionKey` specifies the key used to reference the returned value.  \n  \n If you choose to implement a common expression-builder type, you must map the expression builder to the associated section name in the configuration. If you choose to implement a custom expression-builder type, you must map your expression builder to your custom expression-builder class, which must derive from the <xref:System.Web.Configuration.ExpressionBuilder> class."
  syntax:
    content: 'public sealed class ExpressionBuilder : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ExpressionBuilder.xml
- uid: System.Web.Configuration.ExpressionBuilder.#ctor(System.String,System.String)
  commentId: M:System.Web.Configuration.ExpressionBuilder.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.ExpressionBuilder
  langs:
  - csharp
  name: ExpressionBuilder(String, String)
  nameWithType: ExpressionBuilder.ExpressionBuilder(String, String)
  fullName: ExpressionBuilder.ExpressionBuilder(String, String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Configuration.ExpressionBuilder"></xref> class.
  remarks: ''
  example:
  - "The following code example demonstrates how to create an <xref:System.Web.Configuration.ExpressionBuilder> object. This code example is part of a larger example provided for the <xref:System.Web.Configuration.ExpressionBuilderCollection> class.  \n  \n [!code-csharp[System.Web.Configuration.ExpressionBuilderCollection#2](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.ExpressionBuilderCollection/CS/ExpressionBuilderCollection.cs#2)]\n [!code-vb[System.Web.Configuration.ExpressionBuilderCollection#2](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.ExpressionBuilderCollection/VB/ExpressionBuilderCollection.vb#2)]"
  syntax:
    content: public ExpressionBuilder (string expressionPrefix, string theType);
    parameters:
    - id: expressionPrefix
      type: System.String
      description: A string that identifies the type of expression to retrieve.
    - id: theType
      type: System.String
      description: A string that specifies the expression type.
  overload: System.Web.Configuration.ExpressionBuilder.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ExpressionBuilder.xml
- uid: System.Web.Configuration.ExpressionBuilder.ExpressionPrefix
  commentId: P:System.Web.Configuration.ExpressionBuilder.ExpressionPrefix
  id: ExpressionPrefix
  parent: System.Web.Configuration.ExpressionBuilder
  langs:
  - csharp
  name: ExpressionPrefix
  nameWithType: ExpressionBuilder.ExpressionPrefix
  fullName: ExpressionBuilder.ExpressionPrefix
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets or sets a string that identifies the type of expression to retrieve.
  remarks: The <xref:System.Web.Configuration.ExpressionBuilder.ExpressionPrefix%2A> maps the expression to the associated section name in the configuration for common expression types, or maps the expression to the custom expression class.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("expressionPrefix", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsKey=true, IsRequired=true)]

      [System.Configuration.StringValidator(MinLength=1)]

      public string ExpressionPrefix { get; set; }
    return:
      type: System.String
      description: A string that identifies the type of expression to retrieve.
  overload: System.Web.Configuration.ExpressionBuilder.ExpressionPrefix*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ExpressionBuilder.xml
- uid: System.Web.Configuration.ExpressionBuilder.Properties
  commentId: P:System.Web.Configuration.ExpressionBuilder.Properties
  id: Properties
  parent: System.Web.Configuration.ExpressionBuilder
  langs:
  - csharp
  name: Properties
  nameWithType: ExpressionBuilder.Properties
  fullName: ExpressionBuilder.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.ExpressionBuilder.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ExpressionBuilder.xml
- uid: System.Web.Configuration.ExpressionBuilder.Type
  commentId: P:System.Web.Configuration.ExpressionBuilder.Type
  id: Type
  parent: System.Web.Configuration.ExpressionBuilder
  langs:
  - csharp
  name: Type
  nameWithType: ExpressionBuilder.Type
  fullName: ExpressionBuilder.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets or sets a string that specifies the expression type.
  remarks: The <xref:System.Web.Configuration.ExpressionBuilder.Type%2A> specifies the type of object used to determine the value of the expression. The type can specify either a section within the configuration, or a custom class.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("type", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsRequired=true)]

      [System.Configuration.StringValidator(MinLength=1)]

      public string Type { get; set; }
    return:
      type: System.String
      description: A string that specifies the expression type.
  overload: System.Web.Configuration.ExpressionBuilder.Type*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ExpressionBuilder.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.ExpressionBuilder.#ctor(System.String,System.String)
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: ExpressionBuilder(String, String)
  nameWithType: ExpressionBuilder.ExpressionBuilder(String, String)
  fullName: ExpressionBuilder.ExpressionBuilder(String, String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.ExpressionBuilder.ExpressionPrefix
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: ExpressionPrefix
  nameWithType: ExpressionBuilder.ExpressionPrefix
  fullName: ExpressionBuilder.ExpressionPrefix
- uid: System.Web.Configuration.ExpressionBuilder.Properties
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: Properties
  nameWithType: ExpressionBuilder.Properties
  fullName: ExpressionBuilder.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ExpressionBuilder.Type
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: Type
  nameWithType: ExpressionBuilder.Type
  fullName: ExpressionBuilder.Type
- uid: System.Web.Configuration.ExpressionBuilder.#ctor*
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: ExpressionBuilder
  nameWithType: ExpressionBuilder.ExpressionBuilder
  fullName: ExpressionBuilder.ExpressionBuilder
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ExpressionBuilder.xml
- uid: System.Web.Configuration.ExpressionBuilder.ExpressionPrefix*
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: ExpressionPrefix
  nameWithType: ExpressionBuilder.ExpressionPrefix
  fullName: ExpressionBuilder.ExpressionPrefix
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ExpressionBuilder.xml
- uid: System.Web.Configuration.ExpressionBuilder.Properties*
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: Properties
  nameWithType: ExpressionBuilder.Properties
  fullName: ExpressionBuilder.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ExpressionBuilder.xml
- uid: System.Web.Configuration.ExpressionBuilder.Type*
  parent: System.Web.Configuration.ExpressionBuilder
  isExternal: false
  name: Type
  nameWithType: ExpressionBuilder.Type
  fullName: ExpressionBuilder.Type
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ExpressionBuilder.xml
