### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  commentId: T:System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  id: ArgumentElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Name
  - System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Properties
  langs:
  - csharp
  name: ArgumentElement
  nameWithType: ArgumentElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  type: Class
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: A configuration element that represents an argument .
  syntax:
    content: 'public class ArgumentElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/ArgumentElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.#ctor
  commentId: M:System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  langs:
  - csharp
  name: ArgumentElement()
  nameWithType: ArgumentElement.ArgumentElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ArgumentElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement"></xref> class.
  syntax:
    content: public ArgumentElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/ArgumentElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ElementKey
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ElementKey
  id: ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  langs:
  - csharp
  name: ElementKey
  nameWithType: ArgumentElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ElementKey
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets a key that uniquely identifies the argument.
  syntax:
    content: public override object ElementKey { get; }
    return:
      type: System.Object
      description: The element key.
  overload: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ElementKey*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/ArgumentElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Name
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Name
  id: Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  langs:
  - csharp
  name: Name
  nameWithType: ArgumentElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets or sets the name of the argument.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("name", IsKey=true, IsRequired=true)]

      [System.Configuration.StringValidator(MinLength=0)]

      public string Name { get; set; }
    return:
      type: System.String
      description: The argument name.
  overload: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Name*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/ArgumentElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Properties
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  langs:
  - csharp
  name: Properties
  nameWithType: ArgumentElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets the collection of properties
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: The <xref href="System.Configuration.ConfigurationPropertyCollection"></xref> of properties for the element.
  overload: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/ArgumentElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  parent: System.ServiceModel.Activities.Tracking.Configuration
  isExternal: false
  name: TrackingConfigurationElement
  nameWithType: TrackingConfigurationElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  isExternal: false
  name: ArgumentElement()
  nameWithType: ArgumentElement.ArgumentElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ArgumentElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  isExternal: false
  name: ElementKey
  nameWithType: ArgumentElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ElementKey
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  isExternal: false
  name: Name
  nameWithType: ArgumentElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Name
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  isExternal: false
  name: Properties
  nameWithType: ArgumentElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  isExternal: false
  name: ArgumentElement
  nameWithType: ArgumentElement.ArgumentElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ArgumentElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/ArgumentElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ElementKey*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  isExternal: false
  name: ElementKey
  nameWithType: ArgumentElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.ElementKey
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/ArgumentElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Name*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  isExternal: false
  name: Name
  nameWithType: ArgumentElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Name
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/ArgumentElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement
  isExternal: false
  name: Properties
  nameWithType: ArgumentElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ArgumentElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/ArgumentElement.xml
