### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activation.Configuration.DiagnosticSection
  commentId: T:System.ServiceModel.Activation.Configuration.DiagnosticSection
  id: DiagnosticSection
  children:
  - System.ServiceModel.Activation.Configuration.DiagnosticSection.#ctor
  - System.ServiceModel.Activation.Configuration.DiagnosticSection.PerformanceCountersEnabled
  - System.ServiceModel.Activation.Configuration.DiagnosticSection.Properties
  langs:
  - csharp
  name: DiagnosticSection
  nameWithType: DiagnosticSection
  fullName: System.ServiceModel.Activation.Configuration.DiagnosticSection
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: Represents a configuration element for specifying Windows Communication Foundation (WCF) listener's diagnostics functionalities. This class cannot be inherited.
  remarks: This class specifies if performance counters are enabled for the listener.
  syntax:
    content: 'public sealed class DiagnosticSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/DiagnosticSection.xml
- uid: System.ServiceModel.Activation.Configuration.DiagnosticSection.#ctor
  commentId: M:System.ServiceModel.Activation.Configuration.DiagnosticSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activation.Configuration.DiagnosticSection
  langs:
  - csharp
  name: DiagnosticSection()
  nameWithType: DiagnosticSection.DiagnosticSection()
  fullName: DiagnosticSection.DiagnosticSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Activation.Configuration.DiagnosticSection"></xref> class.
  syntax:
    content: public DiagnosticSection ();
    parameters: []
  overload: System.ServiceModel.Activation.Configuration.DiagnosticSection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/DiagnosticSection.xml
- uid: System.ServiceModel.Activation.Configuration.DiagnosticSection.PerformanceCountersEnabled
  commentId: P:System.ServiceModel.Activation.Configuration.DiagnosticSection.PerformanceCountersEnabled
  id: PerformanceCountersEnabled
  parent: System.ServiceModel.Activation.Configuration.DiagnosticSection
  langs:
  - csharp
  name: PerformanceCountersEnabled
  nameWithType: DiagnosticSection.PerformanceCountersEnabled
  fullName: DiagnosticSection.PerformanceCountersEnabled
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: Gets or sets a Boolean value that indicates whether performance counters are enabled for diagnostic purpose.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("performanceCountersEnabled", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public bool PerformanceCountersEnabled { get; set; }
    return:
      type: System.Boolean
      description: '`true` if performance counters are enabled; otherwise, `false`.'
  overload: System.ServiceModel.Activation.Configuration.DiagnosticSection.PerformanceCountersEnabled*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/DiagnosticSection.xml
- uid: System.ServiceModel.Activation.Configuration.DiagnosticSection.Properties
  commentId: P:System.ServiceModel.Activation.Configuration.DiagnosticSection.Properties
  id: Properties
  parent: System.ServiceModel.Activation.Configuration.DiagnosticSection
  langs:
  - csharp
  name: Properties
  nameWithType: DiagnosticSection.Properties
  fullName: DiagnosticSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Activation.Configuration.DiagnosticSection.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/DiagnosticSection.xml
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Activation.Configuration.DiagnosticSection.#ctor
  parent: System.ServiceModel.Activation.Configuration.DiagnosticSection
  isExternal: false
  name: DiagnosticSection()
  nameWithType: DiagnosticSection.DiagnosticSection()
  fullName: DiagnosticSection.DiagnosticSection()
- uid: System.ServiceModel.Activation.Configuration.DiagnosticSection.PerformanceCountersEnabled
  parent: System.ServiceModel.Activation.Configuration.DiagnosticSection
  isExternal: false
  name: PerformanceCountersEnabled
  nameWithType: DiagnosticSection.PerformanceCountersEnabled
  fullName: DiagnosticSection.PerformanceCountersEnabled
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Activation.Configuration.DiagnosticSection.Properties
  parent: System.ServiceModel.Activation.Configuration.DiagnosticSection
  isExternal: false
  name: Properties
  nameWithType: DiagnosticSection.Properties
  fullName: DiagnosticSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activation.Configuration.DiagnosticSection.#ctor*
  parent: System.ServiceModel.Activation.Configuration.DiagnosticSection
  isExternal: false
  name: DiagnosticSection
  nameWithType: DiagnosticSection.DiagnosticSection
  fullName: DiagnosticSection.DiagnosticSection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/DiagnosticSection.xml
- uid: System.ServiceModel.Activation.Configuration.DiagnosticSection.PerformanceCountersEnabled*
  parent: System.ServiceModel.Activation.Configuration.DiagnosticSection
  isExternal: false
  name: PerformanceCountersEnabled
  nameWithType: DiagnosticSection.PerformanceCountersEnabled
  fullName: DiagnosticSection.PerformanceCountersEnabled
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/DiagnosticSection.xml
- uid: System.ServiceModel.Activation.Configuration.DiagnosticSection.Properties*
  parent: System.ServiceModel.Activation.Configuration.DiagnosticSection
  isExternal: false
  name: Properties
  nameWithType: DiagnosticSection.Properties
  fullName: DiagnosticSection.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/DiagnosticSection.xml
