### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MexHttpBindingElement
  commentId: T:System.ServiceModel.Configuration.MexHttpBindingElement
  id: MexHttpBindingElement
  children:
  - System.ServiceModel.Configuration.MexHttpBindingElement.#ctor
  - System.ServiceModel.Configuration.MexHttpBindingElement.#ctor(System.String)
  langs:
  - csharp
  name: MexHttpBindingElement
  nameWithType: MexHttpBindingElement
  fullName: System.ServiceModel.Configuration.MexHttpBindingElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a configuration element that specifies the settings for a binding used for the WS-MetadataExchange (WS-MEX) message exchange over HTTP.
  syntax:
    content: 'public class MexHttpBindingElement : System.ServiceModel.Configuration.MexBindingElement<System.ServiceModel.WSHttpBinding>'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.StandardBindingElement
  - System.ServiceModel.Configuration.MexBindingElement`1
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.MexBindingElement`1.BindingElementType
  - System.ServiceModel.Configuration.MexBindingElement`1.OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.StandardBindingElement.ApplyConfiguration(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.StandardBindingElement.CloseTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.InitializeFrom(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.StandardBindingElement.Name
  - System.ServiceModel.Configuration.StandardBindingElement.OpenTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.Properties
  - System.ServiceModel.Configuration.StandardBindingElement.ReceiveTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.StandardBindingElement.SendTimeout
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexHttpBindingElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.MexHttpBindingElement.#ctor
  commentId: M:System.ServiceModel.Configuration.MexHttpBindingElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.MexHttpBindingElement
  langs:
  - csharp
  name: MexHttpBindingElement()
  nameWithType: MexHttpBindingElement.MexHttpBindingElement()
  fullName: System.ServiceModel.Configuration.MexHttpBindingElement.MexHttpBindingElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.MexHttpBindingElement"></xref> class.
  syntax:
    content: public MexHttpBindingElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.MexHttpBindingElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexHttpBindingElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.MexHttpBindingElement.#ctor(System.String)
  commentId: M:System.ServiceModel.Configuration.MexHttpBindingElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.MexHttpBindingElement
  langs:
  - csharp
  name: MexHttpBindingElement(String)
  nameWithType: MexHttpBindingElement.MexHttpBindingElement(String)
  fullName: System.ServiceModel.Configuration.MexHttpBindingElement.MexHttpBindingElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.MexHttpBindingElement"></xref> class with the specified name.
  syntax:
    content: public MexHttpBindingElement (string name);
    parameters:
    - id: name
      type: System.String
      description: The name of the binding.
  overload: System.ServiceModel.Configuration.MexHttpBindingElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexHttpBindingElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.ServiceModel.Configuration.MexBindingElement`1
  name: MexBindingElement<TStandardBinding>
  nameWithType: MexBindingElement<TStandardBinding>
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>
- uid: System.ServiceModel.WSHttpBinding
  name: WSHttpBinding
  nameWithType: WSHttpBinding
  fullName: System.ServiceModel.WSHttpBinding
- uid: System.ServiceModel.Configuration.MexBindingElement{System.ServiceModel.WSHttpBinding}
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: MexBindingElement<WSHttpBinding>
  nameWithType: MexBindingElement<WSHttpBinding>
  fullName: System.ServiceModel.Configuration.MexBindingElement<System.ServiceModel.WSHttpBinding>
  spec.csharp:
  - uid: System.ServiceModel.Configuration.MexBindingElement`1
    name: MexBindingElement
    nameWithType: MexBindingElement
    fullName: System.ServiceModel.Configuration.MexBindingElement
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.WSHttpBinding
    name: WSHttpBinding
    nameWithType: WSHttpBinding
    fullName: System.ServiceModel.WSHttpBinding
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.MexHttpBindingElement.#ctor
  parent: System.ServiceModel.Configuration.MexHttpBindingElement
  isExternal: false
  name: MexHttpBindingElement()
  nameWithType: MexHttpBindingElement.MexHttpBindingElement()
  fullName: System.ServiceModel.Configuration.MexHttpBindingElement.MexHttpBindingElement()
- uid: System.ServiceModel.Configuration.MexHttpBindingElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.MexHttpBindingElement
  isExternal: false
  name: MexHttpBindingElement(String)
  nameWithType: MexHttpBindingElement.MexHttpBindingElement(String)
  fullName: System.ServiceModel.Configuration.MexHttpBindingElement.MexHttpBindingElement(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.MexHttpBindingElement.#ctor*
  parent: System.ServiceModel.Configuration.MexHttpBindingElement
  isExternal: false
  name: MexHttpBindingElement
  nameWithType: MexHttpBindingElement.MexHttpBindingElement
  fullName: System.ServiceModel.Configuration.MexHttpBindingElement.MexHttpBindingElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexHttpBindingElement.xml
