### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NamedPipeSettingsElement
  commentId: T:System.ServiceModel.Configuration.NamedPipeSettingsElement
  id: NamedPipeSettingsElement
  children:
  - System.ServiceModel.Configuration.NamedPipeSettingsElement.#ctor
  - System.ServiceModel.Configuration.NamedPipeSettingsElement.ApplicationContainerSettings
  - System.ServiceModel.Configuration.NamedPipeSettingsElement.Properties
  langs:
  - csharp
  name: NamedPipeSettingsElement
  nameWithType: NamedPipeSettingsElement
  fullName: System.ServiceModel.Configuration.NamedPipeSettingsElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a named pipe settings element.
  syntax:
    content: 'public sealed class NamedPipeSettingsElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NamedPipeSettingsElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.NamedPipeSettingsElement.#ctor
  commentId: M:System.ServiceModel.Configuration.NamedPipeSettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NamedPipeSettingsElement
  langs:
  - csharp
  name: NamedPipeSettingsElement()
  nameWithType: NamedPipeSettingsElement.NamedPipeSettingsElement()
  fullName: System.ServiceModel.Configuration.NamedPipeSettingsElement.NamedPipeSettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.NamedPipeSettingsElement"></xref> class.
  syntax:
    content: public NamedPipeSettingsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NamedPipeSettingsElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NamedPipeSettingsElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.NamedPipeSettingsElement.ApplicationContainerSettings
  commentId: P:System.ServiceModel.Configuration.NamedPipeSettingsElement.ApplicationContainerSettings
  id: ApplicationContainerSettings
  parent: System.ServiceModel.Configuration.NamedPipeSettingsElement
  langs:
  - csharp
  name: ApplicationContainerSettings
  nameWithType: NamedPipeSettingsElement.ApplicationContainerSettings
  fullName: System.ServiceModel.Configuration.NamedPipeSettingsElement.ApplicationContainerSettings
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the application container settings used in <xref href="System.ServiceModel.Configuration.NamedPipeSettingsElement"></xref>.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("applicationContainerSettings")]

      public System.ServiceModel.Configuration.ApplicationContainerSettingsElement ApplicationContainerSettings { get; set; }
    return:
      type: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
      description: The application container settings.
  overload: System.ServiceModel.Configuration.NamedPipeSettingsElement.ApplicationContainerSettings*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NamedPipeSettingsElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.NamedPipeSettingsElement.Properties
  commentId: P:System.ServiceModel.Configuration.NamedPipeSettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.NamedPipeSettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: NamedPipeSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.NamedPipeSettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.NamedPipeSettingsElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NamedPipeSettingsElement.xml
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.NamedPipeSettingsElement.#ctor
  parent: System.ServiceModel.Configuration.NamedPipeSettingsElement
  isExternal: false
  name: NamedPipeSettingsElement()
  nameWithType: NamedPipeSettingsElement.NamedPipeSettingsElement()
  fullName: System.ServiceModel.Configuration.NamedPipeSettingsElement.NamedPipeSettingsElement()
- uid: System.ServiceModel.Configuration.NamedPipeSettingsElement.ApplicationContainerSettings
  parent: System.ServiceModel.Configuration.NamedPipeSettingsElement
  isExternal: false
  name: ApplicationContainerSettings
  nameWithType: NamedPipeSettingsElement.ApplicationContainerSettings
  fullName: System.ServiceModel.Configuration.NamedPipeSettingsElement.ApplicationContainerSettings
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ApplicationContainerSettingsElement
  nameWithType: ApplicationContainerSettingsElement
  fullName: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
- uid: System.ServiceModel.Configuration.NamedPipeSettingsElement.Properties
  parent: System.ServiceModel.Configuration.NamedPipeSettingsElement
  isExternal: false
  name: Properties
  nameWithType: NamedPipeSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.NamedPipeSettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.NamedPipeSettingsElement.#ctor*
  parent: System.ServiceModel.Configuration.NamedPipeSettingsElement
  isExternal: false
  name: NamedPipeSettingsElement
  nameWithType: NamedPipeSettingsElement.NamedPipeSettingsElement
  fullName: System.ServiceModel.Configuration.NamedPipeSettingsElement.NamedPipeSettingsElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NamedPipeSettingsElement.xml
- uid: System.ServiceModel.Configuration.NamedPipeSettingsElement.ApplicationContainerSettings*
  parent: System.ServiceModel.Configuration.NamedPipeSettingsElement
  isExternal: false
  name: ApplicationContainerSettings
  nameWithType: NamedPipeSettingsElement.ApplicationContainerSettings
  fullName: System.ServiceModel.Configuration.NamedPipeSettingsElement.ApplicationContainerSettings
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NamedPipeSettingsElement.xml
- uid: System.ServiceModel.Configuration.NamedPipeSettingsElement.Properties*
  parent: System.ServiceModel.Configuration.NamedPipeSettingsElement
  isExternal: false
  name: Properties
  nameWithType: NamedPipeSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.NamedPipeSettingsElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NamedPipeSettingsElement.xml
