### YamlMime:ManagedReference
items:
- uid: System.Configuration.InfiniteTimeSpanConverter
  commentId: T:System.Configuration.InfiniteTimeSpanConverter
  id: InfiniteTimeSpanConverter
  children:
  - System.Configuration.InfiniteTimeSpanConverter.#ctor
  - System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.InfiniteTimeSpanConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: InfiniteTimeSpanConverter
  nameWithType: InfiniteTimeSpanConverter
  fullName: System.Configuration.InfiniteTimeSpanConverter
  type: Class
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Converts between a string and the standard infinite <xref href="System.TimeSpan"></xref> value.
  remarks: "This type, like all the other configuration converter types, converts strings found in the configuration file to and from the related strongly typed properties.  \n  \n In particular the <xref:System.Configuration.InfiniteTimeSpanConverter> converts the <xref:System.String> value \"infinite\" assigned to a configuration property to the standard infinite <xref:System.TimeSpan> and vice versa. The infinite <xref:System.TimeSpan> value is represented by the <xref:System.TimeSpan.MaxValue> enumeration value.  \n  \n This converter is used with <xref:System.TimeSpan> properties. An infinite value is persisted as the \"infinite\" string."
  example:
  - "The following code example shows how to define a custom section property that uses the <xref:System.Configuration.InfiniteTimeSpanConverter> class.  \n  \n For the complete example code that implements the custom section, refer to the <xref:System.Configuration.ConfigurationConverterBase> class.  \n  \n [!code-csharp[System.Configuration.ConfigurationConvertersCustomSection#3](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Configuration.ConfigurationConvertersCustomSection/CS/ConfigurationConvertersCustomSection.cs#3)]\n [!code-vb[System.Configuration.ConfigurationConvertersCustomSection#3](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Configuration.ConfigurationConvertersCustomSection/VB/ConfigurationConvertersCustomSection.vb#3)]  \n  \n The following example code shows how to access the previous custom section property.  \n  \n [!code-csharp[System.Configuration.InfiniteTimeSpanConverter#1](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Configuration.InfiniteTimeSpanConverter/CS/InfiniteTimeSpanConverter.cs#1)]\n [!code-vb[System.Configuration.InfiniteTimeSpanConverter#1](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Configuration.InfiniteTimeSpanConverter/VB/InfiniteTimeSpanConverter.vb#1)]  \n  \n The following is a configuration excerpt as used by the previous example.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n  <configSections>  \n    <section name=\"CustomSection\"   \n      type=\"Samples.AspNet.CustomSection,   \n      ConfigurationConverters,   \n      Version=1.0.0.0, Culture=neutral,   \n      PublicKeyToken=null\"   \n      allowDefinition=\"Everywhere\"   \n      allowExeDefinition=\"MachineToApplication\"   \n      restartOnExternalChanges=\"true\" />  \n    </configSections>  \n    <CustomSection fileName=\"default.txt\" maxIdleTime=\"90\" timeDelay=\"infinite\"/>  \n</configuration>  \n```"
  syntax:
    content: 'public sealed class InfiniteTimeSpanConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/InfiniteTimeSpanConverter.xml
- uid: System.Configuration.InfiniteTimeSpanConverter.#ctor
  commentId: M:System.Configuration.InfiniteTimeSpanConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.InfiniteTimeSpanConverter
  langs:
  - csharp
  name: InfiniteTimeSpanConverter()
  nameWithType: InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
  fullName: InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.InfiniteTimeSpanConverter"></xref> class.
  remarks: Normally, you use the converter types provided by the system. The only time you need to use the <xref:System.Configuration.InfiniteTimeSpanConverter.%23ctor%2A> constructor is when you create your own conversion type.
  syntax:
    content: public InfiniteTimeSpanConverter ();
    parameters: []
  overload: System.Configuration.InfiniteTimeSpanConverter.#ctor*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/InfiniteTimeSpanConverter.xml
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  commentId: M:System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.InfiniteTimeSpanConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
  nameWithType: InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
  fullName: InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
  type: Method
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Converts a <xref href="System.String"></xref> to a <xref href="System.TimeSpan"></xref>.
  remarks: The system uses the <xref:System.Configuration.InfiniteTimeSpanConverter.ConvertFrom%2A> method when reading from a configuration file to convert a <xref:System.String> value to <xref:System.TimeSpan> or the <xref:System.String> "infinite" to <xref:System.TimeSpan.MaxValue>.
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: The <xref href="System.ComponentModel.ITypeDescriptorContext"></xref> object used for type conversions.
    - id: ci
      type: System.Globalization.CultureInfo
      description: The <xref href="System.Globalization.CultureInfo"></xref> object used during conversion.
    - id: data
      type: System.Object
      description: The <xref href="System.String"></xref> object to convert.
    return:
      type: System.Object
      description: The <xref href="System.TimeSpan.MaxValue"></xref>, if the <code>data</code> parameter is the <xref href="System.String"></xref> infinite; otherwise, the <xref href="System.TimeSpan"></xref> representing the <code>data</code> parameter in minutes.
  overload: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/InfiniteTimeSpanConverter.xml
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  commentId: M:System.Configuration.InfiniteTimeSpanConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.InfiniteTimeSpanConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
  nameWithType: InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
  fullName: InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
  type: Method
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Converts a <xref href="System.TimeSpan"></xref> to a <xref href="System.String"></xref>.
  remarks: "The system uses the <xref:System.Configuration.InfiniteTimeSpanConverter.ConvertTo%2A> method when writing an attribute to a configuration file to convert a <xref:System.TimeSpan> object to a <xref:System.String> object.  \n  \n The system uses the <xref:System.Configuration.InfiniteTimeSpanConverter.ConvertTo%2A> method when writing to a configuration file to convert a <xref:System.TimeSpan> value or <xref:System.TimeSpan.MaxValue> to a <xref:System.String>."
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: The <xref href="System.ComponentModel.ITypeDescriptorContext"></xref> object used for type conversions.
    - id: ci
      type: System.Globalization.CultureInfo
      description: The <xref href="System.Globalization.CultureInfo"></xref> used during object conversion.
    - id: value
      type: System.Object
      description: The value to convert.
    - id: type
      type: System.Type
      description: The conversion type.
    return:
      type: System.Object
      description: The <xref href="System.String"></xref> "infinite", if the <code>value</code> parameter is <xref href="System.TimeSpan.MaxValue"></xref>; otherwise, the <xref href="System.String"></xref> representing the <code>value</code> parameter in minutes.
  overload: System.Configuration.InfiniteTimeSpanConverter.ConvertTo*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/InfiniteTimeSpanConverter.xml
references:
- uid: System.Configuration.ConfigurationConverterBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationConverterBase
  nameWithType: ConfigurationConverterBase
  fullName: System.Configuration.ConfigurationConverterBase
- uid: System.Configuration.InfiniteTimeSpanConverter.#ctor
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: InfiniteTimeSpanConverter()
  nameWithType: InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
  fullName: InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
  nameWithType: InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
  fullName: InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext, CultureInfo, Object)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: false
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
  nameWithType: InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
  fullName: InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext, CultureInfo, Object, Type)
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.InfiniteTimeSpanConverter.#ctor*
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: InfiniteTimeSpanConverter
  nameWithType: InfiniteTimeSpanConverter.InfiniteTimeSpanConverter
  fullName: InfiniteTimeSpanConverter.InfiniteTimeSpanConverter
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/InfiniteTimeSpanConverter.xml
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom*
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: InfiniteTimeSpanConverter.ConvertFrom
  fullName: InfiniteTimeSpanConverter.ConvertFrom
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/InfiniteTimeSpanConverter.xml
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertTo*
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertTo
  nameWithType: InfiniteTimeSpanConverter.ConvertTo
  fullName: InfiniteTimeSpanConverter.ConvertTo
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/InfiniteTimeSpanConverter.xml
