### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ScriptingRoleServiceSection
  commentId: T:System.Web.Configuration.ScriptingRoleServiceSection
  id: ScriptingRoleServiceSection
  children:
  - System.Web.Configuration.ScriptingRoleServiceSection.#ctor
  - System.Web.Configuration.ScriptingRoleServiceSection.Enabled
  - System.Web.Configuration.ScriptingRoleServiceSection.Properties
  langs:
  - csharp
  name: ScriptingRoleServiceSection
  nameWithType: ScriptingRoleServiceSection
  fullName: System.Web.Configuration.ScriptingRoleServiceSection
  type: Class
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: Represents the configuration section for role-service settings.
  remarks: "The <xref:System.Web.Configuration.ScriptingRoleServiceSection> class enables you to programmatically access and modify the `roleService` element of the configuration section for using AJAX functionality in [!INCLUDE[vstecasp](~/includes/vstecasp-md.md)].  \n  \n The role service is typically used to retrieve role information for the user who is logged on by using an asynchronous Web service call."
  example:
  - "The following configuration file excerpt shows how to declaratively specify values for the <xref:System.Web.Configuration.ScriptingRoleServiceSection.Enabled%2A> property of the <xref:System.Web.Configuration.ScriptingRoleServiceSection> class.  \n  \n```  \n<system.web.extensions>  \n  <scripting>  \n    <webServices>  \n      <roleService enabled=\"true\" />  \n    </webServices>  \n  </scripting>  \n</system.web.extensions>  \n```  \n  \n The following example shows how to access the <xref:System.Web.Configuration.ScriptingRoleServiceSection> element programmatically.  \n  \n [!code-csharp[System.Web.Configuration#4](~/samples/snippets/csharp/VS_Snippets_Atlas/System.Web.Configuration/CS/App_Code/ConfigSectionSample.cs#4)]\n [!code-vb[System.Web.Configuration#4](~/samples/snippets/visualbasic/VS_Snippets_Atlas/System.Web.Configuration/VB/App_Code/ConfigSectionSample.vb#4)]"
  syntax:
    content: 'public sealed class ScriptingRoleServiceSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingRoleServiceSection.xml
- uid: System.Web.Configuration.ScriptingRoleServiceSection.#ctor
  commentId: M:System.Web.Configuration.ScriptingRoleServiceSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  langs:
  - csharp
  name: ScriptingRoleServiceSection()
  nameWithType: ScriptingRoleServiceSection.ScriptingRoleServiceSection()
  fullName: ScriptingRoleServiceSection.ScriptingRoleServiceSection()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Configuration.ScriptingRoleServiceSection"></xref> class.
  syntax:
    content: public ScriptingRoleServiceSection ();
    parameters: []
  overload: System.Web.Configuration.ScriptingRoleServiceSection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingRoleServiceSection.xml
- uid: System.Web.Configuration.ScriptingRoleServiceSection.Enabled
  commentId: P:System.Web.Configuration.ScriptingRoleServiceSection.Enabled
  id: Enabled
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  langs:
  - csharp
  name: Enabled
  nameWithType: ScriptingRoleServiceSection.Enabled
  fullName: ScriptingRoleServiceSection.Enabled
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: Gets or sets a value that indicates whether the role service is enabled for an [!INCLUDE[vstecasp](~/includes/vstecasp-md.md)] application that uses AJAX features.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("enabled", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: '`true` if the role service is enabled; otherwise, `false`. The default is `false`.'
  overload: System.Web.Configuration.ScriptingRoleServiceSection.Enabled*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingRoleServiceSection.xml
- uid: System.Web.Configuration.ScriptingRoleServiceSection.Properties
  commentId: P:System.Web.Configuration.ScriptingRoleServiceSection.Properties
  id: Properties
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  langs:
  - csharp
  name: Properties
  nameWithType: ScriptingRoleServiceSection.Properties
  fullName: ScriptingRoleServiceSection.Properties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.ScriptingRoleServiceSection.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingRoleServiceSection.xml
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.ScriptingRoleServiceSection.#ctor
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  isExternal: false
  name: ScriptingRoleServiceSection()
  nameWithType: ScriptingRoleServiceSection.ScriptingRoleServiceSection()
  fullName: ScriptingRoleServiceSection.ScriptingRoleServiceSection()
- uid: System.Web.Configuration.ScriptingRoleServiceSection.Enabled
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  isExternal: false
  name: Enabled
  nameWithType: ScriptingRoleServiceSection.Enabled
  fullName: ScriptingRoleServiceSection.Enabled
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.ScriptingRoleServiceSection.Properties
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingRoleServiceSection.Properties
  fullName: ScriptingRoleServiceSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ScriptingRoleServiceSection.#ctor*
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  isExternal: false
  name: ScriptingRoleServiceSection
  nameWithType: ScriptingRoleServiceSection.ScriptingRoleServiceSection
  fullName: ScriptingRoleServiceSection.ScriptingRoleServiceSection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingRoleServiceSection.xml
- uid: System.Web.Configuration.ScriptingRoleServiceSection.Enabled*
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  isExternal: false
  name: Enabled
  nameWithType: ScriptingRoleServiceSection.Enabled
  fullName: ScriptingRoleServiceSection.Enabled
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingRoleServiceSection.xml
- uid: System.Web.Configuration.ScriptingRoleServiceSection.Properties*
  parent: System.Web.Configuration.ScriptingRoleServiceSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingRoleServiceSection.Properties
  fullName: ScriptingRoleServiceSection.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ScriptingRoleServiceSection.xml
