### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationAbortedException
  commentId: T:System.Activities.WorkflowApplicationAbortedException
  id: WorkflowApplicationAbortedException
  children:
  - System.Activities.WorkflowApplicationAbortedException.#ctor
  - System.Activities.WorkflowApplicationAbortedException.#ctor(System.String)
  - System.Activities.WorkflowApplicationAbortedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Exception)
  - System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid)
  - System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid,System.Exception)
  langs:
  - csharp
  name: WorkflowApplicationAbortedException
  nameWithType: WorkflowApplicationAbortedException
  fullName: System.Activities.WorkflowApplicationAbortedException
  type: Class
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: Represents the exception that is thrown when an operation on a workflow instance is not valid because the instance has been aborted.
  syntax:
    content: 'public class WorkflowApplicationAbortedException : System.Activities.WorkflowApplicationException'
  inheritance:
  - System.Object
  - System.Exception
  - System.Activities.WorkflowApplicationException
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationException.InstanceId
  - System.Exception.Data
  - System.Exception.GetBaseException
  - System.Exception.GetType
  - System.Exception.HelpLink
  - System.Exception.HResult
  - System.Exception.InnerException
  - System.Exception.Message
  - System.Exception.SerializeObjectState
  - System.Exception.Source
  - System.Exception.StackTrace
  - System.Exception.TargetSite
  - System.Exception.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationAbortedException.xml
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor
  commentId: M:System.Activities.WorkflowApplicationAbortedException.#ctor
  id: '#ctor'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException()
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException()
  fullName: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: Creates a new instance of the <xref href="System.Activities.WorkflowApplicationAbortedException"></xref> class.
  syntax:
    content: public WorkflowApplicationAbortedException ();
    parameters: []
  overload: System.Activities.WorkflowApplicationAbortedException.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationAbortedException.xml
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String)
  commentId: M:System.Activities.WorkflowApplicationAbortedException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException(String)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String)
  fullName: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: Creates a new instance of the <xref href="System.Activities.WorkflowApplicationAbortedException"></xref> class with a text string description of the exception.
  syntax:
    content: public WorkflowApplicationAbortedException (string message);
    parameters:
    - id: message
      type: System.String
      description: A description of the abort exception.
  overload: System.Activities.WorkflowApplicationAbortedException.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationAbortedException.xml
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  commentId: M:System.Activities.WorkflowApplicationAbortedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException(SerializationInfo, StreamingContext)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(SerializationInfo, StreamingContext)
  fullName: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(SerializationInfo, StreamingContext)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: Creates a new instance of the <xref href="System.Activities.WorkflowApplicationAbortedException"></xref> class with the context and serialization information required to retrieve data about this exception from a serialized stream.
  syntax:
    content: protected WorkflowApplicationAbortedException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: All the information required to serialize or deserialize the abort exception object.
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: The source and destination of a given serialized stream and an additional caller-defined context.
  overload: System.Activities.WorkflowApplicationAbortedException.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationAbortedException.xml
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Exception)
  commentId: M:System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException(String, Exception)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String, Exception)
  fullName: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String, Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: Creates a new instance of the <xref href="System.Activities.WorkflowApplicationAbortedException"></xref> class with a text string description of the exception and an additional exception that is the cause of the abort exception.
  syntax:
    content: public WorkflowApplicationAbortedException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: A description of the abort exception.
    - id: innerException
      type: System.Exception
      description: An exception that has a causal relationship to the application aborted exception. The application aborted exception is thrown in response to the inner exception and can use information from the inner exception to handle the error more appropriately.
  overload: System.Activities.WorkflowApplicationAbortedException.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationAbortedException.xml
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid)
  commentId: M:System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid)
  id: '#ctor(System.String,System.Guid)'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException(String, Guid)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String, Guid)
  fullName: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String, Guid)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: Creates a new instance of the <xref href="System.Activities.WorkflowApplicationAbortedException"></xref> class with a text string description of the abort exception and with a unique identifier for it.
  syntax:
    content: public WorkflowApplicationAbortedException (string message, Guid instanceId);
    parameters:
    - id: message
      type: System.String
      description: A description of the abort exception.
    - id: instanceId
      type: System.Guid
      description: A globally unique identifier.
  overload: System.Activities.WorkflowApplicationAbortedException.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationAbortedException.xml
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid,System.Exception)
  commentId: M:System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid,System.Exception)
  id: '#ctor(System.String,System.Guid,System.Exception)'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException(String, Guid, Exception)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String, Guid, Exception)
  fullName: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String, Guid, Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: Creates a new instance of the <xref href="System.Activities.WorkflowApplicationAbortedException"></xref> class with a text string description of the abort exception, a unique identifier for it, and an additional exception that is the cause of the abort exception.
  syntax:
    content: public WorkflowApplicationAbortedException (string message, Guid instanceId, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: A description of the abort exception.
    - id: instanceId
      type: System.Guid
      description: A globally unique identifier.
    - id: innerException
      type: System.Exception
      description: An exception that has a causal relationship to the application aborted exception. The application aborted exception is thrown in response to the inner exception and can use information from the inner exception to handle the error more appropriately.
  overload: System.Activities.WorkflowApplicationAbortedException.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationAbortedException.xml
references:
- uid: System.Activities.WorkflowApplicationException
  parent: System.Activities
  isExternal: false
  name: WorkflowApplicationException
  nameWithType: WorkflowApplicationException
  fullName: System.Activities.WorkflowApplicationException
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException()
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException()
  fullName: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException()
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String)
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException(String)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String)
  fullName: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException(SerializationInfo, StreamingContext)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(SerializationInfo, StreamingContext)
  fullName: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(SerializationInfo, StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: false
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Exception)
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException(String, Exception)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String, Exception)
  fullName: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String, Exception)
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid)
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException(String, Guid)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String, Guid)
  fullName: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String, Guid)
- uid: System.Guid
  parent: System
  isExternal: false
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid,System.Exception)
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException(String, Guid, Exception)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String, Guid, Exception)
  fullName: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String, Guid, Exception)
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor*
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException
  fullName: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities/WorkflowApplicationAbortedException.xml
