### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement
  commentId: T:System.ServiceModel.Configuration.NetMsmqSecurityElement
  id: NetMsmqSecurityElement
  children:
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
  - System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
  langs:
  - csharp
  name: NetMsmqSecurityElement
  nameWithType: NetMsmqSecurityElement
  fullName: System.ServiceModel.Configuration.NetMsmqSecurityElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: The <xref href="System.ServiceModel.Configuration.NetMsmqSecurityElement"></xref> class encapsulates the MSMQ security features available when using the <xref href="System.ServiceModel.NetMsmqBinding"></xref> binding.
  remarks: Objects of this type are created by creating an instance of the <xref:System.ServiceModel.NetMsmqBinding> binding. You can then use this object to reference all of the various security settings related to the <xref:System.ServiceModel.NetMsmqBinding> binding.
  syntax:
    content: 'public sealed class NetMsmqSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetMsmqSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor
  commentId: M:System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: NetMsmqSecurityElement()
  nameWithType: NetMsmqSecurityElement.NetMsmqSecurityElement()
  fullName: NetMsmqSecurityElement.NetMsmqSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.NetMsmqSecurityElement"></xref> class.
  syntax:
    content: public NetMsmqSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetMsmqSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
  commentId: P:System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
  id: Message
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: Message
  nameWithType: NetMsmqSecurityElement.Message
  fullName: NetMsmqSecurityElement.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets the <xref href="System.ServiceModel.MessageSecurityOverMsmq"></xref> instance that is associated with the <xref href="System.ServiceModel.NetMsmqBinding"></xref> binding.
  remarks: The <xref:System.ServiceModel.MessageSecurityOverMsmq> instance encapsulates the SOAP message security settings.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("message")]

      public System.ServiceModel.Configuration.MessageSecurityOverMsmqElement Message { get; }
    return:
      type: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
      description: The <xref href="System.ServiceModel.MessageSecurityOverMsmq"></xref> instance that is associated with the <xref href="System.ServiceModel.NetMsmqBinding"></xref> binding.
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetMsmqSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
  commentId: P:System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: NetMsmqSecurityElement.Mode
  fullName: NetMsmqSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the <xref href="System.ServiceModel.NetMsmqSecurityMode"></xref> instance that is associated with the <xref href="System.ServiceModel.NetMsmqBinding"></xref> binding.
  remarks: "This property determines the type of security used by the associated `NetMsmqBinding`. The following list describes the acceptable values:  \n  \n-   `None` - No security will be used.  \n  \n-   `Transport` - Transport security will be used.  \n  \n-   `Message` - Message-based security will be used.  \n  \n-   `Both` - Both message-based security and transport security will be used."
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("mode", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.ServiceModel.NetMsmqSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.NetMsmqSecurityMode
      description: The <xref href="System.ServiceModel.NetMsmqSecurityMode"></xref> instance that is associated with the <xref href="System.ServiceModel.NetMsmqBinding"></xref> binding.
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetMsmqSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
  commentId: P:System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: NetMsmqSecurityElement.Properties
  fullName: NetMsmqSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetMsmqSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
  commentId: P:System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
  id: Transport
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  langs:
  - csharp
  name: Transport
  nameWithType: NetMsmqSecurityElement.Transport
  fullName: NetMsmqSecurityElement.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets the <xref href="System.ServiceModel.Configuration.MsmqTransportSecurityElement"></xref> element that is associated with the <xref href="System.ServiceModel.NetMsmqBinding"></xref> binding.
  remarks: This property enables access to Msmq Transport security settings.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("transport")]

      public System.ServiceModel.Configuration.MsmqTransportSecurityElement Transport { get; }
    return:
      type: System.ServiceModel.Configuration.MsmqTransportSecurityElement
      description: The <xref href="System.ServiceModel.MsmqTransportSecurity"></xref> instance that is associated with the <xref href="System.ServiceModel.NetMsmqBinding"></xref> binding.
  overload: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetMsmqSecurityElement.xml
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: NetMsmqSecurityElement()
  nameWithType: NetMsmqSecurityElement.NetMsmqSecurityElement()
  fullName: NetMsmqSecurityElement.NetMsmqSecurityElement()
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Message
  nameWithType: NetMsmqSecurityElement.Message
  fullName: NetMsmqSecurityElement.Message
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: MessageSecurityOverMsmqElement
  nameWithType: MessageSecurityOverMsmqElement
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Mode
  nameWithType: NetMsmqSecurityElement.Mode
  fullName: NetMsmqSecurityElement.Mode
- uid: System.ServiceModel.NetMsmqSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: NetMsmqSecurityMode
  nameWithType: NetMsmqSecurityMode
  fullName: System.ServiceModel.NetMsmqSecurityMode
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NetMsmqSecurityElement.Properties
  fullName: NetMsmqSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Transport
  nameWithType: NetMsmqSecurityElement.Transport
  fullName: NetMsmqSecurityElement.Transport
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: MsmqTransportSecurityElement
  nameWithType: MsmqTransportSecurityElement
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: NetMsmqSecurityElement
  nameWithType: NetMsmqSecurityElement.NetMsmqSecurityElement
  fullName: NetMsmqSecurityElement.NetMsmqSecurityElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetMsmqSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Message*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Message
  nameWithType: NetMsmqSecurityElement.Message
  fullName: NetMsmqSecurityElement.Message
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetMsmqSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Mode
  nameWithType: NetMsmqSecurityElement.Mode
  fullName: NetMsmqSecurityElement.Mode
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetMsmqSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NetMsmqSecurityElement.Properties
  fullName: NetMsmqSecurityElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetMsmqSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetMsmqSecurityElement.Transport*
  parent: System.ServiceModel.Configuration.NetMsmqSecurityElement
  isExternal: false
  name: Transport
  nameWithType: NetMsmqSecurityElement.Transport
  fullName: NetMsmqSecurityElement.Transport
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetMsmqSecurityElement.xml
