### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsManageabilityAttribute
  commentId: T:System.Configuration.SettingsManageabilityAttribute
  id: SettingsManageabilityAttribute
  children:
  - System.Configuration.SettingsManageabilityAttribute.#ctor(System.Configuration.SettingsManageability)
  - System.Configuration.SettingsManageabilityAttribute.Manageability
  langs:
  - csharp
  name: SettingsManageabilityAttribute
  nameWithType: SettingsManageabilityAttribute
  fullName: System.Configuration.SettingsManageabilityAttribute
  type: Class
  assemblies:
  - System
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Specifies special services for application settings properties. This class cannot be inherited.
  remarks: "The <xref:System.Configuration.SettingsManageabilityAttribute> indicates that special, predefined services are to be provided to individual application settings properties and property groups. Most of these services will be provided by the Windows operating system.  \n  \n For more information about application settings properties and their use, see [Application Settings for Windows Forms](~/docs/framework/winforms/advanced/application-settings-for-windows-forms.md)."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SettingsManageabilityAttribute : Attribute
  inheritance:
  - System.Object
  - System.Attribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.AttributeUsageAttribute
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsManageabilityAttribute.xml
- uid: System.Configuration.SettingsManageabilityAttribute.#ctor(System.Configuration.SettingsManageability)
  commentId: M:System.Configuration.SettingsManageabilityAttribute.#ctor(System.Configuration.SettingsManageability)
  id: '#ctor(System.Configuration.SettingsManageability)'
  parent: System.Configuration.SettingsManageabilityAttribute
  langs:
  - csharp
  name: SettingsManageabilityAttribute(SettingsManageability)
  nameWithType: SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
  fullName: SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
  type: Constructor
  assemblies:
  - System
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.SettingsManageabilityAttribute"></xref> class.
  remarks: Multiple services can be requested by combining together values defined by the <xref:System.Configuration.SettingsManageability> enumeration with the logical `OR` operator.
  syntax:
    content: public SettingsManageabilityAttribute (System.Configuration.SettingsManageability manageability);
    parameters:
    - id: manageability
      type: System.Configuration.SettingsManageability
      description: A <xref href="System.Configuration.SettingsManageability"></xref> value that enumerates the services being requested.
  overload: System.Configuration.SettingsManageabilityAttribute.#ctor*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsManageabilityAttribute.xml
- uid: System.Configuration.SettingsManageabilityAttribute.Manageability
  commentId: P:System.Configuration.SettingsManageabilityAttribute.Manageability
  id: Manageability
  parent: System.Configuration.SettingsManageabilityAttribute
  langs:
  - csharp
  name: Manageability
  nameWithType: SettingsManageabilityAttribute.Manageability
  fullName: SettingsManageabilityAttribute.Manageability
  type: Property
  assemblies:
  - System
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Gets the set of special services that have been requested.
  remarks: This property is set in the <xref:System.Configuration.SettingsManageabilityAttribute.%23ctor%2A> constructor.
  syntax:
    content: public System.Configuration.SettingsManageability Manageability { get; }
    return:
      type: System.Configuration.SettingsManageability
      description: A value that results from using the logical `OR` operator to combine all the <xref href="System.Configuration.SettingsManageability"></xref> enumeration values corresponding to the requested services.
  overload: System.Configuration.SettingsManageabilityAttribute.Manageability*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsManageabilityAttribute.xml
references:
- uid: System.Attribute
  parent: System
  isExternal: false
  name: Attribute
  nameWithType: Attribute
  fullName: System.Attribute
- uid: System.Configuration.SettingsManageabilityAttribute.#ctor(System.Configuration.SettingsManageability)
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: SettingsManageabilityAttribute(SettingsManageability)
  nameWithType: SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
  fullName: SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
- uid: System.Configuration.SettingsManageability
  parent: System.Configuration
  isExternal: false
  name: SettingsManageability
  nameWithType: SettingsManageability
  fullName: System.Configuration.SettingsManageability
- uid: System.Configuration.SettingsManageabilityAttribute.Manageability
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: Manageability
  nameWithType: SettingsManageabilityAttribute.Manageability
  fullName: SettingsManageabilityAttribute.Manageability
- uid: System.Configuration.SettingsManageabilityAttribute.#ctor*
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: SettingsManageabilityAttribute
  nameWithType: SettingsManageabilityAttribute.SettingsManageabilityAttribute
  fullName: SettingsManageabilityAttribute.SettingsManageabilityAttribute
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsManageabilityAttribute.xml
- uid: System.Configuration.SettingsManageabilityAttribute.Manageability*
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: Manageability
  nameWithType: SettingsManageabilityAttribute.Manageability
  fullName: SettingsManageabilityAttribute.Manageability
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsManageabilityAttribute.xml
