### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MsmqIntegrationBindingCollectionElement
  commentId: T:System.ServiceModel.Configuration.MsmqIntegrationBindingCollectionElement
  id: MsmqIntegrationBindingCollectionElement
  children:
  - System.ServiceModel.Configuration.MsmqIntegrationBindingCollectionElement.#ctor
  langs:
  - csharp
  name: MsmqIntegrationBindingCollectionElement
  nameWithType: MsmqIntegrationBindingCollectionElement
  fullName: System.ServiceModel.Configuration.MsmqIntegrationBindingCollectionElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a collection of MsmqIntegrationBindingElements.
  syntax:
    content: 'public class MsmqIntegrationBindingCollectionElement : System.ServiceModel.Configuration.StandardBindingCollectionElement<System.ServiceModel.MsmqIntegration.MsmqIntegrationBinding,System.ServiceModel.Configuration.MsmqIntegrationBindingElement>'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.BindingCollectionElement
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Bindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.BindingType
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ConfiguredBindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ContainsKey(System.String)
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.GetDefault
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Properties
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MsmqIntegrationBindingCollectionElement.xml
- uid: System.ServiceModel.Configuration.MsmqIntegrationBindingCollectionElement.#ctor
  commentId: M:System.ServiceModel.Configuration.MsmqIntegrationBindingCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.MsmqIntegrationBindingCollectionElement
  langs:
  - csharp
  name: MsmqIntegrationBindingCollectionElement()
  nameWithType: MsmqIntegrationBindingCollectionElement.MsmqIntegrationBindingCollectionElement()
  fullName: MsmqIntegrationBindingCollectionElement.MsmqIntegrationBindingCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Creates a new instance of <xref href="System.ServiceModel.Configuration.MsmqIntegrationBindingCollectionElement"></xref>.
  syntax:
    content: public MsmqIntegrationBindingCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.MsmqIntegrationBindingCollectionElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MsmqIntegrationBindingCollectionElement.xml
references:
- uid: System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  name: StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  nameWithType: StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationBinding
  name: MsmqIntegrationBinding
  nameWithType: MsmqIntegrationBinding
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationBinding
- uid: System.ServiceModel.Configuration.MsmqIntegrationBindingElement
  name: MsmqIntegrationBindingElement
  nameWithType: MsmqIntegrationBindingElement
  fullName: System.ServiceModel.Configuration.MsmqIntegrationBindingElement
- uid: System.ServiceModel.Configuration.StandardBindingCollectionElement{System.ServiceModel.MsmqIntegration.MsmqIntegrationBinding,System.ServiceModel.Configuration.MsmqIntegrationBindingElement}
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: StandardBindingCollectionElement<MsmqIntegrationBinding,MsmqIntegrationBindingElement>
  nameWithType: StandardBindingCollectionElement<MsmqIntegrationBinding,MsmqIntegrationBindingElement>
  fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement<System.ServiceModel.MsmqIntegration.MsmqIntegrationBinding,System.ServiceModel.Configuration.MsmqIntegrationBindingElement>
  spec.csharp:
  - uid: System.ServiceModel.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationBinding
    name: MsmqIntegrationBinding
    nameWithType: MsmqIntegrationBinding
    fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationBinding
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.ServiceModel.Configuration.MsmqIntegrationBindingElement
    name: MsmqIntegrationBindingElement
    nameWithType: MsmqIntegrationBindingElement
    fullName: System.ServiceModel.Configuration.MsmqIntegrationBindingElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.MsmqIntegrationBindingCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.MsmqIntegrationBindingCollectionElement
  isExternal: false
  name: MsmqIntegrationBindingCollectionElement()
  nameWithType: MsmqIntegrationBindingCollectionElement.MsmqIntegrationBindingCollectionElement()
  fullName: MsmqIntegrationBindingCollectionElement.MsmqIntegrationBindingCollectionElement()
- uid: System.ServiceModel.Configuration.MsmqIntegrationBindingCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.MsmqIntegrationBindingCollectionElement
  isExternal: false
  name: MsmqIntegrationBindingCollectionElement
  nameWithType: MsmqIntegrationBindingCollectionElement.MsmqIntegrationBindingCollectionElement
  fullName: MsmqIntegrationBindingCollectionElement.MsmqIntegrationBindingCollectionElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MsmqIntegrationBindingCollectionElement.xml
