### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WS2007HttpBindingElement
  commentId: T:System.ServiceModel.Configuration.WS2007HttpBindingElement
  id: WS2007HttpBindingElement
  children:
  - System.ServiceModel.Configuration.WS2007HttpBindingElement.#ctor
  - System.ServiceModel.Configuration.WS2007HttpBindingElement.#ctor(System.String)
  - System.ServiceModel.Configuration.WS2007HttpBindingElement.BindingElementType
  langs:
  - csharp
  name: WS2007HttpBindingElement
  nameWithType: WS2007HttpBindingElement
  fullName: System.ServiceModel.Configuration.WS2007HttpBindingElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents an interoperable binding that derives from <xref href="System.ServiceModel.WSHttpBinding"></xref> and provides support for the correct versions of the <xref href="System.ServiceModel.WSHttpBinding.Security"></xref>, <xref href="System.ServiceModel.ReliableSession"></xref>, and <xref href="System.ServiceModel.WSHttpBindingBase.TransactionFlow"></xref> binding elements.
  syntax:
    content: 'public class WS2007HttpBindingElement : System.ServiceModel.Configuration.WSHttpBindingElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.StandardBindingElement
  - System.ServiceModel.Configuration.WSHttpBindingBaseElement
  - System.ServiceModel.Configuration.WSHttpBindingElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.StandardBindingElement.ApplyConfiguration(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.StandardBindingElement.CloseTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.Name
  - System.ServiceModel.Configuration.StandardBindingElement.OpenTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.ReceiveTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.StandardBindingElement.SendTimeout
  - System.ServiceModel.Configuration.WSHttpBindingBaseElement.BypassProxyOnLocal
  - System.ServiceModel.Configuration.WSHttpBindingBaseElement.HostNameComparisonMode
  - System.ServiceModel.Configuration.WSHttpBindingBaseElement.MaxBufferPoolSize
  - System.ServiceModel.Configuration.WSHttpBindingBaseElement.MaxReceivedMessageSize
  - System.ServiceModel.Configuration.WSHttpBindingBaseElement.MessageEncoding
  - System.ServiceModel.Configuration.WSHttpBindingBaseElement.ProxyAddress
  - System.ServiceModel.Configuration.WSHttpBindingBaseElement.ReaderQuotas
  - System.ServiceModel.Configuration.WSHttpBindingBaseElement.ReliableSession
  - System.ServiceModel.Configuration.WSHttpBindingBaseElement.TextEncoding
  - System.ServiceModel.Configuration.WSHttpBindingBaseElement.TransactionFlow
  - System.ServiceModel.Configuration.WSHttpBindingBaseElement.UseDefaultWebProxy
  - System.ServiceModel.Configuration.WSHttpBindingElement.AllowCookies
  - System.ServiceModel.Configuration.WSHttpBindingElement.InitializeFrom(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.WSHttpBindingElement.OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.WSHttpBindingElement.Properties
  - System.ServiceModel.Configuration.WSHttpBindingElement.Security
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WS2007HttpBindingElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.WS2007HttpBindingElement.#ctor
  commentId: M:System.ServiceModel.Configuration.WS2007HttpBindingElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WS2007HttpBindingElement
  langs:
  - csharp
  name: WS2007HttpBindingElement()
  nameWithType: WS2007HttpBindingElement.WS2007HttpBindingElement()
  fullName: System.ServiceModel.Configuration.WS2007HttpBindingElement.WS2007HttpBindingElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.WS2007HttpBindingElement"></xref> class.
  syntax:
    content: public WS2007HttpBindingElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WS2007HttpBindingElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WS2007HttpBindingElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.WS2007HttpBindingElement.#ctor(System.String)
  commentId: M:System.ServiceModel.Configuration.WS2007HttpBindingElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.WS2007HttpBindingElement
  langs:
  - csharp
  name: WS2007HttpBindingElement(String)
  nameWithType: WS2007HttpBindingElement.WS2007HttpBindingElement(String)
  fullName: System.ServiceModel.Configuration.WS2007HttpBindingElement.WS2007HttpBindingElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.WS2007HttpBindingElement"></xref> class with a specified binding.
  syntax:
    content: public WS2007HttpBindingElement (string name);
    parameters:
    - id: name
      type: System.String
      description: The configuration name of the binding. This value should be unique because it is used as identification for the binding.
  overload: System.ServiceModel.Configuration.WS2007HttpBindingElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WS2007HttpBindingElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.WS2007HttpBindingElement.BindingElementType
  commentId: P:System.ServiceModel.Configuration.WS2007HttpBindingElement.BindingElementType
  id: BindingElementType
  parent: System.ServiceModel.Configuration.WS2007HttpBindingElement
  langs:
  - csharp
  name: BindingElementType
  nameWithType: WS2007HttpBindingElement.BindingElementType
  fullName: System.ServiceModel.Configuration.WS2007HttpBindingElement.BindingElementType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets the type of this binding element.
  syntax:
    content: protected override Type BindingElementType { get; }
    return:
      type: System.Type
      description: The type of this binding element.
  overload: System.ServiceModel.Configuration.WS2007HttpBindingElement.BindingElementType*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WS2007HttpBindingElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.ServiceModel.Configuration.WSHttpBindingElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: WSHttpBindingElement
  nameWithType: WSHttpBindingElement
  fullName: System.ServiceModel.Configuration.WSHttpBindingElement
- uid: System.ServiceModel.Configuration.WS2007HttpBindingElement.#ctor
  parent: System.ServiceModel.Configuration.WS2007HttpBindingElement
  isExternal: false
  name: WS2007HttpBindingElement()
  nameWithType: WS2007HttpBindingElement.WS2007HttpBindingElement()
  fullName: System.ServiceModel.Configuration.WS2007HttpBindingElement.WS2007HttpBindingElement()
- uid: System.ServiceModel.Configuration.WS2007HttpBindingElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.WS2007HttpBindingElement
  isExternal: false
  name: WS2007HttpBindingElement(String)
  nameWithType: WS2007HttpBindingElement.WS2007HttpBindingElement(String)
  fullName: System.ServiceModel.Configuration.WS2007HttpBindingElement.WS2007HttpBindingElement(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.WS2007HttpBindingElement.BindingElementType
  parent: System.ServiceModel.Configuration.WS2007HttpBindingElement
  isExternal: false
  name: BindingElementType
  nameWithType: WS2007HttpBindingElement.BindingElementType
  fullName: System.ServiceModel.Configuration.WS2007HttpBindingElement.BindingElementType
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.WS2007HttpBindingElement.#ctor*
  parent: System.ServiceModel.Configuration.WS2007HttpBindingElement
  isExternal: false
  name: WS2007HttpBindingElement
  nameWithType: WS2007HttpBindingElement.WS2007HttpBindingElement
  fullName: System.ServiceModel.Configuration.WS2007HttpBindingElement.WS2007HttpBindingElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WS2007HttpBindingElement.xml
- uid: System.ServiceModel.Configuration.WS2007HttpBindingElement.BindingElementType*
  parent: System.ServiceModel.Configuration.WS2007HttpBindingElement
  isExternal: false
  name: BindingElementType
  nameWithType: WS2007HttpBindingElement.BindingElementType
  fullName: System.ServiceModel.Configuration.WS2007HttpBindingElement.BindingElementType
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WS2007HttpBindingElement.xml
