### YamlMime:ManagedReference
items:
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection
  commentId: T:System.Xml.Serialization.Configuration.XmlSerializerSection
  id: XmlSerializerSection
  children:
  - System.Xml.Serialization.Configuration.XmlSerializerSection.#ctor
  - System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances
  - System.Xml.Serialization.Configuration.XmlSerializerSection.Properties
  - System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation
  - System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration
  langs:
  - csharp
  name: XmlSerializerSection
  nameWithType: XmlSerializerSection
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection
  type: Class
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: Handles the XML elements used to configure XML serialization.
  remarks: This class is used to handle the [\&lt;xmlSerializer\&gt; Element](~/docs/framework/serialization/xmlserializer-element.md).
  syntax:
    content: 'public sealed class XmlSerializerSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/XmlSerializerSection.xml
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.#ctor
  commentId: M:System.Xml.Serialization.Configuration.XmlSerializerSection.#ctor
  id: '#ctor'
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  langs:
  - csharp
  name: XmlSerializerSection()
  nameWithType: XmlSerializerSection.XmlSerializerSection()
  fullName: XmlSerializerSection.XmlSerializerSection()
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: Initializes a new instance of the <xref href="System.Xml.Serialization.Configuration.XmlSerializerSection"></xref> class.
  syntax:
    content: public XmlSerializerSection ();
    parameters: []
  overload: System.Xml.Serialization.Configuration.XmlSerializerSection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/XmlSerializerSection.xml
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances
  commentId: P:System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances
  id: CheckDeserializeAdvances
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  langs:
  - csharp
  name: CheckDeserializeAdvances
  nameWithType: XmlSerializerSection.CheckDeserializeAdvances
  fullName: XmlSerializerSection.CheckDeserializeAdvances
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: Gets or sets a value that determines whether an additional check of progress of the <xref href="System.Xml.Serialization.XmlSerializer"></xref> is done.
  remarks: Do not use this method. Instead, set the `checkDeserializerAdvances` attribute of the [\&lt;xmlSerializer\&gt; Element](~/docs/framework/serialization/xmlserializer-element.md).
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("checkDeserializeAdvances", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public bool CheckDeserializeAdvances { get; set; }
    return:
      type: System.Boolean
      description: '`true` if the check is made; otherwise, `false`. The default is `true`.'
  overload: System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/XmlSerializerSection.xml
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.Properties
  commentId: P:System.Xml.Serialization.Configuration.XmlSerializerSection.Properties
  id: Properties
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  langs:
  - csharp
  name: Properties
  nameWithType: XmlSerializerSection.Properties
  fullName: XmlSerializerSection.Properties
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Xml.Serialization.Configuration.XmlSerializerSection.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/XmlSerializerSection.xml
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation
  commentId: P:System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation
  id: TempFilesLocation
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  langs:
  - csharp
  name: TempFilesLocation
  nameWithType: XmlSerializerSection.TempFilesLocation
  fullName: XmlSerializerSection.TempFilesLocation
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: Returns the location that was specified for the creation of the temporary file.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("tempFilesLocation", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public string TempFilesLocation { get; set; }
    return:
      type: System.String
      description: The location that was specified for the creation of the temporary file.
  overload: System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/XmlSerializerSection.xml
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration
  commentId: P:System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration
  id: UseLegacySerializerGeneration
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  langs:
  - csharp
  name: UseLegacySerializerGeneration
  nameWithType: XmlSerializerSection.UseLegacySerializerGeneration
  fullName: XmlSerializerSection.UseLegacySerializerGeneration
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: Gets or sets a value that indicates whether the specified object uses legacy serializer generation.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("useLegacySerializerGeneration", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public bool UseLegacySerializerGeneration { get; set; }
    return:
      type: System.Boolean
      description: '`true` if the object uses legacy serializer generation; otherwise, `false`.'
  overload: System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/XmlSerializerSection.xml
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.#ctor
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: XmlSerializerSection()
  nameWithType: XmlSerializerSection.XmlSerializerSection()
  fullName: XmlSerializerSection.XmlSerializerSection()
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: CheckDeserializeAdvances
  nameWithType: XmlSerializerSection.CheckDeserializeAdvances
  fullName: XmlSerializerSection.CheckDeserializeAdvances
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.Properties
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: Properties
  nameWithType: XmlSerializerSection.Properties
  fullName: XmlSerializerSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: TempFilesLocation
  nameWithType: XmlSerializerSection.TempFilesLocation
  fullName: XmlSerializerSection.TempFilesLocation
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: UseLegacySerializerGeneration
  nameWithType: XmlSerializerSection.UseLegacySerializerGeneration
  fullName: XmlSerializerSection.UseLegacySerializerGeneration
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.#ctor*
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: XmlSerializerSection
  nameWithType: XmlSerializerSection.XmlSerializerSection
  fullName: XmlSerializerSection.XmlSerializerSection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/XmlSerializerSection.xml
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances*
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: CheckDeserializeAdvances
  nameWithType: XmlSerializerSection.CheckDeserializeAdvances
  fullName: XmlSerializerSection.CheckDeserializeAdvances
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/XmlSerializerSection.xml
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.Properties*
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: Properties
  nameWithType: XmlSerializerSection.Properties
  fullName: XmlSerializerSection.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/XmlSerializerSection.xml
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation*
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: TempFilesLocation
  nameWithType: XmlSerializerSection.TempFilesLocation
  fullName: XmlSerializerSection.TempFilesLocation
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/XmlSerializerSection.xml
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration*
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: UseLegacySerializerGeneration
  nameWithType: XmlSerializerSection.UseLegacySerializerGeneration
  fullName: XmlSerializerSection.UseLegacySerializerGeneration
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.Serialization.Configuration/XmlSerializerSection.xml
