### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationAllowExeDefinition
  commentId: T:System.Configuration.ConfigurationAllowExeDefinition
  id: ConfigurationAllowExeDefinition
  children:
  - System.Configuration.ConfigurationAllowExeDefinition.MachineOnly
  - System.Configuration.ConfigurationAllowExeDefinition.MachineToApplication
  - System.Configuration.ConfigurationAllowExeDefinition.MachineToLocalUser
  - System.Configuration.ConfigurationAllowExeDefinition.MachineToRoamingUser
  langs:
  - csharp
  name: ConfigurationAllowExeDefinition
  nameWithType: ConfigurationAllowExeDefinition
  fullName: System.Configuration.ConfigurationAllowExeDefinition
  type: Enum
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Specifies the locations within the configuration-file hierarchy that can set or override the properties contained within a <xref href="System.Configuration.ConfigurationSection"></xref> object.
  remarks: The values in this enumeration are optionally used when creating a new instance of the <xref:System.Configuration.ConfigurationSection> class. Note this enumeration applies to client applications only.
  syntax:
    content: public enum ConfigurationAllowExeDefinition
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConfigurationAllowExeDefinition.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.ConfigurationAllowExeDefinition.MachineOnly
  commentId: F:System.Configuration.ConfigurationAllowExeDefinition.MachineOnly
  id: MachineOnly
  parent: System.Configuration.ConfigurationAllowExeDefinition
  langs:
  - csharp
  name: MachineOnly
  nameWithType: ConfigurationAllowExeDefinition.MachineOnly
  fullName: System.Configuration.ConfigurationAllowExeDefinition.MachineOnly
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: The <xref href="System.Configuration.ConfigurationSection"></xref> can be defined only in the Machine.config file.
  syntax:
    content: MachineOnly
    return:
      type: System.Configuration.ConfigurationAllowExeDefinition
      description: To be added.
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConfigurationAllowExeDefinition.xml
- uid: System.Configuration.ConfigurationAllowExeDefinition.MachineToApplication
  commentId: F:System.Configuration.ConfigurationAllowExeDefinition.MachineToApplication
  id: MachineToApplication
  parent: System.Configuration.ConfigurationAllowExeDefinition
  langs:
  - csharp
  name: MachineToApplication
  nameWithType: ConfigurationAllowExeDefinition.MachineToApplication
  fullName: System.Configuration.ConfigurationAllowExeDefinition.MachineToApplication
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: The <xref href="System.Configuration.ConfigurationSection"></xref> can be defined either in the Machine.config file or in the Exe.config file in the client application directory. This is the default value.
  syntax:
    content: MachineToApplication
    return:
      type: System.Configuration.ConfigurationAllowExeDefinition
      description: To be added.
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConfigurationAllowExeDefinition.xml
- uid: System.Configuration.ConfigurationAllowExeDefinition.MachineToLocalUser
  commentId: F:System.Configuration.ConfigurationAllowExeDefinition.MachineToLocalUser
  id: MachineToLocalUser
  parent: System.Configuration.ConfigurationAllowExeDefinition
  langs:
  - csharp
  name: MachineToLocalUser
  nameWithType: ConfigurationAllowExeDefinition.MachineToLocalUser
  fullName: System.Configuration.ConfigurationAllowExeDefinition.MachineToLocalUser
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: The <xref href="System.Configuration.ConfigurationSection"></xref> can be defined in the Machine.config file, in the Exe.config file in the client application directory, in the User.config file in the roaming user directory, or in the User.config file in the local user directory.
  syntax:
    content: MachineToLocalUser
    return:
      type: System.Configuration.ConfigurationAllowExeDefinition
      description: To be added.
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConfigurationAllowExeDefinition.xml
- uid: System.Configuration.ConfigurationAllowExeDefinition.MachineToRoamingUser
  commentId: F:System.Configuration.ConfigurationAllowExeDefinition.MachineToRoamingUser
  id: MachineToRoamingUser
  parent: System.Configuration.ConfigurationAllowExeDefinition
  langs:
  - csharp
  name: MachineToRoamingUser
  nameWithType: ConfigurationAllowExeDefinition.MachineToRoamingUser
  fullName: System.Configuration.ConfigurationAllowExeDefinition.MachineToRoamingUser
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: The <xref href="System.Configuration.ConfigurationSection"></xref> can be defined in the Machine.config file, in the Exe.config file in the client application directory, or in the User.config file in the roaming user directory.
  syntax:
    content: MachineToRoamingUser
    return:
      type: System.Configuration.ConfigurationAllowExeDefinition
      description: To be added.
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConfigurationAllowExeDefinition.xml
references:
- uid: System.Enum
  parent: System
  isExternal: false
  name: Enum
  nameWithType: Enum
  fullName: System.Enum
- uid: System.Configuration.ConfigurationAllowExeDefinition.MachineOnly
  parent: System.Configuration.ConfigurationAllowExeDefinition
  isExternal: false
  name: MachineOnly
  nameWithType: ConfigurationAllowExeDefinition.MachineOnly
  fullName: System.Configuration.ConfigurationAllowExeDefinition.MachineOnly
- uid: System.Configuration.ConfigurationAllowExeDefinition
  parent: System.Configuration
  isExternal: false
  name: ConfigurationAllowExeDefinition
  nameWithType: ConfigurationAllowExeDefinition
  fullName: System.Configuration.ConfigurationAllowExeDefinition
- uid: System.Configuration.ConfigurationAllowExeDefinition.MachineToApplication
  parent: System.Configuration.ConfigurationAllowExeDefinition
  isExternal: false
  name: MachineToApplication
  nameWithType: ConfigurationAllowExeDefinition.MachineToApplication
  fullName: System.Configuration.ConfigurationAllowExeDefinition.MachineToApplication
- uid: System.Configuration.ConfigurationAllowExeDefinition.MachineToLocalUser
  parent: System.Configuration.ConfigurationAllowExeDefinition
  isExternal: false
  name: MachineToLocalUser
  nameWithType: ConfigurationAllowExeDefinition.MachineToLocalUser
  fullName: System.Configuration.ConfigurationAllowExeDefinition.MachineToLocalUser
- uid: System.Configuration.ConfigurationAllowExeDefinition.MachineToRoamingUser
  parent: System.Configuration.ConfigurationAllowExeDefinition
  isExternal: false
  name: MachineToRoamingUser
  nameWithType: ConfigurationAllowExeDefinition.MachineToRoamingUser
  fullName: System.Configuration.ConfigurationAllowExeDefinition.MachineToRoamingUser
