### YamlMime:ManagedReference
items:
- uid: System.Xml.XmlConfiguration.XsltConfigSection
  commentId: T:System.Xml.XmlConfiguration.XsltConfigSection
  id: XsltConfigSection
  children:
  - System.Xml.XmlConfiguration.XsltConfigSection.#ctor
  - System.Xml.XmlConfiguration.XsltConfigSection.ProhibitDefaultResolverString
  langs:
  - csharp
  name: XsltConfigSection
  nameWithType: XsltConfigSection
  fullName: System.Xml.XmlConfiguration.XsltConfigSection
  type: Class
  assemblies:
  - System.Xml
  namespace: System.Xml.XmlConfiguration
  summary: Represents an XSLT configuration section.
  syntax:
    content: 'public sealed class XsltConfigSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.XmlConfiguration/XsltConfigSection.xml
  author: mairaw
  ms.author: mairaw
  manager: wpickett
- uid: System.Xml.XmlConfiguration.XsltConfigSection.#ctor
  commentId: M:System.Xml.XmlConfiguration.XsltConfigSection.#ctor
  id: '#ctor'
  parent: System.Xml.XmlConfiguration.XsltConfigSection
  langs:
  - csharp
  name: XsltConfigSection()
  nameWithType: XsltConfigSection.XsltConfigSection()
  fullName: System.Xml.XmlConfiguration.XsltConfigSection.XsltConfigSection()
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.XmlConfiguration
  summary: Initializes a new instance of the <xref href="System.Xml.XmlConfiguration.XsltConfigSection"></xref> class.
  syntax:
    content: public XsltConfigSection ();
    parameters: []
  overload: System.Xml.XmlConfiguration.XsltConfigSection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.XmlConfiguration/XsltConfigSection.xml
  author: mairaw
  ms.author: mairaw
  manager: wpickett
- uid: System.Xml.XmlConfiguration.XsltConfigSection.ProhibitDefaultResolverString
  commentId: P:System.Xml.XmlConfiguration.XsltConfigSection.ProhibitDefaultResolverString
  id: ProhibitDefaultResolverString
  parent: System.Xml.XmlConfiguration.XsltConfigSection
  langs:
  - csharp
  name: ProhibitDefaultResolverString
  nameWithType: XsltConfigSection.ProhibitDefaultResolverString
  fullName: System.Xml.XmlConfiguration.XsltConfigSection.ProhibitDefaultResolverString
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.XmlConfiguration
  summary: Gets or sets a string that represents the XSLT prohibit default resolver.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("prohibitDefaultResolver", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public string ProhibitDefaultResolverString { get; set; }
    return:
      type: System.String
      description: A string that represents the XSLT prohibit default resolver.
  overload: System.Xml.XmlConfiguration.XsltConfigSection.ProhibitDefaultResolverString*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.XmlConfiguration/XsltConfigSection.xml
  author: mairaw
  ms.author: mairaw
  manager: wpickett
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.Xml.XmlConfiguration.XsltConfigSection.#ctor
  parent: System.Xml.XmlConfiguration.XsltConfigSection
  isExternal: false
  name: XsltConfigSection()
  nameWithType: XsltConfigSection.XsltConfigSection()
  fullName: System.Xml.XmlConfiguration.XsltConfigSection.XsltConfigSection()
- uid: System.Xml.XmlConfiguration.XsltConfigSection.ProhibitDefaultResolverString
  parent: System.Xml.XmlConfiguration.XsltConfigSection
  isExternal: false
  name: ProhibitDefaultResolverString
  nameWithType: XsltConfigSection.ProhibitDefaultResolverString
  fullName: System.Xml.XmlConfiguration.XsltConfigSection.ProhibitDefaultResolverString
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Xml.XmlConfiguration.XsltConfigSection.#ctor*
  parent: System.Xml.XmlConfiguration.XsltConfigSection
  isExternal: false
  name: XsltConfigSection
  nameWithType: XsltConfigSection.XsltConfigSection
  fullName: System.Xml.XmlConfiguration.XsltConfigSection.XsltConfigSection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinandroid-7.1
  - xamarinios-10.8
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.XmlConfiguration/XsltConfigSection.xml
- uid: System.Xml.XmlConfiguration.XsltConfigSection.ProhibitDefaultResolverString*
  parent: System.Xml.XmlConfiguration.XsltConfigSection
  isExternal: false
  name: ProhibitDefaultResolverString
  nameWithType: XsltConfigSection.ProhibitDefaultResolverString
  fullName: System.Xml.XmlConfiguration.XsltConfigSection.ProhibitDefaultResolverString
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xml.XmlConfiguration/XsltConfigSection.xml
