### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WsdlImporterElement
  commentId: T:System.ServiceModel.Configuration.WsdlImporterElement
  id: WsdlImporterElement
  children:
  - System.ServiceModel.Configuration.WsdlImporterElement.#ctor
  - System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.String)
  - System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.Type)
  - System.ServiceModel.Configuration.WsdlImporterElement.Properties
  - System.ServiceModel.Configuration.WsdlImporterElement.Type
  langs:
  - csharp
  name: WsdlImporterElement
  nameWithType: WsdlImporterElement
  fullName: System.ServiceModel.Configuration.WsdlImporterElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents the configuration element that specifies the import of Web Services Description Language (WSDL) 1.1 metadata with WS-Policy attachments.
  remarks: "A <xref:System.ServiceModel.Description.WsdlImporter> is used to import metadata as well as convert that information into various classes that represent contract and endpoint information.  \n  \n It can selectively import contract and endpoint information and properties that expose any import errors and accept type information relevant to the import and conversion process. It also supports importing binding information and properties that provide access to any policy documents, WSDL documents, WSDL extensions, and XML schema documents."
  syntax:
    content: 'public sealed class WsdlImporterElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WsdlImporterElement.xml
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor
  commentId: M:System.ServiceModel.Configuration.WsdlImporterElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: WsdlImporterElement()
  nameWithType: WsdlImporterElement.WsdlImporterElement()
  fullName: WsdlImporterElement.WsdlImporterElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.WsdlImporterElement"></xref> class.
  syntax:
    content: public WsdlImporterElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WsdlImporterElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WsdlImporterElement.xml
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.String)
  commentId: M:System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: WsdlImporterElement(String)
  nameWithType: WsdlImporterElement.WsdlImporterElement(String)
  fullName: WsdlImporterElement.WsdlImporterElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.WsdlImporterElement"></xref> class with the specified type.
  syntax:
    content: public WsdlImporterElement (string type);
    parameters:
    - id: type
      type: System.String
      description: The specified type.
  overload: System.ServiceModel.Configuration.WsdlImporterElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WsdlImporterElement.xml
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.Type)
  commentId: M:System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: WsdlImporterElement(Type)
  nameWithType: WsdlImporterElement.WsdlImporterElement(Type)
  fullName: WsdlImporterElement.WsdlImporterElement(Type)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.WsdlImporterElement"></xref> class with the specified type.
  syntax:
    content: public WsdlImporterElement (Type type);
    parameters:
    - id: type
      type: System.Type
      description: The specified type.
  overload: System.ServiceModel.Configuration.WsdlImporterElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WsdlImporterElement.xml
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Properties
  commentId: P:System.ServiceModel.Configuration.WsdlImporterElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: Properties
  nameWithType: WsdlImporterElement.Properties
  fullName: WsdlImporterElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.WsdlImporterElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WsdlImporterElement.xml
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Type
  commentId: P:System.ServiceModel.Configuration.WsdlImporterElement.Type
  id: Type
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: Type
  nameWithType: WsdlImporterElement.Type
  fullName: WsdlImporterElement.Type
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the type of this configuration element.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("type", Options=System.Configuration.ConfigurationPropertyOptions.IsRequired | System.Configuration.ConfigurationPropertyOptions.IsKey)]

      [System.Configuration.StringValidator(MinLength=1)]

      public string Type { get; set; }
    return:
      type: System.String
      description: The type of this configuration element.
  overload: System.ServiceModel.Configuration.WsdlImporterElement.Type*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WsdlImporterElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: WsdlImporterElement()
  nameWithType: WsdlImporterElement.WsdlImporterElement()
  fullName: WsdlImporterElement.WsdlImporterElement()
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: WsdlImporterElement(String)
  nameWithType: WsdlImporterElement.WsdlImporterElement(String)
  fullName: WsdlImporterElement.WsdlImporterElement(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.Type)
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: WsdlImporterElement(Type)
  nameWithType: WsdlImporterElement.WsdlImporterElement(Type)
  fullName: WsdlImporterElement.WsdlImporterElement(Type)
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Properties
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: Properties
  nameWithType: WsdlImporterElement.Properties
  fullName: WsdlImporterElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Type
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: Type
  nameWithType: WsdlImporterElement.Type
  fullName: WsdlImporterElement.Type
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor*
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: WsdlImporterElement
  nameWithType: WsdlImporterElement.WsdlImporterElement
  fullName: WsdlImporterElement.WsdlImporterElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WsdlImporterElement.xml
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Properties*
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: Properties
  nameWithType: WsdlImporterElement.Properties
  fullName: WsdlImporterElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WsdlImporterElement.xml
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Type*
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: Type
  nameWithType: WsdlImporterElement.Type
  fullName: WsdlImporterElement.Type
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WsdlImporterElement.xml
