### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NetTcpContextBindingCollectionElement
  commentId: T:System.ServiceModel.Configuration.NetTcpContextBindingCollectionElement
  id: NetTcpContextBindingCollectionElement
  children:
  - System.ServiceModel.Configuration.NetTcpContextBindingCollectionElement.#ctor
  langs:
  - csharp
  name: NetTcpContextBindingCollectionElement
  nameWithType: NetTcpContextBindingCollectionElement
  fullName: System.ServiceModel.Configuration.NetTcpContextBindingCollectionElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a configuration section that holds a collection of <xref href="System.ServiceModel.Configuration.NetTcpContextBindingElement"></xref> instances.
  syntax:
    content: 'public class NetTcpContextBindingCollectionElement : System.ServiceModel.Configuration.StandardBindingCollectionElement<System.ServiceModel.NetTcpContextBinding,System.ServiceModel.Configuration.NetTcpContextBindingElement>'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.BindingCollectionElement
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Bindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.BindingType
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ConfiguredBindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ContainsKey(System.String)
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.GetDefault
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Properties
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  attributes: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetTcpContextBindingCollectionElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.NetTcpContextBindingCollectionElement.#ctor
  commentId: M:System.ServiceModel.Configuration.NetTcpContextBindingCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NetTcpContextBindingCollectionElement
  langs:
  - csharp
  name: NetTcpContextBindingCollectionElement()
  nameWithType: NetTcpContextBindingCollectionElement.NetTcpContextBindingCollectionElement()
  fullName: System.ServiceModel.Configuration.NetTcpContextBindingCollectionElement.NetTcpContextBindingCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.NetTcpContextBindingCollectionElement"></xref> class.
  syntax:
    content: public NetTcpContextBindingCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NetTcpContextBindingCollectionElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetTcpContextBindingCollectionElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  name: StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  nameWithType: StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement<TStandardBinding,TBindingConfiguration>
- uid: System.ServiceModel.NetTcpContextBinding
  name: NetTcpContextBinding
  nameWithType: NetTcpContextBinding
  fullName: System.ServiceModel.NetTcpContextBinding
- uid: System.ServiceModel.Configuration.NetTcpContextBindingElement
  name: NetTcpContextBindingElement
  nameWithType: NetTcpContextBindingElement
  fullName: System.ServiceModel.Configuration.NetTcpContextBindingElement
- uid: System.ServiceModel.Configuration.StandardBindingCollectionElement{System.ServiceModel.NetTcpContextBinding,System.ServiceModel.Configuration.NetTcpContextBindingElement}
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: StandardBindingCollectionElement<NetTcpContextBinding,NetTcpContextBindingElement>
  nameWithType: StandardBindingCollectionElement<NetTcpContextBinding,NetTcpContextBindingElement>
  fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement<System.ServiceModel.NetTcpContextBinding,System.ServiceModel.Configuration.NetTcpContextBindingElement>
  spec.csharp:
  - uid: System.ServiceModel.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: System.ServiceModel.Configuration.StandardBindingCollectionElement
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.NetTcpContextBinding
    name: NetTcpContextBinding
    nameWithType: NetTcpContextBinding
    fullName: System.ServiceModel.NetTcpContextBinding
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.ServiceModel.Configuration.NetTcpContextBindingElement
    name: NetTcpContextBindingElement
    nameWithType: NetTcpContextBindingElement
    fullName: System.ServiceModel.Configuration.NetTcpContextBindingElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.NetTcpContextBindingCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.NetTcpContextBindingCollectionElement
  isExternal: false
  name: NetTcpContextBindingCollectionElement()
  nameWithType: NetTcpContextBindingCollectionElement.NetTcpContextBindingCollectionElement()
  fullName: System.ServiceModel.Configuration.NetTcpContextBindingCollectionElement.NetTcpContextBindingCollectionElement()
- uid: System.ServiceModel.Configuration.NetTcpContextBindingCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.NetTcpContextBindingCollectionElement
  isExternal: false
  name: NetTcpContextBindingCollectionElement
  nameWithType: NetTcpContextBindingCollectionElement.NetTcpContextBindingCollectionElement
  fullName: System.ServiceModel.Configuration.NetTcpContextBindingCollectionElement.NetTcpContextBindingCollectionElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetTcpContextBindingCollectionElement.xml
