### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement
  commentId: T:System.ServiceModel.Configuration.PeerTransportSecurityElement
  id: PeerTransportSecurityElement
  children:
  - System.ServiceModel.Configuration.PeerTransportSecurityElement.#ctor
  - System.ServiceModel.Configuration.PeerTransportSecurityElement.CredentialType
  - System.ServiceModel.Configuration.PeerTransportSecurityElement.Properties
  langs:
  - csharp
  name: PeerTransportSecurityElement
  nameWithType: PeerTransportSecurityElement
  fullName: System.ServiceModel.Configuration.PeerTransportSecurityElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Defines a configuration element for the secure transport of messages sent by peers.
  syntax:
    content: 'public sealed class PeerTransportSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PeerTransportSecurityElement.xml
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.#ctor
  commentId: M:System.ServiceModel.Configuration.PeerTransportSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  langs:
  - csharp
  name: PeerTransportSecurityElement()
  nameWithType: PeerTransportSecurityElement.PeerTransportSecurityElement()
  fullName: PeerTransportSecurityElement.PeerTransportSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.PeerTransportSecurityElement"></xref> class.
  syntax:
    content: public PeerTransportSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.PeerTransportSecurityElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PeerTransportSecurityElement.xml
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.CredentialType
  commentId: P:System.ServiceModel.Configuration.PeerTransportSecurityElement.CredentialType
  id: CredentialType
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  langs:
  - csharp
  name: CredentialType
  nameWithType: PeerTransportSecurityElement.CredentialType
  fullName: PeerTransportSecurityElement.CredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets and sets the configuration for the type of credentials used to verify messages sent with the peer transport.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("credentialType", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.ServiceModel.PeerTransportCredentialType CredentialType { get; set; }
    return:
      type: System.ServiceModel.PeerTransportCredentialType
      description: <xref href="System.ServiceModel.PeerTransportCredentialType"></xref> enumeration value that contains the type of credentials used to verify messages sent with the peer transport.
  overload: System.ServiceModel.Configuration.PeerTransportSecurityElement.CredentialType*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PeerTransportSecurityElement.xml
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.Properties
  commentId: P:System.ServiceModel.Configuration.PeerTransportSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: PeerTransportSecurityElement.Properties
  fullName: PeerTransportSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.PeerTransportSecurityElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PeerTransportSecurityElement.xml
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  isExternal: false
  name: PeerTransportSecurityElement()
  nameWithType: PeerTransportSecurityElement.PeerTransportSecurityElement()
  fullName: PeerTransportSecurityElement.PeerTransportSecurityElement()
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.CredentialType
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  isExternal: false
  name: CredentialType
  nameWithType: PeerTransportSecurityElement.CredentialType
  fullName: PeerTransportSecurityElement.CredentialType
- uid: System.ServiceModel.PeerTransportCredentialType
  parent: System.ServiceModel
  isExternal: false
  name: PeerTransportCredentialType
  nameWithType: PeerTransportCredentialType
  fullName: System.ServiceModel.PeerTransportCredentialType
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.Properties
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: PeerTransportSecurityElement.Properties
  fullName: PeerTransportSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  isExternal: false
  name: PeerTransportSecurityElement
  nameWithType: PeerTransportSecurityElement.PeerTransportSecurityElement
  fullName: PeerTransportSecurityElement.PeerTransportSecurityElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PeerTransportSecurityElement.xml
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.CredentialType*
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  isExternal: false
  name: CredentialType
  nameWithType: PeerTransportSecurityElement.CredentialType
  fullName: PeerTransportSecurityElement.CredentialType
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PeerTransportSecurityElement.xml
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: PeerTransportSecurityElement.Properties
  fullName: PeerTransportSecurityElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PeerTransportSecurityElement.xml
