### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  commentId: T:System.Web.Services.Configuration.WsdlHelpGeneratorElement
  id: WsdlHelpGeneratorElement
  children:
  - System.Web.Services.Configuration.WsdlHelpGeneratorElement.#ctor
  - System.Web.Services.Configuration.WsdlHelpGeneratorElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Web.Services.Configuration.WsdlHelpGeneratorElement.Href
  - System.Web.Services.Configuration.WsdlHelpGeneratorElement.Properties
  - System.Web.Services.Configuration.WsdlHelpGeneratorElement.Reset(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  name: WsdlHelpGeneratorElement
  nameWithType: WsdlHelpGeneratorElement
  fullName: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  type: Class
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Represents `WsdlHelpGenerator` element in the configuration file that specifies the XML Web service Help page (an .aspx file) that is displayed to a browser when the browser navigates directly to an ASMX XML Web services page.
  syntax:
    content: 'public sealed class WsdlHelpGeneratorElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsdlHelpGeneratorElement.xml
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.#ctor
  commentId: M:System.Web.Services.Configuration.WsdlHelpGeneratorElement.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  langs:
  - csharp
  name: WsdlHelpGeneratorElement()
  nameWithType: WsdlHelpGeneratorElement.WsdlHelpGeneratorElement()
  fullName: WsdlHelpGeneratorElement.WsdlHelpGeneratorElement()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Services.Configuration.WsdlHelpGeneratorElement"></xref> class.
  syntax:
    content: public WsdlHelpGeneratorElement ();
    parameters: []
  overload: System.Web.Services.Configuration.WsdlHelpGeneratorElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsdlHelpGeneratorElement.xml
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  commentId: M:System.Web.Services.Configuration.WsdlHelpGeneratorElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  id: DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  langs:
  - csharp
  name: DeserializeElement(XmlReader, Boolean)
  nameWithType: WsdlHelpGeneratorElement.DeserializeElement(XmlReader, Boolean)
  fullName: WsdlHelpGeneratorElement.DeserializeElement(XmlReader, Boolean)
  type: Method
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override void DeserializeElement (System.Xml.XmlReader reader, bool serializeCollectionKey);
    parameters:
    - id: reader
      type: System.Xml.XmlReader
      description: To be added.
    - id: serializeCollectionKey
      type: System.Boolean
      description: To be added.
  overload: System.Web.Services.Configuration.WsdlHelpGeneratorElement.DeserializeElement*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsdlHelpGeneratorElement.xml
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Href
  commentId: P:System.Web.Services.Configuration.WsdlHelpGeneratorElement.Href
  id: Href
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  langs:
  - csharp
  name: Href
  nameWithType: WsdlHelpGeneratorElement.Href
  fullName: WsdlHelpGeneratorElement.Href
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Gets or sets the file path to the Help page.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("href", IsRequired=true)]

      public string Href { get; set; }
    return:
      type: System.String
      description: A <xref href="System.String"></xref> that contains the file path to the Help page.
  overload: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Href*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsdlHelpGeneratorElement.xml
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Properties
  commentId: P:System.Web.Services.Configuration.WsdlHelpGeneratorElement.Properties
  id: Properties
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  langs:
  - csharp
  name: Properties
  nameWithType: WsdlHelpGeneratorElement.Properties
  fullName: WsdlHelpGeneratorElement.Properties
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsdlHelpGeneratorElement.xml
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Reset(System.Configuration.ConfigurationElement)
  commentId: M:System.Web.Services.Configuration.WsdlHelpGeneratorElement.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: WsdlHelpGeneratorElement.Reset(ConfigurationElement)
  fullName: WsdlHelpGeneratorElement.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: To be added.
  overload: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Reset*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsdlHelpGeneratorElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.#ctor
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: WsdlHelpGeneratorElement()
  nameWithType: WsdlHelpGeneratorElement.WsdlHelpGeneratorElement()
  fullName: WsdlHelpGeneratorElement.WsdlHelpGeneratorElement()
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: DeserializeElement(XmlReader, Boolean)
  nameWithType: WsdlHelpGeneratorElement.DeserializeElement(XmlReader, Boolean)
  fullName: WsdlHelpGeneratorElement.DeserializeElement(XmlReader, Boolean)
- uid: System.Xml.XmlReader
  parent: System.Xml
  isExternal: false
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Href
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: Href
  nameWithType: WsdlHelpGeneratorElement.Href
  fullName: WsdlHelpGeneratorElement.Href
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Properties
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: Properties
  nameWithType: WsdlHelpGeneratorElement.Properties
  fullName: WsdlHelpGeneratorElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Reset(System.Configuration.ConfigurationElement)
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: WsdlHelpGeneratorElement.Reset(ConfigurationElement)
  fullName: WsdlHelpGeneratorElement.Reset(ConfigurationElement)
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.#ctor*
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: WsdlHelpGeneratorElement
  nameWithType: WsdlHelpGeneratorElement.WsdlHelpGeneratorElement
  fullName: WsdlHelpGeneratorElement.WsdlHelpGeneratorElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsdlHelpGeneratorElement.xml
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.DeserializeElement*
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: DeserializeElement
  nameWithType: WsdlHelpGeneratorElement.DeserializeElement
  fullName: WsdlHelpGeneratorElement.DeserializeElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsdlHelpGeneratorElement.xml
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Href*
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: Href
  nameWithType: WsdlHelpGeneratorElement.Href
  fullName: WsdlHelpGeneratorElement.Href
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsdlHelpGeneratorElement.xml
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Properties*
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: Properties
  nameWithType: WsdlHelpGeneratorElement.Properties
  fullName: WsdlHelpGeneratorElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsdlHelpGeneratorElement.xml
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Reset*
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: Reset
  nameWithType: WsdlHelpGeneratorElement.Reset
  fullName: WsdlHelpGeneratorElement.Reset
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/WsdlHelpGeneratorElement.xml
