### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  commentId: T:System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  id: SecurityIdentifierElement
  children:
  - System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor
  - System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor(System.Security.Principal.SecurityIdentifier)
  - System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.Properties
  - System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifier
  langs:
  - csharp
  name: SecurityIdentifierElement
  nameWithType: SecurityIdentifierElement
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: Represents a configuration element that contains user accounts for processes that host WCF services, and are granted connection access to the sharing service. This class cannot be inherited.
  remarks: The security identifier specifies a unique identifier used to identify a user account. The default values are LocalSystem, Administrators, NS, LS, and IIS_USRS.
  syntax:
    content: 'public sealed class SecurityIdentifierElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/SecurityIdentifierElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor
  commentId: M:System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  langs:
  - csharp
  name: SecurityIdentifierElement()
  nameWithType: SecurityIdentifierElement.SecurityIdentifierElement()
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifierElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Activation.Configuration.SecurityIdentifierElement"></xref> class.
  syntax:
    content: public SecurityIdentifierElement ();
    parameters: []
  overload: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/SecurityIdentifierElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor(System.Security.Principal.SecurityIdentifier)
  commentId: M:System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor(System.Security.Principal.SecurityIdentifier)
  id: '#ctor(System.Security.Principal.SecurityIdentifier)'
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  langs:
  - csharp
  name: SecurityIdentifierElement(SecurityIdentifier)
  nameWithType: SecurityIdentifierElement.SecurityIdentifierElement(SecurityIdentifier)
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifierElement(SecurityIdentifier)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Activation.Configuration.SecurityIdentifierElement"></xref> class wit the specified security identifier.
  syntax:
    content: public SecurityIdentifierElement (System.Security.Principal.SecurityIdentifier sid);
    parameters:
    - id: sid
      type: System.Security.Principal.SecurityIdentifier
      description: A security identifier.
  overload: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/SecurityIdentifierElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.Properties
  commentId: P:System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.Properties
  id: Properties
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  langs:
  - csharp
  name: Properties
  nameWithType: SecurityIdentifierElement.Properties
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/SecurityIdentifierElement.xml
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifier
  commentId: P:System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifier
  id: SecurityIdentifier
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  langs:
  - csharp
  name: SecurityIdentifier
  nameWithType: SecurityIdentifierElement.SecurityIdentifier
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifier
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: Gets or sets the security identifier that this element associates with.
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(System.ServiceModel.Activation.Configuration.SecurityIdentifierConverter))]

      [System.Configuration.ConfigurationProperty("securityIdentifier", DefaultValue=Mono.Cecil.CustomAttributeArgument, Options=System.Configuration.ConfigurationPropertyOptions.IsKey)]

      public System.Security.Principal.SecurityIdentifier SecurityIdentifier { get; set; }
    return:
      type: System.Security.Principal.SecurityIdentifier
      description: The security identifier that this element associates with.
  overload: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifier*
  exceptions: []
  attributes:
  - type: System.ComponentModel.TypeConverterAttribute
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/SecurityIdentifierElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  isExternal: false
  name: SecurityIdentifierElement()
  nameWithType: SecurityIdentifierElement.SecurityIdentifierElement()
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifierElement()
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor(System.Security.Principal.SecurityIdentifier)
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  isExternal: false
  name: SecurityIdentifierElement(SecurityIdentifier)
  nameWithType: SecurityIdentifierElement.SecurityIdentifierElement(SecurityIdentifier)
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifierElement(SecurityIdentifier)
- uid: System.Security.Principal.SecurityIdentifier
  parent: System.Security.Principal
  isExternal: false
  name: SecurityIdentifier
  nameWithType: SecurityIdentifier
  fullName: System.Security.Principal.SecurityIdentifier
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.Properties
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  isExternal: false
  name: Properties
  nameWithType: SecurityIdentifierElement.Properties
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifier
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  isExternal: false
  name: SecurityIdentifier
  nameWithType: SecurityIdentifierElement.SecurityIdentifier
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifier
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.#ctor*
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  isExternal: false
  name: SecurityIdentifierElement
  nameWithType: SecurityIdentifierElement.SecurityIdentifierElement
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifierElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/SecurityIdentifierElement.xml
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.Properties*
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  isExternal: false
  name: Properties
  nameWithType: SecurityIdentifierElement.Properties
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/SecurityIdentifierElement.xml
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifier*
  parent: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement
  isExternal: false
  name: SecurityIdentifier
  nameWithType: SecurityIdentifierElement.SecurityIdentifier
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElement.SecurityIdentifier
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activation.Configuration/SecurityIdentifierElement.xml
