### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationPropertyOptions
  commentId: T:System.Configuration.ConfigurationPropertyOptions
  id: ConfigurationPropertyOptions
  children:
  - System.Configuration.ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  - System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection
  - System.Configuration.ConfigurationPropertyOptions.IsKey
  - System.Configuration.ConfigurationPropertyOptions.IsRequired
  - System.Configuration.ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  - System.Configuration.ConfigurationPropertyOptions.IsVersionCheckRequired
  - System.Configuration.ConfigurationPropertyOptions.None
  langs:
  - csharp
  name: ConfigurationPropertyOptions
  nameWithType: ConfigurationPropertyOptions
  fullName: System.Configuration.ConfigurationPropertyOptions
  type: Enum
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Specifies the options to apply to a property.
  remarks: During the creation of a configuration element, you use the <xref:System.Configuration.ConfigurationPropertyOptions> enumerator to programmatically specify the options to apply. These options indicate whether a property is required, is a collection key property, etc. If a value is not specified, the value is assumed to be None.
  syntax:
    content: >-
      [System.Flags]

      public enum ConfigurationPropertyOptions
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
  attributes:
  - type: System.FlagsAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConfigurationPropertyOptions.xml
  author: tdykstra
  ms.author: tdykstra
  manager: wpickett
- uid: System.Configuration.ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  commentId: F:System.Configuration.ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  id: IsAssemblyStringTransformationRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  name: IsAssemblyStringTransformationRequired
  nameWithType: ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Indicates whether the assembly name for the configuration property requires transformation when it is serialized for an earlier version of the .NET Framework.
  syntax:
    content: IsAssemblyStringTransformationRequired
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: To be added.
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConfigurationPropertyOptions.xml
- uid: System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection
  commentId: F:System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection
  id: IsDefaultCollection
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  name: IsDefaultCollection
  nameWithType: ConfigurationPropertyOptions.IsDefaultCollection
  fullName: System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Indicates that the property is a default collection.
  syntax:
    content: IsDefaultCollection
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: To be added.
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConfigurationPropertyOptions.xml
- uid: System.Configuration.ConfigurationPropertyOptions.IsKey
  commentId: F:System.Configuration.ConfigurationPropertyOptions.IsKey
  id: IsKey
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  name: IsKey
  nameWithType: ConfigurationPropertyOptions.IsKey
  fullName: System.Configuration.ConfigurationPropertyOptions.IsKey
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Indicates that the property is a collection key.
  syntax:
    content: IsKey
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: To be added.
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConfigurationPropertyOptions.xml
- uid: System.Configuration.ConfigurationPropertyOptions.IsRequired
  commentId: F:System.Configuration.ConfigurationPropertyOptions.IsRequired
  id: IsRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  name: IsRequired
  nameWithType: ConfigurationPropertyOptions.IsRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsRequired
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Indicates that the property is required.
  syntax:
    content: IsRequired
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: To be added.
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConfigurationPropertyOptions.xml
- uid: System.Configuration.ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  commentId: F:System.Configuration.ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  id: IsTypeStringTransformationRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  name: IsTypeStringTransformationRequired
  nameWithType: ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Indicates whether the type name for the configuration property requires transformation when it is serialized for an earlier version of the .NET Framework.
  syntax:
    content: IsTypeStringTransformationRequired
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: To be added.
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConfigurationPropertyOptions.xml
- uid: System.Configuration.ConfigurationPropertyOptions.IsVersionCheckRequired
  commentId: F:System.Configuration.ConfigurationPropertyOptions.IsVersionCheckRequired
  id: IsVersionCheckRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  name: IsVersionCheckRequired
  nameWithType: ConfigurationPropertyOptions.IsVersionCheckRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsVersionCheckRequired
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Indicates whether the configuration property's parent configuration section should be queried at serialization time to determine whether the configuration property should be serialized into XML.
  syntax:
    content: IsVersionCheckRequired
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: To be added.
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConfigurationPropertyOptions.xml
- uid: System.Configuration.ConfigurationPropertyOptions.None
  commentId: F:System.Configuration.ConfigurationPropertyOptions.None
  id: None
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  name: None
  nameWithType: ConfigurationPropertyOptions.None
  fullName: System.Configuration.ConfigurationPropertyOptions.None
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Indicates that no option applies to the property.
  syntax:
    content: None
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: To be added.
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ConfigurationPropertyOptions.xml
references:
- uid: System.Enum
  parent: System
  isExternal: false
  name: Enum
  nameWithType: Enum
  fullName: System.Enum
- uid: System.Configuration.ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsAssemblyStringTransformationRequired
  nameWithType: ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
- uid: System.Configuration.ConfigurationPropertyOptions
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyOptions
  nameWithType: ConfigurationPropertyOptions
  fullName: System.Configuration.ConfigurationPropertyOptions
- uid: System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsDefaultCollection
  nameWithType: ConfigurationPropertyOptions.IsDefaultCollection
  fullName: System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection
- uid: System.Configuration.ConfigurationPropertyOptions.IsKey
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsKey
  nameWithType: ConfigurationPropertyOptions.IsKey
  fullName: System.Configuration.ConfigurationPropertyOptions.IsKey
- uid: System.Configuration.ConfigurationPropertyOptions.IsRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsRequired
  nameWithType: ConfigurationPropertyOptions.IsRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsRequired
- uid: System.Configuration.ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsTypeStringTransformationRequired
  nameWithType: ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsTypeStringTransformationRequired
- uid: System.Configuration.ConfigurationPropertyOptions.IsVersionCheckRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsVersionCheckRequired
  nameWithType: ConfigurationPropertyOptions.IsVersionCheckRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsVersionCheckRequired
- uid: System.Configuration.ConfigurationPropertyOptions.None
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: None
  nameWithType: ConfigurationPropertyOptions.None
  fullName: System.Configuration.ConfigurationPropertyOptions.None
