### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.DefaultPortElement
  commentId: T:System.ServiceModel.Configuration.DefaultPortElement
  id: DefaultPortElement
  children:
  - System.ServiceModel.Configuration.DefaultPortElement.#ctor
  - System.ServiceModel.Configuration.DefaultPortElement.#ctor(System.ServiceModel.Configuration.DefaultPortElement)
  - System.ServiceModel.Configuration.DefaultPortElement.Port
  - System.ServiceModel.Configuration.DefaultPortElement.Properties
  - System.ServiceModel.Configuration.DefaultPortElement.Scheme
  langs:
  - csharp
  name: DefaultPortElement
  nameWithType: DefaultPortElement
  fullName: System.ServiceModel.Configuration.DefaultPortElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a configuration element that defines the default settings for a communications endpoint.
  remarks: A default port is the default communications endpoint that the client application listens to.
  syntax:
    content: 'public sealed class DefaultPortElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/DefaultPortElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.DefaultPortElement.#ctor
  commentId: M:System.ServiceModel.Configuration.DefaultPortElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.DefaultPortElement
  langs:
  - csharp
  name: DefaultPortElement()
  nameWithType: DefaultPortElement.DefaultPortElement()
  fullName: System.ServiceModel.Configuration.DefaultPortElement.DefaultPortElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Creates a new instance of the <xref href="System.ServiceModel.Configuration.DefaultPortElement"></xref> class.
  syntax:
    content: public DefaultPortElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.DefaultPortElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/DefaultPortElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.DefaultPortElement.#ctor(System.ServiceModel.Configuration.DefaultPortElement)
  commentId: M:System.ServiceModel.Configuration.DefaultPortElement.#ctor(System.ServiceModel.Configuration.DefaultPortElement)
  id: '#ctor(System.ServiceModel.Configuration.DefaultPortElement)'
  parent: System.ServiceModel.Configuration.DefaultPortElement
  langs:
  - csharp
  name: DefaultPortElement(DefaultPortElement)
  nameWithType: DefaultPortElement.DefaultPortElement(DefaultPortElement)
  fullName: System.ServiceModel.Configuration.DefaultPortElement.DefaultPortElement(DefaultPortElement)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Creates a new instance of the <xref href="System.ServiceModel.Configuration.DefaultPortElement"></xref> class with the specified <xref href="System.ServiceModel.Configuration.DefaultPortElement"></xref>.
  syntax:
    content: public DefaultPortElement (System.ServiceModel.Configuration.DefaultPortElement other);
    parameters:
    - id: other
      type: System.ServiceModel.Configuration.DefaultPortElement
      description: The default port element that provides the settings for the current default port element.
  overload: System.ServiceModel.Configuration.DefaultPortElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/DefaultPortElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.DefaultPortElement.Port
  commentId: P:System.ServiceModel.Configuration.DefaultPortElement.Port
  id: Port
  parent: System.ServiceModel.Configuration.DefaultPortElement
  langs:
  - csharp
  name: Port
  nameWithType: DefaultPortElement.Port
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Port
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the default communications port number.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("port", DefaultValue=Mono.Cecil.CustomAttributeArgument, Options=System.Configuration.ConfigurationPropertyOptions.IsRequired)]

      [System.Configuration.IntegerValidator(MaxValue=65535, MinValue=0)]

      public int Port { get; set; }
    return:
      type: System.Int32
      description: The communications port.
  overload: System.ServiceModel.Configuration.DefaultPortElement.Port*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.IntegerValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/DefaultPortElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.DefaultPortElement.Properties
  commentId: P:System.ServiceModel.Configuration.DefaultPortElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.DefaultPortElement
  langs:
  - csharp
  name: Properties
  nameWithType: DefaultPortElement.Properties
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.DefaultPortElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/DefaultPortElement.xml
- uid: System.ServiceModel.Configuration.DefaultPortElement.Scheme
  commentId: P:System.ServiceModel.Configuration.DefaultPortElement.Scheme
  id: Scheme
  parent: System.ServiceModel.Configuration.DefaultPortElement
  langs:
  - csharp
  name: Scheme
  nameWithType: DefaultPortElement.Scheme
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Scheme
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the group of protocol settings associated with a communications port.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("scheme", Options=System.Configuration.ConfigurationPropertyOptions.IsRequired | System.Configuration.ConfigurationPropertyOptions.IsKey)]

      [System.Configuration.StringValidator(MinLength=1)]

      public string Scheme { get; set; }
    return:
      type: System.String
      description: The communications protocol settings.
  overload: System.ServiceModel.Configuration.DefaultPortElement.Scheme*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/DefaultPortElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.DefaultPortElement.#ctor
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: DefaultPortElement()
  nameWithType: DefaultPortElement.DefaultPortElement()
  fullName: System.ServiceModel.Configuration.DefaultPortElement.DefaultPortElement()
- uid: System.ServiceModel.Configuration.DefaultPortElement.#ctor(System.ServiceModel.Configuration.DefaultPortElement)
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: DefaultPortElement(DefaultPortElement)
  nameWithType: DefaultPortElement.DefaultPortElement(DefaultPortElement)
  fullName: System.ServiceModel.Configuration.DefaultPortElement.DefaultPortElement(DefaultPortElement)
- uid: System.ServiceModel.Configuration.DefaultPortElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: DefaultPortElement
  nameWithType: DefaultPortElement
  fullName: System.ServiceModel.Configuration.DefaultPortElement
- uid: System.ServiceModel.Configuration.DefaultPortElement.Port
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Port
  nameWithType: DefaultPortElement.Port
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Port
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.DefaultPortElement.Properties
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Properties
  nameWithType: DefaultPortElement.Properties
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.DefaultPortElement.Scheme
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Scheme
  nameWithType: DefaultPortElement.Scheme
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Scheme
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.DefaultPortElement.#ctor*
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: DefaultPortElement
  nameWithType: DefaultPortElement.DefaultPortElement
  fullName: System.ServiceModel.Configuration.DefaultPortElement.DefaultPortElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/DefaultPortElement.xml
- uid: System.ServiceModel.Configuration.DefaultPortElement.Port*
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Port
  nameWithType: DefaultPortElement.Port
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Port
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/DefaultPortElement.xml
- uid: System.ServiceModel.Configuration.DefaultPortElement.Properties*
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Properties
  nameWithType: DefaultPortElement.Properties
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/DefaultPortElement.xml
- uid: System.ServiceModel.Configuration.DefaultPortElement.Scheme*
  parent: System.ServiceModel.Configuration.DefaultPortElement
  isExternal: false
  name: Scheme
  nameWithType: DefaultPortElement.Scheme
  fullName: System.ServiceModel.Configuration.DefaultPortElement.Scheme
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/DefaultPortElement.xml
