### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  commentId: T:System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  id: BasicHttpMessageSecurityElement
  children:
  - System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.#ctor
  - System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.AlgorithmSuite
  - System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.ClientCredentialType
  - System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.Properties
  langs:
  - csharp
  name: BasicHttpMessageSecurityElement
  nameWithType: BasicHttpMessageSecurityElement
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: An XML element that configures HTTP message security.
  syntax:
    content: 'public sealed class BasicHttpMessageSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpMessageSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.#ctor
  commentId: M:System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  langs:
  - csharp
  name: BasicHttpMessageSecurityElement()
  nameWithType: BasicHttpMessageSecurityElement.BasicHttpMessageSecurityElement()
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.BasicHttpMessageSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.BasicHttpMessageSecurityElement"></xref> class.
  syntax:
    content: public BasicHttpMessageSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpMessageSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.AlgorithmSuite
  commentId: P:System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.AlgorithmSuite
  id: AlgorithmSuite
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  langs:
  - csharp
  name: AlgorithmSuite
  nameWithType: BasicHttpMessageSecurityElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.AlgorithmSuite
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Specifies the algorithms to use with the <xref href="System.ServiceModel.Configuration.BasicHttpMessageSecurityElement"></xref> class.
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(System.ServiceModel.Configuration.SecurityAlgorithmSuiteConverter))]

      [System.Configuration.ConfigurationProperty("algorithmSuite", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.ServiceModel.Security.SecurityAlgorithmSuite AlgorithmSuite { get; set; }
    return:
      type: System.ServiceModel.Security.SecurityAlgorithmSuite
      description: A <xref href="System.ServiceModel.Security.SecurityAlgorithmSuite"></xref>. The default is <xref href="System.ServiceModel.Security.SecurityAlgorithmSuite.Basic256"></xref> .
  overload: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.AlgorithmSuite*
  exceptions: []
  attributes:
  - type: System.ComponentModel.TypeConverterAttribute
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpMessageSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.ClientCredentialType
  commentId: P:System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.ClientCredentialType
  id: ClientCredentialType
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  langs:
  - csharp
  name: ClientCredentialType
  nameWithType: BasicHttpMessageSecurityElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.ClientCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Specifies the type of client credential to use with the <xref href="System.ServiceModel.Configuration.BasicHttpMessageSecurityElement"></xref> class.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("clientCredentialType", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.ServiceModel.BasicHttpMessageCredentialType ClientCredentialType { get; set; }
    return:
      type: System.ServiceModel.BasicHttpMessageCredentialType
      description: A <xref href="System.ServiceModel.BasicHttpMessageCredentialType"></xref> . The default is UserName.
  overload: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.ClientCredentialType*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpMessageSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.Properties
  commentId: P:System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: BasicHttpMessageSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpMessageSecurityElement.xml
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  isExternal: false
  name: BasicHttpMessageSecurityElement()
  nameWithType: BasicHttpMessageSecurityElement.BasicHttpMessageSecurityElement()
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.BasicHttpMessageSecurityElement()
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.AlgorithmSuite
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: BasicHttpMessageSecurityElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.AlgorithmSuite
- uid: System.ServiceModel.Security.SecurityAlgorithmSuite
  parent: System.ServiceModel.Security
  isExternal: false
  name: SecurityAlgorithmSuite
  nameWithType: SecurityAlgorithmSuite
  fullName: System.ServiceModel.Security.SecurityAlgorithmSuite
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.ClientCredentialType
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: BasicHttpMessageSecurityElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.ClientCredentialType
- uid: System.ServiceModel.BasicHttpMessageCredentialType
  parent: System.ServiceModel
  isExternal: false
  name: BasicHttpMessageCredentialType
  nameWithType: BasicHttpMessageCredentialType
  fullName: System.ServiceModel.BasicHttpMessageCredentialType
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.Properties
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  isExternal: false
  name: Properties
  nameWithType: BasicHttpMessageSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  isExternal: false
  name: BasicHttpMessageSecurityElement
  nameWithType: BasicHttpMessageSecurityElement.BasicHttpMessageSecurityElement
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.BasicHttpMessageSecurityElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpMessageSecurityElement.xml
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.AlgorithmSuite*
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: BasicHttpMessageSecurityElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.AlgorithmSuite
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpMessageSecurityElement.xml
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.ClientCredentialType*
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: BasicHttpMessageSecurityElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.ClientCredentialType
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpMessageSecurityElement.xml
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  isExternal: false
  name: Properties
  nameWithType: BasicHttpMessageSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpMessageSecurityElement.xml
