### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.AuthorizationSection
  commentId: T:System.Web.Configuration.AuthorizationSection
  id: AuthorizationSection
  children:
  - System.Web.Configuration.AuthorizationSection.#ctor
  - System.Web.Configuration.AuthorizationSection.PostDeserialize
  - System.Web.Configuration.AuthorizationSection.Properties
  - System.Web.Configuration.AuthorizationSection.Rules
  langs:
  - csharp
  name: AuthorizationSection
  nameWithType: AuthorizationSection
  fullName: System.Web.Configuration.AuthorizationSection
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Configures a Web application authorization. This class cannot be inherited.
  remarks: "The <xref:System.Web.Configuration.AuthorizationSection> class provides a way to programmatically access and modify the `authorization` section of a configuration file.  \n  \n This type is part of a group that includes the <xref:System.Web.Configuration.AuthorizationRule>, the <xref:System.Web.Configuration.AuthorizationRuleCollection>, and the <xref:System.Web.Configuration.AuthorizationRuleAction> types.  \n  \n> [!NOTE]\n>  The <xref:System.Web.Configuration.AuthorizationSection> can read and write information from and to the related section of the configuration file according to the section property <xref:System.Configuration.SectionInformation.AllowDefinition%2A> whose value is <xref:System.Configuration.ConfigurationAllowDefinition.Everywhere>."
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.AuthorizationSection> object from the configuration file of an existing Web application. You can use this object to access its members. The configuration file will contain a setup similar to the following.  \n  \n> [!NOTE]\n>  If you use the `credentials` section, be sure to follow the guidelines explained at [ASP.NET Authentication](http://msdn.microsoft.com/library/fc10b0ef-4ce4-4a7f-9174-886325221ee1). For scalability and better security capability, it is recommended that you use an external database to store the users' credentials. For more information about building secure ASP.NET applications, search the Microsoft MSDN Web site (msdn.microsoft.com) for \"Securing Your ASP.NET Application\" and \"Building Secure ASP.NET Applications: Authentication, Authorization, and Secure Communication.\"  \n  \n```  \n<authorization>  \n  <allow users=\"userName\" roles=\"admin\" verbs=\"post\" />  \n  <deny users=\"*\" verbs=\"post\"/>  \n</authorization>  \n```  \n  \n [!code-csharp[System.Web.Configuration.Authorization#1](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.Authorization/CS/authorization.cs#1)]\n [!code-vb[System.Web.Configuration.Authorization#1](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.Authorization/VB/authorization.vb#1)]  \n  \n [!code-csharp[System.Web.Configuration.Authorization#2](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.Authorization/CS/authorization.cs#2)]\n [!code-vb[System.Web.Configuration.Authorization#2](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.Authorization/VB/authorization.vb#2)]"
  syntax:
    content: 'public sealed class AuthorizationSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AuthorizationSection.xml
- uid: System.Web.Configuration.AuthorizationSection.#ctor
  commentId: M:System.Web.Configuration.AuthorizationSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.AuthorizationSection
  langs:
  - csharp
  name: AuthorizationSection()
  nameWithType: AuthorizationSection.AuthorizationSection()
  fullName: AuthorizationSection.AuthorizationSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Configuration.AuthorizationSection"></xref> class using default settings.
  remarks: The <xref:System.Web.Configuration.AuthorizationSection.%23ctor%2A> constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system. You obtain an instance of the <xref:System.Web.Configuration.AuthorizationSection> class by using the <xref:System.Configuration.Configuration.GetSection%2A> method.
  syntax:
    content: public AuthorizationSection ();
    parameters: []
  overload: System.Web.Configuration.AuthorizationSection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AuthorizationSection.xml
- uid: System.Web.Configuration.AuthorizationSection.PostDeserialize
  commentId: M:System.Web.Configuration.AuthorizationSection.PostDeserialize
  id: PostDeserialize
  parent: System.Web.Configuration.AuthorizationSection
  langs:
  - csharp
  name: PostDeserialize()
  nameWithType: AuthorizationSection.PostDeserialize()
  fullName: AuthorizationSection.PostDeserialize()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override void PostDeserialize ();
    parameters: []
  overload: System.Web.Configuration.AuthorizationSection.PostDeserialize*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AuthorizationSection.xml
- uid: System.Web.Configuration.AuthorizationSection.Properties
  commentId: P:System.Web.Configuration.AuthorizationSection.Properties
  id: Properties
  parent: System.Web.Configuration.AuthorizationSection
  langs:
  - csharp
  name: Properties
  nameWithType: AuthorizationSection.Properties
  fullName: AuthorizationSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.AuthorizationSection.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AuthorizationSection.xml
- uid: System.Web.Configuration.AuthorizationSection.Rules
  commentId: P:System.Web.Configuration.AuthorizationSection.Rules
  id: Rules
  parent: System.Web.Configuration.AuthorizationSection
  langs:
  - csharp
  name: Rules
  nameWithType: AuthorizationSection.Rules
  fullName: AuthorizationSection.Rules
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets the <xref href="System.Web.Configuration.AuthorizationRuleCollection"></xref> of <xref href="System.Web.Configuration.AuthorizationRule"></xref> rules.
  remarks: The <xref:System.Web.Configuration.AuthorizationSection.Rules%2A> collection returned by this method does not refer to any actual element in the underlying configuration file. It is a construct that allows easy access to the rules it contains. This is a common pattern for handling the elements of a configuration file.
  example:
  - "The following code example shows how to use the <xref:System.Web.Configuration.AuthorizationSection.Rules%2A>.  \n  \n [!code-csharp[System.Web.Configuration.Authorization#6](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.Authorization/CS/authorization.cs#6)]\n [!code-vb[System.Web.Configuration.Authorization#6](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.Authorization/VB/authorization.vb#6)]"
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("", IsDefaultCollection=true)]

      public System.Web.Configuration.AuthorizationRuleCollection Rules { get; }
    return:
      type: System.Web.Configuration.AuthorizationRuleCollection
      description: Gets the <xref href="System.Web.Configuration.AuthorizationRuleCollection"></xref> of <xref href="System.Web.Configuration.AuthorizationRule"></xref> rules defined by the <xref href="System.Web.Configuration.AuthorizationSection"></xref>.
  overload: System.Web.Configuration.AuthorizationSection.Rules*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AuthorizationSection.xml
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.AuthorizationSection.#ctor
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: AuthorizationSection()
  nameWithType: AuthorizationSection.AuthorizationSection()
  fullName: AuthorizationSection.AuthorizationSection()
- uid: System.Web.Configuration.AuthorizationSection.PostDeserialize
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: PostDeserialize()
  nameWithType: AuthorizationSection.PostDeserialize()
  fullName: AuthorizationSection.PostDeserialize()
- uid: System.Web.Configuration.AuthorizationSection.Properties
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: Properties
  nameWithType: AuthorizationSection.Properties
  fullName: AuthorizationSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.AuthorizationSection.Rules
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: Rules
  nameWithType: AuthorizationSection.Rules
  fullName: AuthorizationSection.Rules
- uid: System.Web.Configuration.AuthorizationRuleCollection
  parent: System.Web.Configuration
  isExternal: false
  name: AuthorizationRuleCollection
  nameWithType: AuthorizationRuleCollection
  fullName: System.Web.Configuration.AuthorizationRuleCollection
- uid: System.Web.Configuration.AuthorizationSection.#ctor*
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: AuthorizationSection
  nameWithType: AuthorizationSection.AuthorizationSection
  fullName: AuthorizationSection.AuthorizationSection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AuthorizationSection.xml
- uid: System.Web.Configuration.AuthorizationSection.PostDeserialize*
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: PostDeserialize
  nameWithType: AuthorizationSection.PostDeserialize
  fullName: AuthorizationSection.PostDeserialize
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AuthorizationSection.xml
- uid: System.Web.Configuration.AuthorizationSection.Properties*
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: Properties
  nameWithType: AuthorizationSection.Properties
  fullName: AuthorizationSection.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AuthorizationSection.xml
- uid: System.Web.Configuration.AuthorizationSection.Rules*
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: Rules
  nameWithType: AuthorizationSection.Rules
  fullName: AuthorizationSection.Rules
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/AuthorizationSection.xml
