### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.PeerSecurityElement
  commentId: T:System.ServiceModel.Configuration.PeerSecurityElement
  id: PeerSecurityElement
  children:
  - System.ServiceModel.Configuration.PeerSecurityElement.#ctor
  - System.ServiceModel.Configuration.PeerSecurityElement.Mode
  - System.ServiceModel.Configuration.PeerSecurityElement.Properties
  - System.ServiceModel.Configuration.PeerSecurityElement.Transport
  langs:
  - csharp
  name: PeerSecurityElement
  nameWithType: PeerSecurityElement
  fullName: System.ServiceModel.Configuration.PeerSecurityElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Defines the configuration element for a peer's security settings.
  syntax:
    content: 'public sealed class PeerSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PeerSecurityElement.xml
  manager: ghogen
- uid: System.ServiceModel.Configuration.PeerSecurityElement.#ctor
  commentId: M:System.ServiceModel.Configuration.PeerSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  langs:
  - csharp
  name: PeerSecurityElement()
  nameWithType: PeerSecurityElement.PeerSecurityElement()
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.PeerSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new default instance of the <xref href="System.ServiceModel.Configuration.PeerSecurityElement"></xref> class.
  syntax:
    content: public PeerSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.PeerSecurityElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PeerSecurityElement.xml
  manager: ghogen
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Mode
  commentId: P:System.ServiceModel.Configuration.PeerSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: PeerSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets and sets the type of security used by peers configured with this element.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("mode", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.ServiceModel.SecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.SecurityMode
      description: <xref href="System.ServiceModel.SecurityMode"></xref> enumeration value that specifies the type of security used by peers configured with this element.
  overload: System.ServiceModel.Configuration.PeerSecurityElement.Mode*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PeerSecurityElement.xml
  manager: ghogen
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Properties
  commentId: P:System.ServiceModel.Configuration.PeerSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: PeerSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.PeerSecurityElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PeerSecurityElement.xml
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Transport
  commentId: P:System.ServiceModel.Configuration.PeerSecurityElement.Transport
  id: Transport
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  langs:
  - csharp
  name: Transport
  nameWithType: PeerSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets the transport type for secured messages sent by peers configured with this element.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("transport")]

      public System.ServiceModel.Configuration.PeerTransportSecurityElement Transport { get; }
    return:
      type: System.ServiceModel.Configuration.PeerTransportSecurityElement
      description: <xref href="System.ServiceModel.Configuration.PeerTransportSecurityElement"></xref> that specifies the transport type for secured messages sent by peers configured with this element.
  overload: System.ServiceModel.Configuration.PeerSecurityElement.Transport*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PeerSecurityElement.xml
  manager: ghogen
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.PeerSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  isExternal: false
  name: PeerSecurityElement()
  nameWithType: PeerSecurityElement.PeerSecurityElement()
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.PeerSecurityElement()
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Mode
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  isExternal: false
  name: Mode
  nameWithType: PeerSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.Mode
- uid: System.ServiceModel.SecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: SecurityMode
  nameWithType: SecurityMode
  fullName: System.ServiceModel.SecurityMode
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Properties
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  isExternal: false
  name: Properties
  nameWithType: PeerSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Transport
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  isExternal: false
  name: Transport
  nameWithType: PeerSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.Transport
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: PeerTransportSecurityElement
  nameWithType: PeerTransportSecurityElement
  fullName: System.ServiceModel.Configuration.PeerTransportSecurityElement
- uid: System.ServiceModel.Configuration.PeerSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  isExternal: false
  name: PeerSecurityElement
  nameWithType: PeerSecurityElement.PeerSecurityElement
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.PeerSecurityElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PeerSecurityElement.xml
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  isExternal: false
  name: Mode
  nameWithType: PeerSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.Mode
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PeerSecurityElement.xml
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  isExternal: false
  name: Properties
  nameWithType: PeerSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PeerSecurityElement.xml
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Transport*
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  isExternal: false
  name: Transport
  nameWithType: PeerSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.Transport
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PeerSecurityElement.xml
