### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.CustomTypeElement
  commentId: T:System.IdentityModel.Configuration.CustomTypeElement
  id: CustomTypeElement
  children:
  - System.IdentityModel.Configuration.CustomTypeElement.#ctor
  - System.IdentityModel.Configuration.CustomTypeElement.IsConfigured
  - System.IdentityModel.Configuration.CustomTypeElement.Properties
  - System.IdentityModel.Configuration.CustomTypeElement.Resolve``1(System.IdentityModel.Configuration.CustomTypeElement)
  - System.IdentityModel.Configuration.CustomTypeElement.Type
  langs:
  - csharp
  name: CustomTypeElement
  nameWithType: CustomTypeElement
  fullName: System.IdentityModel.Configuration.CustomTypeElement
  type: Class
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: Represents an element or attribute that specifies a custom <xref href="System.Type"></xref> in a configuration file. This class cannot be inherited.
  remarks: The <xref:System.IdentityModel.Configuration.CustomTypeElement> class represents an attribute or an element that specifies a custom type in a configuration file. For example, the [\&lt;claimsAuthenticationManager\&gt;](~/docs/framework/configure-apps/file-schema/windows-identity-foundation/claimsauthenticationmanager.md) element that is used to specify the claims identity manager contains `type` attribute that specifies the <xref:System.Type> of the claims authentication manager; `<claimsAuthenticationManager type="MyNamespace.CustomClaimsAuthenticationManager, MyAssembly"/>`. The <xref:System.IdentityModel.Configuration.IdentityConfigurationElement.ClaimsAuthenticationManager%2A?displayProperty=fullName> property that represents this element as configured under an [\&lt;identityConfiguration\&gt;](~/docs/framework/configure-apps/file-schema/windows-identity-foundation/identityconfiguration.md) element gets and sets an instance of <xref:System.IdentityModel.Configuration.CustomTypeElement>.
  syntax:
    content: 'public sealed class CustomTypeElement : System.IdentityModel.Configuration.ConfigurationElementInterceptor'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(System.Configuration.ConfigurationElement)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/CustomTypeElement.xml
  ms.author: v-jibran
  manager: markgal
- uid: System.IdentityModel.Configuration.CustomTypeElement.#ctor
  commentId: M:System.IdentityModel.Configuration.CustomTypeElement.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.CustomTypeElement
  langs:
  - csharp
  name: CustomTypeElement()
  nameWithType: CustomTypeElement.CustomTypeElement()
  fullName: System.IdentityModel.Configuration.CustomTypeElement.CustomTypeElement()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: Initializes a new instance of the <xref href="System.IdentityModel.Configuration.CustomTypeElement"></xref> class.
  syntax:
    content: public CustomTypeElement ();
    parameters: []
  overload: System.IdentityModel.Configuration.CustomTypeElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/CustomTypeElement.xml
  ms.author: v-jibran
  manager: markgal
- uid: System.IdentityModel.Configuration.CustomTypeElement.IsConfigured
  commentId: P:System.IdentityModel.Configuration.CustomTypeElement.IsConfigured
  id: IsConfigured
  parent: System.IdentityModel.Configuration.CustomTypeElement
  langs:
  - csharp
  name: IsConfigured
  nameWithType: CustomTypeElement.IsConfigured
  fullName: System.IdentityModel.Configuration.CustomTypeElement.IsConfigured
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: Gets a value that indicates whether the element has been configured with non-default values.
  syntax:
    content: public bool IsConfigured { get; }
    return:
      type: System.Boolean
      description: '`true` if the element has been configured with non-default values; otherwise, `false`.'
  overload: System.IdentityModel.Configuration.CustomTypeElement.IsConfigured*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/CustomTypeElement.xml
  ms.author: v-jibran
  manager: markgal
- uid: System.IdentityModel.Configuration.CustomTypeElement.Properties
  commentId: P:System.IdentityModel.Configuration.CustomTypeElement.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.CustomTypeElement
  langs:
  - csharp
  name: Properties
  nameWithType: CustomTypeElement.Properties
  fullName: System.IdentityModel.Configuration.CustomTypeElement.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.IdentityModel.Configuration.CustomTypeElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/CustomTypeElement.xml
- uid: System.IdentityModel.Configuration.CustomTypeElement.Resolve``1(System.IdentityModel.Configuration.CustomTypeElement)
  commentId: M:System.IdentityModel.Configuration.CustomTypeElement.Resolve``1(System.IdentityModel.Configuration.CustomTypeElement)
  id: Resolve``1(System.IdentityModel.Configuration.CustomTypeElement)
  parent: System.IdentityModel.Configuration.CustomTypeElement
  langs:
  - csharp
  name: Resolve<T>(CustomTypeElement)
  nameWithType: CustomTypeElement.Resolve<T>(CustomTypeElement)
  fullName: System.IdentityModel.Configuration.CustomTypeElement.Resolve<T>(CustomTypeElement)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: Attempts to resolve the custom type element to an object of the specified <xref href="System.Type"></xref>.
  syntax:
    content: 'public static T Resolve<T> (System.IdentityModel.Configuration.CustomTypeElement customTypeElement) where T : class;'
    parameters:
    - id: customTypeElement
      type: System.IdentityModel.Configuration.CustomTypeElement
      description: The custom type element to resolve.
    return:
      type: T
      description: An object of <xref href="System.Type"></xref><code>T</code>.
  overload: System.IdentityModel.Configuration.CustomTypeElement.Resolve``1*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/CustomTypeElement.xml
  ms.author: v-jibran
  manager: markgal
- uid: System.IdentityModel.Configuration.CustomTypeElement.Type
  commentId: P:System.IdentityModel.Configuration.CustomTypeElement.Type
  id: Type
  parent: System.IdentityModel.Configuration.CustomTypeElement
  langs:
  - csharp
  name: Type
  nameWithType: CustomTypeElement.Type
  fullName: System.IdentityModel.Configuration.CustomTypeElement.Type
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: The <xref href="System.Type"></xref> represented by the current instance.
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(System.Configuration.TypeNameConverter))]

      [System.Configuration.ConfigurationProperty("type", IsKey=true, IsRequired=true)]

      public Type Type { get; set; }
    return:
      type: System.Type
      description: The type represented by this instance.
  overload: System.IdentityModel.Configuration.CustomTypeElement.Type*
  exceptions: []
  attributes:
  - type: System.ComponentModel.TypeConverterAttribute
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/CustomTypeElement.xml
  ms.author: v-jibran
  manager: markgal
references:
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  parent: System.IdentityModel.Configuration
  isExternal: false
  name: ConfigurationElementInterceptor
  nameWithType: ConfigurationElementInterceptor
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor
- uid: System.IdentityModel.Configuration.CustomTypeElement.#ctor
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: CustomTypeElement()
  nameWithType: CustomTypeElement.CustomTypeElement()
  fullName: System.IdentityModel.Configuration.CustomTypeElement.CustomTypeElement()
- uid: System.IdentityModel.Configuration.CustomTypeElement.IsConfigured
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: IsConfigured
  nameWithType: CustomTypeElement.IsConfigured
  fullName: System.IdentityModel.Configuration.CustomTypeElement.IsConfigured
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.IdentityModel.Configuration.CustomTypeElement.Properties
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: Properties
  nameWithType: CustomTypeElement.Properties
  fullName: System.IdentityModel.Configuration.CustomTypeElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.CustomTypeElement.Resolve``1(System.IdentityModel.Configuration.CustomTypeElement)
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: Resolve<T>(CustomTypeElement)
  nameWithType: CustomTypeElement.Resolve<T>(CustomTypeElement)
  fullName: System.IdentityModel.Configuration.CustomTypeElement.Resolve<T>(CustomTypeElement)
- uid: T
  isExternal: true
  name: T
  nameWithType: T
  fullName: T
- uid: System.IdentityModel.Configuration.CustomTypeElement
  parent: System.IdentityModel.Configuration
  isExternal: false
  name: CustomTypeElement
  nameWithType: CustomTypeElement
  fullName: System.IdentityModel.Configuration.CustomTypeElement
- uid: System.IdentityModel.Configuration.CustomTypeElement.Type
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: Type
  nameWithType: CustomTypeElement.Type
  fullName: System.IdentityModel.Configuration.CustomTypeElement.Type
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.IdentityModel.Configuration.CustomTypeElement.#ctor*
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: CustomTypeElement
  nameWithType: CustomTypeElement.CustomTypeElement
  fullName: System.IdentityModel.Configuration.CustomTypeElement.CustomTypeElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/CustomTypeElement.xml
- uid: System.IdentityModel.Configuration.CustomTypeElement.IsConfigured*
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: IsConfigured
  nameWithType: CustomTypeElement.IsConfigured
  fullName: System.IdentityModel.Configuration.CustomTypeElement.IsConfigured
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/CustomTypeElement.xml
- uid: System.IdentityModel.Configuration.CustomTypeElement.Properties*
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: Properties
  nameWithType: CustomTypeElement.Properties
  fullName: System.IdentityModel.Configuration.CustomTypeElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/CustomTypeElement.xml
- uid: System.IdentityModel.Configuration.CustomTypeElement.Resolve``1*
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: Resolve<T>
  nameWithType: CustomTypeElement.Resolve<T>
  fullName: System.IdentityModel.Configuration.CustomTypeElement.Resolve<T>
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/CustomTypeElement.xml
- uid: System.IdentityModel.Configuration.CustomTypeElement.Type*
  parent: System.IdentityModel.Configuration.CustomTypeElement
  isExternal: false
  name: Type
  nameWithType: CustomTypeElement.Type
  fullName: System.IdentityModel.Configuration.CustomTypeElement.Type
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IdentityModel.Configuration/CustomTypeElement.xml
