### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.TypeElement
  commentId: T:System.Web.Services.Configuration.TypeElement
  id: TypeElement
  children:
  - System.Web.Services.Configuration.TypeElement.#ctor
  - System.Web.Services.Configuration.TypeElement.#ctor(System.String)
  - System.Web.Services.Configuration.TypeElement.#ctor(System.Type)
  - System.Web.Services.Configuration.TypeElement.Properties
  - System.Web.Services.Configuration.TypeElement.Type
  langs:
  - csharp
  name: TypeElement
  nameWithType: TypeElement
  fullName: System.Web.Services.Configuration.TypeElement
  type: Class
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Represents the `type` element in the Web services configuration file.
  syntax:
    content: 'public sealed class TypeElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/TypeElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.Web.Services.Configuration.TypeElement.#ctor
  commentId: M:System.Web.Services.Configuration.TypeElement.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.TypeElement
  langs:
  - csharp
  name: TypeElement()
  nameWithType: TypeElement.TypeElement()
  fullName: System.Web.Services.Configuration.TypeElement.TypeElement()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Initializes an instance of the <xref href="System.Web.Services.Configuration.TypeElement"></xref> class.
  syntax:
    content: public TypeElement ();
    parameters: []
  overload: System.Web.Services.Configuration.TypeElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/TypeElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.Web.Services.Configuration.TypeElement.#ctor(System.String)
  commentId: M:System.Web.Services.Configuration.TypeElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Services.Configuration.TypeElement
  langs:
  - csharp
  name: TypeElement(String)
  nameWithType: TypeElement.TypeElement(String)
  fullName: System.Web.Services.Configuration.TypeElement.TypeElement(String)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Initializes an instance of the <xref href="System.Web.Services.Configuration.TypeElement"></xref> class.
  syntax:
    content: public TypeElement (string type);
    parameters:
    - id: type
      type: System.String
      description: The type of the configuration attribute.
  overload: System.Web.Services.Configuration.TypeElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/TypeElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.Web.Services.Configuration.TypeElement.#ctor(System.Type)
  commentId: M:System.Web.Services.Configuration.TypeElement.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Web.Services.Configuration.TypeElement
  langs:
  - csharp
  name: TypeElement(Type)
  nameWithType: TypeElement.TypeElement(Type)
  fullName: System.Web.Services.Configuration.TypeElement.TypeElement(Type)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Initializes an instance of the <xref href="System.Web.Services.Configuration.TypeElement"></xref> class.
  syntax:
    content: public TypeElement (Type type);
    parameters:
    - id: type
      type: System.Type
      description: The type of the configuration attribute.
  overload: System.Web.Services.Configuration.TypeElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/TypeElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.Web.Services.Configuration.TypeElement.Properties
  commentId: P:System.Web.Services.Configuration.TypeElement.Properties
  id: Properties
  parent: System.Web.Services.Configuration.TypeElement
  langs:
  - csharp
  name: Properties
  nameWithType: TypeElement.Properties
  fullName: System.Web.Services.Configuration.TypeElement.Properties
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Services.Configuration.TypeElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/TypeElement.xml
- uid: System.Web.Services.Configuration.TypeElement.Type
  commentId: P:System.Web.Services.Configuration.TypeElement.Type
  id: Type
  parent: System.Web.Services.Configuration.TypeElement
  langs:
  - csharp
  name: Type
  nameWithType: TypeElement.Type
  fullName: System.Web.Services.Configuration.TypeElement.Type
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: Gets or sets the type of the configuration attribute.
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(System.Web.Services.Configuration.TypeAndNameConverter))]

      [System.Configuration.ConfigurationProperty("type", IsKey=true)]

      public Type Type { get; set; }
    return:
      type: System.Type
      description: The type of the configuration attribute.
  overload: System.Web.Services.Configuration.TypeElement.Type*
  exceptions: []
  attributes:
  - type: System.ComponentModel.TypeConverterAttribute
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/TypeElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Services.Configuration.TypeElement.#ctor
  parent: System.Web.Services.Configuration.TypeElement
  isExternal: false
  name: TypeElement()
  nameWithType: TypeElement.TypeElement()
  fullName: System.Web.Services.Configuration.TypeElement.TypeElement()
- uid: System.Web.Services.Configuration.TypeElement.#ctor(System.String)
  parent: System.Web.Services.Configuration.TypeElement
  isExternal: false
  name: TypeElement(String)
  nameWithType: TypeElement.TypeElement(String)
  fullName: System.Web.Services.Configuration.TypeElement.TypeElement(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Services.Configuration.TypeElement.#ctor(System.Type)
  parent: System.Web.Services.Configuration.TypeElement
  isExternal: false
  name: TypeElement(Type)
  nameWithType: TypeElement.TypeElement(Type)
  fullName: System.Web.Services.Configuration.TypeElement.TypeElement(Type)
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Web.Services.Configuration.TypeElement.Properties
  parent: System.Web.Services.Configuration.TypeElement
  isExternal: false
  name: Properties
  nameWithType: TypeElement.Properties
  fullName: System.Web.Services.Configuration.TypeElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Services.Configuration.TypeElement.Type
  parent: System.Web.Services.Configuration.TypeElement
  isExternal: false
  name: Type
  nameWithType: TypeElement.Type
  fullName: System.Web.Services.Configuration.TypeElement.Type
- uid: System.Web.Services.Configuration.TypeElement.#ctor*
  parent: System.Web.Services.Configuration.TypeElement
  isExternal: false
  name: TypeElement
  nameWithType: TypeElement.TypeElement
  fullName: System.Web.Services.Configuration.TypeElement.TypeElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/TypeElement.xml
- uid: System.Web.Services.Configuration.TypeElement.Properties*
  parent: System.Web.Services.Configuration.TypeElement
  isExternal: false
  name: Properties
  nameWithType: TypeElement.Properties
  fullName: System.Web.Services.Configuration.TypeElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/TypeElement.xml
- uid: System.Web.Services.Configuration.TypeElement.Type*
  parent: System.Web.Services.Configuration.TypeElement
  isExternal: false
  name: Type
  nameWithType: TypeElement.Type
  fullName: System.Web.Services.Configuration.TypeElement.Type
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Services.Configuration/TypeElement.xml
