### YamlMime:ManagedReference
items:
- uid: System.Transactions.Configuration.TransactionsSectionGroup
  commentId: T:System.Transactions.Configuration.TransactionsSectionGroup
  id: TransactionsSectionGroup
  children:
  - System.Transactions.Configuration.TransactionsSectionGroup.#ctor
  - System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings
  - System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  - System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings
  langs:
  - csharp
  name: TransactionsSectionGroup
  nameWithType: TransactionsSectionGroup
  fullName: System.Transactions.Configuration.TransactionsSectionGroup
  type: Class
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: Represents a configuration section that encapsulates and allows traversal of all the transaction configuration XML elements and attributes that are within this configuration section. This class cannot be inherited.
  syntax:
    content: 'public class TransactionsSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Transactions.Configuration/TransactionsSectionGroup.xml
  manager: ghogen
- uid: System.Transactions.Configuration.TransactionsSectionGroup.#ctor
  commentId: M:System.Transactions.Configuration.TransactionsSectionGroup.#ctor
  id: '#ctor'
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  langs:
  - csharp
  name: TransactionsSectionGroup()
  nameWithType: TransactionsSectionGroup.TransactionsSectionGroup()
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.TransactionsSectionGroup()
  type: Constructor
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: Initializes a new instance of the <xref href="System.Transactions.Configuration.TransactionsSectionGroup"></xref> class.
  syntax:
    content: public TransactionsSectionGroup ();
    parameters: []
  overload: System.Transactions.Configuration.TransactionsSectionGroup.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Transactions.Configuration/TransactionsSectionGroup.xml
  manager: ghogen
- uid: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings
  commentId: P:System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings
  id: DefaultSettings
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  langs:
  - csharp
  name: DefaultSettings
  nameWithType: TransactionsSectionGroup.DefaultSettings
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings
  type: Property
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: Gets the default settings used to initialize the elements and attributes in a transactions section.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("defaultSettings")]

      public System.Transactions.Configuration.DefaultSettingsSection DefaultSettings { get; }
    return:
      type: System.Transactions.Configuration.DefaultSettingsSection
      description: A <xref href="System.Transactions.Configuration.DefaultSettingsSection"></xref> that represents the default settings. The default is a <xref href="System.Transactions.Configuration.DefaultSettingsSection"></xref> that is populated with default values.
  overload: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Transactions.Configuration/TransactionsSectionGroup.xml
  manager: ghogen
- uid: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  commentId: M:System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  id: GetSectionGroup(System.Configuration.Configuration)
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  langs:
  - csharp
  name: GetSectionGroup(Configuration)
  nameWithType: TransactionsSectionGroup.GetSectionGroup(Configuration)
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup(Configuration)
  type: Method
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: Provides static access to a <xref href="System.Transactions.Configuration.TransactionsSectionGroup"></xref>.
  syntax:
    content: public static System.Transactions.Configuration.TransactionsSectionGroup GetSectionGroup (System.Configuration.Configuration config);
    parameters:
    - id: config
      type: System.Configuration.Configuration
      description: A <xref href="System.Configuration.Configuration"></xref> representing the configuration settings that apply to a particular computer, application, or resource.
    return:
      type: System.Transactions.Configuration.TransactionsSectionGroup
      description: A <xref href="System.Transactions.Configuration.TransactionsSectionGroup"></xref> object.
  overload: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Transactions.Configuration/TransactionsSectionGroup.xml
  manager: ghogen
- uid: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings
  commentId: P:System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings
  id: MachineSettings
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  langs:
  - csharp
  name: MachineSettings
  nameWithType: TransactionsSectionGroup.MachineSettings
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings
  type: Property
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: Gets the configuration settings set at the machine level.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("machineSettings")]

      public System.Transactions.Configuration.MachineSettingsSection MachineSettings { get; }
    return:
      type: System.Transactions.Configuration.MachineSettingsSection
      description: A <xref href="System.Transactions.Configuration.MachineSettingsSection"></xref> that represents the configuration settings at the machine level. The default is a <xref href="System.Transactions.Configuration.MachineSettingsSection"></xref> that is populated with default values.
  overload: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Transactions.Configuration/TransactionsSectionGroup.xml
  manager: ghogen
references:
- uid: System.Configuration.ConfigurationSectionGroup
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSectionGroup
  nameWithType: ConfigurationSectionGroup
  fullName: System.Configuration.ConfigurationSectionGroup
- uid: System.Transactions.Configuration.TransactionsSectionGroup.#ctor
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: TransactionsSectionGroup()
  nameWithType: TransactionsSectionGroup.TransactionsSectionGroup()
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.TransactionsSectionGroup()
- uid: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: DefaultSettings
  nameWithType: TransactionsSectionGroup.DefaultSettings
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings
- uid: System.Transactions.Configuration.DefaultSettingsSection
  parent: System.Transactions.Configuration
  isExternal: false
  name: DefaultSettingsSection
  nameWithType: DefaultSettingsSection
  fullName: System.Transactions.Configuration.DefaultSettingsSection
- uid: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: GetSectionGroup(Configuration)
  nameWithType: TransactionsSectionGroup.GetSectionGroup(Configuration)
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup(Configuration)
- uid: System.Transactions.Configuration.TransactionsSectionGroup
  parent: System.Transactions.Configuration
  isExternal: false
  name: TransactionsSectionGroup
  nameWithType: TransactionsSectionGroup
  fullName: System.Transactions.Configuration.TransactionsSectionGroup
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: MachineSettings
  nameWithType: TransactionsSectionGroup.MachineSettings
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings
- uid: System.Transactions.Configuration.MachineSettingsSection
  parent: System.Transactions.Configuration
  isExternal: false
  name: MachineSettingsSection
  nameWithType: MachineSettingsSection
  fullName: System.Transactions.Configuration.MachineSettingsSection
- uid: System.Transactions.Configuration.TransactionsSectionGroup.#ctor*
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: TransactionsSectionGroup
  nameWithType: TransactionsSectionGroup.TransactionsSectionGroup
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.TransactionsSectionGroup
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Transactions.Configuration/TransactionsSectionGroup.xml
- uid: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings*
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: DefaultSettings
  nameWithType: TransactionsSectionGroup.DefaultSettings
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.DefaultSettings
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Transactions.Configuration/TransactionsSectionGroup.xml
- uid: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup*
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: GetSectionGroup
  nameWithType: TransactionsSectionGroup.GetSectionGroup
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.GetSectionGroup
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Transactions.Configuration/TransactionsSectionGroup.xml
- uid: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings*
  parent: System.Transactions.Configuration.TransactionsSectionGroup
  isExternal: false
  name: MachineSettings
  nameWithType: TransactionsSectionGroup.MachineSettings
  fullName: System.Transactions.Configuration.TransactionsSectionGroup.MachineSettings
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Transactions.Configuration/TransactionsSectionGroup.xml
