### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SessionPageStateSection
  commentId: T:System.Web.Configuration.SessionPageStateSection
  id: SessionPageStateSection
  children:
  - System.Web.Configuration.SessionPageStateSection.#ctor
  - System.Web.Configuration.SessionPageStateSection.DefaultHistorySize
  - System.Web.Configuration.SessionPageStateSection.HistorySize
  - System.Web.Configuration.SessionPageStateSection.Properties
  langs:
  - csharp
  name: SessionPageStateSection
  nameWithType: SessionPageStateSection
  fullName: System.Web.Configuration.SessionPageStateSection
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Configures the `sessionPageState` section. This class cannot be inherited.
  remarks: "The <xref:System.Web.Configuration.SessionPageStateSection> refers to the `sessionPageState` section of the configuration file.  \n  \n> [!NOTE]\n>  The <xref:System.Web.Configuration.SessionPageStateSection> can read and write information from and to the related section of the configuration file according to the section property <xref:System.Configuration.SectionInformation.AllowDefinition%2A> whose value is <xref:System.Configuration.ConfigurationAllowDefinition>."
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.SessionPageStateSection> object from the configuration file associated with an existing Web application.  \n  \n [!code-csharp[System.Web.Configuration.SessionPageStateSection#1](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.SessionPageStateSection/CS/sessionpagestatesection.cs#1)]\n [!code-vb[System.Web.Configuration.SessionPageStateSection#1](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.SessionPageStateSection/VB/sessionpagestatesection.vb#1)]"
  syntax:
    content: 'public sealed class SessionPageStateSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SessionPageStateSection.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.SessionPageStateSection.#ctor
  commentId: M:System.Web.Configuration.SessionPageStateSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.SessionPageStateSection
  langs:
  - csharp
  name: SessionPageStateSection()
  nameWithType: SessionPageStateSection.SessionPageStateSection()
  fullName: System.Web.Configuration.SessionPageStateSection.SessionPageStateSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Creates a new instance of <xref href="System.Web.Configuration.SessionPageStateSection"></xref>.
  remarks: The <xref:System.Web.Configuration.SessionPageStateSection.%23ctor%2A> constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system. You obtain an instance of the <xref:System.Web.Configuration.SessionPageStateSection> class by using the <xref:System.Configuration.Configuration.GetSection%2A> method.
  syntax:
    content: public SessionPageStateSection ();
    parameters: []
  overload: System.Web.Configuration.SessionPageStateSection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SessionPageStateSection.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.SessionPageStateSection.DefaultHistorySize
  commentId: F:System.Web.Configuration.SessionPageStateSection.DefaultHistorySize
  id: DefaultHistorySize
  parent: System.Web.Configuration.SessionPageStateSection
  langs:
  - csharp
  name: DefaultHistorySize
  nameWithType: SessionPageStateSection.DefaultHistorySize
  fullName: System.Web.Configuration.SessionPageStateSection.DefaultHistorySize
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Defines the size of the page history.
  remarks: ''
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.SessionPageStateSection.DefaultHistorySize> property from the configuration file associated with an existing Web application.  \n  \n [!code-csharp[System.Web.Configuration.SessionPageStateSection#2](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.SessionPageStateSection/CS/sessionpagestatesection.cs#2)]\n [!code-vb[System.Web.Configuration.SessionPageStateSection#2](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.SessionPageStateSection/VB/sessionpagestatesection.vb#2)]"
  syntax:
    content: public const int DefaultHistorySize = 9;
    return:
      type: System.Int32
      description: To be added.
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SessionPageStateSection.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.SessionPageStateSection.HistorySize
  commentId: P:System.Web.Configuration.SessionPageStateSection.HistorySize
  id: HistorySize
  parent: System.Web.Configuration.SessionPageStateSection
  langs:
  - csharp
  name: HistorySize
  nameWithType: SessionPageStateSection.HistorySize
  fullName: System.Web.Configuration.SessionPageStateSection.HistorySize
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets or sets the size of the page history.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("historySize", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      [System.Configuration.IntegerValidator(MinValue=1)]

      public int HistorySize { get; set; }
    return:
      type: System.Int32
      description: The size of the page history.
  overload: System.Web.Configuration.SessionPageStateSection.HistorySize*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.IntegerValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SessionPageStateSection.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.SessionPageStateSection.Properties
  commentId: P:System.Web.Configuration.SessionPageStateSection.Properties
  id: Properties
  parent: System.Web.Configuration.SessionPageStateSection
  langs:
  - csharp
  name: Properties
  nameWithType: SessionPageStateSection.Properties
  fullName: System.Web.Configuration.SessionPageStateSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.SessionPageStateSection.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SessionPageStateSection.xml
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.SessionPageStateSection.#ctor
  parent: System.Web.Configuration.SessionPageStateSection
  isExternal: false
  name: SessionPageStateSection()
  nameWithType: SessionPageStateSection.SessionPageStateSection()
  fullName: System.Web.Configuration.SessionPageStateSection.SessionPageStateSection()
- uid: System.Web.Configuration.SessionPageStateSection.DefaultHistorySize
  parent: System.Web.Configuration.SessionPageStateSection
  isExternal: false
  name: DefaultHistorySize
  nameWithType: SessionPageStateSection.DefaultHistorySize
  fullName: System.Web.Configuration.SessionPageStateSection.DefaultHistorySize
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.SessionPageStateSection.HistorySize
  parent: System.Web.Configuration.SessionPageStateSection
  isExternal: false
  name: HistorySize
  nameWithType: SessionPageStateSection.HistorySize
  fullName: System.Web.Configuration.SessionPageStateSection.HistorySize
- uid: System.Web.Configuration.SessionPageStateSection.Properties
  parent: System.Web.Configuration.SessionPageStateSection
  isExternal: false
  name: Properties
  nameWithType: SessionPageStateSection.Properties
  fullName: System.Web.Configuration.SessionPageStateSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.SessionPageStateSection.#ctor*
  parent: System.Web.Configuration.SessionPageStateSection
  isExternal: false
  name: SessionPageStateSection
  nameWithType: SessionPageStateSection.SessionPageStateSection
  fullName: System.Web.Configuration.SessionPageStateSection.SessionPageStateSection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SessionPageStateSection.xml
- uid: System.Web.Configuration.SessionPageStateSection.HistorySize*
  parent: System.Web.Configuration.SessionPageStateSection
  isExternal: false
  name: HistorySize
  nameWithType: SessionPageStateSection.HistorySize
  fullName: System.Web.Configuration.SessionPageStateSection.HistorySize
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SessionPageStateSection.xml
- uid: System.Web.Configuration.SessionPageStateSection.Properties*
  parent: System.Web.Configuration.SessionPageStateSection
  isExternal: false
  name: Properties
  nameWithType: SessionPageStateSection.Properties
  fullName: System.Web.Configuration.SessionPageStateSection.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SessionPageStateSection.xml
