### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BasicHttpSecurityElement
  commentId: T:System.ServiceModel.Configuration.BasicHttpSecurityElement
  id: BasicHttpSecurityElement
  children:
  - System.ServiceModel.Configuration.BasicHttpSecurityElement.#ctor
  - System.ServiceModel.Configuration.BasicHttpSecurityElement.Message
  - System.ServiceModel.Configuration.BasicHttpSecurityElement.Mode
  - System.ServiceModel.Configuration.BasicHttpSecurityElement.Properties
  - System.ServiceModel.Configuration.BasicHttpSecurityElement.Transport
  langs:
  - csharp
  name: BasicHttpSecurityElement
  nameWithType: BasicHttpSecurityElement
  fullName: System.ServiceModel.Configuration.BasicHttpSecurityElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents an XML element that configures the security for a basic HTTP service.
  syntax:
    content: 'public sealed class BasicHttpSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.BasicHttpSecurityElement.#ctor
  commentId: M:System.ServiceModel.Configuration.BasicHttpSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BasicHttpSecurityElement
  langs:
  - csharp
  name: BasicHttpSecurityElement()
  nameWithType: BasicHttpSecurityElement.BasicHttpSecurityElement()
  fullName: System.ServiceModel.Configuration.BasicHttpSecurityElement.BasicHttpSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.BasicHttpSecurityElement"></xref> class.
  syntax:
    content: public BasicHttpSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.BasicHttpSecurityElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.BasicHttpSecurityElement.Message
  commentId: P:System.ServiceModel.Configuration.BasicHttpSecurityElement.Message
  id: Message
  parent: System.ServiceModel.Configuration.BasicHttpSecurityElement
  langs:
  - csharp
  name: Message
  nameWithType: BasicHttpSecurityElement.Message
  fullName: System.ServiceModel.Configuration.BasicHttpSecurityElement.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets an XML element that configures the message security for a basic HTTP service.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("message")]

      public System.ServiceModel.Configuration.BasicHttpMessageSecurityElement Message { get; }
    return:
      type: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
      description: An XML element that configures the message security for a basic HTTP service.
  overload: System.ServiceModel.Configuration.BasicHttpSecurityElement.Message*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.BasicHttpSecurityElement.Mode
  commentId: P:System.ServiceModel.Configuration.BasicHttpSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.BasicHttpSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: BasicHttpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.BasicHttpSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets an XML element that specifies the security mode for a basic HTTP service.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("mode", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.ServiceModel.BasicHttpSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.BasicHttpSecurityMode
      description: The security mode for a basic HTTP service.
  overload: System.ServiceModel.Configuration.BasicHttpSecurityElement.Mode*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.BasicHttpSecurityElement.Properties
  commentId: P:System.ServiceModel.Configuration.BasicHttpSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.BasicHttpSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: BasicHttpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.BasicHttpSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.BasicHttpSecurityElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpSecurityElement.xml
- uid: System.ServiceModel.Configuration.BasicHttpSecurityElement.Transport
  commentId: P:System.ServiceModel.Configuration.BasicHttpSecurityElement.Transport
  id: Transport
  parent: System.ServiceModel.Configuration.BasicHttpSecurityElement
  langs:
  - csharp
  name: Transport
  nameWithType: BasicHttpSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.BasicHttpSecurityElement.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets an XML element that specifies the transport for a basic HTTP service.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("transport")]

      public System.ServiceModel.Configuration.HttpTransportSecurityElement Transport { get; }
    return:
      type: System.ServiceModel.Configuration.HttpTransportSecurityElement
      description: An XML element that specifies the transport for a basic HTTP service.
  overload: System.ServiceModel.Configuration.BasicHttpSecurityElement.Transport*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.BasicHttpSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.BasicHttpSecurityElement
  isExternal: false
  name: BasicHttpSecurityElement()
  nameWithType: BasicHttpSecurityElement.BasicHttpSecurityElement()
  fullName: System.ServiceModel.Configuration.BasicHttpSecurityElement.BasicHttpSecurityElement()
- uid: System.ServiceModel.Configuration.BasicHttpSecurityElement.Message
  parent: System.ServiceModel.Configuration.BasicHttpSecurityElement
  isExternal: false
  name: Message
  nameWithType: BasicHttpSecurityElement.Message
  fullName: System.ServiceModel.Configuration.BasicHttpSecurityElement.Message
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: BasicHttpMessageSecurityElement
  nameWithType: BasicHttpMessageSecurityElement
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
- uid: System.ServiceModel.Configuration.BasicHttpSecurityElement.Mode
  parent: System.ServiceModel.Configuration.BasicHttpSecurityElement
  isExternal: false
  name: Mode
  nameWithType: BasicHttpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.BasicHttpSecurityElement.Mode
- uid: System.ServiceModel.BasicHttpSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: BasicHttpSecurityMode
  nameWithType: BasicHttpSecurityMode
  fullName: System.ServiceModel.BasicHttpSecurityMode
- uid: System.ServiceModel.Configuration.BasicHttpSecurityElement.Properties
  parent: System.ServiceModel.Configuration.BasicHttpSecurityElement
  isExternal: false
  name: Properties
  nameWithType: BasicHttpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.BasicHttpSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.BasicHttpSecurityElement.Transport
  parent: System.ServiceModel.Configuration.BasicHttpSecurityElement
  isExternal: false
  name: Transport
  nameWithType: BasicHttpSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.BasicHttpSecurityElement.Transport
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: HttpTransportSecurityElement
  nameWithType: HttpTransportSecurityElement
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement
- uid: System.ServiceModel.Configuration.BasicHttpSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.BasicHttpSecurityElement
  isExternal: false
  name: BasicHttpSecurityElement
  nameWithType: BasicHttpSecurityElement.BasicHttpSecurityElement
  fullName: System.ServiceModel.Configuration.BasicHttpSecurityElement.BasicHttpSecurityElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpSecurityElement.xml
- uid: System.ServiceModel.Configuration.BasicHttpSecurityElement.Message*
  parent: System.ServiceModel.Configuration.BasicHttpSecurityElement
  isExternal: false
  name: Message
  nameWithType: BasicHttpSecurityElement.Message
  fullName: System.ServiceModel.Configuration.BasicHttpSecurityElement.Message
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpSecurityElement.xml
- uid: System.ServiceModel.Configuration.BasicHttpSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.BasicHttpSecurityElement
  isExternal: false
  name: Mode
  nameWithType: BasicHttpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.BasicHttpSecurityElement.Mode
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpSecurityElement.xml
- uid: System.ServiceModel.Configuration.BasicHttpSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.BasicHttpSecurityElement
  isExternal: false
  name: Properties
  nameWithType: BasicHttpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.BasicHttpSecurityElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpSecurityElement.xml
- uid: System.ServiceModel.Configuration.BasicHttpSecurityElement.Transport*
  parent: System.ServiceModel.Configuration.BasicHttpSecurityElement
  isExternal: false
  name: Transport
  nameWithType: BasicHttpSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.BasicHttpSecurityElement.Transport
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpSecurityElement.xml
