### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebControlsSection
  commentId: T:System.Web.Configuration.WebControlsSection
  id: WebControlsSection
  children:
  - System.Web.Configuration.WebControlsSection.#ctor
  - System.Web.Configuration.WebControlsSection.ClientScriptsLocation
  - System.Web.Configuration.WebControlsSection.GetRuntimeObject
  - System.Web.Configuration.WebControlsSection.Properties
  langs:
  - csharp
  name: WebControlsSection
  nameWithType: WebControlsSection
  fullName: System.Web.Configuration.WebControlsSection
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Configures the `webControls` section. This class cannot be inherited.
  remarks: "The <xref:System.Web.Configuration.WebControlsSection> class provides a way to programmatically access and modify the `webControls` section of a configuration file.  \n  \n> [!NOTE]\n>  ASP.NET provides a shared location for the client script files, where they can be accessed from multiple pages and across applications.  The <xref:System.Web.Configuration.WebControlsSection> can read and write information from and to the related section of the configuration file according to the section property <xref:System.Configuration.SectionInformation.AllowDefinition%2A> whose value is <xref:System.Configuration.ConfigurationAllowDefinition.Everywhere>."
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.WebControlsSection> object from the configuration file associated with an existing Web application.  \n  \n [!code-csharp[System.Web.Configuration.WebControlsSection#1](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.WebControlsSection/CS/webcontrolssection.cs#1)]\n [!code-vb[System.Web.Configuration.WebControlsSection#1](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.WebControlsSection/VB/vb_webcontrolssection.vb#1)]"
  syntax:
    content: 'public sealed class WebControlsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/WebControlsSection.xml
- uid: System.Web.Configuration.WebControlsSection.#ctor
  commentId: M:System.Web.Configuration.WebControlsSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.WebControlsSection
  langs:
  - csharp
  name: WebControlsSection()
  nameWithType: WebControlsSection.WebControlsSection()
  fullName: WebControlsSection.WebControlsSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Creates a new instance of <xref href="System.Web.Configuration.WebControlsSection"></xref>.
  remarks: The <xref:System.Web.Configuration.WebControlsSection.%23ctor%2A> constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system. You obtain an instance of the <xref:System.Web.Configuration.WebControlsSection> class by using the <xref:System.Configuration.Configuration.GetSection%2A> method.
  syntax:
    content: public WebControlsSection ();
    parameters: []
  overload: System.Web.Configuration.WebControlsSection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/WebControlsSection.xml
- uid: System.Web.Configuration.WebControlsSection.ClientScriptsLocation
  commentId: P:System.Web.Configuration.WebControlsSection.ClientScriptsLocation
  id: ClientScriptsLocation
  parent: System.Web.Configuration.WebControlsSection
  langs:
  - csharp
  name: ClientScriptsLocation
  nameWithType: WebControlsSection.ClientScriptsLocation
  fullName: WebControlsSection.ClientScriptsLocation
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets the client scripts location.
  remarks: For details about the client scripts and their use, refer to [Client Script in ASP.NET Web Pages](http://msdn.microsoft.com/library/13edb6b9-2dea-43c6-b8c1-a47207de19aa).
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.WebControlsSection.ClientScriptsLocation%2A>.  \n  \n [!code-csharp[System.Web.Configuration.WebControlsSection#1](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.WebControlsSection/CS/webcontrolssection.cs#1)]\n [!code-vb[System.Web.Configuration.WebControlsSection#1](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.WebControlsSection/VB/vb_webcontrolssection.vb#1)]"
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("clientScriptsLocation", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsRequired=true)]

      [System.Configuration.StringValidator(MinLength=1)]

      public string ClientScriptsLocation { get; }
    return:
      type: System.String
      description: The location of the client scripts.
  overload: System.Web.Configuration.WebControlsSection.ClientScriptsLocation*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/WebControlsSection.xml
- uid: System.Web.Configuration.WebControlsSection.GetRuntimeObject
  commentId: M:System.Web.Configuration.WebControlsSection.GetRuntimeObject
  id: GetRuntimeObject
  parent: System.Web.Configuration.WebControlsSection
  langs:
  - csharp
  name: GetRuntimeObject()
  nameWithType: WebControlsSection.GetRuntimeObject()
  fullName: WebControlsSection.GetRuntimeObject()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override object GetRuntimeObject ();
    parameters: []
    return:
      type: System.Object
      description: To be added.
  overload: System.Web.Configuration.WebControlsSection.GetRuntimeObject*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/WebControlsSection.xml
- uid: System.Web.Configuration.WebControlsSection.Properties
  commentId: P:System.Web.Configuration.WebControlsSection.Properties
  id: Properties
  parent: System.Web.Configuration.WebControlsSection
  langs:
  - csharp
  name: Properties
  nameWithType: WebControlsSection.Properties
  fullName: WebControlsSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.WebControlsSection.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/WebControlsSection.xml
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.WebControlsSection.#ctor
  parent: System.Web.Configuration.WebControlsSection
  isExternal: false
  name: WebControlsSection()
  nameWithType: WebControlsSection.WebControlsSection()
  fullName: WebControlsSection.WebControlsSection()
- uid: System.Web.Configuration.WebControlsSection.ClientScriptsLocation
  parent: System.Web.Configuration.WebControlsSection
  isExternal: false
  name: ClientScriptsLocation
  nameWithType: WebControlsSection.ClientScriptsLocation
  fullName: WebControlsSection.ClientScriptsLocation
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.WebControlsSection.GetRuntimeObject
  parent: System.Web.Configuration.WebControlsSection
  isExternal: false
  name: GetRuntimeObject()
  nameWithType: WebControlsSection.GetRuntimeObject()
  fullName: WebControlsSection.GetRuntimeObject()
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.WebControlsSection.Properties
  parent: System.Web.Configuration.WebControlsSection
  isExternal: false
  name: Properties
  nameWithType: WebControlsSection.Properties
  fullName: WebControlsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.WebControlsSection.#ctor*
  parent: System.Web.Configuration.WebControlsSection
  isExternal: false
  name: WebControlsSection
  nameWithType: WebControlsSection.WebControlsSection
  fullName: WebControlsSection.WebControlsSection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/WebControlsSection.xml
- uid: System.Web.Configuration.WebControlsSection.ClientScriptsLocation*
  parent: System.Web.Configuration.WebControlsSection
  isExternal: false
  name: ClientScriptsLocation
  nameWithType: WebControlsSection.ClientScriptsLocation
  fullName: WebControlsSection.ClientScriptsLocation
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/WebControlsSection.xml
- uid: System.Web.Configuration.WebControlsSection.GetRuntimeObject*
  parent: System.Web.Configuration.WebControlsSection
  isExternal: false
  name: GetRuntimeObject
  nameWithType: WebControlsSection.GetRuntimeObject
  fullName: WebControlsSection.GetRuntimeObject
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/WebControlsSection.xml
- uid: System.Web.Configuration.WebControlsSection.Properties*
  parent: System.Web.Configuration.WebControlsSection
  isExternal: false
  name: Properties
  nameWithType: WebControlsSection.Properties
  fullName: WebControlsSection.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/WebControlsSection.xml
