### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.BuildProvider
  commentId: T:System.Web.Configuration.BuildProvider
  id: BuildProvider
  children:
  - System.Web.Configuration.BuildProvider.#ctor(System.String,System.String)
  - System.Web.Configuration.BuildProvider.Equals(System.Object)
  - System.Web.Configuration.BuildProvider.Extension
  - System.Web.Configuration.BuildProvider.GetHashCode
  - System.Web.Configuration.BuildProvider.Properties
  - System.Web.Configuration.BuildProvider.Type
  langs:
  - csharp
  name: BuildProvider
  nameWithType: BuildProvider
  fullName: System.Web.Configuration.BuildProvider
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Provides functionality to parse a particular file type and generate code during compilation of a dynamic resource. This class cannot be inherited.
  syntax:
    content: 'public sealed class BuildProvider : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/BuildProvider.xml
  author: tdykstra
  ms.author: tdykstra
  manager: wpickett
- uid: System.Web.Configuration.BuildProvider.#ctor(System.String,System.String)
  commentId: M:System.Web.Configuration.BuildProvider.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: BuildProvider(String, String)
  nameWithType: BuildProvider.BuildProvider(String, String)
  fullName: System.Web.Configuration.BuildProvider.BuildProvider(String, String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Creates an instance of a <xref href="System.Web.Configuration.BuildProvider"></xref> class, initialized to the provided values.
  syntax:
    content: public BuildProvider (string extension, string type);
    parameters:
    - id: extension
      type: System.String
      description: The file extension of the dynamic resource used during compilation.
    - id: type
      type: System.String
      description: The type that represents the <xref href="System.Web.Configuration.BuildProvider"></xref> instance to use when parsing and compiling the given extension.
  overload: System.Web.Configuration.BuildProvider.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/BuildProvider.xml
  author: tdykstra
  ms.author: tdykstra
  manager: wpickett
- uid: System.Web.Configuration.BuildProvider.Equals(System.Object)
  commentId: M:System.Web.Configuration.BuildProvider.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: BuildProvider.Equals(Object)
  fullName: System.Web.Configuration.BuildProvider.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Determines whether the specified build provider object is equal to the current object.
  remarks: The serializer uses this method to determine whether the same object already exists in the parent collection and whether it needs to be serialized at a lower level if it is not inherited.
  syntax:
    content: public override bool Equals (object provider);
    parameters:
    - id: provider
      type: System.Object
      description: The build provider object to compare with the current object.
    return:
      type: System.Boolean
      description: '`true` if the objects are equal; otherwise, `false`.'
  overload: System.Web.Configuration.BuildProvider.Equals*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/BuildProvider.xml
  author: tdykstra
  ms.author: tdykstra
  manager: wpickett
- uid: System.Web.Configuration.BuildProvider.Extension
  commentId: P:System.Web.Configuration.BuildProvider.Extension
  id: Extension
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: Extension
  nameWithType: BuildProvider.Extension
  fullName: System.Web.Configuration.BuildProvider.Extension
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets or sets the file extension to map to during compilation of a dynamic resource.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("extension", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsKey=true, IsRequired=true)]

      [System.Configuration.StringValidator(MinLength=1)]

      public string Extension { get; set; }
    return:
      type: System.String
      description: A string specifying the file extension to map to during compilation of a dynamic resource.
  overload: System.Web.Configuration.BuildProvider.Extension*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/BuildProvider.xml
  author: tdykstra
  ms.author: tdykstra
  manager: wpickett
- uid: System.Web.Configuration.BuildProvider.GetHashCode
  commentId: M:System.Web.Configuration.BuildProvider.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: BuildProvider.GetHashCode()
  fullName: System.Web.Configuration.BuildProvider.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Generates the hash code for the build provider.
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: An integer representing the hash code for the build provider.
  overload: System.Web.Configuration.BuildProvider.GetHashCode*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/BuildProvider.xml
  author: tdykstra
  ms.author: tdykstra
  manager: wpickett
- uid: System.Web.Configuration.BuildProvider.Properties
  commentId: P:System.Web.Configuration.BuildProvider.Properties
  id: Properties
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: Properties
  nameWithType: BuildProvider.Properties
  fullName: System.Web.Configuration.BuildProvider.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.BuildProvider.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/BuildProvider.xml
- uid: System.Web.Configuration.BuildProvider.Type
  commentId: P:System.Web.Configuration.BuildProvider.Type
  id: Type
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: Type
  nameWithType: BuildProvider.Type
  fullName: System.Web.Configuration.BuildProvider.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets or set the comma-separated class and assembly combination that indicates the <xref href="System.Web.Configuration.BuildProvider"></xref> instance to use.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("type", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsRequired=true)]

      [System.Configuration.StringValidator(MinLength=1)]

      public string Type { get; set; }
    return:
      type: System.String
      description: A comma-separated class and assembly combination that indicates the <xref href="System.Web.Configuration.BuildProvider"></xref> instance to use.
  overload: System.Web.Configuration.BuildProvider.Type*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/BuildProvider.xml
  author: tdykstra
  ms.author: tdykstra
  manager: wpickett
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.BuildProvider.#ctor(System.String,System.String)
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: BuildProvider(String, String)
  nameWithType: BuildProvider.BuildProvider(String, String)
  fullName: System.Web.Configuration.BuildProvider.BuildProvider(String, String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.BuildProvider.Equals(System.Object)
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Equals(Object)
  nameWithType: BuildProvider.Equals(Object)
  fullName: System.Web.Configuration.BuildProvider.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.BuildProvider.Extension
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Extension
  nameWithType: BuildProvider.Extension
  fullName: System.Web.Configuration.BuildProvider.Extension
- uid: System.Web.Configuration.BuildProvider.GetHashCode
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: GetHashCode()
  nameWithType: BuildProvider.GetHashCode()
  fullName: System.Web.Configuration.BuildProvider.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.BuildProvider.Properties
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Properties
  nameWithType: BuildProvider.Properties
  fullName: System.Web.Configuration.BuildProvider.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.BuildProvider.Type
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Type
  nameWithType: BuildProvider.Type
  fullName: System.Web.Configuration.BuildProvider.Type
- uid: System.Web.Configuration.BuildProvider.#ctor*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: BuildProvider
  nameWithType: BuildProvider.BuildProvider
  fullName: System.Web.Configuration.BuildProvider.BuildProvider
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/BuildProvider.xml
- uid: System.Web.Configuration.BuildProvider.Equals*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Equals
  nameWithType: BuildProvider.Equals
  fullName: System.Web.Configuration.BuildProvider.Equals
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/BuildProvider.xml
- uid: System.Web.Configuration.BuildProvider.Extension*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Extension
  nameWithType: BuildProvider.Extension
  fullName: System.Web.Configuration.BuildProvider.Extension
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/BuildProvider.xml
- uid: System.Web.Configuration.BuildProvider.GetHashCode*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: GetHashCode
  nameWithType: BuildProvider.GetHashCode
  fullName: System.Web.Configuration.BuildProvider.GetHashCode
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/BuildProvider.xml
- uid: System.Web.Configuration.BuildProvider.Properties*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Properties
  nameWithType: BuildProvider.Properties
  fullName: System.Web.Configuration.BuildProvider.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/BuildProvider.xml
- uid: System.Web.Configuration.BuildProvider.Type*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Type
  nameWithType: BuildProvider.Type
  fullName: System.Web.Configuration.BuildProvider.Type
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/BuildProvider.xml
