### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SystemWebExtensionsSectionGroup
  commentId: T:System.Web.Configuration.SystemWebExtensionsSectionGroup
  id: SystemWebExtensionsSectionGroup
  children:
  - System.Web.Configuration.SystemWebExtensionsSectionGroup.#ctor
  - System.Web.Configuration.SystemWebExtensionsSectionGroup.Scripting
  langs:
  - csharp
  name: SystemWebExtensionsSectionGroup
  nameWithType: SystemWebExtensionsSectionGroup
  fullName: System.Web.Configuration.SystemWebExtensionsSectionGroup
  type: Class
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: Represents a group of related sections in a configuration file. This class cannot be inherited.
  syntax:
    content: 'public sealed class SystemWebExtensionsSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SystemWebExtensionsSectionGroup.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.SystemWebExtensionsSectionGroup.#ctor
  commentId: M:System.Web.Configuration.SystemWebExtensionsSectionGroup.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.SystemWebExtensionsSectionGroup
  langs:
  - csharp
  name: SystemWebExtensionsSectionGroup()
  nameWithType: SystemWebExtensionsSectionGroup.SystemWebExtensionsSectionGroup()
  fullName: System.Web.Configuration.SystemWebExtensionsSectionGroup.SystemWebExtensionsSectionGroup()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Configuration.SystemWebExtensionsSectionGroup"></xref> class.
  syntax:
    content: public SystemWebExtensionsSectionGroup ();
    parameters: []
  overload: System.Web.Configuration.SystemWebExtensionsSectionGroup.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SystemWebExtensionsSectionGroup.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.SystemWebExtensionsSectionGroup.Scripting
  commentId: P:System.Web.Configuration.SystemWebExtensionsSectionGroup.Scripting
  id: Scripting
  parent: System.Web.Configuration.SystemWebExtensionsSectionGroup
  langs:
  - csharp
  name: Scripting
  nameWithType: SystemWebExtensionsSectionGroup.Scripting
  fullName: System.Web.Configuration.SystemWebExtensionsSectionGroup.Scripting
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: Gets a <xref href="System.Web.Configuration.ScriptingSectionGroup"></xref> object that is derived from the current system configuration.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("scripting")]

      public System.Web.Configuration.ScriptingSectionGroup Scripting { get; }
    return:
      type: System.Web.Configuration.ScriptingSectionGroup
      description: A <xref href="System.Web.Configuration.ScriptingSectionGroup"></xref> object.
  overload: System.Web.Configuration.SystemWebExtensionsSectionGroup.Scripting*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SystemWebExtensionsSectionGroup.xml
  ms.author: riande
  manager: wpickett
references:
- uid: System.Configuration.ConfigurationSectionGroup
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSectionGroup
  nameWithType: ConfigurationSectionGroup
  fullName: System.Configuration.ConfigurationSectionGroup
- uid: System.Web.Configuration.SystemWebExtensionsSectionGroup.#ctor
  parent: System.Web.Configuration.SystemWebExtensionsSectionGroup
  isExternal: false
  name: SystemWebExtensionsSectionGroup()
  nameWithType: SystemWebExtensionsSectionGroup.SystemWebExtensionsSectionGroup()
  fullName: System.Web.Configuration.SystemWebExtensionsSectionGroup.SystemWebExtensionsSectionGroup()
- uid: System.Web.Configuration.SystemWebExtensionsSectionGroup.Scripting
  parent: System.Web.Configuration.SystemWebExtensionsSectionGroup
  isExternal: false
  name: Scripting
  nameWithType: SystemWebExtensionsSectionGroup.Scripting
  fullName: System.Web.Configuration.SystemWebExtensionsSectionGroup.Scripting
- uid: System.Web.Configuration.ScriptingSectionGroup
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingSectionGroup
  nameWithType: ScriptingSectionGroup
  fullName: System.Web.Configuration.ScriptingSectionGroup
- uid: System.Web.Configuration.SystemWebExtensionsSectionGroup.#ctor*
  parent: System.Web.Configuration.SystemWebExtensionsSectionGroup
  isExternal: false
  name: SystemWebExtensionsSectionGroup
  nameWithType: SystemWebExtensionsSectionGroup.SystemWebExtensionsSectionGroup
  fullName: System.Web.Configuration.SystemWebExtensionsSectionGroup.SystemWebExtensionsSectionGroup
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SystemWebExtensionsSectionGroup.xml
- uid: System.Web.Configuration.SystemWebExtensionsSectionGroup.Scripting*
  parent: System.Web.Configuration.SystemWebExtensionsSectionGroup
  isExternal: false
  name: Scripting
  nameWithType: SystemWebExtensionsSectionGroup.Scripting
  fullName: System.Web.Configuration.SystemWebExtensionsSectionGroup.Scripting
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/SystemWebExtensionsSectionGroup.xml
