### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.ModuleElement
  commentId: T:System.Net.Configuration.ModuleElement
  id: ModuleElement
  children:
  - System.Net.Configuration.ModuleElement.#ctor
  - System.Net.Configuration.ModuleElement.Properties
  - System.Net.Configuration.ModuleElement.Type
  langs:
  - csharp
  name: ModuleElement
  nameWithType: ModuleElement
  fullName: System.Net.Configuration.ModuleElement
  type: Class
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Represents the type information for a custom <xref href="System.Net.IWebProxy"></xref> module. This class cannot be inherited.
  remarks: "This class corresponds to the `type` attribute of the [\\&lt;module\\&gt; Element (Network Settings)](~/docs/framework/configure-apps/file-schema/network/module-element-network-settings.md) configuration element.  \n  \n This class is used to specify a Web proxy that handles requests made with the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class ModuleElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ModuleElement.xml
- uid: System.Net.Configuration.ModuleElement.#ctor
  commentId: M:System.Net.Configuration.ModuleElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.ModuleElement
  langs:
  - csharp
  name: ModuleElement()
  nameWithType: ModuleElement.ModuleElement()
  fullName: ModuleElement.ModuleElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Initializes a new instance of the <xref href="System.Net.Configuration.ModuleElement"></xref> class.
  remarks: This constructor adds a <xref:System.Configuration.ConfigurationProperty> object for the <xref:System.Net.Configuration.ModuleElement.Type%2A> property to the <xref:System.Configuration.ConfigurationElement.Properties%2A> collection.
  syntax:
    content: public ModuleElement ();
    parameters: []
  overload: System.Net.Configuration.ModuleElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ModuleElement.xml
- uid: System.Net.Configuration.ModuleElement.Properties
  commentId: P:System.Net.Configuration.ModuleElement.Properties
  id: Properties
  parent: System.Net.Configuration.ModuleElement
  langs:
  - csharp
  name: Properties
  nameWithType: ModuleElement.Properties
  fullName: ModuleElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Net.Configuration.ModuleElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ModuleElement.xml
- uid: System.Net.Configuration.ModuleElement.Type
  commentId: P:System.Net.Configuration.ModuleElement.Type
  id: Type
  parent: System.Net.Configuration.ModuleElement
  langs:
  - csharp
  name: Type
  nameWithType: ModuleElement.Type
  fullName: ModuleElement.Type
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Gets or sets the type and assembly information for the current instance.
  remarks: This property contains the fully qualified type name followed by a comma (,) and the assembly information. The elements of the assembly information are separated with commas, for example, `Corp.Net.CustomWebProxy, CorpLibrary, Version=1.0.5000.0, Culture=neutral, PublicKeyToken="00000000000000000"`.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("type")]

      public string Type { get; set; }
    return:
      type: System.String
      description: A string that identifies a type that implements the <xref href="System.Net.IWebProxy"></xref> interface or `null` if no value has been specified.
  overload: System.Net.Configuration.ModuleElement.Type*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ModuleElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.ModuleElement.#ctor
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: ModuleElement()
  nameWithType: ModuleElement.ModuleElement()
  fullName: ModuleElement.ModuleElement()
- uid: System.Net.Configuration.ModuleElement.Properties
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: Properties
  nameWithType: ModuleElement.Properties
  fullName: ModuleElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.ModuleElement.Type
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: Type
  nameWithType: ModuleElement.Type
  fullName: ModuleElement.Type
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.Configuration.ModuleElement.#ctor*
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: ModuleElement
  nameWithType: ModuleElement.ModuleElement
  fullName: ModuleElement.ModuleElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ModuleElement.xml
- uid: System.Net.Configuration.ModuleElement.Properties*
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: Properties
  nameWithType: ModuleElement.Properties
  fullName: ModuleElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ModuleElement.xml
- uid: System.Net.Configuration.ModuleElement.Type*
  parent: System.Net.Configuration.ModuleElement
  isExternal: false
  name: Type
  nameWithType: ModuleElement.Type
  fullName: ModuleElement.Type
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ModuleElement.xml
