### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsGroupDescriptionAttribute
  commentId: T:System.Configuration.SettingsGroupDescriptionAttribute
  id: SettingsGroupDescriptionAttribute
  children:
  - System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  - System.Configuration.SettingsGroupDescriptionAttribute.Description
  langs:
  - csharp
  name: SettingsGroupDescriptionAttribute
  nameWithType: SettingsGroupDescriptionAttribute
  fullName: System.Configuration.SettingsGroupDescriptionAttribute
  type: Class
  assemblies:
  - System
  namespace: System.Configuration
  summary: Provides a string that describes an application settings property group. This class cannot be inherited.
  remarks: "An application settings class, derived from <xref:System.Configuration.ApplicationSettingsBase>, defines one or more properties that belong to the same application property group. <xref:System.Configuration.SettingsGroupDescriptionAttribute> is an optional attribute that you can use to provide descriptive text for a settings property group. This text is intended to assist both design-time tools and administrative run-time tools in identifying and describing the associated property group.  \n  \n> [!NOTE]\n>  This attribute can only be applied at the wrapper class level."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class SettingsGroupDescriptionAttribute : Attribute
  inheritance:
  - System.Object
  - System.Attribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.AttributeUsageAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsGroupDescriptionAttribute.xml
  author: stevehoag
  ms.author: shoag
  manager: wpickett
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  commentId: M:System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  langs:
  - csharp
  name: SettingsGroupDescriptionAttribute(String)
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.SettingsGroupDescriptionAttribute"></xref> class.
  remarks: Although the theoretical maximum length of the `description` parameter is constrained by the upper bounds of an <xref:System.Int32>, practical limits, determined by usability and quota limitations imposed by the settings provider, will be much smaller.
  syntax:
    content: public SettingsGroupDescriptionAttribute (string description);
    parameters:
    - id: description
      type: System.String
      description: A <xref href="System.String"></xref> containing the descriptive text for the application settings group.
  overload: System.Configuration.SettingsGroupDescriptionAttribute.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsGroupDescriptionAttribute.xml
  author: stevehoag
  ms.author: shoag
  manager: wpickett
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description
  commentId: P:System.Configuration.SettingsGroupDescriptionAttribute.Description
  id: Description
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  langs:
  - csharp
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.Description
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: The descriptive text for the application settings properties group.
  remarks: The <xref:System.Configuration.SettingsGroupDescriptionAttribute.Description%2A> property value is set in the <xref:System.Configuration.SettingsGroupDescriptionAttribute.%23ctor%2A> constructor.
  syntax:
    content: public string Description { get; }
    return:
      type: System.String
      description: A <xref href="System.String"></xref> containing the descriptive text for the application settings group.
  overload: System.Configuration.SettingsGroupDescriptionAttribute.Description*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsGroupDescriptionAttribute.xml
  author: stevehoag
  ms.author: shoag
  manager: wpickett
references:
- uid: System.Attribute
  parent: System
  isExternal: false
  name: Attribute
  nameWithType: Attribute
  fullName: System.Attribute
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: SettingsGroupDescriptionAttribute(String)
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.Description
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor*
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: SettingsGroupDescriptionAttribute
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsGroupDescriptionAttribute.xml
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description*
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.Description
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/SettingsGroupDescriptionAttribute.xml
