### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpModuleAction
  commentId: T:System.Web.Configuration.HttpModuleAction
  id: HttpModuleAction
  children:
  - System.Web.Configuration.HttpModuleAction.#ctor(System.String,System.String)
  - System.Web.Configuration.HttpModuleAction.ElementProperty
  - System.Web.Configuration.HttpModuleAction.Name
  - System.Web.Configuration.HttpModuleAction.Properties
  - System.Web.Configuration.HttpModuleAction.Type
  langs:
  - csharp
  name: HttpModuleAction
  nameWithType: HttpModuleAction
  fullName: System.Web.Configuration.HttpModuleAction
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Configures the <xref href="System.Web.Configuration.HttpModulesSection"></xref> modules. This class cannot be inherited.
  remarks: "The <xref:System.Web.Configuration.HttpModuleAction> class provides a way to programmatically access and modify the `add` element of the `httpModules` section of a configuration file.  \n  \n The <xref:System.Web.Configuration.HttpModuleAction> type is part of a group that includes the <xref:System.Web.Configuration.HttpModuleActionCollection>, collection, and the <xref:System.Web.Configuration.HttpModulesSection> types."
  example:
  - "This example demonstrates how to specify values declaratively for several attributes of the `add` element of the `httpModules` section, which can also be accessed as members of the <xref:System.Web.Configuration.HttpModuleAction> class.  \n  \n The following configuration file example shows how to specify values declaratively for the `httpModules` section.  \n  \n Refer to the [NIB: How to: Create and Configure an HTTP Module](http://msdn.microsoft.com/en-us/4174fd13-a9c4-4ff6-baa5-3f7d7fc73ef3) to see how to build and configure an HTTP module.  \n  \n```  \n<httpModules>  \n    <add name=\"TimerModule\"   \n      type=\"Samples.Aspnet.Configuration.RequestTimeInterval, RequestTimeInterval Version=1.0.1557.23158, Culture=neutral,  \n      PublicKeyToken=7bfb33146a87b52e, processorArchitecture=MSIL\"/>  \n</httpModules>  \n```  \n  \n The following code example shows how to use the <xref:System.Web.Configuration.HttpModuleAction> class.  \n  \n [!code-csharp[System.Web.Configuration.HttpModuleAction#1](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.HttpModuleAction/CS/httpmoduleaction.cs#1)]\n [!code-vb[System.Web.Configuration.HttpModuleAction#1](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.HttpModuleAction/VB/httpmoduleaction.vb#1)]"
  syntax:
    content: 'public sealed class HttpModuleAction : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModuleAction.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.HttpModuleAction.#ctor(System.String,System.String)
  commentId: M:System.Web.Configuration.HttpModuleAction.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.HttpModuleAction
  langs:
  - csharp
  name: HttpModuleAction(String, String)
  nameWithType: HttpModuleAction.HttpModuleAction(String, String)
  fullName: System.Web.Configuration.HttpModuleAction.HttpModuleAction(String, String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Configuration.HttpModuleAction"></xref> class using the passed parameters.
  remarks: The module name is an alias you can use to associate event handlers with the module events. ASP.NET searches for the assembly DLL first in the application's private \bin directory and then in the Global Assembly Cache (GAC).
  example:
  - "The following code example shows how to create an <xref:System.Web.Configuration.HttpModuleAction> object.  \n  \n [!code-csharp[System.Web.Configuration.HttpModuleAction#3](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.HttpModuleAction/CS/httpmoduleaction.cs#3)]\n [!code-vb[System.Web.Configuration.HttpModuleAction#3](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.HttpModuleAction/VB/httpmoduleaction.vb#3)]"
  syntax:
    content: public HttpModuleAction (string name, string type);
    parameters:
    - id: name
      type: System.String
      description: The module name.
    - id: type
      type: System.String
      description: A comma-separated list containing the module type name and the assembly information.
  overload: System.Web.Configuration.HttpModuleAction.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModuleAction.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.HttpModuleAction.ElementProperty
  commentId: P:System.Web.Configuration.HttpModuleAction.ElementProperty
  id: ElementProperty
  parent: System.Web.Configuration.HttpModuleAction
  langs:
  - csharp
  name: ElementProperty
  nameWithType: HttpModuleAction.ElementProperty
  fullName: System.Web.Configuration.HttpModuleAction.ElementProperty
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationElementProperty ElementProperty { get; }
    return:
      type: System.Configuration.ConfigurationElementProperty
      description: To be added.
  overload: System.Web.Configuration.HttpModuleAction.ElementProperty*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModuleAction.xml
- uid: System.Web.Configuration.HttpModuleAction.Name
  commentId: P:System.Web.Configuration.HttpModuleAction.Name
  id: Name
  parent: System.Web.Configuration.HttpModuleAction
  langs:
  - csharp
  name: Name
  nameWithType: HttpModuleAction.Name
  fullName: System.Web.Configuration.HttpModuleAction.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets or sets the module name.
  remarks: The module name is used to identify this <xref:System.Web.Configuration.HttpModuleAction> object.
  example:
  - "The following code example shows how to use the <xref:System.Web.Configuration.HttpModuleAction.Name%2A> property.  \n  \n [!code-csharp[System.Web.Configuration.HttpModuleAction#4](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.HttpModuleAction/CS/httpmoduleaction.cs#4)]\n [!code-vb[System.Web.Configuration.HttpModuleAction#4](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.HttpModuleAction/VB/httpmoduleaction.vb#4)]"
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("name", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsKey=true, IsRequired=true)]

      [System.Configuration.StringValidator(MinLength=1)]

      public string Name { get; set; }
    return:
      type: System.String
      description: The module name.
  overload: System.Web.Configuration.HttpModuleAction.Name*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModuleAction.xml
  ms.author: riande
  manager: wpickett
- uid: System.Web.Configuration.HttpModuleAction.Properties
  commentId: P:System.Web.Configuration.HttpModuleAction.Properties
  id: Properties
  parent: System.Web.Configuration.HttpModuleAction
  langs:
  - csharp
  name: Properties
  nameWithType: HttpModuleAction.Properties
  fullName: System.Web.Configuration.HttpModuleAction.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.HttpModuleAction.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModuleAction.xml
- uid: System.Web.Configuration.HttpModuleAction.Type
  commentId: P:System.Web.Configuration.HttpModuleAction.Type
  id: Type
  parent: System.Web.Configuration.HttpModuleAction
  langs:
  - csharp
  name: Type
  nameWithType: HttpModuleAction.Type
  fullName: System.Web.Configuration.HttpModuleAction.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets or sets the module type.
  remarks: To find the assembly defined by the <xref:System.Web.Configuration.HttpModuleAction.Type%2A>, ASP.NET searches for the assembly DLL first in the application's private \bin directory, and then in the system assembly cache.
  example:
  - "The following code example shows how to access the <xref:System.Web.Configuration.HttpModuleAction.Type%2A> property.  \n  \n [!code-csharp[System.Web.Configuration.HttpModuleAction#5](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.HttpModuleAction/CS/httpmoduleaction.cs#5)]\n [!code-vb[System.Web.Configuration.HttpModuleAction#5](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.HttpModuleAction/VB/httpmoduleaction.vb#5)]"
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("type", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsRequired=true)]

      public string Type { get; set; }
    return:
      type: System.String
      description: A comma-separated list containing the module type name and the assembly information.
  overload: System.Web.Configuration.HttpModuleAction.Type*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModuleAction.xml
  ms.author: riande
  manager: wpickett
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.HttpModuleAction.#ctor(System.String,System.String)
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: HttpModuleAction(String, String)
  nameWithType: HttpModuleAction.HttpModuleAction(String, String)
  fullName: System.Web.Configuration.HttpModuleAction.HttpModuleAction(String, String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.HttpModuleAction.ElementProperty
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: ElementProperty
  nameWithType: HttpModuleAction.ElementProperty
  fullName: System.Web.Configuration.HttpModuleAction.ElementProperty
- uid: System.Configuration.ConfigurationElementProperty
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElementProperty
  nameWithType: ConfigurationElementProperty
  fullName: System.Configuration.ConfigurationElementProperty
- uid: System.Web.Configuration.HttpModuleAction.Name
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: Name
  nameWithType: HttpModuleAction.Name
  fullName: System.Web.Configuration.HttpModuleAction.Name
- uid: System.Web.Configuration.HttpModuleAction.Properties
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: Properties
  nameWithType: HttpModuleAction.Properties
  fullName: System.Web.Configuration.HttpModuleAction.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.HttpModuleAction.Type
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: Type
  nameWithType: HttpModuleAction.Type
  fullName: System.Web.Configuration.HttpModuleAction.Type
- uid: System.Web.Configuration.HttpModuleAction.#ctor*
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: HttpModuleAction
  nameWithType: HttpModuleAction.HttpModuleAction
  fullName: System.Web.Configuration.HttpModuleAction.HttpModuleAction
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModuleAction.xml
- uid: System.Web.Configuration.HttpModuleAction.ElementProperty*
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: ElementProperty
  nameWithType: HttpModuleAction.ElementProperty
  fullName: System.Web.Configuration.HttpModuleAction.ElementProperty
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModuleAction.xml
- uid: System.Web.Configuration.HttpModuleAction.Name*
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: Name
  nameWithType: HttpModuleAction.Name
  fullName: System.Web.Configuration.HttpModuleAction.Name
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModuleAction.xml
- uid: System.Web.Configuration.HttpModuleAction.Properties*
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: Properties
  nameWithType: HttpModuleAction.Properties
  fullName: System.Web.Configuration.HttpModuleAction.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModuleAction.xml
- uid: System.Web.Configuration.HttpModuleAction.Type*
  parent: System.Web.Configuration.HttpModuleAction
  isExternal: false
  name: Type
  nameWithType: HttpModuleAction.Type
  fullName: System.Web.Configuration.HttpModuleAction.Type
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/HttpModuleAction.xml
