### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  commentId: T:System.ServiceModel.Configuration.BasicHttpsSecurityElement
  id: BasicHttpsSecurityElement
  children:
  - System.ServiceModel.Configuration.BasicHttpsSecurityElement.#ctor
  - System.ServiceModel.Configuration.BasicHttpsSecurityElement.Message
  - System.ServiceModel.Configuration.BasicHttpsSecurityElement.Mode
  - System.ServiceModel.Configuration.BasicHttpsSecurityElement.Properties
  - System.ServiceModel.Configuration.BasicHttpsSecurityElement.Transport
  langs:
  - csharp
  name: BasicHttpsSecurityElement
  nameWithType: BasicHttpsSecurityElement
  fullName: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Specifies settings for the basic https security element.
  syntax:
    content: 'public sealed class BasicHttpsSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpsSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.BasicHttpsSecurityElement.#ctor
  commentId: M:System.ServiceModel.Configuration.BasicHttpsSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  langs:
  - csharp
  name: BasicHttpsSecurityElement()
  nameWithType: BasicHttpsSecurityElement.BasicHttpsSecurityElement()
  fullName: System.ServiceModel.Configuration.BasicHttpsSecurityElement.BasicHttpsSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.BasicHttpsSecurityElement"></xref> class.
  syntax:
    content: public BasicHttpsSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.BasicHttpsSecurityElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpsSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Message
  commentId: P:System.ServiceModel.Configuration.BasicHttpsSecurityElement.Message
  id: Message
  parent: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  langs:
  - csharp
  name: Message
  nameWithType: BasicHttpsSecurityElement.Message
  fullName: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets the basic HTTPS security element message
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("message")]

      public System.ServiceModel.Configuration.BasicHttpMessageSecurityElement Message { get; }
    return:
      type: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
      description: The basic HTTPS security element.
  overload: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Message*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpsSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Mode
  commentId: P:System.ServiceModel.Configuration.BasicHttpsSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: BasicHttpsSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the basic HTTPS security mode.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("mode", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.ServiceModel.BasicHttpsSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.BasicHttpsSecurityMode
      description: The basic HTTPS security mode.
  overload: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Mode*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpsSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Properties
  commentId: P:System.ServiceModel.Configuration.BasicHttpsSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: BasicHttpsSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpsSecurityElement.xml
- uid: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Transport
  commentId: P:System.ServiceModel.Configuration.BasicHttpsSecurityElement.Transport
  id: Transport
  parent: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  langs:
  - csharp
  name: Transport
  nameWithType: BasicHttpsSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets the transport used for the HTTPS basic security element.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("transport")]

      public System.ServiceModel.Configuration.HttpTransportSecurityElement Transport { get; }
    return:
      type: System.ServiceModel.Configuration.HttpTransportSecurityElement
      description: The transport used.
  overload: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Transport*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpsSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.BasicHttpsSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  isExternal: false
  name: BasicHttpsSecurityElement()
  nameWithType: BasicHttpsSecurityElement.BasicHttpsSecurityElement()
  fullName: System.ServiceModel.Configuration.BasicHttpsSecurityElement.BasicHttpsSecurityElement()
- uid: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Message
  parent: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  isExternal: false
  name: Message
  nameWithType: BasicHttpsSecurityElement.Message
  fullName: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Message
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: BasicHttpMessageSecurityElement
  nameWithType: BasicHttpMessageSecurityElement
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
- uid: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Mode
  parent: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  isExternal: false
  name: Mode
  nameWithType: BasicHttpsSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Mode
- uid: System.ServiceModel.BasicHttpsSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: BasicHttpsSecurityMode
  nameWithType: BasicHttpsSecurityMode
  fullName: System.ServiceModel.BasicHttpsSecurityMode
- uid: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Properties
  parent: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  isExternal: false
  name: Properties
  nameWithType: BasicHttpsSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Transport
  parent: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  isExternal: false
  name: Transport
  nameWithType: BasicHttpsSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Transport
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: HttpTransportSecurityElement
  nameWithType: HttpTransportSecurityElement
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement
- uid: System.ServiceModel.Configuration.BasicHttpsSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  isExternal: false
  name: BasicHttpsSecurityElement
  nameWithType: BasicHttpsSecurityElement.BasicHttpsSecurityElement
  fullName: System.ServiceModel.Configuration.BasicHttpsSecurityElement.BasicHttpsSecurityElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpsSecurityElement.xml
- uid: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Message*
  parent: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  isExternal: false
  name: Message
  nameWithType: BasicHttpsSecurityElement.Message
  fullName: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Message
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpsSecurityElement.xml
- uid: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  isExternal: false
  name: Mode
  nameWithType: BasicHttpsSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Mode
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpsSecurityElement.xml
- uid: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  isExternal: false
  name: Properties
  nameWithType: BasicHttpsSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpsSecurityElement.xml
- uid: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Transport*
  parent: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  isExternal: false
  name: Transport
  nameWithType: BasicHttpsSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.BasicHttpsSecurityElement.Transport
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/BasicHttpsSecurityElement.xml
