### YamlMime:ManagedReference
items:
- uid: System.Configuration.CallbackValidatorAttribute
  commentId: T:System.Configuration.CallbackValidatorAttribute
  id: CallbackValidatorAttribute
  children:
  - System.Configuration.CallbackValidatorAttribute.#ctor
  - System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  - System.Configuration.CallbackValidatorAttribute.Type
  - System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: CallbackValidatorAttribute
  nameWithType: CallbackValidatorAttribute
  fullName: System.Configuration.CallbackValidatorAttribute
  type: Class
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Specifies a <xref href="System.Configuration.CallbackValidator"></xref> object to use for code validation. This class cannot be inherited.
  remarks: The <xref:System.Configuration.CallbackValidatorAttribute> attribute class provides an association between a <xref:System.Configuration.CallbackValidator> object and the code to validate. The <xref:System.Configuration.CallbackValidatorAttribute> class is derived from the <xref:System.Configuration.ConfigurationValidatorAttribute> class.
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class CallbackValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Object
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.AttributeUsageAttribute
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/CallbackValidatorAttribute.xml
- uid: System.Configuration.CallbackValidatorAttribute.#ctor
  commentId: M:System.Configuration.CallbackValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: CallbackValidatorAttribute()
  nameWithType: CallbackValidatorAttribute.CallbackValidatorAttribute()
  fullName: CallbackValidatorAttribute.CallbackValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.CallbackValidatorAttribute"></xref> class.
  syntax:
    content: public CallbackValidatorAttribute ();
    parameters: []
  overload: System.Configuration.CallbackValidatorAttribute.#ctor*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/CallbackValidatorAttribute.xml
- uid: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  commentId: P:System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  id: CallbackMethodName
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: CallbackMethodName
  nameWithType: CallbackValidatorAttribute.CallbackMethodName
  fullName: CallbackValidatorAttribute.CallbackMethodName
  type: Property
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Gets or sets the name of the callback method.
  syntax:
    content: public string CallbackMethodName { get; set; }
    return:
      type: System.String
      description: The name of the method to call.
  overload: System.Configuration.CallbackValidatorAttribute.CallbackMethodName*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/CallbackValidatorAttribute.xml
- uid: System.Configuration.CallbackValidatorAttribute.Type
  commentId: P:System.Configuration.CallbackValidatorAttribute.Type
  id: Type
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: Type
  nameWithType: CallbackValidatorAttribute.Type
  fullName: CallbackValidatorAttribute.Type
  type: Property
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Gets or sets the type of the validator.
  syntax:
    content: public Type Type { get; set; }
    return:
      type: System.Type
      description: The <xref href="System.Type"></xref> of the current validator attribute instance.
  overload: System.Configuration.CallbackValidatorAttribute.Type*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/CallbackValidatorAttribute.xml
- uid: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  commentId: P:System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: CallbackValidatorAttribute.ValidatorInstance
  fullName: CallbackValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Gets the validator instance.
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: The current <xref href="System.Configuration.ConfigurationValidatorBase"></xref> instance.
  overload: System.Configuration.CallbackValidatorAttribute.ValidatorInstance*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: The value of the <xref href="System.Configuration.CallbackValidatorAttribute.Type"></xref> property is `null`.
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: The <xref href="System.Configuration.CallbackValidatorAttribute.CallbackMethodName"></xref> property is not set to a public static void method with one object parameter.
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/CallbackValidatorAttribute.xml
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorAttribute
  nameWithType: ConfigurationValidatorAttribute
  fullName: System.Configuration.ConfigurationValidatorAttribute
- uid: System.ArgumentNullException
  parent: System
  isExternal: false
  name: ArgumentNullException
  nameWithType: ArgumentNullException
  fullName: System.ArgumentNullException
- uid: System.ArgumentException
  parent: System
  isExternal: false
  name: ArgumentException
  nameWithType: ArgumentException
  fullName: System.ArgumentException
- uid: System.Configuration.CallbackValidatorAttribute.#ctor
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackValidatorAttribute()
  nameWithType: CallbackValidatorAttribute.CallbackValidatorAttribute()
  fullName: CallbackValidatorAttribute.CallbackValidatorAttribute()
- uid: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackMethodName
  nameWithType: CallbackValidatorAttribute.CallbackMethodName
  fullName: CallbackValidatorAttribute.CallbackMethodName
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.CallbackValidatorAttribute.Type
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: Type
  nameWithType: CallbackValidatorAttribute.Type
  fullName: CallbackValidatorAttribute.Type
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: CallbackValidatorAttribute.ValidatorInstance
  fullName: CallbackValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.CallbackValidatorAttribute.#ctor*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackValidatorAttribute
  nameWithType: CallbackValidatorAttribute.CallbackValidatorAttribute
  fullName: CallbackValidatorAttribute.CallbackValidatorAttribute
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/CallbackValidatorAttribute.xml
- uid: System.Configuration.CallbackValidatorAttribute.CallbackMethodName*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackMethodName
  nameWithType: CallbackValidatorAttribute.CallbackMethodName
  fullName: CallbackValidatorAttribute.CallbackMethodName
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/CallbackValidatorAttribute.xml
- uid: System.Configuration.CallbackValidatorAttribute.Type*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: Type
  nameWithType: CallbackValidatorAttribute.Type
  fullName: CallbackValidatorAttribute.Type
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/CallbackValidatorAttribute.xml
- uid: System.Configuration.CallbackValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: CallbackValidatorAttribute.ValidatorInstance
  fullName: CallbackValidatorAttribute.ValidatorInstance
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/CallbackValidatorAttribute.xml
