### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WindowsServiceElement
  commentId: T:System.ServiceModel.Configuration.WindowsServiceElement
  id: WindowsServiceElement
  children:
  - System.ServiceModel.Configuration.WindowsServiceElement.#ctor
  - System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons
  - System.ServiceModel.Configuration.WindowsServiceElement.Copy(System.ServiceModel.Configuration.WindowsServiceElement)
  - System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups
  - System.ServiceModel.Configuration.WindowsServiceElement.Properties
  langs:
  - csharp
  name: WindowsServiceElement
  nameWithType: WindowsServiceElement
  fullName: System.ServiceModel.Configuration.WindowsServiceElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a configuration element that specifies the settings of a Windows service credential. This class cannot be inherited.
  remarks: ''
  example:
  - <xref:System.ServiceModel.Security.WindowsServiceCredential>
  syntax:
    content: 'public sealed class WindowsServiceElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsServiceElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.WindowsServiceElement.#ctor
  commentId: M:System.ServiceModel.Configuration.WindowsServiceElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  langs:
  - csharp
  name: WindowsServiceElement()
  nameWithType: WindowsServiceElement.WindowsServiceElement()
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.WindowsServiceElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.WindowsServiceElement"></xref> class.
  syntax:
    content: public WindowsServiceElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WindowsServiceElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsServiceElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons
  commentId: P:System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons
  id: AllowAnonymousLogons
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  langs:
  - csharp
  name: AllowAnonymousLogons
  nameWithType: WindowsServiceElement.AllowAnonymousLogons
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets a Boolean value that specifies whether anonymous users can logon.
  remarks: When using Windows service credentials on a binding, the system does not allow anonymous access by default. This means that only domain or workgroup authenticated users have access to the system. You can use this property to allow anonymous, unauthenticated users to access the service. You should exercise caution when using this setting.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("allowAnonymousLogons", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public bool AllowAnonymousLogons { get; set; }
    return:
      type: System.Boolean
      description: '`true` if anonymous users can logon; otherwise, `false`. The default is `false`.'
  overload: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsServiceElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Copy(System.ServiceModel.Configuration.WindowsServiceElement)
  commentId: M:System.ServiceModel.Configuration.WindowsServiceElement.Copy(System.ServiceModel.Configuration.WindowsServiceElement)
  id: Copy(System.ServiceModel.Configuration.WindowsServiceElement)
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  langs:
  - csharp
  name: Copy(WindowsServiceElement)
  nameWithType: WindowsServiceElement.Copy(WindowsServiceElement)
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.Copy(WindowsServiceElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Copies the content of the specified configuration element to this configuration element.
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.WindowsServiceElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.WindowsServiceElement
      description: The configuration element to be copied.
  overload: System.ServiceModel.Configuration.WindowsServiceElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: <code>from</code> is `null`.
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: The configuration file is read-only.
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsServiceElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups
  commentId: P:System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups
  id: IncludeWindowsGroups
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  langs:
  - csharp
  name: IncludeWindowsGroups
  nameWithType: WindowsServiceElement.IncludeWindowsGroups
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets a value that indicates whether Windows groups are included in the security context.
  remarks: Setting this property to `true` has a performance impact as it results in a full group expansion. Set this property to `false` if you do not need to establish the list of groups a user belongs to.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("includeWindowsGroups", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public bool IncludeWindowsGroups { get; set; }
    return:
      type: System.Boolean
      description: '`true` if Windows groups are included in the security context; otherwise, `false`. The default is `false`.'
  overload: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsServiceElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Properties
  commentId: P:System.ServiceModel.Configuration.WindowsServiceElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  langs:
  - csharp
  name: Properties
  nameWithType: WindowsServiceElement.Properties
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.WindowsServiceElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsServiceElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  parent: System
  isExternal: false
  name: ArgumentNullException
  nameWithType: ArgumentNullException
  fullName: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.WindowsServiceElement.#ctor
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: WindowsServiceElement()
  nameWithType: WindowsServiceElement.WindowsServiceElement()
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.WindowsServiceElement()
- uid: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: AllowAnonymousLogons
  nameWithType: WindowsServiceElement.AllowAnonymousLogons
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Copy(System.ServiceModel.Configuration.WindowsServiceElement)
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: Copy(WindowsServiceElement)
  nameWithType: WindowsServiceElement.Copy(WindowsServiceElement)
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.Copy(WindowsServiceElement)
- uid: System.ServiceModel.Configuration.WindowsServiceElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: WindowsServiceElement
  nameWithType: WindowsServiceElement
  fullName: System.ServiceModel.Configuration.WindowsServiceElement
- uid: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: IncludeWindowsGroups
  nameWithType: WindowsServiceElement.IncludeWindowsGroups
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Properties
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: Properties
  nameWithType: WindowsServiceElement.Properties
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WindowsServiceElement.#ctor*
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: WindowsServiceElement
  nameWithType: WindowsServiceElement.WindowsServiceElement
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.WindowsServiceElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsServiceElement.xml
- uid: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons*
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: AllowAnonymousLogons
  nameWithType: WindowsServiceElement.AllowAnonymousLogons
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsServiceElement.xml
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Copy*
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: Copy
  nameWithType: WindowsServiceElement.Copy
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.Copy
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsServiceElement.xml
- uid: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups*
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: IncludeWindowsGroups
  nameWithType: WindowsServiceElement.IncludeWindowsGroups
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsServiceElement.xml
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Properties*
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: Properties
  nameWithType: WindowsServiceElement.Properties
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsServiceElement.xml
