### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.ComponentInstaller
  commentId: T:System.Configuration.Install.ComponentInstaller
  id: ComponentInstaller
  children:
  - System.Configuration.Install.ComponentInstaller.#ctor
  - System.Configuration.Install.ComponentInstaller.CopyFromComponent(System.ComponentModel.IComponent)
  - System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller(System.Configuration.Install.ComponentInstaller)
  langs:
  - csharp
  name: ComponentInstaller
  nameWithType: ComponentInstaller
  fullName: System.Configuration.Install.ComponentInstaller
  type: Class
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: Specifies an installer that copies properties from a component to use at install time.
  syntax:
    content: 'public abstract class ComponentInstaller : System.Configuration.Install.Installer'
  inheritance:
  - System.Object
  - System.MarshalByRefObject
  - System.ComponentModel.Component
  - System.Configuration.Install.Installer
  derivedClasses:
  - System.Diagnostics.EventLogInstaller
  - System.Diagnostics.PerformanceCounterInstaller
  - System.Messaging.MessageQueueInstaller
  - System.ServiceProcess.ServiceInstaller
  - System.ServiceProcess.ServiceProcessInstaller
  implements: []
  inheritedMembers:
  - System.ComponentModel.Component.CanRaiseEvents
  - System.ComponentModel.Component.Container
  - System.ComponentModel.Component.DesignMode
  - System.ComponentModel.Component.Dispose
  - System.ComponentModel.Component.Dispose(System.Boolean)
  - System.ComponentModel.Component.Disposed
  - System.ComponentModel.Component.Events
  - System.ComponentModel.Component.GetService(System.Type)
  - System.ComponentModel.Component.Site
  - System.ComponentModel.Component.ToString
  - System.Configuration.Install.Installer.AfterInstall
  - System.Configuration.Install.Installer.AfterRollback
  - System.Configuration.Install.Installer.AfterUninstall
  - System.Configuration.Install.Installer.BeforeInstall
  - System.Configuration.Install.Installer.BeforeRollback
  - System.Configuration.Install.Installer.BeforeUninstall
  - System.Configuration.Install.Installer.Commit(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.Committed
  - System.Configuration.Install.Installer.Committing
  - System.Configuration.Install.Installer.Context
  - System.Configuration.Install.Installer.HelpText
  - System.Configuration.Install.Installer.Install(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.Installers
  - System.Configuration.Install.Installer.OnAfterInstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnAfterRollback(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnAfterUninstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeInstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeRollback(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeUninstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnCommitted(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnCommitting(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.Parent
  - System.Configuration.Install.Installer.Rollback(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.Uninstall(System.Collections.IDictionary)
  - System.MarshalByRefObject.CreateObjRef(System.Type)
  - System.MarshalByRefObject.GetLifetimeService
  - System.MarshalByRefObject.InitializeLifetimeService
  - System.MarshalByRefObject.MemberwiseClone(System.Boolean)
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Install/ComponentInstaller.xml
  author: mairaw
  ms.author: mairaw
  manager: wpickett
- uid: System.Configuration.Install.ComponentInstaller.#ctor
  commentId: M:System.Configuration.Install.ComponentInstaller.#ctor
  id: '#ctor'
  parent: System.Configuration.Install.ComponentInstaller
  langs:
  - csharp
  name: ComponentInstaller()
  nameWithType: ComponentInstaller.ComponentInstaller()
  fullName: System.Configuration.Install.ComponentInstaller.ComponentInstaller()
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: Initializes a new instance of the <xref href="System.Configuration.Install.ComponentInstaller"></xref> class.
  syntax:
    content: protected ComponentInstaller ();
    parameters: []
  overload: System.Configuration.Install.ComponentInstaller.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Install/ComponentInstaller.xml
  author: mairaw
  ms.author: mairaw
  manager: wpickett
- uid: System.Configuration.Install.ComponentInstaller.CopyFromComponent(System.ComponentModel.IComponent)
  commentId: M:System.Configuration.Install.ComponentInstaller.CopyFromComponent(System.ComponentModel.IComponent)
  id: CopyFromComponent(System.ComponentModel.IComponent)
  parent: System.Configuration.Install.ComponentInstaller
  langs:
  - csharp
  name: CopyFromComponent(IComponent)
  nameWithType: ComponentInstaller.CopyFromComponent(IComponent)
  fullName: System.Configuration.Install.ComponentInstaller.CopyFromComponent(IComponent)
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: When overridden in a derived class, copies all the properties that are required at install time from the specified component.
  remarks: The installer should take all the information it can from the live component, and store it for use at install time.
  example:
  - "The following example defines a class `MyInstallClass`, which creates the event log and copies the properties of the event log component to the <xref:System.Diagnostics.EventLogInstaller>. It also checks whether the <xref:System.ServiceProcess.ServiceInstaller> can perform the same kind of installation as the <xref:System.Diagnostics.EventLogInstaller>.  \n  \n [!code-cpp[ComponentInstaller_CopyFromComponent#1](~/samples/snippets/cpp/VS_Snippets_CLR/ComponentInstaller_CopyFromComponent/CPP/componentinstaller_copyfromcomponent.cpp#1)]\n [!code-csharp[ComponentInstaller_CopyFromComponent#1](~/samples/snippets/csharp/VS_Snippets_CLR/ComponentInstaller_CopyFromComponent/CS/componentinstaller_copyfromcomponent.cs#1)]\n [!code-vb[ComponentInstaller_CopyFromComponent#1](~/samples/snippets/visualbasic/VS_Snippets_CLR/ComponentInstaller_CopyFromComponent/VB/componentinstaller_copyfromcomponent.vb#1)]"
  syntax:
    content: public abstract void CopyFromComponent (System.ComponentModel.IComponent component);
    parameters:
    - id: component
      type: System.ComponentModel.IComponent
      description: The component to copy from.
  overload: System.Configuration.Install.ComponentInstaller.CopyFromComponent*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Install/ComponentInstaller.xml
  author: mairaw
  ms.author: mairaw
  manager: wpickett
- uid: System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller(System.Configuration.Install.ComponentInstaller)
  commentId: M:System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller(System.Configuration.Install.ComponentInstaller)
  id: IsEquivalentInstaller(System.Configuration.Install.ComponentInstaller)
  parent: System.Configuration.Install.ComponentInstaller
  langs:
  - csharp
  name: IsEquivalentInstaller(ComponentInstaller)
  nameWithType: ComponentInstaller.IsEquivalentInstaller(ComponentInstaller)
  fullName: System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller(ComponentInstaller)
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: Determines if the specified installer installs the same object as this installer.
  remarks: Typically, <xref:System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller%2A> returns `true` only if this installer and the installer specified by the `otherInstaller` parameter install the same object. In such a case, calling the <xref:System.Configuration.Install.Installer.Install%2A> or <xref:System.Configuration.Install.Installer.Uninstall%2A> method on either installer results in the same system state.
  example:
  - "The following example defines a class `MyInstallClass`, which creates the event log and copies the properties of the event log component to the <xref:System.Diagnostics.EventLogInstaller> object. It also checks whether <xref:System.ServiceProcess.ServiceInstaller> object can handle the same kind of installation as <xref:System.Diagnostics.EventLogInstaller>.  \n  \n [!code-cpp[ComponentInstaller_CopyFromComponent#2](~/samples/snippets/cpp/VS_Snippets_CLR/ComponentInstaller_CopyFromComponent/CPP/componentinstaller_copyfromcomponent.cpp#2)]\n [!code-csharp[ComponentInstaller_CopyFromComponent#2](~/samples/snippets/csharp/VS_Snippets_CLR/ComponentInstaller_CopyFromComponent/CS/componentinstaller_copyfromcomponent.cs#2)]\n [!code-vb[ComponentInstaller_CopyFromComponent#2](~/samples/snippets/visualbasic/VS_Snippets_CLR/ComponentInstaller_CopyFromComponent/VB/componentinstaller_copyfromcomponent.vb#2)]"
  syntax:
    content: public virtual bool IsEquivalentInstaller (System.Configuration.Install.ComponentInstaller otherInstaller);
    parameters:
    - id: otherInstaller
      type: System.Configuration.Install.ComponentInstaller
      description: The installer to compare.
    return:
      type: System.Boolean
      description: '`true` if this installer and the installer specified by the <code>otherInstaller</code> parameter install the same object; otherwise, `false`.'
  overload: System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Install/ComponentInstaller.xml
  author: mairaw
  ms.author: mairaw
  manager: wpickett
references:
- uid: System.Configuration.Install.Installer
  parent: System.Configuration.Install
  isExternal: false
  name: Installer
  nameWithType: Installer
  fullName: System.Configuration.Install.Installer
- uid: System.Configuration.Install.ComponentInstaller.#ctor
  parent: System.Configuration.Install.ComponentInstaller
  isExternal: false
  name: ComponentInstaller()
  nameWithType: ComponentInstaller.ComponentInstaller()
  fullName: System.Configuration.Install.ComponentInstaller.ComponentInstaller()
- uid: System.Configuration.Install.ComponentInstaller.CopyFromComponent(System.ComponentModel.IComponent)
  parent: System.Configuration.Install.ComponentInstaller
  isExternal: false
  name: CopyFromComponent(IComponent)
  nameWithType: ComponentInstaller.CopyFromComponent(IComponent)
  fullName: System.Configuration.Install.ComponentInstaller.CopyFromComponent(IComponent)
- uid: System.ComponentModel.IComponent
  parent: System.ComponentModel
  isExternal: false
  name: IComponent
  nameWithType: IComponent
  fullName: System.ComponentModel.IComponent
- uid: System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller(System.Configuration.Install.ComponentInstaller)
  parent: System.Configuration.Install.ComponentInstaller
  isExternal: false
  name: IsEquivalentInstaller(ComponentInstaller)
  nameWithType: ComponentInstaller.IsEquivalentInstaller(ComponentInstaller)
  fullName: System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller(ComponentInstaller)
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Install.ComponentInstaller
  parent: System.Configuration.Install
  isExternal: false
  name: ComponentInstaller
  nameWithType: ComponentInstaller
  fullName: System.Configuration.Install.ComponentInstaller
- uid: System.Configuration.Install.ComponentInstaller.#ctor*
  parent: System.Configuration.Install.ComponentInstaller
  isExternal: false
  name: ComponentInstaller
  nameWithType: ComponentInstaller.ComponentInstaller
  fullName: System.Configuration.Install.ComponentInstaller.ComponentInstaller
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Install/ComponentInstaller.xml
- uid: System.Configuration.Install.ComponentInstaller.CopyFromComponent*
  parent: System.Configuration.Install.ComponentInstaller
  isExternal: false
  name: CopyFromComponent
  nameWithType: ComponentInstaller.CopyFromComponent
  fullName: System.Configuration.Install.ComponentInstaller.CopyFromComponent
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Install/ComponentInstaller.xml
- uid: System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller*
  parent: System.Configuration.Install.ComponentInstaller
  isExternal: false
  name: IsEquivalentInstaller
  nameWithType: ComponentInstaller.IsEquivalentInstaller
  fullName: System.Configuration.Install.ComponentInstaller.IsEquivalentInstaller
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Install/ComponentInstaller.xml
