### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MexHttpBindingCollectionElement
  commentId: T:System.ServiceModel.Configuration.MexHttpBindingCollectionElement
  id: MexHttpBindingCollectionElement
  children:
  - System.ServiceModel.Configuration.MexHttpBindingCollectionElement.#ctor
  - System.ServiceModel.Configuration.MexHttpBindingCollectionElement.GetDefault
  langs:
  - csharp
  name: MexHttpBindingCollectionElement
  nameWithType: MexHttpBindingCollectionElement
  fullName: System.ServiceModel.Configuration.MexHttpBindingCollectionElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a collection of <xref href="System.ServiceModel.Configuration.MexHttpBindingElement"></xref> instances.
  syntax:
    content: 'public class MexHttpBindingCollectionElement : System.ServiceModel.Configuration.MexBindingBindingCollectionElement<System.ServiceModel.WSHttpBinding,System.ServiceModel.Configuration.MexHttpBindingElement>'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.BindingCollectionElement
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  - System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  - System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Bindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.BindingType
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ConfiguredBindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ContainsKey(System.String)
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Properties
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexHttpBindingCollectionElement.xml
- uid: System.ServiceModel.Configuration.MexHttpBindingCollectionElement.#ctor
  commentId: M:System.ServiceModel.Configuration.MexHttpBindingCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.MexHttpBindingCollectionElement
  langs:
  - csharp
  name: MexHttpBindingCollectionElement()
  nameWithType: MexHttpBindingCollectionElement.MexHttpBindingCollectionElement()
  fullName: MexHttpBindingCollectionElement.MexHttpBindingCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.MexHttpBindingCollectionElement"></xref> class.
  syntax:
    content: public MexHttpBindingCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.MexHttpBindingCollectionElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexHttpBindingCollectionElement.xml
- uid: System.ServiceModel.Configuration.MexHttpBindingCollectionElement.GetDefault
  commentId: M:System.ServiceModel.Configuration.MexHttpBindingCollectionElement.GetDefault
  id: GetDefault
  parent: System.ServiceModel.Configuration.MexHttpBindingCollectionElement
  langs:
  - csharp
  name: GetDefault()
  nameWithType: MexHttpBindingCollectionElement.GetDefault()
  fullName: MexHttpBindingCollectionElement.GetDefault()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Retrieves the default values of a configuration element.
  syntax:
    content: protected override System.ServiceModel.Channels.Binding GetDefault ();
    parameters: []
    return:
      type: System.ServiceModel.Channels.Binding
      description: The default binding.
  overload: System.ServiceModel.Configuration.MexHttpBindingCollectionElement.GetDefault*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexHttpBindingCollectionElement.xml
references:
- uid: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2
  name: MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  nameWithType: MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>
  fullName: System.ServiceModel.Configuration.MexBindingBindingCollectionElement<TStandardBinding,TBindingConfiguration>
- uid: System.ServiceModel.WSHttpBinding
  name: WSHttpBinding
  nameWithType: WSHttpBinding
  fullName: System.ServiceModel.WSHttpBinding
- uid: System.ServiceModel.Configuration.MexHttpBindingElement
  name: MexHttpBindingElement
  nameWithType: MexHttpBindingElement
  fullName: System.ServiceModel.Configuration.MexHttpBindingElement
- uid: System.ServiceModel.Configuration.MexBindingBindingCollectionElement{System.ServiceModel.WSHttpBinding,System.ServiceModel.Configuration.MexHttpBindingElement}
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: MexBindingBindingCollectionElement<WSHttpBinding,MexHttpBindingElement>
  nameWithType: MexBindingBindingCollectionElement<WSHttpBinding,MexHttpBindingElement>
  fullName: System.ServiceModel.Configuration.MexBindingBindingCollectionElement<System.ServiceModel.WSHttpBinding,System.ServiceModel.Configuration.MexHttpBindingElement>
  spec.csharp:
  - uid: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2
    name: MexBindingBindingCollectionElement
    nameWithType: MexBindingBindingCollectionElement
    fullName: System.ServiceModel.Configuration.MexBindingBindingCollectionElement
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.WSHttpBinding
    name: WSHttpBinding
    nameWithType: WSHttpBinding
    fullName: System.ServiceModel.WSHttpBinding
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.ServiceModel.Configuration.MexHttpBindingElement
    name: MexHttpBindingElement
    nameWithType: MexHttpBindingElement
    fullName: System.ServiceModel.Configuration.MexHttpBindingElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.MexHttpBindingCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.MexHttpBindingCollectionElement
  isExternal: false
  name: MexHttpBindingCollectionElement()
  nameWithType: MexHttpBindingCollectionElement.MexHttpBindingCollectionElement()
  fullName: MexHttpBindingCollectionElement.MexHttpBindingCollectionElement()
- uid: System.ServiceModel.Configuration.MexHttpBindingCollectionElement.GetDefault
  parent: System.ServiceModel.Configuration.MexHttpBindingCollectionElement
  isExternal: false
  name: GetDefault()
  nameWithType: MexHttpBindingCollectionElement.GetDefault()
  fullName: MexHttpBindingCollectionElement.GetDefault()
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: false
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.Configuration.MexHttpBindingCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.MexHttpBindingCollectionElement
  isExternal: false
  name: MexHttpBindingCollectionElement
  nameWithType: MexHttpBindingCollectionElement.MexHttpBindingCollectionElement
  fullName: MexHttpBindingCollectionElement.MexHttpBindingCollectionElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexHttpBindingCollectionElement.xml
- uid: System.ServiceModel.Configuration.MexHttpBindingCollectionElement.GetDefault*
  parent: System.ServiceModel.Configuration.MexHttpBindingCollectionElement
  isExternal: false
  name: GetDefault
  nameWithType: MexHttpBindingCollectionElement.GetDefault
  fullName: MexHttpBindingCollectionElement.GetDefault
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexHttpBindingCollectionElement.xml
