### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.RsaElement
  commentId: T:System.ServiceModel.Configuration.RsaElement
  id: RsaElement
  children:
  - System.ServiceModel.Configuration.RsaElement.#ctor
  - System.ServiceModel.Configuration.RsaElement.Properties
  - System.ServiceModel.Configuration.RsaElement.Value
  langs:
  - csharp
  name: RsaElement
  nameWithType: RsaElement
  fullName: System.ServiceModel.Configuration.RsaElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a configuration element for a RSA identity. This class cannot be inherited.
  remarks: ''
  example:
  - '[\&lt;rsa\&gt;](~/docs/framework/configure-apps/file-schema/wcf/rsa.md)'
  syntax:
    content: 'public sealed class RsaElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/RsaElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.RsaElement.#ctor
  commentId: M:System.ServiceModel.Configuration.RsaElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.RsaElement
  langs:
  - csharp
  name: RsaElement()
  nameWithType: RsaElement.RsaElement()
  fullName: System.ServiceModel.Configuration.RsaElement.RsaElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.RsaElement"></xref> class.
  syntax:
    content: public RsaElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.RsaElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/RsaElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.RsaElement.Properties
  commentId: P:System.ServiceModel.Configuration.RsaElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.RsaElement
  langs:
  - csharp
  name: Properties
  nameWithType: RsaElement.Properties
  fullName: System.ServiceModel.Configuration.RsaElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.RsaElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/RsaElement.xml
- uid: System.ServiceModel.Configuration.RsaElement.Value
  commentId: P:System.ServiceModel.Configuration.RsaElement.Value
  id: Value
  parent: System.ServiceModel.Configuration.RsaElement
  langs:
  - csharp
  name: Value
  nameWithType: RsaElement.Value
  fullName: System.ServiceModel.Configuration.RsaElement.Value
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the value encrypted by this identity.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("value", DefaultValue=Mono.Cecil.CustomAttributeArgument, Options=System.Configuration.ConfigurationPropertyOptions.None)]

      [System.Configuration.StringValidator(InvalidCharacters=null, MaxLength=2147483647, MinLength=0)]

      public string Value { get; set; }
    return:
      type: System.String
      description: The value encrypted by this identity.
  overload: System.ServiceModel.Configuration.RsaElement.Value*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/RsaElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.RsaElement.#ctor
  parent: System.ServiceModel.Configuration.RsaElement
  isExternal: false
  name: RsaElement()
  nameWithType: RsaElement.RsaElement()
  fullName: System.ServiceModel.Configuration.RsaElement.RsaElement()
- uid: System.ServiceModel.Configuration.RsaElement.Properties
  parent: System.ServiceModel.Configuration.RsaElement
  isExternal: false
  name: Properties
  nameWithType: RsaElement.Properties
  fullName: System.ServiceModel.Configuration.RsaElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.RsaElement.Value
  parent: System.ServiceModel.Configuration.RsaElement
  isExternal: false
  name: Value
  nameWithType: RsaElement.Value
  fullName: System.ServiceModel.Configuration.RsaElement.Value
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.RsaElement.#ctor*
  parent: System.ServiceModel.Configuration.RsaElement
  isExternal: false
  name: RsaElement
  nameWithType: RsaElement.RsaElement
  fullName: System.ServiceModel.Configuration.RsaElement.RsaElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/RsaElement.xml
- uid: System.ServiceModel.Configuration.RsaElement.Properties*
  parent: System.ServiceModel.Configuration.RsaElement
  isExternal: false
  name: Properties
  nameWithType: RsaElement.Properties
  fullName: System.ServiceModel.Configuration.RsaElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/RsaElement.xml
- uid: System.ServiceModel.Configuration.RsaElement.Value*
  parent: System.ServiceModel.Configuration.RsaElement
  isExternal: false
  name: Value
  nameWithType: RsaElement.Value
  fullName: System.ServiceModel.Configuration.RsaElement.Value
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/RsaElement.xml
