### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Discovery.Configuration.DynamicEndpointCollectionElement
  commentId: T:System.ServiceModel.Discovery.Configuration.DynamicEndpointCollectionElement
  id: DynamicEndpointCollectionElement
  children:
  - System.ServiceModel.Discovery.Configuration.DynamicEndpointCollectionElement.#ctor
  langs:
  - csharp
  name: DynamicEndpointCollectionElement
  nameWithType: DynamicEndpointCollectionElement
  fullName: System.ServiceModel.Discovery.Configuration.DynamicEndpointCollectionElement
  type: Class
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: Represents a workflow configuration element that provides a collection of endpoints that each contain information to enable an application to function as a client program that can search for, find, and use a workflow service during runtime.
  syntax:
    content: 'public class DynamicEndpointCollectionElement : System.ServiceModel.Configuration.StandardEndpointCollectionElement<System.ServiceModel.Discovery.DynamicEndpoint,System.ServiceModel.Discovery.Configuration.DynamicEndpointElement>'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.EndpointCollectionElement
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.ConfiguredEndpoints
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.ContainsKey(System.String)
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.Endpoints
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.EndpointType
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.GetDefaultStandardEndpointElement
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.Properties
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.TryAdd(System.String,System.ServiceModel.Description.ServiceEndpoint,System.Configuration.Configuration)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/DynamicEndpointCollectionElement.xml
- uid: System.ServiceModel.Discovery.Configuration.DynamicEndpointCollectionElement.#ctor
  commentId: M:System.ServiceModel.Discovery.Configuration.DynamicEndpointCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Discovery.Configuration.DynamicEndpointCollectionElement
  langs:
  - csharp
  name: DynamicEndpointCollectionElement()
  nameWithType: DynamicEndpointCollectionElement.DynamicEndpointCollectionElement()
  fullName: DynamicEndpointCollectionElement.DynamicEndpointCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: Creates a new instance of the <xref href="System.ServiceModel.Discovery.Configuration.DynamicEndpointCollectionElement"></xref> class.
  syntax:
    content: public DynamicEndpointCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Discovery.Configuration.DynamicEndpointCollectionElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/DynamicEndpointCollectionElement.xml
references:
- uid: System.ServiceModel.Configuration.StandardEndpointCollectionElement`2
  name: StandardEndpointCollectionElement<TStandardEndpoint,TEndpointConfiguration>
  nameWithType: StandardEndpointCollectionElement<TStandardEndpoint,TEndpointConfiguration>
  fullName: System.ServiceModel.Configuration.StandardEndpointCollectionElement<TStandardEndpoint,TEndpointConfiguration>
- uid: System.ServiceModel.Discovery.DynamicEndpoint
  name: DynamicEndpoint
  nameWithType: DynamicEndpoint
  fullName: System.ServiceModel.Discovery.DynamicEndpoint
- uid: System.ServiceModel.Discovery.Configuration.DynamicEndpointElement
  name: DynamicEndpointElement
  nameWithType: DynamicEndpointElement
  fullName: System.ServiceModel.Discovery.Configuration.DynamicEndpointElement
- uid: System.ServiceModel.Configuration.StandardEndpointCollectionElement{System.ServiceModel.Discovery.DynamicEndpoint,System.ServiceModel.Discovery.Configuration.DynamicEndpointElement}
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: StandardEndpointCollectionElement<DynamicEndpoint,DynamicEndpointElement>
  nameWithType: StandardEndpointCollectionElement<DynamicEndpoint,DynamicEndpointElement>
  fullName: System.ServiceModel.Configuration.StandardEndpointCollectionElement<System.ServiceModel.Discovery.DynamicEndpoint,System.ServiceModel.Discovery.Configuration.DynamicEndpointElement>
  spec.csharp:
  - uid: System.ServiceModel.Configuration.StandardEndpointCollectionElement`2
    name: StandardEndpointCollectionElement
    nameWithType: StandardEndpointCollectionElement
    fullName: System.ServiceModel.Configuration.StandardEndpointCollectionElement
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Discovery.DynamicEndpoint
    name: DynamicEndpoint
    nameWithType: DynamicEndpoint
    fullName: System.ServiceModel.Discovery.DynamicEndpoint
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.ServiceModel.Discovery.Configuration.DynamicEndpointElement
    name: DynamicEndpointElement
    nameWithType: DynamicEndpointElement
    fullName: System.ServiceModel.Discovery.Configuration.DynamicEndpointElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Discovery.Configuration.DynamicEndpointCollectionElement.#ctor
  parent: System.ServiceModel.Discovery.Configuration.DynamicEndpointCollectionElement
  isExternal: false
  name: DynamicEndpointCollectionElement()
  nameWithType: DynamicEndpointCollectionElement.DynamicEndpointCollectionElement()
  fullName: DynamicEndpointCollectionElement.DynamicEndpointCollectionElement()
- uid: System.ServiceModel.Discovery.Configuration.DynamicEndpointCollectionElement.#ctor*
  parent: System.ServiceModel.Discovery.Configuration.DynamicEndpointCollectionElement
  isExternal: false
  name: DynamicEndpointCollectionElement
  nameWithType: DynamicEndpointCollectionElement.DynamicEndpointCollectionElement
  fullName: DynamicEndpointCollectionElement.DynamicEndpointCollectionElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/DynamicEndpointCollectionElement.xml
