### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MexBindingElement`1
  commentId: T:System.ServiceModel.Configuration.MexBindingElement`1
  id: MexBindingElement`1
  children:
  - System.ServiceModel.Configuration.MexBindingElement`1.#ctor(System.String)
  - System.ServiceModel.Configuration.MexBindingElement`1.BindingElementType
  - System.ServiceModel.Configuration.MexBindingElement`1.OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  langs:
  - csharp
  name: MexBindingElement<TStandardBinding>
  nameWithType: MexBindingElement<TStandardBinding>
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a base configuration element that specifies the settings for a binding used for the WS-MetadataExchange (WS-MEX) message exchange.
  remarks: This binding element defines the basic settings for publishing service metadata for retrieval using a WS-MetadataExchange (WS-MEX) message exchange.
  syntax:
    content: 'public abstract class MexBindingElement<TStandardBinding> : System.ServiceModel.Configuration.StandardBindingElement where TStandardBinding : Binding'
    typeParameters:
    - id: TStandardBinding
      description: A standard binding element.
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.StandardBindingElement
  derivedClasses:
  - System.ServiceModel.Configuration.MexHttpBindingElement
  - System.ServiceModel.Configuration.MexHttpsBindingElement
  - System.ServiceModel.Configuration.MexNamedPipeBindingElement
  - System.ServiceModel.Configuration.MexTcpBindingElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.StandardBindingElement.ApplyConfiguration(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.StandardBindingElement.CloseTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.InitializeFrom(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.StandardBindingElement.Name
  - System.ServiceModel.Configuration.StandardBindingElement.OpenTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.Properties
  - System.ServiceModel.Configuration.StandardBindingElement.ReceiveTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.StandardBindingElement.SendTimeout
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexBindingElement`1.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.MexBindingElement`1.#ctor(System.String)
  commentId: M:System.ServiceModel.Configuration.MexBindingElement`1.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  langs:
  - csharp
  name: MexBindingElement<TStandardBinding>(String)
  nameWithType: MexBindingElement<TStandardBinding>.MexBindingElement<TStandardBinding>(String)
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>.MexBindingElement<TStandardBinding>(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.MexBindingElement`1"></xref> class with the specified name.
  syntax:
    content: protected MexBindingElement (string name);
    parameters:
    - id: name
      type: System.String
      description: The name of the binding.
  overload: System.ServiceModel.Configuration.MexBindingElement`1.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexBindingElement`1.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.MexBindingElement`1.BindingElementType
  commentId: P:System.ServiceModel.Configuration.MexBindingElement`1.BindingElementType
  id: BindingElementType
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  langs:
  - csharp
  name: BindingElementType
  nameWithType: MexBindingElement<TStandardBinding>.BindingElementType
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>.BindingElementType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets the type of this binding element.
  syntax:
    content: protected override Type BindingElementType { get; }
    return:
      type: System.Type
      description: The <xref href="System.Type"></xref> of this binding element.
  overload: System.ServiceModel.Configuration.MexBindingElement`1.BindingElementType*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexBindingElement`1.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.MexBindingElement`1.OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  commentId: M:System.ServiceModel.Configuration.MexBindingElement`1.OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  id: OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  langs:
  - csharp
  name: OnApplyConfiguration(Binding)
  nameWithType: MexBindingElement<TStandardBinding>.OnApplyConfiguration(Binding)
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>.OnApplyConfiguration(Binding)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Called when the content of a specified binding configuration element is applied to this binding configuration element.
  syntax:
    content: protected override void OnApplyConfiguration (System.ServiceModel.Channels.Binding binding);
    parameters:
    - id: binding
      type: System.ServiceModel.Channels.Binding
      description: A binding configuration element.
  overload: System.ServiceModel.Configuration.MexBindingElement`1.OnApplyConfiguration*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexBindingElement`1.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.ServiceModel.Configuration.StandardBindingElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: StandardBindingElement
  nameWithType: StandardBindingElement
  fullName: System.ServiceModel.Configuration.StandardBindingElement
- uid: System.ServiceModel.Configuration.MexBindingElement`1.#ctor(System.String)
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  isExternal: false
  name: MexBindingElement<TStandardBinding>(String)
  nameWithType: MexBindingElement<TStandardBinding>.MexBindingElement<TStandardBinding>(String)
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>.MexBindingElement<TStandardBinding>(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.MexBindingElement`1.BindingElementType
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  isExternal: false
  name: BindingElementType
  nameWithType: MexBindingElement<TStandardBinding>.BindingElementType
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>.BindingElementType
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.MexBindingElement`1.OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  isExternal: false
  name: OnApplyConfiguration(Binding)
  nameWithType: MexBindingElement<TStandardBinding>.OnApplyConfiguration(Binding)
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>.OnApplyConfiguration(Binding)
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: false
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.Configuration.MexBindingElement`1.#ctor*
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  isExternal: false
  name: MexBindingElement<TStandardBinding>
  nameWithType: MexBindingElement<TStandardBinding>.MexBindingElement<TStandardBinding>
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>.MexBindingElement<TStandardBinding>
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexBindingElement`1.xml
- uid: System.ServiceModel.Configuration.MexBindingElement`1.BindingElementType*
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  isExternal: false
  name: BindingElementType
  nameWithType: MexBindingElement<TStandardBinding>.BindingElementType
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>.BindingElementType
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexBindingElement`1.xml
- uid: System.ServiceModel.Configuration.MexBindingElement`1.OnApplyConfiguration*
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  isExternal: false
  name: OnApplyConfiguration
  nameWithType: MexBindingElement<TStandardBinding>.OnApplyConfiguration
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>.OnApplyConfiguration
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/MexBindingElement`1.xml
