### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
  commentId: T:System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
  id: SmtpSpecifiedPickupDirectoryElement
  children:
  - System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.#ctor
  - System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.PickupDirectoryLocation
  - System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.Properties
  langs:
  - csharp
  name: SmtpSpecifiedPickupDirectoryElement
  nameWithType: SmtpSpecifiedPickupDirectoryElement
  fullName: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
  type: Class
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Represents an SMTP pickup directory configuration element.
  syntax:
    content: 'public sealed class SmtpSpecifiedPickupDirectoryElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/SmtpSpecifiedPickupDirectoryElement.xml
- uid: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.#ctor
  commentId: M:System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
  langs:
  - csharp
  name: SmtpSpecifiedPickupDirectoryElement()
  nameWithType: SmtpSpecifiedPickupDirectoryElement.SmtpSpecifiedPickupDirectoryElement()
  fullName: SmtpSpecifiedPickupDirectoryElement.SmtpSpecifiedPickupDirectoryElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Initializes a new instance of the <xref href="System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement"></xref> class.
  syntax:
    content: public SmtpSpecifiedPickupDirectoryElement ();
    parameters: []
  overload: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/SmtpSpecifiedPickupDirectoryElement.xml
- uid: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.PickupDirectoryLocation
  commentId: P:System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.PickupDirectoryLocation
  id: PickupDirectoryLocation
  parent: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
  langs:
  - csharp
  name: PickupDirectoryLocation
  nameWithType: SmtpSpecifiedPickupDirectoryElement.PickupDirectoryLocation
  fullName: SmtpSpecifiedPickupDirectoryElement.PickupDirectoryLocation
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Gets or sets the folder where applications save mail messages to be processed by the SMTP server.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("pickupDirectoryLocation")]

      public string PickupDirectoryLocation { get; set; }
    return:
      type: System.String
      description: A string that specifies the pickup directory for e-mail messages.
  overload: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.PickupDirectoryLocation*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/SmtpSpecifiedPickupDirectoryElement.xml
- uid: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.Properties
  commentId: P:System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.Properties
  id: Properties
  parent: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
  langs:
  - csharp
  name: Properties
  nameWithType: SmtpSpecifiedPickupDirectoryElement.Properties
  fullName: SmtpSpecifiedPickupDirectoryElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/SmtpSpecifiedPickupDirectoryElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.#ctor
  parent: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
  isExternal: false
  name: SmtpSpecifiedPickupDirectoryElement()
  nameWithType: SmtpSpecifiedPickupDirectoryElement.SmtpSpecifiedPickupDirectoryElement()
  fullName: SmtpSpecifiedPickupDirectoryElement.SmtpSpecifiedPickupDirectoryElement()
- uid: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.PickupDirectoryLocation
  parent: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
  isExternal: false
  name: PickupDirectoryLocation
  nameWithType: SmtpSpecifiedPickupDirectoryElement.PickupDirectoryLocation
  fullName: SmtpSpecifiedPickupDirectoryElement.PickupDirectoryLocation
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.Properties
  parent: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
  isExternal: false
  name: Properties
  nameWithType: SmtpSpecifiedPickupDirectoryElement.Properties
  fullName: SmtpSpecifiedPickupDirectoryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.#ctor*
  parent: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
  isExternal: false
  name: SmtpSpecifiedPickupDirectoryElement
  nameWithType: SmtpSpecifiedPickupDirectoryElement.SmtpSpecifiedPickupDirectoryElement
  fullName: SmtpSpecifiedPickupDirectoryElement.SmtpSpecifiedPickupDirectoryElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/SmtpSpecifiedPickupDirectoryElement.xml
- uid: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.PickupDirectoryLocation*
  parent: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
  isExternal: false
  name: PickupDirectoryLocation
  nameWithType: SmtpSpecifiedPickupDirectoryElement.PickupDirectoryLocation
  fullName: SmtpSpecifiedPickupDirectoryElement.PickupDirectoryLocation
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/SmtpSpecifiedPickupDirectoryElement.xml
- uid: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement.Properties*
  parent: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
  isExternal: false
  name: Properties
  nameWithType: SmtpSpecifiedPickupDirectoryElement.Properties
  fullName: SmtpSpecifiedPickupDirectoryElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/SmtpSpecifiedPickupDirectoryElement.xml
