### YamlMime:ManagedReference
items:
- uid: System.Activities.Expressions.EnvironmentLocationValue`1
  commentId: T:System.Activities.Expressions.EnvironmentLocationValue`1
  id: EnvironmentLocationValue`1
  children:
  - System.Activities.Expressions.EnvironmentLocationValue`1.CacheMetadata(System.Activities.CodeActivityMetadata)
  - System.Activities.Expressions.EnvironmentLocationValue`1.Execute(System.Activities.CodeActivityContext)
  - System.Activities.Expressions.EnvironmentLocationValue`1.LocationReference
  langs:
  - csharp
  name: EnvironmentLocationValue<T>
  nameWithType: EnvironmentLocationValue<T>
  fullName: System.Activities.Expressions.EnvironmentLocationValue<T>
  type: Class
  assemblies:
  - System.Activities
  namespace: System.Activities.Expressions
  summary: Represents the environment location value.
  syntax:
    content: 'public class EnvironmentLocationValue<T> : System.Activities.CodeActivity<T>'
    typeParameters:
    - id: T
      description: The data type of the <xref href="System.Activities.Expressions.EnvironmentLocationValue`1"></xref>.
  inheritance:
  - System.Object
  - System.Activities.Activity
  - System.Activities.ActivityWithResult
  - System.Activities.Activity`1
  - System.Activities.CodeActivity`1
  derivedClasses:
  - System.Activities.Expressions.ArgumentValue`1
  - System.Activities.Expressions.DelegateArgumentValue`1
  - System.Activities.Expressions.VariableValue`1
  implements: []
  inheritedMembers:
  - System.Activities.Activity.CacheId
  - System.Activities.Activity.Constraints
  - System.Activities.Activity.DisplayName
  - System.Activities.Activity.Id
  - System.Activities.Activity.ShouldSerializeDisplayName
  - System.Activities.Activity.ToString
  - System.Activities.Activity`1.FromValue(`0)
  - System.Activities.Activity`1.FromVariable(System.Activities.Variable)
  - System.Activities.Activity`1.FromVariable(System.Activities.Variable{`0})
  - System.Activities.Activity`1.op_Implicit(System.Activities.Variable to System.Activities.Activity{TResult})
  - System.Activities.Activity`1.op_Implicit(System.Activities.Variable{TResult} to System.Activities.Activity{TResult})
  - System.Activities.Activity`1.op_Implicit(TResult to System.Activities.Activity{TResult})
  - System.Activities.Activity`1.Result
  - System.Activities.ActivityWithResult.ResultType
  - System.Activities.CodeActivity`1.CacheMetadata(System.Activities.ActivityMetadata)
  - System.Activities.CodeActivity`1.Implementation
  - System.Activities.CodeActivity`1.ImplementationVersion
  - System.Activities.CodeActivity`1.OnCreateDynamicUpdateMap(System.Activities.DynamicUpdate.UpdateMapMetadata,System.Activities.Activity)
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities.Expressions/EnvironmentLocationValue`1.xml
- uid: System.Activities.Expressions.EnvironmentLocationValue`1.CacheMetadata(System.Activities.CodeActivityMetadata)
  commentId: M:System.Activities.Expressions.EnvironmentLocationValue`1.CacheMetadata(System.Activities.CodeActivityMetadata)
  id: CacheMetadata(System.Activities.CodeActivityMetadata)
  parent: System.Activities.Expressions.EnvironmentLocationValue`1
  langs:
  - csharp
  name: CacheMetadata(CodeActivityMetadata)
  nameWithType: EnvironmentLocationValue<T>.CacheMetadata(CodeActivityMetadata)
  fullName: EnvironmentLocationValue<T>.CacheMetadata(CodeActivityMetadata)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.Expressions
  summary: Creates and validates a description of the activity’s arguments, variables, child activities, and activity delegates.
  syntax:
    content: protected override void CacheMetadata (System.Activities.CodeActivityMetadata metadata);
    parameters:
    - id: metadata
      type: System.Activities.CodeActivityMetadata
      description: The activity’s metadata that encapsulates the activity’s arguments, variables, child activities, and activity delegates.
  overload: System.Activities.Expressions.EnvironmentLocationValue`1.CacheMetadata*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities.Expressions/EnvironmentLocationValue`1.xml
- uid: System.Activities.Expressions.EnvironmentLocationValue`1.Execute(System.Activities.CodeActivityContext)
  commentId: M:System.Activities.Expressions.EnvironmentLocationValue`1.Execute(System.Activities.CodeActivityContext)
  id: Execute(System.Activities.CodeActivityContext)
  parent: System.Activities.Expressions.EnvironmentLocationValue`1
  langs:
  - csharp
  name: Execute(CodeActivityContext)
  nameWithType: EnvironmentLocationValue<T>.Execute(CodeActivityContext)
  fullName: EnvironmentLocationValue<T>.Execute(CodeActivityContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.Expressions
  summary: Performs the execution of the activity.
  syntax:
    content: protected override T Execute (System.Activities.CodeActivityContext context);
    parameters:
    - id: context
      type: System.Activities.CodeActivityContext
      description: The execution context under which the activity executes.
    return:
      type: T
      description: The execution of the activity.
  overload: System.Activities.Expressions.EnvironmentLocationValue`1.Execute*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities.Expressions/EnvironmentLocationValue`1.xml
- uid: System.Activities.Expressions.EnvironmentLocationValue`1.LocationReference
  commentId: P:System.Activities.Expressions.EnvironmentLocationValue`1.LocationReference
  id: LocationReference
  parent: System.Activities.Expressions.EnvironmentLocationValue`1
  langs:
  - csharp
  name: LocationReference
  nameWithType: EnvironmentLocationValue<T>.LocationReference
  fullName: EnvironmentLocationValue<T>.LocationReference
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Expressions
  summary: Gets the location reference value.
  syntax:
    content: public virtual System.Activities.LocationReference LocationReference { get; }
    return:
      type: System.Activities.LocationReference
      description: The location reference value.
  overload: System.Activities.Expressions.EnvironmentLocationValue`1.LocationReference*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities.Expressions/EnvironmentLocationValue`1.xml
references:
- uid: System.Activities.CodeActivity`1
  name: CodeActivity<TResult>
  nameWithType: CodeActivity<TResult>
  fullName: System.Activities.CodeActivity<TResult>
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: System.Activities.CodeActivity{T}
  parent: System.Activities
  isExternal: false
  name: CodeActivity<T>
  nameWithType: CodeActivity<T>
  fullName: System.Activities.CodeActivity<T>
  spec.csharp:
  - uid: System.Activities.CodeActivity`1
    name: CodeActivity
    nameWithType: CodeActivity
    fullName: System.Activities.CodeActivity
  - name: <
    nameWithType: <
    fullName: <
  - uid: T
    name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Activities.Expressions.EnvironmentLocationValue`1.CacheMetadata(System.Activities.CodeActivityMetadata)
  parent: System.Activities.Expressions.EnvironmentLocationValue`1
  isExternal: false
  name: CacheMetadata(CodeActivityMetadata)
  nameWithType: EnvironmentLocationValue<T>.CacheMetadata(CodeActivityMetadata)
  fullName: EnvironmentLocationValue<T>.CacheMetadata(CodeActivityMetadata)
- uid: System.Activities.CodeActivityMetadata
  parent: System.Activities
  isExternal: false
  name: CodeActivityMetadata
  nameWithType: CodeActivityMetadata
  fullName: System.Activities.CodeActivityMetadata
- uid: System.Activities.Expressions.EnvironmentLocationValue`1.Execute(System.Activities.CodeActivityContext)
  parent: System.Activities.Expressions.EnvironmentLocationValue`1
  isExternal: false
  name: Execute(CodeActivityContext)
  nameWithType: EnvironmentLocationValue<T>.Execute(CodeActivityContext)
  fullName: EnvironmentLocationValue<T>.Execute(CodeActivityContext)
- uid: System.Activities.CodeActivityContext
  parent: System.Activities
  isExternal: false
  name: CodeActivityContext
  nameWithType: CodeActivityContext
  fullName: System.Activities.CodeActivityContext
- uid: System.Activities.Expressions.EnvironmentLocationValue`1.LocationReference
  parent: System.Activities.Expressions.EnvironmentLocationValue`1
  isExternal: false
  name: LocationReference
  nameWithType: EnvironmentLocationValue<T>.LocationReference
  fullName: EnvironmentLocationValue<T>.LocationReference
- uid: System.Activities.LocationReference
  parent: System.Activities
  isExternal: false
  name: LocationReference
  nameWithType: LocationReference
  fullName: System.Activities.LocationReference
- uid: System.Activities.Expressions.EnvironmentLocationValue`1.CacheMetadata*
  parent: System.Activities.Expressions.EnvironmentLocationValue`1
  isExternal: false
  name: CacheMetadata
  nameWithType: EnvironmentLocationValue<T>.CacheMetadata
  fullName: EnvironmentLocationValue<T>.CacheMetadata
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities.Expressions/EnvironmentLocationValue`1.xml
- uid: System.Activities.Expressions.EnvironmentLocationValue`1.Execute*
  parent: System.Activities.Expressions.EnvironmentLocationValue`1
  isExternal: false
  name: Execute
  nameWithType: EnvironmentLocationValue<T>.Execute
  fullName: EnvironmentLocationValue<T>.Execute
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities.Expressions/EnvironmentLocationValue`1.xml
- uid: System.Activities.Expressions.EnvironmentLocationValue`1.LocationReference*
  parent: System.Activities.Expressions.EnvironmentLocationValue`1
  isExternal: false
  name: LocationReference
  nameWithType: EnvironmentLocationValue<T>.LocationReference
  fullName: EnvironmentLocationValue<T>.LocationReference
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Activities.Expressions/EnvironmentLocationValue`1.xml
