### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WindowsClientElement
  commentId: T:System.ServiceModel.Configuration.WindowsClientElement
  id: WindowsClientElement
  children:
  - System.ServiceModel.Configuration.WindowsClientElement.#ctor
  - System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel
  - System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm
  - System.ServiceModel.Configuration.WindowsClientElement.Copy(System.ServiceModel.Configuration.WindowsClientElement)
  - System.ServiceModel.Configuration.WindowsClientElement.Properties
  langs:
  - csharp
  name: WindowsClientElement
  nameWithType: WindowsClientElement
  fullName: System.ServiceModel.Configuration.WindowsClientElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a configuration element that specifies the settings for a Windows credential to be used to represent the client. This class cannot be inherited.
  syntax:
    content: 'public sealed class WindowsClientElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsClientElement.xml
- uid: System.ServiceModel.Configuration.WindowsClientElement.#ctor
  commentId: M:System.ServiceModel.Configuration.WindowsClientElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WindowsClientElement
  langs:
  - csharp
  name: WindowsClientElement()
  nameWithType: WindowsClientElement.WindowsClientElement()
  fullName: WindowsClientElement.WindowsClientElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.WindowsClientElement"></xref> class.
  syntax:
    content: public WindowsClientElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WindowsClientElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsClientElement.xml
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel
  commentId: P:System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel
  id: AllowedImpersonationLevel
  parent: System.ServiceModel.Configuration.WindowsClientElement
  langs:
  - csharp
  name: AllowedImpersonationLevel
  nameWithType: WindowsClientElement.AllowedImpersonationLevel
  fullName: WindowsClientElement.AllowedImpersonationLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the permissible impersonation level.
  remarks: See <xref:System.Security.Principal.TokenImpersonationLevel> for a description of the enumeration.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("allowedImpersonationLevel", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.Security.Principal.TokenImpersonationLevel AllowedImpersonationLevel { get; set; }
    return:
      type: System.Security.Principal.TokenImpersonationLevel
      description: A valid <xref href="System.Security.Principal.TokenImpersonationLevel"></xref> value that specifies the permissible impersonation level. The default is <xref href="System.Security.Principal.TokenImpersonationLevel.Identification"></xref>.
  overload: System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsClientElement.xml
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm
  commentId: P:System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm
  id: AllowNtlm
  parent: System.ServiceModel.Configuration.WindowsClientElement
  langs:
  - csharp
  name: AllowNtlm
  nameWithType: WindowsClientElement.AllowNtlm
  fullName: WindowsClientElement.AllowNtlm
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets a boolean value that specifies whether NTLM authentication is allowed.
  remarks: When this property is set to `true`, Windows security is enabled at the workgroup level. Otherwise, Windows security is only supported at the domain level.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("allowNtlm", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public bool AllowNtlm { get; set; }
    return:
      type: System.Boolean
      description: '`true` if Windows security is enabled in the workgroup scenario; otherwise, `false`. The default is `false`.'
  overload: System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsClientElement.xml
- uid: System.ServiceModel.Configuration.WindowsClientElement.Copy(System.ServiceModel.Configuration.WindowsClientElement)
  commentId: M:System.ServiceModel.Configuration.WindowsClientElement.Copy(System.ServiceModel.Configuration.WindowsClientElement)
  id: Copy(System.ServiceModel.Configuration.WindowsClientElement)
  parent: System.ServiceModel.Configuration.WindowsClientElement
  langs:
  - csharp
  name: Copy(WindowsClientElement)
  nameWithType: WindowsClientElement.Copy(WindowsClientElement)
  fullName: WindowsClientElement.Copy(WindowsClientElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Copies the content of the specified configuration element to this configuration element.
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.WindowsClientElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.WindowsClientElement
      description: The configuration element to be copied.
  overload: System.ServiceModel.Configuration.WindowsClientElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: <code>from</code> is `null`.
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: The configuration file is read-only.
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsClientElement.xml
- uid: System.ServiceModel.Configuration.WindowsClientElement.Properties
  commentId: P:System.ServiceModel.Configuration.WindowsClientElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WindowsClientElement
  langs:
  - csharp
  name: Properties
  nameWithType: WindowsClientElement.Properties
  fullName: WindowsClientElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.WindowsClientElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsClientElement.xml
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  parent: System
  isExternal: false
  name: ArgumentNullException
  nameWithType: ArgumentNullException
  fullName: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.WindowsClientElement.#ctor
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: WindowsClientElement()
  nameWithType: WindowsClientElement.WindowsClientElement()
  fullName: WindowsClientElement.WindowsClientElement()
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: AllowedImpersonationLevel
  nameWithType: WindowsClientElement.AllowedImpersonationLevel
  fullName: WindowsClientElement.AllowedImpersonationLevel
- uid: System.Security.Principal.TokenImpersonationLevel
  parent: System.Security.Principal
  isExternal: false
  name: TokenImpersonationLevel
  nameWithType: TokenImpersonationLevel
  fullName: System.Security.Principal.TokenImpersonationLevel
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: AllowNtlm
  nameWithType: WindowsClientElement.AllowNtlm
  fullName: WindowsClientElement.AllowNtlm
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.WindowsClientElement.Copy(System.ServiceModel.Configuration.WindowsClientElement)
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: Copy(WindowsClientElement)
  nameWithType: WindowsClientElement.Copy(WindowsClientElement)
  fullName: WindowsClientElement.Copy(WindowsClientElement)
- uid: System.ServiceModel.Configuration.WindowsClientElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: WindowsClientElement
  nameWithType: WindowsClientElement
  fullName: System.ServiceModel.Configuration.WindowsClientElement
- uid: System.ServiceModel.Configuration.WindowsClientElement.Properties
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: Properties
  nameWithType: WindowsClientElement.Properties
  fullName: WindowsClientElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WindowsClientElement.#ctor*
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: WindowsClientElement
  nameWithType: WindowsClientElement.WindowsClientElement
  fullName: WindowsClientElement.WindowsClientElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsClientElement.xml
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel*
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: AllowedImpersonationLevel
  nameWithType: WindowsClientElement.AllowedImpersonationLevel
  fullName: WindowsClientElement.AllowedImpersonationLevel
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsClientElement.xml
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm*
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: AllowNtlm
  nameWithType: WindowsClientElement.AllowNtlm
  fullName: WindowsClientElement.AllowNtlm
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsClientElement.xml
- uid: System.ServiceModel.Configuration.WindowsClientElement.Copy*
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: Copy
  nameWithType: WindowsClientElement.Copy
  fullName: WindowsClientElement.Copy
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsClientElement.xml
- uid: System.ServiceModel.Configuration.WindowsClientElement.Properties*
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: Properties
  nameWithType: WindowsClientElement.Properties
  fullName: WindowsClientElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/WindowsClientElement.xml
