### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  commentId: T:System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  id: BookmarkResumptionQueryElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Name
  - System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.NewTrackingQuery
  - System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Properties
  langs:
  - csharp
  name: BookmarkResumptionQueryElement
  nameWithType: BookmarkResumptionQueryElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  type: Class
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: A configuration element that represents a <xref href="System.Activities.Tracking.BookmarkResumptionQuery"></xref>.
  syntax:
    content: 'public class BookmarkResumptionQueryElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Annotations
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.UpdateTrackingQuery(System.Activities.Tracking.TrackingQuery)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/BookmarkResumptionQueryElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.#ctor
  commentId: M:System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  langs:
  - csharp
  name: BookmarkResumptionQueryElement()
  nameWithType: BookmarkResumptionQueryElement.BookmarkResumptionQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.BookmarkResumptionQueryElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement"></xref> class.
  syntax:
    content: public BookmarkResumptionQueryElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/BookmarkResumptionQueryElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Name
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Name
  id: Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  langs:
  - csharp
  name: Name
  nameWithType: BookmarkResumptionQueryElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets or sets the name of the bookmark.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("name", DefaultValue=Mono.Cecil.CustomAttributeArgument, IsKey=true)]

      [System.Configuration.StringValidator(MinLength=0)]

      public string Name { get; set; }
    return:
      type: System.String
      description: The bookmark name.
  overload: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Name*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/BookmarkResumptionQueryElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.NewTrackingQuery
  commentId: M:System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.NewTrackingQuery
  id: NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  langs:
  - csharp
  name: NewTrackingQuery()
  nameWithType: BookmarkResumptionQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.NewTrackingQuery()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Creates the <xref href="System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement"></xref>.
  syntax:
    content: protected override System.Activities.Tracking.TrackingQuery NewTrackingQuery ();
    parameters: []
    return:
      type: System.Activities.Tracking.TrackingQuery
      description: The bookmark resumption query.
  overload: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.NewTrackingQuery*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/BookmarkResumptionQueryElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Properties
  commentId: P:System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  langs:
  - csharp
  name: Properties
  nameWithType: BookmarkResumptionQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: Gets a <xref href="System.Configuration.ConfigurationPropertyCollection"></xref> that contains the properties associated with this element.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: A collection of properties.
  overload: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/BookmarkResumptionQueryElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  parent: System.ServiceModel.Activities.Tracking.Configuration
  isExternal: false
  name: TrackingQueryElement
  nameWithType: TrackingQueryElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  isExternal: false
  name: BookmarkResumptionQueryElement()
  nameWithType: BookmarkResumptionQueryElement.BookmarkResumptionQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.BookmarkResumptionQueryElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  isExternal: false
  name: Name
  nameWithType: BookmarkResumptionQueryElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Name
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  isExternal: false
  name: NewTrackingQuery()
  nameWithType: BookmarkResumptionQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.NewTrackingQuery()
- uid: System.Activities.Tracking.TrackingQuery
  parent: System.Activities.Tracking
  isExternal: false
  name: TrackingQuery
  nameWithType: TrackingQuery
  fullName: System.Activities.Tracking.TrackingQuery
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  isExternal: false
  name: Properties
  nameWithType: BookmarkResumptionQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  isExternal: false
  name: BookmarkResumptionQueryElement
  nameWithType: BookmarkResumptionQueryElement.BookmarkResumptionQueryElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.BookmarkResumptionQueryElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/BookmarkResumptionQueryElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Name*
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  isExternal: false
  name: Name
  nameWithType: BookmarkResumptionQueryElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Name
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/BookmarkResumptionQueryElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.NewTrackingQuery*
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  isExternal: false
  name: NewTrackingQuery
  nameWithType: BookmarkResumptionQueryElement.NewTrackingQuery
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.NewTrackingQuery
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/BookmarkResumptionQueryElement.xml
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  isExternal: false
  name: Properties
  nameWithType: BookmarkResumptionQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Activities.Tracking.Configuration/BookmarkResumptionQueryElement.xml
