### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointCollectionElement
  commentId: T:System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointCollectionElement
  id: UdpDiscoveryEndpointCollectionElement
  children:
  - System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointCollectionElement.#ctor
  langs:
  - csharp
  name: UdpDiscoveryEndpointCollectionElement
  nameWithType: UdpDiscoveryEndpointCollectionElement
  fullName: System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointCollectionElement
  type: Class
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: Represents a container for <xref href="System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointElement"></xref> configuration elements.
  syntax:
    content: 'public class UdpDiscoveryEndpointCollectionElement : System.ServiceModel.Configuration.StandardEndpointCollectionElement<System.ServiceModel.Discovery.UdpDiscoveryEndpoint,System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointElement>'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.EndpointCollectionElement
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.ConfiguredEndpoints
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.ContainsKey(System.String)
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.Endpoints
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.EndpointType
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.GetDefaultStandardEndpointElement
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.Properties
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.TryAdd(System.String,System.ServiceModel.Description.ServiceEndpoint,System.Configuration.Configuration)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/UdpDiscoveryEndpointCollectionElement.xml
- uid: System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointCollectionElement.#ctor
  commentId: M:System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointCollectionElement
  langs:
  - csharp
  name: UdpDiscoveryEndpointCollectionElement()
  nameWithType: UdpDiscoveryEndpointCollectionElement.UdpDiscoveryEndpointCollectionElement()
  fullName: UdpDiscoveryEndpointCollectionElement.UdpDiscoveryEndpointCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: Creates a new instance of the <xref href="System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointCollectionElement"></xref>.
  syntax:
    content: public UdpDiscoveryEndpointCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointCollectionElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/UdpDiscoveryEndpointCollectionElement.xml
references:
- uid: System.ServiceModel.Configuration.StandardEndpointCollectionElement`2
  name: StandardEndpointCollectionElement<TStandardEndpoint,TEndpointConfiguration>
  nameWithType: StandardEndpointCollectionElement<TStandardEndpoint,TEndpointConfiguration>
  fullName: System.ServiceModel.Configuration.StandardEndpointCollectionElement<TStandardEndpoint,TEndpointConfiguration>
- uid: System.ServiceModel.Discovery.UdpDiscoveryEndpoint
  name: UdpDiscoveryEndpoint
  nameWithType: UdpDiscoveryEndpoint
  fullName: System.ServiceModel.Discovery.UdpDiscoveryEndpoint
- uid: System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointElement
  name: UdpDiscoveryEndpointElement
  nameWithType: UdpDiscoveryEndpointElement
  fullName: System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointElement
- uid: System.ServiceModel.Configuration.StandardEndpointCollectionElement{System.ServiceModel.Discovery.UdpDiscoveryEndpoint,System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointElement}
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: StandardEndpointCollectionElement<UdpDiscoveryEndpoint,UdpDiscoveryEndpointElement>
  nameWithType: StandardEndpointCollectionElement<UdpDiscoveryEndpoint,UdpDiscoveryEndpointElement>
  fullName: System.ServiceModel.Configuration.StandardEndpointCollectionElement<System.ServiceModel.Discovery.UdpDiscoveryEndpoint,System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointElement>
  spec.csharp:
  - uid: System.ServiceModel.Configuration.StandardEndpointCollectionElement`2
    name: StandardEndpointCollectionElement
    nameWithType: StandardEndpointCollectionElement
    fullName: System.ServiceModel.Configuration.StandardEndpointCollectionElement
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Discovery.UdpDiscoveryEndpoint
    name: UdpDiscoveryEndpoint
    nameWithType: UdpDiscoveryEndpoint
    fullName: System.ServiceModel.Discovery.UdpDiscoveryEndpoint
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointElement
    name: UdpDiscoveryEndpointElement
    nameWithType: UdpDiscoveryEndpointElement
    fullName: System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointCollectionElement.#ctor
  parent: System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointCollectionElement
  isExternal: false
  name: UdpDiscoveryEndpointCollectionElement()
  nameWithType: UdpDiscoveryEndpointCollectionElement.UdpDiscoveryEndpointCollectionElement()
  fullName: UdpDiscoveryEndpointCollectionElement.UdpDiscoveryEndpointCollectionElement()
- uid: System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointCollectionElement.#ctor*
  parent: System.ServiceModel.Discovery.Configuration.UdpDiscoveryEndpointCollectionElement
  isExternal: false
  name: UdpDiscoveryEndpointCollectionElement
  nameWithType: UdpDiscoveryEndpointCollectionElement.UdpDiscoveryEndpointCollectionElement
  fullName: UdpDiscoveryEndpointCollectionElement.UdpDiscoveryEndpointCollectionElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Discovery.Configuration/UdpDiscoveryEndpointCollectionElement.xml
