### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  commentId: T:System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  id: IssuedTokenParametersEndpointAddressElement
  children:
  - System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.#ctor
  - System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Binding
  - System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  - System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Properties
  langs:
  - csharp
  name: IssuedTokenParametersEndpointAddressElement
  nameWithType: IssuedTokenParametersEndpointAddressElement
  fullName: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a configuration element that specifies an endpoint that issues a security token. This class cannot be inherited.
  syntax:
    content: 'public sealed class IssuedTokenParametersEndpointAddressElement : System.ServiceModel.Configuration.EndpointAddressElementBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.EndpointAddressElementBase
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.EndpointAddressElementBase.Address
  - System.ServiceModel.Configuration.EndpointAddressElementBase.Copy(System.ServiceModel.Configuration.EndpointAddressElementBase)
  - System.ServiceModel.Configuration.EndpointAddressElementBase.Headers
  - System.ServiceModel.Configuration.EndpointAddressElementBase.Identity
  - System.ServiceModel.Configuration.EndpointAddressElementBase.InitializeFrom(System.ServiceModel.EndpointAddress)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenParametersEndpointAddressElement.xml
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.#ctor
  commentId: M:System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  langs:
  - csharp
  name: IssuedTokenParametersEndpointAddressElement()
  nameWithType: IssuedTokenParametersEndpointAddressElement.IssuedTokenParametersEndpointAddressElement()
  fullName: IssuedTokenParametersEndpointAddressElement.IssuedTokenParametersEndpointAddressElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement"></xref> class.
  syntax:
    content: public IssuedTokenParametersEndpointAddressElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenParametersEndpointAddressElement.xml
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Binding
  commentId: P:System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Binding
  id: Binding
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  langs:
  - csharp
  name: Binding
  nameWithType: IssuedTokenParametersEndpointAddressElement.Binding
  fullName: IssuedTokenParametersEndpointAddressElement.Binding
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the type of binding to use.
  remarks: The type must have a registered configuration section in order to be referenced. The type is registered by section name, rather than by the type name of the binding.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("binding", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      [System.Configuration.StringValidator(MinLength=0)]

      public string Binding { get; set; }
    return:
      type: System.String
      description: The type of binding to use.
  overload: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Binding*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenParametersEndpointAddressElement.xml
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  commentId: P:System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  id: BindingConfiguration
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  langs:
  - csharp
  name: BindingConfiguration
  nameWithType: IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  fullName: IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the name of the binding configuration to use when the endpoint is instantiated. The binding configuration must be in scope when the endpoint is defined.
  remarks: The binding configuration must be in scope when the endpoint is defined.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("bindingConfiguration", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      [System.Configuration.StringValidator(MinLength=0)]

      public string BindingConfiguration { get; set; }
    return:
      type: System.String
      description: The name of the binding configuration to use when the endpoint is instantiated.
  overload: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenParametersEndpointAddressElement.xml
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Properties
  commentId: P:System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  langs:
  - csharp
  name: Properties
  nameWithType: IssuedTokenParametersEndpointAddressElement.Properties
  fullName: IssuedTokenParametersEndpointAddressElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenParametersEndpointAddressElement.xml
references:
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: EndpointAddressElementBase
  nameWithType: EndpointAddressElementBase
  fullName: System.ServiceModel.Configuration.EndpointAddressElementBase
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.#ctor
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  isExternal: false
  name: IssuedTokenParametersEndpointAddressElement()
  nameWithType: IssuedTokenParametersEndpointAddressElement.IssuedTokenParametersEndpointAddressElement()
  fullName: IssuedTokenParametersEndpointAddressElement.IssuedTokenParametersEndpointAddressElement()
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Binding
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  isExternal: false
  name: Binding
  nameWithType: IssuedTokenParametersEndpointAddressElement.Binding
  fullName: IssuedTokenParametersEndpointAddressElement.Binding
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  isExternal: false
  name: BindingConfiguration
  nameWithType: IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  fullName: IssuedTokenParametersEndpointAddressElement.BindingConfiguration
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Properties
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  isExternal: false
  name: Properties
  nameWithType: IssuedTokenParametersEndpointAddressElement.Properties
  fullName: IssuedTokenParametersEndpointAddressElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.#ctor*
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  isExternal: false
  name: IssuedTokenParametersEndpointAddressElement
  nameWithType: IssuedTokenParametersEndpointAddressElement.IssuedTokenParametersEndpointAddressElement
  fullName: IssuedTokenParametersEndpointAddressElement.IssuedTokenParametersEndpointAddressElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenParametersEndpointAddressElement.xml
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Binding*
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  isExternal: false
  name: Binding
  nameWithType: IssuedTokenParametersEndpointAddressElement.Binding
  fullName: IssuedTokenParametersEndpointAddressElement.Binding
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenParametersEndpointAddressElement.xml
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration*
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  isExternal: false
  name: BindingConfiguration
  nameWithType: IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  fullName: IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenParametersEndpointAddressElement.xml
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Properties*
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  isExternal: false
  name: Properties
  nameWithType: IssuedTokenParametersEndpointAddressElement.Properties
  fullName: IssuedTokenParametersEndpointAddressElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/IssuedTokenParametersEndpointAddressElement.xml
