### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.DeploymentSection
  commentId: T:System.Web.Configuration.DeploymentSection
  id: DeploymentSection
  children:
  - System.Web.Configuration.DeploymentSection.#ctor
  - System.Web.Configuration.DeploymentSection.Properties
  - System.Web.Configuration.DeploymentSection.Retail
  langs:
  - csharp
  name: DeploymentSection
  nameWithType: DeploymentSection
  fullName: System.Web.Configuration.DeploymentSection
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Defines a configuration setting that is typically used on a production server to override application-level settings that are appropriate only on development computers.
  syntax:
    content: 'public sealed class DeploymentSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/DeploymentSection.xml
- uid: System.Web.Configuration.DeploymentSection.#ctor
  commentId: M:System.Web.Configuration.DeploymentSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.DeploymentSection
  langs:
  - csharp
  name: DeploymentSection()
  nameWithType: DeploymentSection.DeploymentSection()
  fullName: DeploymentSection.DeploymentSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Configuration.DeploymentSection"></xref> class.
  remarks: This constructor is called by the ASP.NET configuration system. You obtain an instance of the <xref:System.Web.Configuration.DeploymentSection> class by using the <xref:System.Configuration.Configuration.GetSection%2A> method.
  syntax:
    content: public DeploymentSection ();
    parameters: []
  overload: System.Web.Configuration.DeploymentSection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/DeploymentSection.xml
- uid: System.Web.Configuration.DeploymentSection.Properties
  commentId: P:System.Web.Configuration.DeploymentSection.Properties
  id: Properties
  parent: System.Web.Configuration.DeploymentSection
  langs:
  - csharp
  name: Properties
  nameWithType: DeploymentSection.Properties
  fullName: DeploymentSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.DeploymentSection.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/DeploymentSection.xml
- uid: System.Web.Configuration.DeploymentSection.Retail
  commentId: P:System.Web.Configuration.DeploymentSection.Retail
  id: Retail
  parent: System.Web.Configuration.DeploymentSection
  langs:
  - csharp
  name: Retail
  nameWithType: DeploymentSection.Retail
  fullName: DeploymentSection.Retail
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets or sets a value that specifies whether Web applications on the computer are deployed in `retail` mode.
  remarks: "When <xref:System.Web.Configuration.DeploymentSection.Retail%2A> is `true`, ASP.NET disables trace output, disables debug capabilities, and disables detailed system-generated error messages for remote users. For applications that have a `customErrors` element in the application Web.config file, the `mode` attribute is forced to `On`. These settings override any settings that are made in application Web.config files.  \n  \n> [!NOTE]\n>  When you use the `retail` setting, you should continue to set the `debug` attribute to `false` in application Web.config files that are deployed to the server. The `debug` setting disables request execution timeout, and this is not overridden by the `retail` setting. For more information, see. [Most Common ASP.NET Support issues - Reporting from deep inside Microsoft Developer Support](http://www.hanselman.com/blog/MostCommonASPNETSupportIssuesReportingFromDeepInsideMicrosoftDeveloperSupport.aspx) on Scott Hanselman's blog."
  example:
  - "The following configuration file example shows how to set this property to `true` in the machine.config file. The machine.config file is located in this folder:  \n  \n `%windir%\\Microsoft.NET\\Framework\\<frameworkversion>\\Config`  \n  \n```  \n<system.web>  \n  <deployment   \n    retail=\"true\" />  \n</system.web>  \n```"
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("retail", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public bool Retail { get; set; }
    return:
      type: System.Boolean
      description: '`true` if Web applications are deployed in `retail` mode; otherwise, `false`. The default is `false`.'
  overload: System.Web.Configuration.DeploymentSection.Retail*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/DeploymentSection.xml
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.DeploymentSection.#ctor
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: DeploymentSection()
  nameWithType: DeploymentSection.DeploymentSection()
  fullName: DeploymentSection.DeploymentSection()
- uid: System.Web.Configuration.DeploymentSection.Properties
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: Properties
  nameWithType: DeploymentSection.Properties
  fullName: DeploymentSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.DeploymentSection.Retail
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: Retail
  nameWithType: DeploymentSection.Retail
  fullName: DeploymentSection.Retail
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.DeploymentSection.#ctor*
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: DeploymentSection
  nameWithType: DeploymentSection.DeploymentSection
  fullName: DeploymentSection.DeploymentSection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/DeploymentSection.xml
- uid: System.Web.Configuration.DeploymentSection.Properties*
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: Properties
  nameWithType: DeploymentSection.Properties
  fullName: DeploymentSection.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/DeploymentSection.xml
- uid: System.Web.Configuration.DeploymentSection.Retail*
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: Retail
  nameWithType: DeploymentSection.Retail
  fullName: DeploymentSection.Retail
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/DeploymentSection.xml
