### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.ConnectionManagementSection
  commentId: T:System.Net.Configuration.ConnectionManagementSection
  id: ConnectionManagementSection
  children:
  - System.Net.Configuration.ConnectionManagementSection.#ctor
  - System.Net.Configuration.ConnectionManagementSection.ConnectionManagement
  - System.Net.Configuration.ConnectionManagementSection.Properties
  langs:
  - csharp
  name: ConnectionManagementSection
  nameWithType: ConnectionManagementSection
  fullName: System.Net.Configuration.ConnectionManagementSection
  type: Class
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Represents the configuration section for connection management. This class cannot be inherited.
  remarks: "This class corresponds to the [\\&lt;connectionManagement\\&gt; Element (Network Settings)](~/docs/framework/configure-apps/file-schema/network/connectionmanagement-element-network-settings.md) configuration element.  \n  \n This class is used to access information about the number of simultaneous connections allowed between the local computer and a remote computer.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class ConnectionManagementSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ConnectionManagementSection.xml
  ms.author: bobdel
  manager: markl
- uid: System.Net.Configuration.ConnectionManagementSection.#ctor
  commentId: M:System.Net.Configuration.ConnectionManagementSection.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.ConnectionManagementSection
  langs:
  - csharp
  name: ConnectionManagementSection()
  nameWithType: ConnectionManagementSection.ConnectionManagementSection()
  fullName: System.Net.Configuration.ConnectionManagementSection.ConnectionManagementSection()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Initializes a new instance of the <xref href="System.Net.Configuration.ConnectionManagementSection"></xref> class.
  syntax:
    content: public ConnectionManagementSection ();
    parameters: []
  overload: System.Net.Configuration.ConnectionManagementSection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ConnectionManagementSection.xml
  ms.author: bobdel
  manager: markl
- uid: System.Net.Configuration.ConnectionManagementSection.ConnectionManagement
  commentId: P:System.Net.Configuration.ConnectionManagementSection.ConnectionManagement
  id: ConnectionManagement
  parent: System.Net.Configuration.ConnectionManagementSection
  langs:
  - csharp
  name: ConnectionManagement
  nameWithType: ConnectionManagementSection.ConnectionManagement
  fullName: System.Net.Configuration.ConnectionManagementSection.ConnectionManagement
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: Gets the collection of connection management objects in the section.
  remarks: The <xref:System.Net.Configuration.ConnectionManagementElementCollection> returned by this property contains one <xref:System.Net.Configuration.ConnectionManagementElement> for each `connectionManagement` element in the configuration file.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("", Options=System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection)]

      public System.Net.Configuration.ConnectionManagementElementCollection ConnectionManagement { get; }
    return:
      type: System.Net.Configuration.ConnectionManagementElementCollection
      description: A <xref href="System.Net.Configuration.ConnectionManagementElementCollection"></xref> that contains the connection management information for the local computer.
  overload: System.Net.Configuration.ConnectionManagementSection.ConnectionManagement*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ConnectionManagementSection.xml
  ms.author: bobdel
  manager: markl
- uid: System.Net.Configuration.ConnectionManagementSection.Properties
  commentId: P:System.Net.Configuration.ConnectionManagementSection.Properties
  id: Properties
  parent: System.Net.Configuration.ConnectionManagementSection
  langs:
  - csharp
  name: Properties
  nameWithType: ConnectionManagementSection.Properties
  fullName: System.Net.Configuration.ConnectionManagementSection.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Net.Configuration.ConnectionManagementSection.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ConnectionManagementSection.xml
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.Net.Configuration.ConnectionManagementSection.#ctor
  parent: System.Net.Configuration.ConnectionManagementSection
  isExternal: false
  name: ConnectionManagementSection()
  nameWithType: ConnectionManagementSection.ConnectionManagementSection()
  fullName: System.Net.Configuration.ConnectionManagementSection.ConnectionManagementSection()
- uid: System.Net.Configuration.ConnectionManagementSection.ConnectionManagement
  parent: System.Net.Configuration.ConnectionManagementSection
  isExternal: false
  name: ConnectionManagement
  nameWithType: ConnectionManagementSection.ConnectionManagement
  fullName: System.Net.Configuration.ConnectionManagementSection.ConnectionManagement
- uid: System.Net.Configuration.ConnectionManagementElementCollection
  parent: System.Net.Configuration
  isExternal: false
  name: ConnectionManagementElementCollection
  nameWithType: ConnectionManagementElementCollection
  fullName: System.Net.Configuration.ConnectionManagementElementCollection
- uid: System.Net.Configuration.ConnectionManagementSection.Properties
  parent: System.Net.Configuration.ConnectionManagementSection
  isExternal: false
  name: Properties
  nameWithType: ConnectionManagementSection.Properties
  fullName: System.Net.Configuration.ConnectionManagementSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.ConnectionManagementSection.#ctor*
  parent: System.Net.Configuration.ConnectionManagementSection
  isExternal: false
  name: ConnectionManagementSection
  nameWithType: ConnectionManagementSection.ConnectionManagementSection
  fullName: System.Net.Configuration.ConnectionManagementSection.ConnectionManagementSection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ConnectionManagementSection.xml
- uid: System.Net.Configuration.ConnectionManagementSection.ConnectionManagement*
  parent: System.Net.Configuration.ConnectionManagementSection
  isExternal: false
  name: ConnectionManagement
  nameWithType: ConnectionManagementSection.ConnectionManagement
  fullName: System.Net.Configuration.ConnectionManagementSection.ConnectionManagement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ConnectionManagementSection.xml
- uid: System.Net.Configuration.ConnectionManagementSection.Properties*
  parent: System.Net.Configuration.ConnectionManagementSection
  isExternal: false
  name: Properties
  nameWithType: ConnectionManagementSection.Properties
  fullName: System.Net.Configuration.ConnectionManagementSection.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Net.Configuration/ConnectionManagementSection.xml
