### YamlMime:ManagedReference
items:
- uid: System.Data.Services.Configuration.DataServicesFeaturesSection
  commentId: T:System.Data.Services.Configuration.DataServicesFeaturesSection
  id: DataServicesFeaturesSection
  children:
  - System.Data.Services.Configuration.DataServicesFeaturesSection.#ctor
  - System.Data.Services.Configuration.DataServicesFeaturesSection.ReplaceFunction
  langs:
  - csharp
  name: DataServicesFeaturesSection
  nameWithType: DataServicesFeaturesSection
  fullName: System.Data.Services.Configuration.DataServicesFeaturesSection
  type: Class
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services.Configuration
  summary: A configuration section that allows you to configure WCF data services features.
  syntax:
    content: 'public sealed class DataServicesFeaturesSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Configuration/DataServicesFeaturesSection.xml
- uid: System.Data.Services.Configuration.DataServicesFeaturesSection.#ctor
  commentId: M:System.Data.Services.Configuration.DataServicesFeaturesSection.#ctor
  id: '#ctor'
  parent: System.Data.Services.Configuration.DataServicesFeaturesSection
  langs:
  - csharp
  name: DataServicesFeaturesSection()
  nameWithType: DataServicesFeaturesSection.DataServicesFeaturesSection()
  fullName: DataServicesFeaturesSection.DataServicesFeaturesSection()
  type: Constructor
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services.Configuration
  summary: Initializes a new instance of the <xref href="System.Data.Services.Configuration.DataServicesFeaturesSection"></xref> class.
  syntax:
    content: public DataServicesFeaturesSection ();
    parameters: []
  overload: System.Data.Services.Configuration.DataServicesFeaturesSection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Configuration/DataServicesFeaturesSection.xml
- uid: System.Data.Services.Configuration.DataServicesFeaturesSection.ReplaceFunction
  commentId: P:System.Data.Services.Configuration.DataServicesFeaturesSection.ReplaceFunction
  id: ReplaceFunction
  parent: System.Data.Services.Configuration.DataServicesFeaturesSection
  langs:
  - csharp
  name: ReplaceFunction
  nameWithType: DataServicesFeaturesSection.ReplaceFunction
  fullName: DataServicesFeaturesSection.ReplaceFunction
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services.Configuration
  summary: Gets or sets a DataServiceReplaceFunctionFeature instance.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("replaceFunction")]

      public System.Data.Services.Configuration.DataServicesReplaceFunctionFeature ReplaceFunction { get; set; }
    return:
      type: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature
      description: A DataServiceReplaceFunctionFeature instance.
  overload: System.Data.Services.Configuration.DataServicesFeaturesSection.ReplaceFunction*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Configuration/DataServicesFeaturesSection.xml
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.Data.Services.Configuration.DataServicesFeaturesSection.#ctor
  parent: System.Data.Services.Configuration.DataServicesFeaturesSection
  isExternal: false
  name: DataServicesFeaturesSection()
  nameWithType: DataServicesFeaturesSection.DataServicesFeaturesSection()
  fullName: DataServicesFeaturesSection.DataServicesFeaturesSection()
- uid: System.Data.Services.Configuration.DataServicesFeaturesSection.ReplaceFunction
  parent: System.Data.Services.Configuration.DataServicesFeaturesSection
  isExternal: false
  name: ReplaceFunction
  nameWithType: DataServicesFeaturesSection.ReplaceFunction
  fullName: DataServicesFeaturesSection.ReplaceFunction
- uid: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature
  parent: System.Data.Services.Configuration
  isExternal: false
  name: DataServicesReplaceFunctionFeature
  nameWithType: DataServicesReplaceFunctionFeature
  fullName: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature
- uid: System.Data.Services.Configuration.DataServicesFeaturesSection.#ctor*
  parent: System.Data.Services.Configuration.DataServicesFeaturesSection
  isExternal: false
  name: DataServicesFeaturesSection
  nameWithType: DataServicesFeaturesSection.DataServicesFeaturesSection
  fullName: DataServicesFeaturesSection.DataServicesFeaturesSection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Configuration/DataServicesFeaturesSection.xml
- uid: System.Data.Services.Configuration.DataServicesFeaturesSection.ReplaceFunction*
  parent: System.Data.Services.Configuration.DataServicesFeaturesSection
  isExternal: false
  name: ReplaceFunction
  nameWithType: DataServicesFeaturesSection.ReplaceFunction
  fullName: DataServicesFeaturesSection.ReplaceFunction
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Configuration/DataServicesFeaturesSection.xml
