### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ClientTargetSection
  commentId: T:System.Web.Configuration.ClientTargetSection
  id: ClientTargetSection
  children:
  - System.Web.Configuration.ClientTargetSection.#ctor
  - System.Web.Configuration.ClientTargetSection.ClientTargets
  - System.Web.Configuration.ClientTargetSection.Properties
  langs:
  - csharp
  name: ClientTargetSection
  nameWithType: ClientTargetSection
  fullName: System.Web.Configuration.ClientTargetSection
  type: Class
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Configures the `clientTarget` section. This class cannot be inherited.
  remarks: "The <xref:System.Web.Configuration.ClientTargetSection> class provides a way to programmatically access and modify the `clientTarget` section of the configuration file. It belongs to a group that includes the <xref:System.Web.Configuration.ClientTargetCollection> class and the <xref:System.Web.Configuration.ClientTarget> class.  \n  \n The <xref:System.Web.Configuration.ClientTargetSection> class contains <xref:System.Web.Configuration.ClientTarget> objects that define pairs of aliases and associated target user agents for which ASP.NET server controls should render content."
  example:
  - "This section provides two code examples. The first displays a declarative representation of the <xref:System.Web.Configuration.ClientTargetSection> class and also demonstrates how to declaratively specify values for several properties of the <xref:System.Web.Configuration.ClientTarget> class. The second shows how to obtain the <xref:System.Web.Configuration.ClientTargetCollection> object from the configuration file. You use this object to access the <xref:System.Web.Configuration.ClientTarget> objects it contains.  \n  \n The following code example shows how to declaratively specify values for several properties of the <xref:System.Web.Configuration.ClientTarget> class.  \n  \n```  \n<clientTarget>  \n  <add alias=  \n    \"uplevel\" userAgent=\"Mozilla/5.0 (compatible;MSIE 6.0;Windows NT 5.1)\"/>  \n  <add alias=\"downlevel\" userAgent=\"Generic Downlevel\"/>  \n</clientTarget>  \n```  \n  \n The following code example shows how to obtain the <xref:System.Web.Configuration.ClientTargetCollection> object from the configuration file  \n  \n [!code-csharp[System.Web.Configuration.ClientTarget#1](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.ClientTarget/CS/clienttarget.cs#1)]\n [!code-vb[System.Web.Configuration.ClientTarget#1](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.ClientTarget/VB/clienttarget.vb#1)]"
  syntax:
    content: 'public sealed class ClientTargetSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ClientTargetSection.xml
- uid: System.Web.Configuration.ClientTargetSection.#ctor
  commentId: M:System.Web.Configuration.ClientTargetSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ClientTargetSection
  langs:
  - csharp
  name: ClientTargetSection()
  nameWithType: ClientTargetSection.ClientTargetSection()
  fullName: ClientTargetSection.ClientTargetSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Initializes a new instance of the <xref href="System.Web.Configuration.ClientTargetSection"></xref> class.
  remarks: This constructor is called by the ASP.NET configuration system and is not intended to be used directly from your code. You can obtain an instance of the <xref:System.Web.Configuration.ClientTargetSection> class by using the <xref:System.Configuration.Configuration.GetSection%2A> method.
  syntax:
    content: public ClientTargetSection ();
    parameters: []
  overload: System.Web.Configuration.ClientTargetSection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ClientTargetSection.xml
- uid: System.Web.Configuration.ClientTargetSection.ClientTargets
  commentId: P:System.Web.Configuration.ClientTargetSection.ClientTargets
  id: ClientTargets
  parent: System.Web.Configuration.ClientTargetSection
  langs:
  - csharp
  name: ClientTargets
  nameWithType: ClientTargetSection.ClientTargets
  fullName: ClientTargetSection.ClientTargets
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: Gets the collection of <xref href="System.Web.Configuration.ClientTarget"></xref> objects.
  remarks: Each <xref:System.Web.Configuration.ClientTarget> object contains two properties identifying a client browser, also called the user agent. One property is the alias associated with the client browser that is identified by the other property. ASP.NET uses this information to render server controls on a page.
  example:
  - "The following code example shows how to get the <xref:System.Web.Configuration.ClientTargetSection.ClientTargets%2A> collection.  \n  \n [!code-csharp[System.Web.Configuration.ClientTarget#2](~/samples/snippets/csharp/VS_Snippets_WebNet/System.Web.Configuration.ClientTarget/CS/clienttarget.cs#2)]\n [!code-vb[System.Web.Configuration.ClientTarget#2](~/samples/snippets/visualbasic/VS_Snippets_WebNet/System.Web.Configuration.ClientTarget/VB/clienttarget.vb#2)]"
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("", IsDefaultCollection=true, IsRequired=true)]

      public System.Web.Configuration.ClientTargetCollection ClientTargets { get; }
    return:
      type: System.Web.Configuration.ClientTargetCollection
      description: A <xref href="System.Web.Configuration.ClientTargetCollection"></xref> that contains the <xref href="System.Web.Configuration.ClientTarget"></xref> objects.
  overload: System.Web.Configuration.ClientTargetSection.ClientTargets*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ClientTargetSection.xml
- uid: System.Web.Configuration.ClientTargetSection.Properties
  commentId: P:System.Web.Configuration.ClientTargetSection.Properties
  id: Properties
  parent: System.Web.Configuration.ClientTargetSection
  langs:
  - csharp
  name: Properties
  nameWithType: ClientTargetSection.Properties
  fullName: ClientTargetSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Web.Configuration.ClientTargetSection.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ClientTargetSection.xml
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.ClientTargetSection.#ctor
  parent: System.Web.Configuration.ClientTargetSection
  isExternal: false
  name: ClientTargetSection()
  nameWithType: ClientTargetSection.ClientTargetSection()
  fullName: ClientTargetSection.ClientTargetSection()
- uid: System.Web.Configuration.ClientTargetSection.ClientTargets
  parent: System.Web.Configuration.ClientTargetSection
  isExternal: false
  name: ClientTargets
  nameWithType: ClientTargetSection.ClientTargets
  fullName: ClientTargetSection.ClientTargets
- uid: System.Web.Configuration.ClientTargetCollection
  parent: System.Web.Configuration
  isExternal: false
  name: ClientTargetCollection
  nameWithType: ClientTargetCollection
  fullName: System.Web.Configuration.ClientTargetCollection
- uid: System.Web.Configuration.ClientTargetSection.Properties
  parent: System.Web.Configuration.ClientTargetSection
  isExternal: false
  name: Properties
  nameWithType: ClientTargetSection.Properties
  fullName: ClientTargetSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ClientTargetSection.#ctor*
  parent: System.Web.Configuration.ClientTargetSection
  isExternal: false
  name: ClientTargetSection
  nameWithType: ClientTargetSection.ClientTargetSection
  fullName: ClientTargetSection.ClientTargetSection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ClientTargetSection.xml
- uid: System.Web.Configuration.ClientTargetSection.ClientTargets*
  parent: System.Web.Configuration.ClientTargetSection
  isExternal: false
  name: ClientTargets
  nameWithType: ClientTargetSection.ClientTargets
  fullName: ClientTargetSection.ClientTargets
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ClientTargetSection.xml
- uid: System.Web.Configuration.ClientTargetSection.Properties*
  parent: System.Web.Configuration.ClientTargetSection
  isExternal: false
  name: Properties
  nameWithType: ClientTargetSection.Properties
  fullName: ClientTargetSection.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Configuration/ClientTargetSection.xml
