### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  commentId: T:System.ServiceModel.Configuration.AddressHeaderCollectionElement
  id: AddressHeaderCollectionElement
  children:
  - System.ServiceModel.Configuration.AddressHeaderCollectionElement.#ctor
  - System.ServiceModel.Configuration.AddressHeaderCollectionElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.ServiceModel.Configuration.AddressHeaderCollectionElement.Headers
  - System.ServiceModel.Configuration.AddressHeaderCollectionElement.Properties
  - System.ServiceModel.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  langs:
  - csharp
  name: AddressHeaderCollectionElement
  nameWithType: AddressHeaderCollectionElement
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents the configuration element that contains a collection of address headers. This class cannot be inherited.
  syntax:
    content: 'public sealed class AddressHeaderCollectionElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/AddressHeaderCollectionElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.#ctor
  commentId: M:System.ServiceModel.Configuration.AddressHeaderCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  langs:
  - csharp
  name: AddressHeaderCollectionElement()
  nameWithType: AddressHeaderCollectionElement.AddressHeaderCollectionElement()
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.AddressHeaderCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.AddressHeaderCollectionElement"></xref> class.
  syntax:
    content: public AddressHeaderCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.AddressHeaderCollectionElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/AddressHeaderCollectionElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  commentId: M:System.ServiceModel.Configuration.AddressHeaderCollectionElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  id: DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  langs:
  - csharp
  name: DeserializeElement(XmlReader, Boolean)
  nameWithType: AddressHeaderCollectionElement.DeserializeElement(XmlReader, Boolean)
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.DeserializeElement(XmlReader, Boolean)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override void DeserializeElement (System.Xml.XmlReader reader, bool serializeCollectionKey);
    parameters:
    - id: reader
      type: System.Xml.XmlReader
      description: To be added.
    - id: serializeCollectionKey
      type: System.Boolean
      description: To be added.
  overload: System.ServiceModel.Configuration.AddressHeaderCollectionElement.DeserializeElement*
  exceptions: []
  attributes: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/AddressHeaderCollectionElement.xml
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Headers
  commentId: P:System.ServiceModel.Configuration.AddressHeaderCollectionElement.Headers
  id: Headers
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  langs:
  - csharp
  name: Headers
  nameWithType: AddressHeaderCollectionElement.Headers
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Headers
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets a collection of address headers.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("headers", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.ServiceModel.Channels.AddressHeaderCollection Headers { get; set; }
    return:
      type: System.ServiceModel.Channels.AddressHeaderCollection
      description: A collection of address headers.
  overload: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Headers*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/AddressHeaderCollectionElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Properties
  commentId: P:System.ServiceModel.Configuration.AddressHeaderCollectionElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  langs:
  - csharp
  name: Properties
  nameWithType: AddressHeaderCollectionElement.Properties
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/AddressHeaderCollectionElement.xml
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  commentId: M:System.ServiceModel.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  id: SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  langs:
  - csharp
  name: SerializeToXmlElement(XmlWriter, String)
  nameWithType: AddressHeaderCollectionElement.SerializeToXmlElement(XmlWriter, String)
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement(XmlWriter, String)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override bool SerializeToXmlElement (System.Xml.XmlWriter writer, string elementName);
    parameters:
    - id: writer
      type: System.Xml.XmlWriter
      description: To be added.
    - id: elementName
      type: System.String
      description: To be added.
    return:
      type: System.Boolean
      description: To be added.
  overload: System.ServiceModel.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/AddressHeaderCollectionElement.xml
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: AddressHeaderCollectionElement()
  nameWithType: AddressHeaderCollectionElement.AddressHeaderCollectionElement()
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.AddressHeaderCollectionElement()
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: DeserializeElement(XmlReader, Boolean)
  nameWithType: AddressHeaderCollectionElement.DeserializeElement(XmlReader, Boolean)
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.DeserializeElement(XmlReader, Boolean)
- uid: System.Xml.XmlReader
  parent: System.Xml
  isExternal: false
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Headers
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: Headers
  nameWithType: AddressHeaderCollectionElement.Headers
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Headers
- uid: System.ServiceModel.Channels.AddressHeaderCollection
  parent: System.ServiceModel.Channels
  isExternal: false
  name: AddressHeaderCollection
  nameWithType: AddressHeaderCollection
  fullName: System.ServiceModel.Channels.AddressHeaderCollection
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Properties
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: Properties
  nameWithType: AddressHeaderCollectionElement.Properties
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: SerializeToXmlElement(XmlWriter, String)
  nameWithType: AddressHeaderCollectionElement.SerializeToXmlElement(XmlWriter, String)
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement(XmlWriter, String)
- uid: System.Xml.XmlWriter
  parent: System.Xml
  isExternal: false
  name: XmlWriter
  nameWithType: XmlWriter
  fullName: System.Xml.XmlWriter
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: AddressHeaderCollectionElement
  nameWithType: AddressHeaderCollectionElement.AddressHeaderCollectionElement
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.AddressHeaderCollectionElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/AddressHeaderCollectionElement.xml
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.DeserializeElement*
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: DeserializeElement
  nameWithType: AddressHeaderCollectionElement.DeserializeElement
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.DeserializeElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/AddressHeaderCollectionElement.xml
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Headers*
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: Headers
  nameWithType: AddressHeaderCollectionElement.Headers
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Headers
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/AddressHeaderCollectionElement.xml
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Properties*
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: Properties
  nameWithType: AddressHeaderCollectionElement.Properties
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/AddressHeaderCollectionElement.xml
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement*
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: SerializeToXmlElement
  nameWithType: AddressHeaderCollectionElement.SerializeToXmlElement
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/AddressHeaderCollectionElement.xml
