### YamlMime:ManagedReference
items:
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection
  commentId: T:System.Runtime.Caching.Configuration.MemoryCacheSection
  id: MemoryCacheSection
  children:
  - System.Runtime.Caching.Configuration.MemoryCacheSection.#ctor
  - System.Runtime.Caching.Configuration.MemoryCacheSection.NamedCaches
  - System.Runtime.Caching.Configuration.MemoryCacheSection.Properties
  langs:
  - csharp
  name: MemoryCacheSection
  nameWithType: MemoryCacheSection
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection
  type: Class
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  summary: Defines a configuration section for a cache based on the <xref href="System.Runtime.Caching.MemoryCache"></xref> class. This class cannot be inherited.
  remarks: "The <xref:System.Runtime.Caching.Configuration.MemoryCacheSection> class defines the settings that are available in the `memoryCache` section of a configuration file. In this section, the `namedCaches` element is used to configure a default instance of the cache and to configure any additional named instances.  \n  \n For more information, see [\\&lt;memoryCache\\&gt; Element (Cache Settings)](~/docs/framework/configure-apps/file-schema/runtime/memorycache-element-cache-settings.md)."
  syntax:
    content: 'public sealed class MemoryCacheSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Caching.Configuration/MemoryCacheSection.xml
  author: Erikre
  ms.author: erikre
  manager: ghogen
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.#ctor
  commentId: M:System.Runtime.Caching.Configuration.MemoryCacheSection.#ctor
  id: '#ctor'
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  langs:
  - csharp
  name: MemoryCacheSection()
  nameWithType: MemoryCacheSection.MemoryCacheSection()
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection.MemoryCacheSection()
  type: Constructor
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  summary: Initializes a new instance of the <xref href="System.Runtime.Caching.Configuration.MemoryCacheSection"></xref> class.
  syntax:
    content: public MemoryCacheSection ();
    parameters: []
  overload: System.Runtime.Caching.Configuration.MemoryCacheSection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Caching.Configuration/MemoryCacheSection.xml
  author: Erikre
  ms.author: erikre
  manager: ghogen
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.NamedCaches
  commentId: P:System.Runtime.Caching.Configuration.MemoryCacheSection.NamedCaches
  id: NamedCaches
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  langs:
  - csharp
  name: NamedCaches
  nameWithType: MemoryCacheSection.NamedCaches
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection.NamedCaches
  type: Property
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  summary: Gets the collection of configuration settings for the named <xref href="System.Runtime.Caching.MemoryCache"></xref> instances.
  remarks: The <xref:System.Runtime.Caching.Configuration.MemoryCacheSection.NamedCaches%2A> property references the collection of configuration settings from one or more `namedCaches` elements of the configuration file. For more information about configuration options that are related to this property, see [\&lt;namedCaches\&gt; Element (Cache Settings)](~/docs/framework/configure-apps/file-schema/runtime/namedcaches-element-cache-settings.md).
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("namedCaches")]

      public System.Runtime.Caching.Configuration.MemoryCacheSettingsCollection NamedCaches { get; }
    return:
      type: System.Runtime.Caching.Configuration.MemoryCacheSettingsCollection
      description: A collection of settings for each named cache.
  overload: System.Runtime.Caching.Configuration.MemoryCacheSection.NamedCaches*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Caching.Configuration/MemoryCacheSection.xml
  author: Erikre
  ms.author: erikre
  manager: ghogen
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.Properties
  commentId: P:System.Runtime.Caching.Configuration.MemoryCacheSection.Properties
  id: Properties
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  langs:
  - csharp
  name: Properties
  nameWithType: MemoryCacheSection.Properties
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection.Properties
  type: Property
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Runtime.Caching.Configuration.MemoryCacheSection.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Caching.Configuration/MemoryCacheSection.xml
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.#ctor
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  isExternal: false
  name: MemoryCacheSection()
  nameWithType: MemoryCacheSection.MemoryCacheSection()
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection.MemoryCacheSection()
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.NamedCaches
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  isExternal: false
  name: NamedCaches
  nameWithType: MemoryCacheSection.NamedCaches
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection.NamedCaches
- uid: System.Runtime.Caching.Configuration.MemoryCacheSettingsCollection
  parent: System.Runtime.Caching.Configuration
  isExternal: false
  name: MemoryCacheSettingsCollection
  nameWithType: MemoryCacheSettingsCollection
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSettingsCollection
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.Properties
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  isExternal: false
  name: Properties
  nameWithType: MemoryCacheSection.Properties
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.#ctor*
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  isExternal: false
  name: MemoryCacheSection
  nameWithType: MemoryCacheSection.MemoryCacheSection
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection.MemoryCacheSection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Caching.Configuration/MemoryCacheSection.xml
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.NamedCaches*
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  isExternal: false
  name: NamedCaches
  nameWithType: MemoryCacheSection.NamedCaches
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection.NamedCaches
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Caching.Configuration/MemoryCacheSection.xml
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.Properties*
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  isExternal: false
  name: Properties
  nameWithType: MemoryCacheSection.Properties
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Caching.Configuration/MemoryCacheSection.xml
