### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.PolicyImporterElement
  commentId: T:System.ServiceModel.Configuration.PolicyImporterElement
  id: PolicyImporterElement
  children:
  - System.ServiceModel.Configuration.PolicyImporterElement.#ctor
  - System.ServiceModel.Configuration.PolicyImporterElement.#ctor(System.String)
  - System.ServiceModel.Configuration.PolicyImporterElement.#ctor(System.Type)
  - System.ServiceModel.Configuration.PolicyImporterElement.Properties
  - System.ServiceModel.Configuration.PolicyImporterElement.Type
  langs:
  - csharp
  name: PolicyImporterElement
  nameWithType: PolicyImporterElement
  fullName: System.ServiceModel.Configuration.PolicyImporterElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents the configuration element that specifies the import of custom policy assertions about bindings. This class cannot be inherited.
  remarks: This configuration section specifies the settings for searching custom policy assertions about binding features, as well as attaching a custom binding element that implements the features the assertion requires.
  syntax:
    content: 'public sealed class PolicyImporterElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PolicyImporterElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.PolicyImporterElement.#ctor
  commentId: M:System.ServiceModel.Configuration.PolicyImporterElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  langs:
  - csharp
  name: PolicyImporterElement()
  nameWithType: PolicyImporterElement.PolicyImporterElement()
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.PolicyImporterElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.PolicyImporterElement"></xref> class.
  syntax:
    content: public PolicyImporterElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.PolicyImporterElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PolicyImporterElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.PolicyImporterElement.#ctor(System.String)
  commentId: M:System.ServiceModel.Configuration.PolicyImporterElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  langs:
  - csharp
  name: PolicyImporterElement(String)
  nameWithType: PolicyImporterElement.PolicyImporterElement(String)
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.PolicyImporterElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.PolicyImporterElement"></xref> class with a specific policy type.
  syntax:
    content: public PolicyImporterElement (string type);
    parameters:
    - id: type
      type: System.String
      description: The type of policy.
  overload: System.ServiceModel.Configuration.PolicyImporterElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PolicyImporterElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.PolicyImporterElement.#ctor(System.Type)
  commentId: M:System.ServiceModel.Configuration.PolicyImporterElement.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  langs:
  - csharp
  name: PolicyImporterElement(Type)
  nameWithType: PolicyImporterElement.PolicyImporterElement(Type)
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.PolicyImporterElement(Type)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.PolicyImporterElement"></xref> class with a specific policy type.
  syntax:
    content: public PolicyImporterElement (Type type);
    parameters:
    - id: type
      type: System.Type
      description: The type of policy.
  overload: System.ServiceModel.Configuration.PolicyImporterElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PolicyImporterElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.PolicyImporterElement.Properties
  commentId: P:System.ServiceModel.Configuration.PolicyImporterElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  langs:
  - csharp
  name: Properties
  nameWithType: PolicyImporterElement.Properties
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.PolicyImporterElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PolicyImporterElement.xml
- uid: System.ServiceModel.Configuration.PolicyImporterElement.Type
  commentId: P:System.ServiceModel.Configuration.PolicyImporterElement.Type
  id: Type
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  langs:
  - csharp
  name: Type
  nameWithType: PolicyImporterElement.Type
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.Type
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the type of this configuration element.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("type", Options=System.Configuration.ConfigurationPropertyOptions.IsRequired | System.Configuration.ConfigurationPropertyOptions.IsKey)]

      [System.Configuration.StringValidator(MinLength=1)]

      public string Type { get; set; }
    return:
      type: System.String
      description: The type of this configuration element.
  overload: System.ServiceModel.Configuration.PolicyImporterElement.Type*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  - type: System.Configuration.StringValidatorAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PolicyImporterElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.PolicyImporterElement.#ctor
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  isExternal: false
  name: PolicyImporterElement()
  nameWithType: PolicyImporterElement.PolicyImporterElement()
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.PolicyImporterElement()
- uid: System.ServiceModel.Configuration.PolicyImporterElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  isExternal: false
  name: PolicyImporterElement(String)
  nameWithType: PolicyImporterElement.PolicyImporterElement(String)
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.PolicyImporterElement(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.PolicyImporterElement.#ctor(System.Type)
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  isExternal: false
  name: PolicyImporterElement(Type)
  nameWithType: PolicyImporterElement.PolicyImporterElement(Type)
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.PolicyImporterElement(Type)
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.PolicyImporterElement.Properties
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  isExternal: false
  name: Properties
  nameWithType: PolicyImporterElement.Properties
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.PolicyImporterElement.Type
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  isExternal: false
  name: Type
  nameWithType: PolicyImporterElement.Type
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.Type
- uid: System.ServiceModel.Configuration.PolicyImporterElement.#ctor*
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  isExternal: false
  name: PolicyImporterElement
  nameWithType: PolicyImporterElement.PolicyImporterElement
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.PolicyImporterElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PolicyImporterElement.xml
- uid: System.ServiceModel.Configuration.PolicyImporterElement.Properties*
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  isExternal: false
  name: Properties
  nameWithType: PolicyImporterElement.Properties
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PolicyImporterElement.xml
- uid: System.ServiceModel.Configuration.PolicyImporterElement.Type*
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  isExternal: false
  name: Type
  nameWithType: PolicyImporterElement.Type
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.Type
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/PolicyImporterElement.xml
