### YamlMime:ManagedReference
items:
- uid: System.Configuration.ApplicationSettingsGroup
  commentId: T:System.Configuration.ApplicationSettingsGroup
  id: ApplicationSettingsGroup
  children:
  - System.Configuration.ApplicationSettingsGroup.#ctor
  langs:
  - csharp
  name: ApplicationSettingsGroup
  nameWithType: ApplicationSettingsGroup
  fullName: System.Configuration.ApplicationSettingsGroup
  type: Class
  assemblies:
  - System
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Represents a grouping of related application settings sections within a configuration file. This class cannot be inherited.
  syntax:
    content: 'public sealed class ApplicationSettingsGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ApplicationSettingsGroup.xml
- uid: System.Configuration.ApplicationSettingsGroup.#ctor
  commentId: M:System.Configuration.ApplicationSettingsGroup.#ctor
  id: '#ctor'
  parent: System.Configuration.ApplicationSettingsGroup
  langs:
  - csharp
  name: ApplicationSettingsGroup()
  nameWithType: ApplicationSettingsGroup.ApplicationSettingsGroup()
  fullName: ApplicationSettingsGroup.ApplicationSettingsGroup()
  type: Constructor
  assemblies:
  - System
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.ApplicationSettingsGroup"></xref> class.
  syntax:
    content: public ApplicationSettingsGroup ();
    parameters: []
  overload: System.Configuration.ApplicationSettingsGroup.#ctor*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ApplicationSettingsGroup.xml
references:
- uid: System.Configuration.ConfigurationSectionGroup
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSectionGroup
  nameWithType: ConfigurationSectionGroup
  fullName: System.Configuration.ConfigurationSectionGroup
- uid: System.Configuration.ApplicationSettingsGroup.#ctor
  parent: System.Configuration.ApplicationSettingsGroup
  isExternal: false
  name: ApplicationSettingsGroup()
  nameWithType: ApplicationSettingsGroup.ApplicationSettingsGroup()
  fullName: ApplicationSettingsGroup.ApplicationSettingsGroup()
- uid: System.Configuration.ApplicationSettingsGroup.#ctor*
  parent: System.Configuration.ApplicationSettingsGroup
  isExternal: false
  name: ApplicationSettingsGroup
  nameWithType: ApplicationSettingsGroup.ApplicationSettingsGroup
  fullName: ApplicationSettingsGroup.ApplicationSettingsGroup
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ApplicationSettingsGroup.xml
