### YamlMime:ManagedReference
items:
- uid: System.Configuration.Provider.ProviderException
  commentId: T:System.Configuration.Provider.ProviderException
  id: ProviderException
  children:
  - System.Configuration.Provider.ProviderException.#ctor
  - System.Configuration.Provider.ProviderException.#ctor(System.String)
  - System.Configuration.Provider.ProviderException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.Provider.ProviderException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ProviderException
  nameWithType: ProviderException
  fullName: System.Configuration.Provider.ProviderException
  type: Class
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration.Provider
  summary: The exception that is thrown when a configuration provider error has occurred. This exception class is also used by providers to throw exceptions when internal errors occur within the provider that do not map to other pre-existing exception classes.
  remarks: The <xref:System.Configuration.Provider.ProviderException> is thrown when any error occurs while loading a configuration provider.
  syntax:
    content: 'public class ProviderException : Exception'
  inheritance:
  - System.Object
  - System.Exception
  implements: []
  inheritedMembers:
  - System.Exception.Data
  - System.Exception.GetBaseException
  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Exception.GetType
  - System.Exception.HelpLink
  - System.Exception.HResult
  - System.Exception.InnerException
  - System.Exception.Message
  - System.Exception.SerializeObjectState
  - System.Exception.Source
  - System.Exception.StackTrace
  - System.Exception.TargetSite
  - System.Exception.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Provider/ProviderException.xml
- uid: System.Configuration.Provider.ProviderException.#ctor
  commentId: M:System.Configuration.Provider.ProviderException.#ctor
  id: '#ctor'
  parent: System.Configuration.Provider.ProviderException
  langs:
  - csharp
  name: ProviderException()
  nameWithType: ProviderException.ProviderException()
  fullName: ProviderException.ProviderException()
  type: Constructor
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration.Provider
  summary: Creates a new instance of the <xref href="System.Configuration.Provider.ProviderException"></xref> class.
  syntax:
    content: public ProviderException ();
    parameters: []
  overload: System.Configuration.Provider.ProviderException.#ctor*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Provider/ProviderException.xml
- uid: System.Configuration.Provider.ProviderException.#ctor(System.String)
  commentId: M:System.Configuration.Provider.ProviderException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.Provider.ProviderException
  langs:
  - csharp
  name: ProviderException(String)
  nameWithType: ProviderException.ProviderException(String)
  fullName: ProviderException.ProviderException(String)
  type: Constructor
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration.Provider
  summary: Creates a new instance of the <xref href="System.Configuration.Provider.ProviderException"></xref> class.
  syntax:
    content: public ProviderException (string message);
    parameters:
    - id: message
      type: System.String
      description: A message describing why this <xref href="System.Configuration.Provider.ProviderException"></xref> was thrown.
  overload: System.Configuration.Provider.ProviderException.#ctor*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Provider/ProviderException.xml
- uid: System.Configuration.Provider.ProviderException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  commentId: M:System.Configuration.Provider.ProviderException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Configuration.Provider.ProviderException
  langs:
  - csharp
  name: ProviderException(SerializationInfo, StreamingContext)
  nameWithType: ProviderException.ProviderException(SerializationInfo, StreamingContext)
  fullName: ProviderException.ProviderException(SerializationInfo, StreamingContext)
  type: Constructor
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration.Provider
  summary: Creates a new instance of the <xref href="System.Configuration.Provider.ProviderException"></xref> class.
  syntax:
    content: protected ProviderException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: The object that holds the information to deserialize.
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: Contextual information about the source or destination.
  overload: System.Configuration.Provider.ProviderException.#ctor*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Provider/ProviderException.xml
- uid: System.Configuration.Provider.ProviderException.#ctor(System.String,System.Exception)
  commentId: M:System.Configuration.Provider.ProviderException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Configuration.Provider.ProviderException
  langs:
  - csharp
  name: ProviderException(String, Exception)
  nameWithType: ProviderException.ProviderException(String, Exception)
  fullName: ProviderException.ProviderException(String, Exception)
  type: Constructor
  assemblies:
  - System.Configuration
  - System.Configuration.ConfigurationManager
  namespace: System.Configuration.Provider
  summary: Creates a new instance of the <xref href="System.Configuration.Provider.ProviderException"></xref> class.
  syntax:
    content: public ProviderException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: A message describing why this <xref href="System.Configuration.Provider.ProviderException"></xref> was thrown.
    - id: innerException
      type: System.Exception
      description: The exception that caused this <xref href="System.Configuration.Provider.ProviderException"></xref> to be thrown.
  overload: System.Configuration.Provider.ProviderException.#ctor*
  exceptions: []
  version:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Provider/ProviderException.xml
references:
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Configuration.Provider.ProviderException.#ctor
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: ProviderException()
  nameWithType: ProviderException.ProviderException()
  fullName: ProviderException.ProviderException()
- uid: System.Configuration.Provider.ProviderException.#ctor(System.String)
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: ProviderException(String)
  nameWithType: ProviderException.ProviderException(String)
  fullName: ProviderException.ProviderException(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Provider.ProviderException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: ProviderException(SerializationInfo, StreamingContext)
  nameWithType: ProviderException.ProviderException(SerializationInfo, StreamingContext)
  fullName: ProviderException.ProviderException(SerializationInfo, StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: false
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.Provider.ProviderException.#ctor(System.String,System.Exception)
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: ProviderException(String, Exception)
  nameWithType: ProviderException.ProviderException(String, Exception)
  fullName: ProviderException.ProviderException(String, Exception)
- uid: System.Configuration.Provider.ProviderException.#ctor*
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: ProviderException
  nameWithType: ProviderException.ProviderException
  fullName: ProviderException.ProviderException
  monikers:
  - netcore-2.0
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Provider/ProviderException.xml
