### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  commentId: T:System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  id: NetNamedPipeSecurityElement
  children:
  - System.ServiceModel.Configuration.NetNamedPipeSecurityElement.#ctor
  - System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Mode
  - System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Properties
  - System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Transport
  langs:
  - csharp
  name: NetNamedPipeSecurityElement
  nameWithType: NetNamedPipeSecurityElement
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  type: Class
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Represents a configuration element that specifies security settings for a named pipe binding. This class cannot be inherited.
  syntax:
    content: 'public sealed class NetNamedPipeSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetNamedPipeSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.#ctor
  commentId: M:System.ServiceModel.Configuration.NetNamedPipeSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  langs:
  - csharp
  name: NetNamedPipeSecurityElement()
  nameWithType: NetNamedPipeSecurityElement.NetNamedPipeSecurityElement()
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.NetNamedPipeSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Initializes a new instance of the <xref href="System.ServiceModel.Configuration.NetNamedPipeSecurityElement"></xref> class.
  syntax:
    content: public NetNamedPipeSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetNamedPipeSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Mode
  commentId: P:System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: NetNamedPipeSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets or sets the type of security that is applied to this binding.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("mode", DefaultValue=Mono.Cecil.CustomAttributeArgument)]

      public System.ServiceModel.NetNamedPipeSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.NetNamedPipeSecurityMode
      description: A <xref href="System.ServiceModel.NetNamedPipeSecurityMode"></xref> that specifies the type of security applied to this binding. The default value is <xref href="System.ServiceModel.NetNamedPipeSecurityMode.Transport"></xref>.
  overload: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Mode*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetNamedPipeSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Properties
  commentId: P:System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: NetNamedPipeSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetNamedPipeSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Transport
  commentId: P:System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Transport
  id: Transport
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  langs:
  - csharp
  name: Transport
  nameWithType: NetNamedPipeSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: Gets the security settings for the transport.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("transport")]

      public System.ServiceModel.Configuration.NamedPipeTransportSecurityElement Transport { get; }
    return:
      type: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
      description: The security settings for the transport.
  overload: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Transport*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetNamedPipeSecurityElement.xml
  author: Erikre
  ms.author: erikre
  manager: erikre
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  isExternal: false
  name: NetNamedPipeSecurityElement()
  nameWithType: NetNamedPipeSecurityElement.NetNamedPipeSecurityElement()
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.NetNamedPipeSecurityElement()
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Mode
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  isExternal: false
  name: Mode
  nameWithType: NetNamedPipeSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Mode
- uid: System.ServiceModel.NetNamedPipeSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: NetNamedPipeSecurityMode
  nameWithType: NetNamedPipeSecurityMode
  fullName: System.ServiceModel.NetNamedPipeSecurityMode
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Properties
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NetNamedPipeSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Transport
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  isExternal: false
  name: Transport
  nameWithType: NetNamedPipeSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Transport
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: NamedPipeTransportSecurityElement
  nameWithType: NamedPipeTransportSecurityElement
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  isExternal: false
  name: NetNamedPipeSecurityElement
  nameWithType: NetNamedPipeSecurityElement.NetNamedPipeSecurityElement
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.NetNamedPipeSecurityElement
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetNamedPipeSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  isExternal: false
  name: Mode
  nameWithType: NetNamedPipeSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Mode
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetNamedPipeSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NetNamedPipeSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetNamedPipeSecurityElement.xml
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Transport*
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  isExternal: false
  name: Transport
  nameWithType: NetNamedPipeSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Transport
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.ServiceModel.Configuration/NetNamedPipeSecurityElement.xml
