### YamlMime:ManagedReference
items:
- uid: System.Configuration.ClientSettingsSection
  commentId: T:System.Configuration.ClientSettingsSection
  id: ClientSettingsSection
  children:
  - System.Configuration.ClientSettingsSection.#ctor
  - System.Configuration.ClientSettingsSection.Properties
  - System.Configuration.ClientSettingsSection.Settings
  langs:
  - csharp
  name: ClientSettingsSection
  nameWithType: ClientSettingsSection
  fullName: System.Configuration.ClientSettingsSection
  type: Class
  assemblies:
  - System
  namespace: System.Configuration
  summary: Represents a group of user-scoped application settings in a configuration file.
  remarks: "The [!INCLUDE[dnprdnshort](~/includes/dnprdnshort-md.md)] contains a single default settings provider, <xref:System.Configuration.LocalFileSettingsProvider>, which stores configuration data to the local file system in files with the extension `.config`. The contents of configuration files are structured as XML documents. User-scoped settings are persisted in a file with the name `username.config`. Within this file, data is stored as elements within a `<userSettings>` section. Each of these sections is represented by a corresponding <xref:System.Configuration.ClientSettingsSection>. Each section object is owned and administered by a configuration section handler, which is an <xref:System.Configuration.IConfigurationSectionHandler>.  \n  \n The <xref:System.Configuration.ClientSettingsSection> class represents a simple extension of the <xref:System.Configuration.ConfigurationSection> class, which is used in the [!INCLUDE[dnprdnshort](~/includes/dnprdnshort-md.md)] support for general configuration files.  \n  \n For more information about application settings, see the topic [Application Settings for Windows Forms](~/docs/framework/winforms/advanced/application-settings-for-windows-forms.md)."
  syntax:
    content: 'public sealed class ClientSettingsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ClientSettingsSection.xml
  author: stevehoag
  ms.author: shoag
  manager: wpickett
- uid: System.Configuration.ClientSettingsSection.#ctor
  commentId: M:System.Configuration.ClientSettingsSection.#ctor
  id: '#ctor'
  parent: System.Configuration.ClientSettingsSection
  langs:
  - csharp
  name: ClientSettingsSection()
  nameWithType: ClientSettingsSection.ClientSettingsSection()
  fullName: System.Configuration.ClientSettingsSection.ClientSettingsSection()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: Initializes a new instance of the <xref href="System.Configuration.ClientSettingsSection"></xref> class.
  remarks: The default <xref:System.Configuration.ClientSettingsSection.%23ctor%2A> constructor initializes the <xref:System.Configuration.ClientSettingsSection.Settings%2A> property.
  syntax:
    content: public ClientSettingsSection ();
    parameters: []
  overload: System.Configuration.ClientSettingsSection.#ctor*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ClientSettingsSection.xml
  author: stevehoag
  ms.author: shoag
  manager: wpickett
- uid: System.Configuration.ClientSettingsSection.Properties
  commentId: P:System.Configuration.ClientSettingsSection.Properties
  id: Properties
  parent: System.Configuration.ClientSettingsSection
  langs:
  - csharp
  name: Properties
  nameWithType: ClientSettingsSection.Properties
  fullName: System.Configuration.ClientSettingsSection.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  overload: System.Configuration.ClientSettingsSection.Properties*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ClientSettingsSection.xml
- uid: System.Configuration.ClientSettingsSection.Settings
  commentId: P:System.Configuration.ClientSettingsSection.Settings
  id: Settings
  parent: System.Configuration.ClientSettingsSection
  langs:
  - csharp
  name: Settings
  nameWithType: ClientSettingsSection.Settings
  fullName: System.Configuration.ClientSettingsSection.Settings
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: Gets the collection of client settings for the section.
  remarks: The <xref:System.Configuration.ClientSettingsSection.Settings%2A> property is itself a configuration property.
  syntax:
    content: >-
      [System.Configuration.ConfigurationProperty("", Options=System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection)]

      public System.Configuration.SettingElementCollection Settings { get; }
    return:
      type: System.Configuration.SettingElementCollection
      description: A <xref href="System.Configuration.SettingElementCollection"></xref> containing all the client settings found in the current configuration section.
  overload: System.Configuration.ClientSettingsSection.Settings*
  exceptions: []
  attributes:
  - type: System.Configuration.ConfigurationPropertyAttribute
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ClientSettingsSection.xml
  author: stevehoag
  ms.author: shoag
  manager: wpickett
references:
- uid: System.Configuration.ConfigurationSection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: System.Configuration.ConfigurationSection
- uid: System.Configuration.ClientSettingsSection.#ctor
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: ClientSettingsSection()
  nameWithType: ClientSettingsSection.ClientSettingsSection()
  fullName: System.Configuration.ClientSettingsSection.ClientSettingsSection()
- uid: System.Configuration.ClientSettingsSection.Properties
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: Properties
  nameWithType: ClientSettingsSection.Properties
  fullName: System.Configuration.ClientSettingsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.ClientSettingsSection.Settings
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: Settings
  nameWithType: ClientSettingsSection.Settings
  fullName: System.Configuration.ClientSettingsSection.Settings
- uid: System.Configuration.SettingElementCollection
  parent: System.Configuration
  isExternal: false
  name: SettingElementCollection
  nameWithType: SettingElementCollection
  fullName: System.Configuration.SettingElementCollection
- uid: System.Configuration.ClientSettingsSection.#ctor*
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: ClientSettingsSection
  nameWithType: ClientSettingsSection.ClientSettingsSection
  fullName: System.Configuration.ClientSettingsSection.ClientSettingsSection
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ClientSettingsSection.xml
- uid: System.Configuration.ClientSettingsSection.Properties*
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: Properties
  nameWithType: ClientSettingsSection.Properties
  fullName: System.Configuration.ClientSettingsSection.Properties
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ClientSettingsSection.xml
- uid: System.Configuration.ClientSettingsSection.Settings*
  parent: System.Configuration.ClientSettingsSection
  isExternal: false
  name: Settings
  nameWithType: ClientSettingsSection.Settings
  fullName: System.Configuration.ClientSettingsSection.Settings
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration/ClientSettingsSection.xml
