### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IConfigErrorInfo
  commentId: T:System.Configuration.Internal.IConfigErrorInfo
  id: IConfigErrorInfo
  children:
  - System.Configuration.Internal.IConfigErrorInfo.Filename
  - System.Configuration.Internal.IConfigErrorInfo.LineNumber
  langs:
  - csharp
  name: IConfigErrorInfo
  nameWithType: IConfigErrorInfo
  fullName: System.Configuration.Internal.IConfigErrorInfo
  type: Interface
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: Defines an interface used by the .NET Framework to support creating error configuration records.
  syntax:
    content: public interface IConfigErrorInfo
  implements: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IConfigErrorInfo.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.Internal.IConfigErrorInfo.Filename
  commentId: P:System.Configuration.Internal.IConfigErrorInfo.Filename
  id: Filename
  parent: System.Configuration.Internal.IConfigErrorInfo
  langs:
  - csharp
  name: Filename
  nameWithType: IConfigErrorInfo.Filename
  fullName: System.Configuration.Internal.IConfigErrorInfo.Filename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: Gets a string specifying the file name related to the configuration details.
  syntax:
    content: public string Filename { get; }
    return:
      type: System.String
      description: A string specifying a filename.
  overload: System.Configuration.Internal.IConfigErrorInfo.Filename*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IConfigErrorInfo.xml
  ms.author: riande
  manager: wpickett
- uid: System.Configuration.Internal.IConfigErrorInfo.LineNumber
  commentId: P:System.Configuration.Internal.IConfigErrorInfo.LineNumber
  id: LineNumber
  parent: System.Configuration.Internal.IConfigErrorInfo
  langs:
  - csharp
  name: LineNumber
  nameWithType: IConfigErrorInfo.LineNumber
  fullName: System.Configuration.Internal.IConfigErrorInfo.LineNumber
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: Gets an integer specifying the line number related to the configuration details.
  syntax:
    content: public int LineNumber { get; }
    return:
      type: System.Int32
      description: An integer specifying a line number.
  overload: System.Configuration.Internal.IConfigErrorInfo.LineNumber*
  exceptions: []
  version:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IConfigErrorInfo.xml
  ms.author: riande
  manager: wpickett
references:
- uid: System.Configuration.Internal.IConfigErrorInfo.Filename
  parent: System.Configuration.Internal.IConfigErrorInfo
  isExternal: false
  name: Filename
  nameWithType: IConfigErrorInfo.Filename
  fullName: System.Configuration.Internal.IConfigErrorInfo.Filename
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IConfigErrorInfo.LineNumber
  parent: System.Configuration.Internal.IConfigErrorInfo
  isExternal: false
  name: LineNumber
  nameWithType: IConfigErrorInfo.LineNumber
  fullName: System.Configuration.Internal.IConfigErrorInfo.LineNumber
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.Internal.IConfigErrorInfo.Filename*
  parent: System.Configuration.Internal.IConfigErrorInfo
  isExternal: false
  name: Filename
  nameWithType: IConfigErrorInfo.Filename
  fullName: System.Configuration.Internal.IConfigErrorInfo.Filename
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IConfigErrorInfo.xml
- uid: System.Configuration.Internal.IConfigErrorInfo.LineNumber*
  parent: System.Configuration.Internal.IConfigErrorInfo
  isExternal: false
  name: LineNumber
  nameWithType: IConfigErrorInfo.LineNumber
  fullName: System.Configuration.Internal.IConfigErrorInfo.LineNumber
  monikers:
  - netframework-4.5.1
  - netframework-4.5.2
  - netframework-4.5
  - netframework-4.6.1
  - netframework-4.6.2
  - netframework-4.6
  - netframework-4.7
  - xamarinmac-3.0
  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Configuration.Internal/IConfigErrorInfo.xml
